<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><span class="flag-icon flag-icon-nl"></span> <?= $this->translate('Dutch') ?></label>
        </div>
        <hr>
        <?php
        $name = $form->get('name')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'name-nl');
        $name->setValue($this->localisedTextElement($name));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($name) ?>">
            <label for="<?= $name->getAttribute('id') ?>" class="control-label label-required">
                <?= $name->getLabel() ?>
            </label>
            <?= $this->formText($name) ?>
            <?= $this->formElementErrors($name) ?>
        </div>
        <?php
        $namePlural = $form->get('namePlural')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'name-plural-nl');
        $namePlural->setValue($this->localisedTextElement($namePlural));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($namePlural) ?>">
            <label for="<?= $namePlural->getAttribute('id') ?>" class="control-label label-required">
                <?= $namePlural->getLabel() ?>
            </label>
            <?= $this->formText($namePlural) ?>
            <?= $this->formElementErrors($namePlural) ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><span class="flag-icon flag-icon-en"></span> <?= $this->translate('English') ?></label>
        </div>
        <hr>
        <?php
        $nameEn = $form->get('nameEn')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'name-en');
        $nameEn->setValue($this->localisedTextElement($nameEn));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($nameEn) ?>">
            <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $nameEn->getLabel() ?>
            </label>
            <?= $this->formText($nameEn) ?>
            <?= $this->formElementErrors($nameEn) ?>
        </div>
        <?php
        $namePluralEn = $form->get('namePluralEn')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'name-plural-en');
        $namePluralEn->setValue($this->localisedTextElement($namePluralEn));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($namePluralEn) ?>">
            <label for="<?= $namePluralEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $namePluralEn->getLabel() ?>
            </label>
            <?= $this->formText($namePluralEn) ?>
            <?= $this->formElementErrors($namePluralEn) ?>
        </div>
    </div>
    <div class="col-md-12">
        <?php
        $hidden = $form->get('hidden')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'hidden');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($hidden) ?>">
            <label for="<?= $hidden->getAttribute('id') ?>" class="control-label label-required">
                <?= $hidden->getLabel() ?>
            </label>
            <?= $this->formCheckbox($hidden) ?>
            <?= $this->formElementErrors($hidden) ?>
        </div>
    </div>
</div>
