
<dl><!-- common elements -->
<?php $element = $this->form->get('name') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

<?php $element = $this->form->get('asciiName') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('address') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('phone') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('email') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>    
</dl>

<dl><!-- english elements -->
<?php $element = $this->form->get('en.website') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('en.description') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('en.logo') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

<?php $element = $this->form->get('en.slogan') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

</dl>

<dl><!-- dutch elements -->
<?php $element = $this->form->get('nl.website') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('nl.description') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $this->form->get('nl.logo') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

<?php $element = $this->form->get('nl.slogan') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

</dl>