<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
    </div>
    <div class="col-md-6">
        <?php
        $startDate = $form->get('startDate')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'start-date');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($startDate) ?>">
            <label for="<?= $startDate->getAttribute('id') ?>" class="control-label label-required">
                <?= $startDate->getLabel() ?>
            </label>
            <?= $this->formDate($startDate) ?>
            <?= $this->formElementErrors($startDate) ?>
        </div>
        <?php
        $expirationDate = $form->get('expirationDate')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'expiration-date');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($expirationDate) ?>">
            <label for="<?= $expirationDate->getAttribute('id') ?>" class="control-label label-required">
                <?= $expirationDate->getLabel() ?>
            </label>
            <?= $this->formDate($expirationDate) ?>
            <?= $this->formElementErrors($expirationDate) ?>
        </div>
    </div>
    <div class="col-md-6">
        <?php
        $published = $form->get('published')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'published');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($published) ?>">
            <label for="<?= $published->getAttribute('id') ?>" class="control-label label-required">
                <?= $published->getLabel() ?>
            </label>
            <?= $this->formCheckbox($published) ?>
            <?= $this->formElementErrors($published) ?>
        </div>
    </div>
    <?php
    if ('featured' === $type):
    ?>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <?php
                    $language = $form->get('language')
                        ->setAttribute('class', 'form-control')
                        ->setAttribute('id', 'language');
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($language) ?>">
                        <label for="<?= $language->getAttribute('id') ?>" class="control-label label-required">
                            <?= $language->getLabel() ?>
                        </label>
                        <?= $this->formRadio($language) ?>
                        <?= $this->formElementErrors($language) ?>
                    </div>
                </div>
                <div class="col-md-9">
                    <?php
                    $article = $form->get('article')
                        ->setAttribute('class', 'form-control')
                        ->setAttribute('id', 'article');
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($article) ?>">
                        <label for="<?= $article->getAttribute('id') ?>" class="control-label label-required">
                            <?= $article->getLabel() ?>
                        </label>
                        <?= $this->formTextarea($article) ?>
                        <?= $this->formElementErrors($article) ?>
                    </div>
                </div>
            </div>
        </div>
    <?php
    elseif ('banner' === $type):
    ?>
        <div class="col-md-12">
            <?php
            $banner = $form->get('banner')
                ->setAttribute('class', 'form-control')
                ->setAttribute('id', 'banner');
            ?>
            <div class="form-group <?= $this->bootstrapElementError($banner) ?>">
                <label for="<?= $banner->getAttribute('id') ?>" class="control-label label-required">
                    <?= $banner->getLabel() ?>
                </label>
                <?= $this->formCheckbox($banner) ?>
                <?= $this->formElementErrors($banner) ?>
            </div>
        </div>
    <?php
    endif;
    ?>
</div>
