<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
    </div>
    <div class="col-md-6">
        <?php
        $startDate = $form->get('startDate')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'start-date');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($startDate) ?>">
            <label for="<?= $startDate->getAttribute('id') ?>" class="control-label label-required">
                <?= $startDate->getLabel() ?>
            </label>
            <?= $this->formDate($startDate) ?>
            <?= $this->formElementErrors($startDate) ?>
        </div>
        <?php
        $expirationDate = $form->get('expirationDate')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'expiration-date');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($expirationDate) ?>">
            <label for="<?= $expirationDate->getAttribute('id') ?>" class="control-label label-required">
                <?= $expirationDate->getLabel() ?>
            </label>
            <?= $this->formDate($expirationDate) ?>
            <?= $this->formElementErrors($expirationDate) ?>
        </div>
    </div>
    <div class="col-md-6">
        <?php
        $published = $form->get('published')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'published');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($published) ?>">
            <label for="<?= $published->getAttribute('id') ?>" class="control-label label-required">
                <?= $published->getLabel() ?>
            </label>
            <?= $this->formCheckbox($published) ?>
            <?= $this->formElementErrors($published) ?>
        </div>
    </div>
    <?php
    if ('featured' === $type):
    ?>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <?php
                    $checkboxDutch = $form->get('language_dutch')
                        ->setAttribute('onchange', 'Company.updateForm()')
                        ->setAttribute('id', 'dutch-check')
                        ->setAttribute('class', 'language-control');
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($checkboxDutch) ?>">
                        <label for="<?= $checkboxDutch->getAttribute('id') ?>" class="control-label"
                               title="<?= $checkboxDutch->getLabel() ?>">
                            <?= $this->formCheckbox($checkboxDutch) ?>
                            <span class="flag-icon flag-icon-nl"></span>
                            <?= $this->translate('Dutch') ?>
                        </label>
                        <?= $this->formElementErrors($checkboxDutch) ?>
                    </div>
                    <hr>
                    <?php
                    $article = $form->get('article')
                        ->setAttribute('disabled', 'disabled')
                        ->setAttribute('class', 'form-control form-control-dutch')
                        ->setAttribute('style', 'width:100%; height:10em; resize:none')
                        ->setAttribute('id', 'article-nl');
                    $article->setValue($this->localisedTextElement($article));
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($article) ?>">
                        <label for="<?= $article->getAttribute('id') ?>" class="control-label">
                            <?= $article->getLabel() ?>
                        </label>
                        <?= $this->formTextarea($article) ?>
                        <?= $this->formElementErrors($article) ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <?php
                    $checkboxEnglish = $form->get('language_english')
                        ->setAttribute('onchange', 'Company.updateForm()')
                        ->setAttribute('id', 'english-check')
                        ->setAttribute('class', 'language-control');
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($checkboxEnglish) ?>">
                        <label for="<?= $checkboxEnglish->getAttribute('id') ?>" class="control-label"
                               title="<?= $checkboxEnglish->getLabel() ?>">
                            <?= $this->formCheckbox($checkboxEnglish) ?>
                            <span class="flag-icon flag-icon-en"></span>
                            <?= $this->translate('English') ?>
                        </label>
                        <?= $this->formElementErrors($checkboxEnglish) ?>
                    </div>
                    <hr>
                    <?php
                    $articleEn = $form->get('articleEn')
                        ->setAttribute('disabled', 'disabled')
                        ->setAttribute('class', 'form-control form-control-english')
                        ->setAttribute('style', 'width:100%; height:10em; resize:none')
                        ->setAttribute('id', 'article-en');
                    $articleEn->setValue($this->localisedTextElement($articleEn));
                    ?>
                    <div class="form-group <?= $this->bootstrapElementError($articleEn) ?>">
                        <label for="<?= $articleEn->getAttribute('id') ?>" class="control-label">
                            <?= $articleEn->getLabel() ?>
                        </label>
                        <?= $this->formTextarea($articleEn) ?>
                        <?= $this->formElementErrors($articleEn) ?>
                    </div>
                </div>
            </div>
        </div>
    <?php
    elseif ('banner' === $type):
    ?>
        <div class="col-md-12">
            <?php
            $banner = $form->get('banner')
                ->setAttribute('class', 'form-control')
                ->setAttribute('id', 'banner');
            ?>
            <div class="form-group <?= $this->bootstrapElementError($banner) ?>">
                <label for="<?= $banner->getAttribute('id') ?>" class="control-label label-required">
                    <?= $banner->getLabel() ?>
                </label>
                <?= $this->formFile($banner) ?>
                <?= $this->formElementErrors($banner) ?>
            </div>
        </div>
    <?php
    endif;
    ?>
</div>
