<?php

declare(strict_types=1);

namespace User\Authentication\Adapter;

use Laminas\Authentication\Adapter\AdapterInterface;
use Laminas\Authentication\Result;
use Laminas\Crypt\Password\Bcrypt;
use Laminas\Mvc\I18n\Translator;
use SensitiveParameter;
use User\Authentication\Service\LoginAttempt as LoginAttemptService;
use User\Mapper\CompanyUser as CompanyUserMapper;
use User\Service\PwnedPasswords as PwnedPasswordsService;

class CompanyUserAdapter implements AdapterInterface
{
    private string $email;

    private string $password;

    public function __construct(
        private readonly Translator $translator,
        private readonly Bcrypt $bcrypt,
        private readonly LoginAttemptService $loginAttemptService,
        private readonly PwnedPasswordsService $pwnedPasswordsService,
        private readonly CompanyUserMapper $mapper,
    ) {
    }

    /**
     * Try to authenticate.
     *
     * @return Result
     */
    public function authenticate(): Result
    {
        $company = $this->mapper->findByLogin($this->email);

        if (null === $company) {
            return new Result(
                Result::FAILURE_IDENTITY_NOT_FOUND,
                null,
                [
                    $this->translator->translate('The login and password combination is incorrect.'),
                ],
            );
        }

        if ($this->loginAttemptService->loginAttemptsExceeded($company)) {
            return new Result(
                Result::FAILURE,
                null,
                [
                    $this->translator->translate('Too many login attempts, try again later.'),
                ],
            );
        }

        if (!$this->verifyPassword($this->password, $company->getPassword())) {
            $this->loginAttemptService->logFailedLogin($company);

            return new Result(
                Result::FAILURE_IDENTITY_NOT_FOUND,
                null,
                [
                    $this->translator->translate('The login and password combination is incorrect.'),
                ],
            );
        }

        if ($this->pwnedPasswordsService->isPasswordLeaked($this->password)) {
            return new Result(
                // Use Result::FAILURE_CREDENTIAL_INVALID to make this ends up as an error on the password field
                Result::FAILURE_CREDENTIAL_INVALID,
                null,
                [
                    // phpcs:ignore -- user-visible strings should not be split
                    $this->translator->translate('Your password was found in a public data breach and is therefore considered insecure. Please request a password reset before continuing. We recommend using a password generated by a good password manager, such as Bitwarden or 1Password.'),
                ],
            );
        }

        return new Result(Result::SUCCESS, $company);
    }

    /**
     * Verify a password.
     *
     * @param string $password
     * @param string $hash
     *
     * @return bool
     */
    public function verifyPassword(
        #[SensitiveParameter]
        string $password,
        #[SensitiveParameter]
        string $hash,
    ): bool {
        if ($this->bcrypt->verify($password, $hash)) {
            return true;
        }

        return false;
    }

    /**
     * Sets the credentials used to authenticate.
     *
     * @param string $email
     * @param string $password
     */
    public function setCredentials(
        string $email,
        #[SensitiveParameter]
        string $password,
    ): void {
        $this->email = $email;
        $this->password = $password;
    }

    /**
     * Get the mapper.
     *
     * @return CompanyUserMapper
     */
    public function getMapper(): CompanyUserMapper
    {
        return $this->mapper;
    }
}
