<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('photo'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php
    $nameField = $form->get('name');
    $nameField->setAttribute('class', 'form-control');
    $authorField = $form->get('author');
    $authorField->setAttribute('class', 'form-control');
    ?>
    <?= $this->formLabel($nameField) ?>
    <?= $this->formInput($nameField) ?>
    <?= $this->formElementErrors($nameField) ?>
    <?= $this->formLabel($authorField) ?>
    <?= $this->formInput($authorField) ?>
    <?= $this->formElementErrors($authorField) ?>
</div>

<?php
$submit = $form->get('submit');
//$submit->setLabel($this->translate('Create album'));
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>