<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('admin_photo/importaction'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php
    $albumField = $form->get('album_id');
    $albumField->setAttribute('class', 'form-control');
    $pathField = $form->get('folder_path');
    $pathField->setAttribute('class', 'form-control');
    ?>
    <?= $this->formInput($albumField) ?>
    <?= $this->formElementErrors($albumField) ?>
    <?= $this->formLabel($pathField) ?>
    <?= $this->formInput($pathField) ?>
    <?= $this->formElementErrors($pathField) ?>
</div>

<?php
$submit = $form->get('submit');
//$submit->setLabel($this->translate('Create album'));
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
