<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\Album as AlbumModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AlbumModel $album
 * @var int|null $year
 */

$this->inlineScript()
    ->appendFile(
        $this->basepath('js/dropzone-min.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/photo.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/photo-admin.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
$this->headLink()->appendStylesheet($this->basepath('css/dropzone.css'));

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Photos'), true, $this->url('admin_photo'));

if (null === $year) {
    $this->breadcrumbs()
        ->addBreadcrumb(
            $this->translate('Undated'),
            true,
            $this->url('admin_photo/album_undated'),
        );
} else {
    $this->breadcrumbs()
        ->addBreadcrumb(
            sprintf(
                '%d/%d',
                $year,
                $year + 1,
            ),
            true,
            $this->url('admin_photo/album_year', ['year' => $year]),
        );
}


if (null !== $album->getParent()) {
    $parents = [];
    $currentAlbum = $album;

    while (null !== ($parent = $currentAlbum->getParent())) {
        $parents[] = [
            $this->escapeHtml($parent->getName()),
            true,
            $this->url('admin_photo/album', ['album_id' => $parent->getId()]),
        ];

        $currentAlbum = $parent;
    }

    $parents = array_reverse($parents);

    foreach ($parents as $info) {
        $this->breadcrumbs()->addBreadcrumb(...$info);
    }
}

$this->breadcrumbs()
    ->addBreadcrumb(
        $this->escapeHtml($album->getName()),
        true,
        $this->url('admin_photo/album', ['album_id' => $album->getId()]),
    )
    ->addBreadcrumb($this->translate('Upload Photos'));
?>
<h1><?= sprintf($this->translate('Uploading photos to %s'), $album->getName()) ?></h1>
<hr>
<div class="panel panel-default">
    <form action="upload" class="dropzone" id="image-dropzone"></form>
</div>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.addEventListener("DOMContentLoaded", function() {
        Dropzone.options.imageDropzone = {
            acceptedFiles: 'image/*',
            init: function () {
                let uploading = false;

                window.addEventListener("beforeunload", function (e) {
                    if (uploading) {
                        e.preventDefault();
                        // Most modern browsers no longer support setting custom dialog messages
                        // for this dialog, but for backwards compatibility this could be nice.
                        // So, included for legacy support, e.g. Chrome/Edge < 119:
                        e.returnValue = "You are currently uploading files, are you sure you want to leave?";
                    }
                });

                this.on("addedfile", function (file) {
                    uploading = true
                })

                this.on("queuecomplete", function (file) {
                    uploading = false
                });
             }
        };
        Dropzone.discover();
    });
</script>
