<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\Album as AlbumModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AlbumModel $album
 */

$this->inlineScript()
    ->appendFile(
        $this->basepath('js/dropzone-min.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/photo.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/photo-admin.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
$this->headLink()->appendStylesheet($this->basepath('css/dropzone.css'));

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Photos'), true, $this->url('admin_photo'))
    ->addBreadcrumb($album->getName(), true, $this->url(
        'admin_photo',
        [],
        [
            'fragment' => $album->getId(),
        ],
    ))
    ->addBreadcrumb($this->translate('Upload Photos'));
?>
<h1><?= sprintf($this->translate('Uploading photos to %s'), $album->getName()) ?></h1>
<hr>
<div class="panel panel-default">
    <form action="upload" class="dropzone" id="image-dropzone"></form>
</div>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.addEventListener("DOMContentLoaded", function() {
        Dropzone.options.imageDropzone = {
            acceptedFiles: 'image/*',
        };
        Dropzone.discover();
    });
</script>
