<?php

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Form\CreateAlbum as CreateAlbumForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CreateAlbumForm $form
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Photos'), true, $this->url('admin_photo'))
    ->addBreadcrumb($this->translate('Create Album'));

$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php
    $element = $form->get('name');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $this->translate('Album title'));
    ?>
    <?= $this->formLabel($element) ?>
    <?= $this->formText($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Create album'));
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
