<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Form\Album as EditAlbumForm;
use Photo\Model\Album as AlbumModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AlbumModel|null $album
 * @var EditAlbumForm $form
 */

$editing = isset($album);

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Photos'), true, $this->url('admin_photo'));

if ($editing) {
    $this->breadcrumbs()
        ->addBreadcrumb($this->escapeHtml($album->getName()), true, $this->url(
            'admin_photo/album',
            [
                'album_id' => $album->getId(),
            ],
        ))
        ->addBreadcrumb($this->translate('Edit Album'));
} else {
    $this->breadcrumbs()
        ->addBreadcrumb($this->translate('Create Album'));
}

$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <?php if ($editing): ?>
            <h2><?= $this->translate('Update Album') ?></h2>
        <?php else: ?>
            <h2><?= $this->translate('Create Album') ?></h2>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>
        <div class="row">
            <div class="col-md-12">
                <?php
                $name = $form->get('name')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'name');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($name) ?>">
                    <label for="<?= $name->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('Name') ?>
                    </label>
                    <?= $this->formText($name) ?>
                    <?= $this->formElementErrors($name) ?>
                </div>
            </div>
            <div class="col-md-6">
                <?php
                $startDateTime = $form->get('startDateTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'start-date');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($startDateTime) ?>">
                    <label for="<?= $startDateTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $startDateTime->getLabel() ?>
                    </label>
                    <?= $this->formDateTimeLocal($startDateTime) ?>
                    <?= $this->formElementErrors($startDateTime) ?>
                </div>
            </div>
            <div class="col-md-6">
                <?php
                $endDateTime = $form->get('endDateTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'end-date');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($endDateTime) ?>">
                    <label for="<?= $endDateTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $endDateTime->getLabel() ?>
                    </label>
                    <?= $this->formDateTimeLocal($endDateTime) ?>
                    <?= $this->formElementErrors($endDateTime) ?>
                </div>
                <br>
            </div>
            <div class="col-md-12">
                <?php
                $published = $form->get('published')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'published');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($published) ?>">
                    <label for="<?= $published->getAttribute('id') ?>" class="control-label label-required">
                        <?= $published->getLabel() ?>
                    </label>
                    <?= $this->formCheckbox($published) ?>
                    <?= $this->formElementErrors($published) ?>
                </div>
            </div>
            <div class="col-md-12">
                <?php
                $submit = $form->get('submit')
                    ->setAttribute('class', 'btn btn-primary');
                ?>
                <div class="form-group">
                    <?= $this->formButton($submit) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>

