<?php
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->appendFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');

$form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Update Album') ?></h2>
    </div>
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>
        <div class="row">
            <div class="col-md-12">
                <?php
                $name = $form->get('name')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'name');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($name) ?>">
                    <label for="<?= $name->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('Name') ?>
                    </label>
                    <?= $this->formInput($name) ?>
                    <?= $this->formElementErrors($name) ?>
                </div>
            </div>
            <div class="col-md-6">
                <?php
                $startDateTime = $form->get('startDateTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'start-date');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($startDateTime) ?>">
                    <label for="<?= $startDateTime->getAttribute('id') ?>">
                        <?= $startDateTime->getLabel() ?>
                    </label>
                    <?= $this->formInput($startDateTime) ?>
                    <?= $this->formElementErrors($startDateTime) ?>
                </div>
            </div>
            <div class="col-md-6">
                <?php
                $endDateTime = $form->get('endDateTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'end-date');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($endDateTime) ?>">
                    <label for="<?= $endDateTime->getAttribute('id') ?>">
                        <?= $endDateTime->getLabel() ?>
                    </label>
                    <?= $this->formInput($endDateTime) ?>
                    <?= $this->formElementErrors($endDateTime) ?>
                </div>
                <br>
            </div>
            <div class="col-md-12">
                <?php
                $submit = $form->get('submit')
                    ->setAttribute('class', 'btn btn-primary');
                ?>
                <div class="form-group">
                    <?= $this->formButton($submit) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>

<script>
    $('[name="startDateTime"]').datetimepicker();
    $('[name="endDateTime"]').datetimepicker();
</script>
