<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/photo-admin.js')
    ->prependFile($this->basePath() . '/js/photo.js');
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/tree.css')
    ->prependStylesheet($this->basePath() . '/css/photo-admin.css');

$this->scriptUrl()->requireUrl('admin_photo/album_page', ['album_id', 'page'])
    ->requireUrls(
        [
            'admin_photo/album_edit',
            'admin_photo/album_delete',
            'admin_photo/album_add',
            'admin_photo/album_create',
            'admin_photo/album_move',
            'admin_photo/album_delete',
            'admin_photo/album_cover',
            'admin_photo/album_index'
        ],
        ['album_id']
    )
    ->requireUrls(
        ['admin_photo/photo_index', 'admin_photo/photo_delete', 'admin_photo/photo_move'],
        ['photo_id']
    )
    ->requireUrl('home');
?>
<h1><?= $this->translate('Photo admin') ?></h1>
<hr>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="tree">
                    <?php
                    function showTree($albums, $context)
                    {
                        foreach ($albums as $album): ?>
                            <li><a
                                    id="<?= $album->getId() ?>"
                                    href="<?= $context->url('admin_photo/album_index',
                                        ['album_id' => $album->getId()]) ?>">
                                    <?= $context->escapeHtml($album->getName()) ?>
                                </a>

                                <?php $children = $album->getChildren() ?>
                                <?php if (!empty($children)): ?>
                                    <ul>
                                        <?php showTree($children, $context); ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php
                        endforeach;
                    }

                    foreach ($albumsByYear as $year => $albums):
                        if (!empty($albums)):
                            $nextYear = $year + 1;
                            ?>
                            <li>
                                <?= "$year/$nextYear" ?>
                                <ul>
                                    <?php showTree($albums, $this); ?>
                                </ul>
                            </li>
                        <?php endif;
                    endforeach;
                    if (!empty($albumsWithoutDate)):
                        ?>
                        <li>
                            <?= $this->translate('Other albums'); ?>
                            <ul>
                                <?php showTree($albumsWithoutDate, $this); ?>
                            </ul>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-9">

        <a id="btnCreate" class="btn btn-primary" href="<?= $this->url('admin_photo/album_create'); ?>"><span
                class="glyphicon glyphicon-plus"></span>&nbsp;<?= $this->translate('Create new album') ?></a>
        <hr>
        <div id="albumControls">
            <ol id="breadcrumb" class="breadcrumb"></ol>
            <a id="btnEdit" type="button" class="btn btn-primary" href=""><span class="glyphicon glyphicon-edit"></span>&nbsp;<?= $this->translate('Edit album') ?>
            </a>
            <a id="btnAdd" class="btn btn-primary" href=""><span
                    class="glyphicon glyphicon-upload"></span>&nbsp;<?= $this->translate('Add photos') ?></a>
            <button type="button" data-toggle="modal" data-target="#moveAlbumModal" class="btn btn-primary"><span
                    class="glyphicon glyphicon-folder-open"></span>&nbsp;<?= $this->translate('Move album') ?></button>
            <button type="button" data-toggle="modal" data-target="#multipleMoveModal"
                    class="btn btn-primary btn-hidden" id="btnMultipleMove"><span
                    class="glyphicon glyphicon-folder-open"></span>&nbsp;<?= $this->translate('Move %i photos') ?>
            </button>
            <button type="button" data-toggle="modal" data-target="#coverModal" class="btn btn-primary btn-regenerate">
                <span class="glyphicon glyphicon-picture"></span>&nbsp;<?= $this->translate('Regenerate album cover') ?>
            </button>
            <br><br>
            <button type="button" data-toggle="modal" data-target="#deleteModal" class="btn btn-danger"><span
                    class="glyphicon glyphicon-trash"></span>&nbsp;<?= $this->translate('Delete album') ?></button>
            <button type="button" data-toggle="modal" data-target="#multipleDeleteModal"
                    class="btn btn-danger btn-hidden" id="btnMultipleDelete"><span
                    class="glyphicon glyphicon-trash"></span>&nbsp;<?= $this->translate('Delete %i photos') ?></button>
        </div>
        <hr>

        <nav>
            <ul class="pagination" id="paging"></ul>
        </nav>
        <div id="album"></div>
    </div>
</div>

<!-- Regenerate album cover modal -->
<div class="modal fade" id="coverModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Generate a new cover photo') ?></h4>
            </div>
            <div class="modal-body">
                <center>
                    <div id="coverSpinner" class="spinner"></div>
                    <img id="coverPreview" class="cover-preview" src="">
                </center>
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-primary btn-regenerate"><?= $this->translate('Regenerate') ?></button>
                <button type="button" class="btn btn-primary"
                        data-dismiss="modal"><?= $this->translate('Close') ?></button>
            </div>
        </div>
    </div>
</div>

<!-- Move album modal -->
<div class="modal fade" id="moveAlbumModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Move the album') ?></h4>
            </div>
            <div class="modal-body">
                <div id="albumMoveSelect">
                    <!-- TODO: find a user friendly way to do this -->
                    <p><?= $this->translate('Select a new parent for the album') ?></p>
                    <input id="newAlbumParent" name="parent_id" type="text"/>
                </div>
                <div id="albumMoveDone" style="display:none">
                    <p><?= $this->translate('The album has been moved') ?></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="moveAlbumButton"
                        class="btn btn-primary"><?= $this->translate('Move') ?></button>
            </div>
        </div>
    </div>
</div>

<!-- Delete album modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
            </div>
            <div class="modal-body">
                <div id="deleteConfirm">
                    <p><?= $this->translate('Are you sure you want to delete this album including all photos inside of it? <b>This action can not be reverted.</b>') ?> </p>
                </div>
                <div id="deleteProgress" style="display:none">
                    <center><p><?= $this->translate('Please wait while the album is being deleted.') ?></p></center>
                    <center>
                        <div class="spinner"></div>
                    </center>
                </div>
                <div id="deleteDone" style="display:none">
                    <p><?= $this->translate('The album has been deleted') ?> </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="deleteAlbumButton"
                        class="btn btn-danger"><?= $this->translate('Delete album') ?></button>
                <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
            </div>
        </div>
    </div>
</div>

<!-- Delete multiple modal -->
<div class="modal fade" id="multipleDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
            </div>
            <div class="modal-body">
                <div id="multipleDeleteConfirm">
                    <p><?= $this->translate('Are you sure you want to delete the selected items? <b>This action can not be reverted.</b>') ?> </p>
                </div>
                <div id="multipleDeleteProgress" style="display:none">
                    <center><p><?= $this->translate('Please wait while the photos are being deleted.') ?></p></center>
                    <center>
                        <div class="spinner"></div>
                    </center>
                </div>
                <div id="multipleDeleteDone" style="display:none">
                    <p><?= $this->translate('The photos have been been deleted') ?> </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="multipleDeleteButton"
                        class="btn btn-danger"><?= $this->translate('Delete photos') ?></button>
                <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
            </div>
        </div>
    </div>
</div>

<!-- Move multiple photo modal -->
<div class="modal fade" id="multipleMoveModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Move the photos to another album') ?></h4>
            </div>
            <div class="modal-body">
                <div id="multipleMoveSelect">
                    <!-- TODO: find a user friendly way to do this -->
                    <p><?= $this->translate('Select a new parent album') ?></p>
                    <input id="newPhotoAlbum" name="album_id" type="text"/>
                </div>
                <div id="multipleMoveDone" style="display:none">
                    <p><?= $this->translate('The photos have been moved') ?></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="multipleMoveButton"
                        class="btn btn-primary"><?= $this->translate('Move') ?></button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.tree').treed();
        Photo.Admin.init();
    });
</script>
