<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var int[] $years
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Photos'));
?>
<?= $this->partial('partial/years', ['years' => $years, 'admin' => true]) ?>
<br>
<div class="row">
    <div class="col-md-12">
        <?php if (0 === count($years)): ?>
            <p><?= $this->translate('There are no albums, create one to continue.') ?></p>
        <?php else: ?>
            <p><?= $this->translate('Select an association year to continue.') ?></p>
        <?php endif; ?>
    </div>
</div>
