<div class="jumbotron jumbotron--panorama"></div>

<section class="section">
    <div class="container">
        <div class="row">

            <div class="col-sm-7 col-md-8">
                <section class="content-section">
                    <h1><?= $this->translate('Studievereniging GEWIS') ?></h1>
                    <p class="lead">
                        <?= $this->translate('Welcome to the website of Study association GEWIS, the study association of
                    the department of Mathematics & Computer Science of the Eindhoven University of Technology.') ?>
                    </p>
                </section>

                <section class="content-section">
                    <h2><?= $this->translate('News') ?></h2>

                    <?php foreach ($news as $item): ?>
                        <article class="content-article">
                            <h3>
                                <?php
                                // TODO: Fix design and URLs
                                $lang = $this->plugin('translate')->getTranslator()->getLocale();
                                if ($item instanceof \Activity\Model\Activity) {
                                    echo ($lang === 'en') ? $item->getNameEn() : $item->getName();
                                } else {
                                    echo ($lang === 'en') ? $item->getEnglishTitle() : $item->getDutchTitle();
                                }
                                ?>
                            </h3>
                            <p>
                                <?php
                                if ($item instanceof \Activity\Model\Activity) {
                                    echo ($lang === 'en') ? $item->getDescriptionEn() : $item->getDescription();
                                } else {
                                    echo ($lang === 'en') ? $item->getEnglishContent() : $item->getDutchContent();
                                }
                                ?>
                            </p>
                        </article>
                    <?php endforeach; ?>
                </section>
            </div>

            <aside class="col-sm-5 col-md-4">
                <div class="panel panel-default agenda">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Agenda') ?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="list-group">
                            <?php foreach ($activities as $activity): ?>
                                <a class="list-group-item agenda-item"
                                   href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                                <span class="badge">
                                    <span class="text-lowercase small"><?= $activity->getBeginTime()->format('M') ?>
                                        &nbsp;</span>
                                    <span><?= $activity->getBeginTime()->format('d') ?></span>
                                </span>

                                    <?= $activity->getName(); ?>

                                </a>
                            <?php endforeach; ?>
                        </div>

                        <p>
                            <?= sprintf(
                                $this->translate('Donderdags is er %sborrel%s van 16.30 tot 19.00 uur.'),
                                '<a href="~bac">',
                                '</a>'
                            )
                            ?>
                        </p>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-xs-8">
                                <a href="<?= $this->url('activity') ?>">
                                    <?= $this->translate('Complete agenda') ?>
                                    <span class="glyphicon glyphicon-arrow-right"></span>
                                </a>
                            </div>
                            <div class="col-xs-4 text-right">
                                <a href="https://www.google.com/calendar/embed?src=v23gq10ij44fhdsfdof1s613ak%40group.calendar.google.com&gsessionid=OK"
                                   title="<?= $this->translate('Google Calendar') ?>">
                                    <span class="glyphicon glyphicon-calendar"></span>&nbsp;iCal
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Photo of the week') ?></h3>
                    </div>
                    <div class="panel-body">
                        <?php if (!is_null($weeklyPhoto)): ?>
                            <div class="thumb">
                                <a class="thumbnail" href="<?= $this->url('photo/photo',
                                    ['photo_id' => $weeklyPhoto->getPhoto()->getId()]); ?>">
                                    <img class="img-responsive"
                                         src="<?= $this->fileUrl($weeklyPhoto->getPhoto()->getLargeThumbPath()) ?>"
                                         alt="">
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Poll') ?></h3>
                    </div>
                    <?php if (isset($poll['poll'])): ?>
                        <div class="panel-body">
                            <?= $this->partial('partial/poll.phtml', [
                                'poll' => $poll['poll'],
                                'canVote' => $poll['canVote'],
                                'userVote' => $poll['userVote'],
                                'showResults' => false
                            ]) ?>
                        </div>
                        <div class="panel-footer">
                            <a href="<?= $this->url('poll') ?>"><?= $this->translate('View the results') ?></a>
                        </div>
                    <?php else: ?>
                        <div class="panel-footer">
                            <?= $this->translate('There currently is no poll.'); ?>
                            <a href="<?= $this->url('poll/request') ?>"><?= $this->translate('Request a poll') ?></a> <?= $this->translate('or') ?>
                            <a href="<?= $this->url('poll/history') ?>"><?= $this->translate('view old polls') ?></a>.
                        </div>
                    <?php endif; ?>
                </div>
            </aside>
        </div>
    </div>
</section>
