<?php

declare(strict_types=1);

use Activity\Service\AclService as ActivityAclService;
use Application\View\HelperTrait;
use Company\Service\AclService as CompanyAclService;
use Decision\Service\AclService as DecisionAclService;
use Education\Service\AclService as EducationAclService;
use Frontpage\Service\AclService as FrontpageAclService;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Service\AclService as PhotoAclService;
use User\Service\AclService as UserAclService;

/** @var PhpRenderer|HelperTrait $this */
?>
<div class="admin-container">
    <nav class="navbar navbar-gewis-admin navbar-fixed-left rainbow">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" id="admin-collapsable" data-toggle="collapse"
                        data-target="#navbar-admin" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar-admin" class="navbar-collapse collapse width" aria-expanded="false">
                <ul class="nav navbar-nav">
                    <?php if (null === $this->identity()): ?>
                        <li>
                            <a href="<?= $this->url(
                                'user/login',
                                ['user_type' => 'member'],
                                ['query' => ['redirect_to' => base64_encode($this->serverUrl(true))]],
                            ) ?>">
                                <?= $this->translate('Login') ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(ActivityAclService::class)->isAllowed('activity_admin', 'view')): ?>
                        <li class="dropdown <?= $this->moduleIsActive(['activity']) ? 'active' : '' ?>">
                            <a href="<?= $this->url('activity_admin') ?>" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Activities') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?= $this->url('activity_admin') ?>"><?= $this->translate(
                                            'Overview'
                                        ) ?></a>
                                </li>
                                <?php
                                if ($this->acl(ActivityAclService::class)->isAllowed('activity', 'listCategories')): ?>
                                    <li>
                                        <a href="<?= $this->url('activity_admin_categories') ?>"><?= $this->translate(
                                                'Categories'
                                            ) ?></a>
                                    </li>
                                <?php
                                endif; ?>
                                <?php
                                if ($this->acl(ActivityAclService::class)->isAllowed(
                                    'activity_calendar_period',
                                    'view'
                                )): ?>
                                    <li>
                                        <a href="<?= $this->url('activity_admin_options') ?>"><?= $this->translate(
                                                'Option Calendar'
                                            ) ?></a>
                                    </li>
                                <?php
                                endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(CompanyAclService::class)->isAllowed('company_admin', 'view')): ?>
                        <li class="dropdown <?= $this->moduleIsActive(['company']) ? 'active' : '' ?>">
                            <a href="<?= $this->url('company_admin') ?>" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Career') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <?php
                                if ($this->acl(CompanyAclService::class)->isAllowed('company', 'listAll')): ?>
                                    <li>
                                        <a href="<?= $this->url('company_admin') ?>">
                                            <?= $this->translate('Companies') ?>
                                        </a>
                                    </li>
                                <?php
                                endif; ?>
                                <?php
                                if (
                                    $this->acl(CompanyAclService::class)->isAllowed('company', 'approve')
                                    || $this->acl(CompanyAclService::class)->isAllowed('job', 'approve')
                                ):
                                    ?>
                                    <li>
                                        <a href="<?= $this->url('company_admin_approval') ?>">
                                            <?= $this->translate('Approvals') ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                                <?php if ($this->acl(CompanyAclService::class)->isAllowed('jobCategory', 'listAll')): ?>
                                    <li>
                                        <a href="<?= $this->url('company_admin/categories') ?>">
                                            <?= $this->translate('Categories') ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                                <?php if ($this->acl(CompanyAclService::class)->isAllowed('jobLabel', 'listAll')): ?>
                                    <li>
                                        <a href="<?= $this->url('company_admin/labels') ?>">
                                            <?= $this->translate('Labels') ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(EducationAclService::class)->isAllowed('education_admin', 'view')): ?>
                        <li class="dropdown <?= $this->moduleIsActive(['frontpage', 'exam']) ? 'active' : '' ?>">
                            <a href="<?= $this->hashUrl() ?>" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Education') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?= $this->url('admin_education/course') ?>">
                                        <?= $this->translate('Courses') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('admin_education/bulk_upload_exam') ?>">
                                        <?= $this->translate('Upload exams') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('admin_education/bulk_upload_summary') ?>">
                                        <?= $this->translate('Upload summaries') ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(DecisionAclService::class)->isAllowed('decision_admin', 'view')): ?>
                        <li class="dropdown">
                            <a href="<?= $this->hashUrl() ?>" class="dropdown-toggle" data-toggle="dropdown"
                               role="button" aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Meetings') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?= $this->url('decision_admin/minutes') ?>"><?= $this->translate(
                                            'Minutes'
                                        ) ?></a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('decision_admin/document') ?>"><?= $this->translate(
                                            'Documents'
                                        ) ?></a>
                                </li>
                                <li>
                                    <a href="<?= $this->url('decision_admin/authorizations') ?>"><?= $this->translate(
                                            'Authorizations'
                                        ) ?></a>
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(DecisionAclService::class)->isAllowed('decision_organ_admin', 'view')): ?>
                        <li>
                            <a href="<?= $this->url('admin_organ') ?>">
                                <?= $this->translate('Organs') ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(FrontpageAclService::class)->isAllowed('news_item', 'create')): ?>
                        <li class="<?= $this->moduleIsActive(['frontpage', 'news']) ? 'active' : '' ?>">
                            <a href="<?= $this->url('admin_news') ?>"><?= $this->translate('News') ?></a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(FrontpageAclService::class)->isAllowed('page', 'create')): ?>
                        <li class="<?= $this->moduleIsActive(['frontpage', 'page']) ? 'active' : '' ?>">
                            <a href="<?= $this->url('admin_page') ?>"><?= $this->translate('Pages') ?></a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(PhotoAclService::class)->isAllowed('photo_admin', 'view')): ?>
                    <li class="dropdown <?= $this->moduleIsActive(['photo']) ? 'active' : '' ?>">
                        <a href="<?= $this->hashUrl() ?>" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            <?= $this->translate('Photos') ?> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <?php if ($this->acl(PhotoAclService::class)->isAllowed('album', 'edit')): ?>
                                <li>
                                    <a href="<?= $this->url('admin_photo') ?>"><?= $this->translate('Albums') ?></a>
                                </li>
                            <?php endif; ?>
                            <?php if ($this->acl(PhotoAclService::class)->isAllowed('photo', 'edit')): ?>
                                <li>
                                    <a href="<?= $this->url('admin_photo/weekly') ?>"><?= $this->translate('Photo of the Week') ?></a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ($this->acl(FrontpageAclService::class)->isAllowed('poll', 'approve')): ?>
                        <li class="<?= $this->moduleIsActive(['frontpage', 'poll']) ? 'active' : '' ?>">
                            <a href="<?= $this->url('admin_poll') ?>"><?= $this->translate('Polls') ?></a>
                        </li>
                    <?php endif; ?>
                    <?php if ($this->acl(UserAclService::class)->isAllowed('user_admin', 'view')): ?>
                        <li class="dropdown <?= $this->moduleIsActive(['user']) ? 'active' : '' ?>">
                            <a href="<?= $this->hashUrl() ?>" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Users') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <?php if ($this->acl(UserAclService::class)->isAllowed('apiuser', 'add')): ?>
                                    <li>
                                        <a href="<?= $this->url('user_admin/api') ?>">
                                            <?= $this->translate('API Users') ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                                <?php if ($this->acl(UserAclService::class)->isAllowed('user', 'view_status')): ?>
                                    <li>
                                        <a href="<?= $this->url('user_admin/members') ?>">
                                            <?= $this->translate('Members') ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <li class="stick-to-bottom">
                        <?php
                        $commit = getenv('GIT_COMMIT');
                        ?>
                        <a href="https://github.com/gewis/gewisweb/commit/<?= $commit ?>">
                            <span class="fab fa-github"></span> <?= $commit ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="content-container">
        <section class="section section-breadcrumb">
            <div class="container-admin">
                <ol class="breadcrumb">
                    <li class="active">
                        <a href="<?= $this->url('admin') ?>"><?= $this->translate('Admin') ?></a>
                    </li>
                    <?= $this->breadcrumbs() ?>
                </ol>
            </div>
        </section>
        <section class="section">
            <div class="container-admin">
                <?php
                // The FlashMessenger config accepts namespaced options, we only need to define the classes. ?>
                <?= $this->flashMessenger()->render('default', ['alert', 'alert-dismissible', 'alert-info']) ?>
                <?= $this->flashMessenger()->render('error', ['alert', 'alert-dismissible', 'alert-danger']) ?>
                <?= $this->flashMessenger()->render('info', ['alert', 'alert-dismissible', 'alert-info']) ?>
                <?= $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']) ?>
                <?= $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'alert-warning']) ?>
                <?= $this->content ?>
            </div>
        </section>
    </div>
</div>
