<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-md-1">
                <img src="<?= $this->basePath() ?>/img/gewis-footer.svg"/>
            </div>
            <div class="col-sm-10 col-md-7">
                <div class="row">
                    <div class="col-sm-12">
                        <?php if($this->acl('decision_acl')->isAllowed('member', 'birthdays')): ?>
                            <h3><?= $this->translate('Infima') ?></h3>
                            <p>
                                <?= $this->infima() ?>
                            </p>
                        <?php endif ?>
                        <p>&copy; 2013
                            - <?php echo date('Y') ?> <?= $this->translate("by WebCommissie GEWIS.") ?> <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <h3><?= $this->translate('Visiting address') ?></h3>
                        <address>
                            <?= $this->translate('Study association GEWIS') ?><br>
                            MF 3.155<br>
                            De Groene Loper 5<br>
                            5612 AZ Eindhoven<br>
                            <?= $this->translate('Netherlands') ?>
                        </address>
                    </div>
                    <div class="col-sm-4">
                        <h3><?= $this->translate('Postal address') ?></h3>
                        <address>
                            <?= $this->translate('Study association GEWIS') ?><br>
                            MF 3.155<br>
                            Postbus 513<br>
                            5600 MB Eindhoven<br>
                            <?= $this->translate('Netherlands') ?>
                        </address>
                    </div>
                    <div class="col-sm-4">
                        <i class="glyphicon glyphicon-earphone"></i> <a href="tel:+31402472815">+31 (0)40 247 2815</a><br>
                        <i class="glyphicon glyphicon-envelope"></i> <a href="mailto:bestuur@gewis.nl">bestuur@gewis.nl</a><br>
                        <img src="/img/linkedin.ico" class="glyphicon" width="15" height="15"></img> <a href="https://www.linkedin.com/company/study-association-gewis/">LinkedIn</a><br>
                        <img src="/img/facebook.ico" class="glyphicon" width="15" height="15"></img> <a href="https://www.facebook.com/svgewis/">Facebook</a><br>
                        <img src="/img/instagram.ico" class="glyphicon" width="15" height="15"></img> <a href="https://www.instagram.com/svgewis/">Instagram</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
