<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-2 col-md-1">
                <div class="gi gewis-base" style="font-size: 7em;"></div>
            </div>
            <div class="col-sm-10 col-md-11">
                <div class="row">
                    <div class="col-sm-8">
                        <?php if ($this->acl('frontpage_service_acl')->isAllowed('infimum', 'view')): ?>
                            <h3><?= $this->translate('Infimum') ?></h3>
                            <p id="infima-footer"></p>
                            <script type="text/javascript" nonce="<?= NONCE_REPLACEMENT_STRING ?>">
                                $.getJSON("<?= $this->url('infimum') ?>", function(data) {
                                    $("#infima-footer")[0].textContent = data['content'];
                                });
                            </script>
                        <?php endif ?>
                        <p>&copy; 2013
                            - <?php echo date('Y') ?> <?= $this->translate("by WebCommissie GEWIS.") ?> <?php echo $this->translate('All rights reserved.') ?></p>
                    </div>
                    <div class="col-sm-4">
                        <span class="fas fa-address-book"></span> <a
                            href="/vereniging/contact"><?= $this->translate('Contact') ?></a><br>
                        <span class="fab fa-linkedin"></span> <a
                            href="https://www.linkedin.com/company/study-association-gewis/">LinkedIn</a><br>
                        <span class="fab fa-facebook-square"></span> <a
                            href="https://www.facebook.com/svgewis/">Facebook</a><br>
                        <span class="fab fa-instagram"></span> <a href="https://www.instagram.com/svgewis/">Instagram</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
