<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();
?>
<nav class="navbar navbar-gewis navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header navbar-left pull-left">
            <a href="<?= $this->url('home') ?>" class="navbar-brand">
                <img src="<?= $this->basePath() ?>/img/gewis-branding.svg" alt="<?= $this->translate('GEWIS Logo') ?>">
            </a>
        </div>
        <div class="navbar-header navbar-right pull-right">
            <ul class="nav navbar-nav pull-left no-collapse">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-globe"></span>
                        <span class="sr-only"><?= $this->translate('Language settings') ?></span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu language <?= ($lang == 'en') ? 'reverse' : ''?> ">
                        <li>
                            <a class="<?= ($lang == 'en') ? 'disabled' : '' ?>" href="<?= $this->url('lang', ['lang' => 'en']) ?>">
                                <span class="flag-icon flag-icon-en" style="background-image: url('<?= $this->basePath() ?>/img/en.svg');"></span>English
                            </a>
                        </li>
                        <li>
                            <a class="<?= ($lang == 'nl') ? 'disabled' : '' ?>" href="<?= $this->url('lang', ['lang' => 'nl']) ?>">
                                <span class="flag-icon flag-icon-nl" style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');"></span>Nederlands
                            </a>
                        </li>
                    </ul>
                </li>
                <?php if (null === $this->identity()): ?>
                    <li class="visible-xs pull-left">
                        <a href="<?= $this->url('user') ?>">
                            <span class="glyphicon glyphicon-user"></span>
                            <span class="sr-only"><?= $this->translate('Login') ?></span>
                        </a>
                    </li>
                    <li class="dropdown pull-left hidden-xs">
                        <a href="<?= $this->url('user') ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-user"></span>
                            <span class="sr-only"><?= $this->translate('Login') ?></span>
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-login">
                            <form action="<?= $this->url('user') ?>" method="post">
                                <div class="form-group">
                                    <input type="text" name="login" class="form-control" placeholder="<?= $this->translate('Membership number or email address') ?>" />
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" class="form-control" placeholder="<?= $this->translate('Password') ?>">
                                </div>
                                <button type="submit" class="btn btn-primary btn-block"><?= $this->translate('Login') ?></button>
                                <p><?= $this->translate('Or go to the') ?> <a href="<?= $this->url('user/default', ['action' => 'register']) ?>"><?= $this->translate('registration page') ?></a></p>

                                <input type="hidden" name="redirect" value="<?= $_SERVER['REQUEST_URI'] ?>">
                            </form>
                        </div>
                    </li>
                <?php else: ?>
                    <?php $member = $this->identity()->getMember() ?>
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <?= $member->getFirstName() ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= $this->url('member') ?>"><?= $this->translate('Members') ?></a></li>
                            <li><a href="<?= $this->url('member/self') ?>"><?= $this->translate('My information') ?></a></li>
                            <li><a href="https://gewis.nl/susos/"><?= $this->translate('SuSOS') ?></a></li>
                            <li><a href="<?= $this->url('user/default', ['action' => 'password']) ?>"><?= $this->translate('Change password') ?></a></li>
                            <?php if ($member->getOrganInstallations()->count() > 0): ?>
                                <li><a href="<?= $this->url('admin') ?>"><?= $this->translate('Admin') ?></a></li>
                            <?php endif; ?>
                            <li><a href="<?= $this->url('user/default', [
                                    'action' => 'logout'
                                ]) ?>"><?= $this->translate('Logout') ?></a></li>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only"><?= $this->translate('Toggle navigation') ?></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="visible-xs-block clearfix"></div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                <li class="dropdown dropdown-hover <?= $this->moduleIsActive(['frontpage', 'page']) ? 'active default' : '' ?>">
                    <a href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>" role="button" aria-haspopup="true" aria-expanded="false">
                        <?= $this->translate('Association') ?>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'av']) ?>"><?= $this->translate('General Meeting') ?></a></li>
                        <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'bestuur']) ?>"><?= $this->translate('Board 2015/2016') ?></a></li>
                        <li><a href="<?= $this->url('home/committee_list') ?>"><?= $this->translate('Committees') ?></a></li>
                        <li><a href="<?= $this->url('home/fraternity_list') ?>"><?= $this->translate('Fraternities') ?></a></li>
                        <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'lied']) ?>"><?= $this->translate('GEWIS song') ?></a></li>
                        <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'statuten']) ?>"><?= $this->translate('Regulations') ?></a></li>
                        <li><a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'contact']) ?>"><?= $this->translate('Contact') ?></a></li>
                    </ul>
                </li>
                <li class="dropdown dropdown-hover <?= $this->moduleIsActive(['company']) ? 'active default' : '' ?>">
                    <a href="<?= $this->url('company') ?>" role="button" aria-haspopup="true" aria-expanded="false">
                        <?= $this->translate('Companies') ?>
                    </a>
                    <ul class="dropdown-menu">
                        <?php if (!is_null($this->featuredCompanyPackage())): ?>
                            <li>
                                <a href="<?= $this->url('company/spotlight') ?>">
                                    <span class="glyphicon glyphicon-star"></span>
                                    <?= $this->translate('Featured') ?>:
                                    <?= $this->featuredCompanyPackage()->getCompany()->getName() ?>
                                </a>
                            </li>
                        <?php endif; ?>
                        <li><a href="<?= $this->url('company/jobList') ?>"><?= $this->translate('Jobs') ?></a></li>
                    </ul>
                </li>
                <li class="<?= $this->moduleIsActive(['education']) ? 'active' : '' ?>"><a href="<?= $this->url('education') ?>"><?= $this->translate('Education') ?></a></li>
                <li class="dropdown dropdown-hover <?= $this->moduleIsActive(['activity']) ? 'active default' : '' ?>">
                    <a href="<?= $this->url('company') ?>" role="button" aria-haspopup="true" aria-expanded="false">
                        <?= $this->translate('Activities') ?>
                    </a>
                    <ul class="dropdown-menu">
                        <?php if ($this->acl('activity_acl')->isAllowed('activity', 'create')): ?>
                            <li><a href="<?= $this->url('activity/create') ?>"> <?= $this->translate('Create an activity') ?></a></li>
                        <?php endif; ?>

                    </ul>
                </li>
                <li class="dropdown dropdown-hover <?= $this->moduleIsActive(['photo']) ? 'active' : '' ?>"><a href="<?= $this->url('photo') ?>"><?= $this->translate('Photos') ?></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->url('photo/weekly') ?>"><?= $this->translate('Photo of the week') ?></a></li>

                    </ul>
                </li>
            </ul>
            <?php if (null != $this->identity()): ?>
            <ul class="nav navbar-nav navbar-right">
                <li class="<?= $this->moduleIsActive(['decision']) ? 'active' : '' ?>"><a href="<?= $this->url('member') ?>"><?= $this->translate('Members') ?></a></li>
            </ul>
            <?php endif; ?>
        </div><!--/.nav-collapse -->
    </div>
</nav>
