<?php if ($this->pageCount): ?>
    <nav>
        <ul class="pagination">
            <?php if (isset($this->previous)): ?>
                <li>
                    <a id="previous" href="<?= $this->path ?>/<?= $this->previous; ?>">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only"><?= $this->translate('Previous') ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?= ($page == $this->current) ? 'class="active"' : '' ?>>
                    <a href="<?= $this->path ?>/<?= $page; ?>"><?= $page; ?>
                    </a>
                </li>
            <?php endforeach; ?>
            <?php if (isset($this->next)): ?>
                <li>
                    <a id="next" href="<?= $this->path ?>/<?= $this->next; ?>">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only"><?= $this->translate('Next') ?></span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>
