<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<div class="privacy-widget closed">
    <div class="widget-popout">
        <p><?= $this->translate(
                'GEWIS uses functional cookies to make the website function and analytical cookies to provide you with an optimal user experience. If you do not want analytical cookies, you can opt out below.'
            ) ?></p>
        <div class="widget-opt-out">
            <input type="checkbox" id="opt-out" name="opt-out">
            <label for="opt-out">
                <strong>
                    <?= $this->translate("Analytics are currently") ?>
                    <span id="opt-out-status-false" class="hidden"><?= $this->translate('enabled') ?></span>
                    <span id="opt-out-status-true" class="hidden"><?= $this->translate('disabled') ?></span>
                    <span id="opt-out-status-disabled" class="hidden"><?= $this->translate(
                            'disabled (Do Not Track)'
                        ) ?></span>
                    <span id="opt-out-status-unavailable"><?= $this->translate('unavailable') ?></span>
                </strong>
            </label>
        </div>
        <div class="widget-dismiss">
            <a href="<?= $this->url(
                'home/page',
                [
                    'category' => 'vereniging',
                    'categoryEn' => 'association',
                    'sub_category' => 'reglementen',
                    'sub_categoryEn' => 'regulations',
                ],
            ) ?>">
                <?= $this->translate('Privacy Policy') ?>
            </a>
            <button class="btn btn-primary"><?= $this->translate("Continue") ?></button>
        </div>
    </div>
    <div class="widget-button">
        <div class="gi gewis-base"></div>
    </div>
</div>
