<div class="privacy-widget closed">
    <div class="widget-popout">
        <p><?= $this->translate("S.v. GEWIS uses cookies on this website, these are required for the website to function. Additionally, we may collection information about how you use our website in order to improve your experience. If you do not want your behaviour to be tracked please opt out below.")?></p>
        <div class="widget-opt-out">
            <input type="checkbox" id="opt-out" name="opt-out">
            <label for="opt-out">
                <strong>
                    <?= $this->translate("Tracking is currently") ?>
                    <span id="opt-out-status-false" class="hidden"><?= $this->translate('enabled') ?></span>
                    <span id="opt-out-status-true" class="hidden"><?= $this->translate('disabled') ?></span>
                    <span id="opt-out-status-disabled" class="hidden"><?= $this->translate('disabled (Do Not Track)') ?></span>
                    <span id="opt-out-status-unavailable"><?= $this->translate('unavailable') ?></span>
                </strong>
            </label>
        </div>
        <div class="widget-dismiss">
            <a href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'statuten']) ?>"><?= $this->translate('Privacy Policy') ?></a>
            <button class="btn btn-primary"><?= $this->translate("Continue") ?></button>
        </div>
    </div>
    <div class="widget-button">
        <div class="gi gewis-base"></div>
    </div>
</div>
