<?php
$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Option Calendar'))
    ->addBreadcrumb($this->translate('Overview'));

?>
<div class="row">
    <div class="col-md-12">
        <p>
            <?php if (null !== $current): ?>
                <?= sprintf(
                    $this->translate('Options can be proposed from <strong>%s</strong> till <strong>%s</strong> for the period <strong>%s</strong> to <strong>%s</strong>.'),
                    $this->dateFormat($current->getBeginPlanningTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                    $this->dateFormat($current->getEndPlanningTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                    $this->dateFormat($current->getBeginOptionTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                    $this->dateFormat($current->getEndOptionTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                ) ?>
            <?php elseif (null !== $upcoming): ?>
                <?= sprintf(
                    $this->translate('The next option creation period will from <strong>%s</strong> till <strong>%s</strong>.'),
                    $this->dateFormat($upcoming->getBeginPlanningTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                    $this->dateFormat($upcoming->getEndPlanningTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                ) ?>
            <?php else: ?>
                <?= $this->translate('There is currently no option creation period planned.') ?>
            <?php endif; ?>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url('activity_admin_options/add') ?>" class="btn btn-primary">
            <?= $this->translate('Add Option Period')?>
        </a>
        <?php if (null !== $upcoming): ?>
            <a href="<?= $this->url('activity_admin_options/edit', ['id' => $upcoming->getId()]) ?>" class="btn btn-primary">
                <?= $this->translate('Edit Upcoming Period')?>
            </a>
        <?php endif; ?>
    </div>
</div>
