<div class="content-container">
    <section class="section">
        <div class="container">
            <ul class="nav nav-pills head-menu">
                <?php for ($i = count($years) - 1; $i >= max(0, count($years) - 5); $i--): ?>
                    <li>
                        <a href="<?= $this->url('activity/year', ['year' => $years[$i]]); ?>">
                            <?= $years[$i] ?>-<?= $years[$i] + 1 ?>
                        </a>
                    </li>
                <?php endfor; ?>
                <?php if (7 <= count($years)): ?>
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle"
                           data-toggle="dropdown"
                           href="#"
                           role="button"
                           aria-haspopup="true"
                           aria-expanded="false">
                            <?= $this->translate('Older') ?> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <?php for ($i = max(0, count($years) - 6); $i > 0; $i--): ?>
                                <li>
                                    <a href="<?= $this->url('activity/year', ['year' => $years[$i]]); ?>">
                                        <?= $years[$i] ?>-<?= $years[$i] + 1 ?>
                                    </a>
                                </li>
                            <?php endfor ?>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </section>
    <div class="container">
        <?php if (0 !== count($activities)): ?>
            <?= $this->partial('activity/activity/list.phtml', ['activities' => $activities]) ?>
        <?php else: ?>
            <p><?= $this->translate('There are no activities the archive.') ?></p>
        <?php endif; ?>
    </div>
</div>
