<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<section class="section">
    <div class="container">
        <div class="alert alert-success" role="alert">
            <div class="container">
                <span class="fas fa-check"></span>
                <?= $this->translate("The activity has been successfully created."); ?>
                <?= $this->translate("It will become visible after it has been approved by the board."); ?>
            </div>
        </div>
    </div>
</section>
