<?php
$form->setAttribute('action', '');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('beginTime'));
echo $this->formRow($form->get('endTime'));
echo $this->formRow($form->get('location'));
echo $this->formRow($form->get('costs'));
echo $this->formRow($form->get('optie'));
echo $this->formRow($form->get('discription'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();