<section class="section">
    <div class="container">
        <div class="alert alert-success" role="alert">
            <div class="container">
                <em class="fas fa-check"></em>
                <?= $this->translate("The activity has been successfully created."); ?>
                <?= $this->translate("It will become visible after it has been approved by the board."); ?>
            </div>
        </div>
    </div>
</section>
