<?php
$this->headTitle($this->translate('Create activity'));
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-markdown.min.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap-markdown.js')
    ->prependFile($this->basePath() . '/js/activity-create.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');

$form->prepare();
?>
<style>
    .row-spacing-top--lg { margin-top: 4rem; }
</style>
<section class="section">
    <div class="container">
        <?= $this->form()->openTag($form) ?>
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate('Create an activity') ?></h1>
            </div>
        </div>
        <div class="row row-spacing-top">
            <div class="col-md-12">
                <h2>Organizer</h2>
                <p><?= $this->translate('Select which organ or fraternity is responsible for the activity. Individual initiatives are also welcome!') ?></p>
            </div>
            <div class="col-md-6">
                <?php
                $organ = $form->get('organ');
                $organ->setAttribute('class', 'form-control');
                $organ->setAttribute('id', 'organizing-organ');
                ?>
                <div class="form-group <?= count($organ->getMessages()) > 0 ? 'has-error' : '' ?>">
                    <label for="<?= $organ->getAttribute('id'); ?>" class="control-label">
                        <?= $this->translate('Committee / fraternity') ?>
                    </label>
                    <?= $this->formSelect($organ) ?>
                    <?= $this->formElementErrors($organ) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('partial/create', [ 'form' => $form ]) ?>
            </div>
        </div>
        <div class="row row-spacing-top--lg">
            <div class="col-md-12">
                <?php
                /* render template for fields */
                $fs = $form->get('fields')->getTemplateElement();
                ob_start();
                echo $this->partial('partial/field-fieldset.phtml', ['fs' => $fs, 'index' => '__index__']);
                $tpl = trim(ob_get_clean())
                ?>
                <h2><?= $this->translate('Additional fields') ?></h2>
                <fieldset id="additionalFields">
                    <span class="template" data-template="<?= $this->escapeHtmlAttr($tpl) ?>"></span>
                    <?php
                    $index = 0;
                    foreach ($form->get('fields')->getIterator() as $fs){
                        echo $this->partial('partial/field-fieldset.phtml', ['fs' => $fs, 'index' => $index]);
                        $index++;
                    }
                    ?>
                    <div class="form-group add-field">
                        <button class="btn btn-danger" type="button" onclick="return Activity.removeField()">
                            <span class="glyphicon glyphicon-minus"></span>
                            <?= $this->translate('Remove the last field') ?>
                        </button>
                        <button class="btn btn-success" type="button" onclick="return Activity.addField()">
                            <span class="glyphicon glyphicon-plus"></span>
                            <?= $this->translate('Add a field') ?>
                        </button>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row row-spacing-top--lg">
            <div class="col-md-12">
                <?php
                $submit = $form->get('submit');
                $submit->setLabel($this->translate('Create activity'));
                $submit->setAttribute('class', 'btn btn-primary');
                ?>
                <div class="form-group">
                    <?= $this->formButton($submit) ?>
                </div>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</section>

<script>
    $('[name="beginTime"]').datetimepicker();
    $('[name="endTime"]').datetimepicker();
    $('[name="subscriptionDeadline"]').datetimepicker();
    $('.markdown-editor').each(function() {
      $(this).markdown();
    });
    Activity.updateForm();
    for (var i = 0; i < <?= $index ?>; i++) {
        Activity.updateFieldset(i);
    }
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
