<?php
$this->headTitle($this->translate('Create activity'));
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-markdown.min.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap-markdown.js')
    ->prependFile($this->basePath() . '/js/activity-create.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');

$form->prepare();
?>
<div class="container">
    <?= $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col-md-12">
            <h1><?= $this->translate('Create an activity') ?></h1>
            <hr>
            <h3><?= $this->translate('Display languages') ?></h3>
            <?php
            $dutchElement = $form->get('language_dutch');
            $dutchElement->setAttribute('onchange', 'Activity.updateForm()');
            $dutchElement->setAttribute('id', 'dutch-check');
            $dutchElement->setAttribute('class', 'form-control');
            $englishElement = $form->get('language_english');
            $englishElement->setAttribute('onchange', 'Activity.updateForm()');
            $englishElement->setAttribute('id', 'english-check');
            $englishElement->setAttribute('class', 'form-control');
            ?>
            <div class="form-group form-inline">
                <div class="form-group<?= count($dutchElement->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $dutchElement->getAttribute('id') ?>" class="control-label col-sm-2"><?=
                        $this->translate('Dutch') ?></label>
                    <div class="col-sm-10">
                        <?= $this->formCheckbox($dutchElement) ?>
                        <?= $this->formElementErrors($dutchElement) ?>
                    </div>
                </div>
                <div class="form-group<?= count($englishElement->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $englishElement->getAttribute('id') ?>" class="control-label col-sm-2"><?=
                        $this->translate('English') ?></label>
                    <div class="col-sm-10">
                        <?= $this->formCheckbox($englishElement) ?>
                        <?= $this->formElementErrors($englishElement) ?>
                    </div>
                </div>
            </div>
            <h3><?= $this->translate('Time and date') ?></h3>
            <div class="form-group form-inline">
                <?php
                $beginTime = $form->get('beginTime');
                $beginTime->setAttribute('class', 'form-control')->setAttribute('id', 'begin-time');
                $endTime = $form->get('endTime');
                $endTime->setAttribute('class', 'form-control')->setAttribute('id', 'end-time');
                ?>
                <div class="form-group<?= count($beginTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $beginTime->getAttribute('id') ?>" class="control-label col-sm-2">
                        <?= $this->translate('From') ?>
                    </label>
                    <div class="col-sm-10">
                        <?= $this->formInput($beginTime) ?>
                        <?= $this->formElementErrors($beginTime) ?>
                    </div>
                </div>

                <div class="form-group<?= count($endTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $endTime->getAttribute('id') ?>" class="control-label col-sm-2">
                        <?= $this->translate('Until') ?>
                    </label>
                    <div class="col-sm-10">
                        <?= $this->formInput($endTime) ?>
                        <?= $this->formElementErrors($endTime) ?>
                    </div>
                </div>
            </div>
            <?php
            $subscriptionDeadline = $form->get('subscriptionDeadline');
            $subscriptionDeadline->setAttribute('class', 'form-control')->setAttribute('id', 'deadline-date');
            ?>
            <div class="form-group<?= count($subscriptionDeadline->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $subscriptionDeadline->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Subscription deadline') ?>
                </label>
                <div class="col-sm-10">
                    <?= $this->formInput($subscriptionDeadline) ?>
                    <?= $this->formElementErrors($subscriptionDeadline) ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h3>Dutch</h3>
            <?php
            $name = $form->get('name');
            $name->setAttribute('disabled', 'disabled');
            $name->setAttribute('class', 'form-control form-control-dutch');
            $name->setAttribute('id', 'name-nl');
            ?>
            <div class="form-group<?= count($name->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $name->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Name') ?>
                </label>
                <?= $this->formInput($name) ?>
                <?= $this->formElementErrors($name) ?>
            </div>
            <?php
            $location = $form->get('location');
            $location->setAttribute('disabled', 'disabled');
            $location->setAttribute('class', 'form-control form-control-dutch');
            $location->setAttribute('id', 'location-nl');
            ?>
            <div class="form-group<?= count($location->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $location->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Location') ?>
                </label>
                <?= $this->formInput($location) ?>
                <?= $this->formElementErrors($location) ?>
            </div>
            <?php
            $costs = $form->get('costs');
            $costs->setAttribute('disabled', 'disabled');
            $costs->setAttribute('class', 'form-control form-control-dutch');
            $costs->setAttribute('id', 'cost-nl');
            ?>
            <div class="form-group<?= count($costs->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $costs->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Costs') ?>
                </label>
                <?= $this->formInput($costs) ?>
                <?= $this->formElementErrors($costs) ?>
            </div>
            <?php
            $description = $form->get('description');
            $description->setAttribute('class', 'form-control form-control-dutch markdown-editor');
            $description->setAttribute('style', 'width:100%; height:10em; resize:none');
            $description->setAttribute('data-provide', 'markdown');
            $description->setAttribute('id', 'description-nl');
            ?>
            <div class="form-group<?= count($description->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $description->getAttribute('id') ?>" class="control-label col-sm-2" style="margin-top:10px">
                    <?= $this->translate('Description') ?>
                </label>
                <?= $this->formRow($description) ?>
                <?= $this->formElementErrors($description) ?>
            </div>
        </div>
        <div class="col-md-6">
            <h3>English</h3>
            <?php
            $nameEn = $form->get('nameEn');
            $nameEn->setAttribute('disabled', 'disabled');
            $nameEn->setAttribute('class', 'form-control form-control-english');
            $nameEn->setAttribute('id', 'name-en');
            ?>
            <div class="form-group<?= count($nameEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Name') ?>
                </label>
                <?= $this->formInput($nameEn) ?>
                <?= $this->formElementErrors($nameEn) ?>
            </div>
            <?php
            $locationEn = $form->get('locationEn');
            $locationEn->setAttribute('disabled', 'disabled');
            $locationEn->setAttribute('class', 'form-control form-control-english');
            $locationEn->setAttribute('id', 'location-en');
            ?>
            <div class="form-group<?= count($locationEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $locationEn->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Location') ?>
                </label>
                <?= $this->formInput($locationEn) ?>
                <?= $this->formElementErrors($locationEn) ?>
            </div>
            <?php
            $costsEn = $form->get('costsEn');
            $costsEn->setAttribute('disabled', 'disabled');
            $costsEn->setAttribute('class', 'form-control form-control-english');
            $costsEn->setAttribute('id', 'cost-en');
            ?>
            <div class="form-group<?= count($costsEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $costsEn->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Costs') ?>
                </label>
                <?= $this->formInput($costsEn) ?>
                <?= $this->formElementErrors($costsEn) ?>
            </div>
            <?php
            $descriptionEn = $form->get('descriptionEn');
            $descriptionEn->setAttribute('class', 'form-control form-control-english markdown-editor');
            $descriptionEn->setAttribute('style', 'width:100%; height:10em; resize:none');
            $descriptionEn->setAttribute('data-provide', 'markdown');
            $descriptionEn->setAttribute('id', 'description-en');
            ?>
            <div class="form-group<?= count($descriptionEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $descriptionEn->getAttribute('id') ?>" class="control-label col-sm-2" style="margin-top:10px">
                    <?= $this->translate('Description') ?>
                </label>
                <?= $this->formRow($descriptionEn) ?>
                <?= $this->formElementErrors($descriptionEn) ?>
            </div>
        </div>
        <div class="col-md-12">
            <?php
            $canSignUp = $form->get('canSignUp');
            ?>
            <div class="form-group<?= count($canSignUp->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label>
                    <?= $this->formCheckbox($canSignUp) ?>
                    <?= $this->translate('Enable subscriptions') ?>
                    <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if people need to subscribe to this activity.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    <?= $this->formElementErrors($canSignUp) ?>
                </label>
            </div>
            <?php
            $isFood = $form->get('isFood');
            ?>
            <div class="form-group<?= count($isFood->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label>
                    <?= $this->formCheckbox($isFood) ?>
                    <?= $this->translate('This is a food subscription list') ?>
                    <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if the activity is a food subscription list, it then won\'t be displayed on the information screens.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    <?= $this->formElementErrors($isFood) ?>
                </label>
            </div>
            <?php
            $isMyFuture = $form->get('isMyFuture');
            ?>
            <div class="form-group<?= count($isMyFuture->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label>
                    <?= $this->formCheckbox($isMyFuture) ?>
                    <?= $this->translate('This is a My Future related activity') ?>
                    <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('If this is checked the My Future logo will be displayed on the activity page.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    <?= $this->formElementErrors($isMyFuture) ?>
                </label>
            </div>


            <?php
            $organ = $form->get('organ');
            $organ->setAttribute('class', 'form-control');
            $organ->setAttribute('id', 'organizing-organ');
            ?>
            <div class="form-group<?= count($organ->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $organ->getAttribute('id'); ?>" class="control-label col-sm-2">
                    <?= $this->translate('Organizing committee / fraternity') ?>
                </label>
                <div class="col-sm-10">
                    <?= $this->formSelect($organ) ?>
                    <?= $this->formElementErrors($organ) ?>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <?php
            /* render template for fields */
            $fs = $form->get('fields')->getTemplateElement();
            ob_start();
            echo $this->partial('partial/field-fieldset.phtml', ['fs' => $fs, 'index' => '__index__']);
            $tpl = trim(ob_get_clean())
            ?>
            <h3><?= $this->translate('Additional signup fields') ?></h3>
            <fieldset id="additionalFields">
                <span class="template" data-template="<?= $this->escapeHtmlAttr($tpl) ?>"></span>
                <?php
                $index = 0;
                foreach ($form->get('fields')->getIterator() as $fs){
                    echo $this->partial('partial/field-fieldset.phtml', ['fs' => $fs, 'index' => $index]);
                    $index++;
                }
                ?>
                <div class="form-group add-field">
                    <button class="btn btn-danger" type="button" onclick="return Activity.removeField()">
                        <span class="glyphicon glyphicon-minus"></span>
                        <?= $this->translate('Remove the last field') ?>
                    </button>
                    <button class="btn btn-success" type="button" onclick="return Activity.addField()">
                        <span class="glyphicon glyphicon-plus"></span>
                        <?= $this->translate('Add a field') ?>
                    </button>
                </div>
            </fieldset>
        </div>
        <div class="col-md-12">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($this->translate('Create activity'));
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <div class="form-group">
                <?= $this->formButton($submit) ?>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<script>
    $('[name="beginTime"]').datetimepicker();
    $('[name="endTime"]').datetimepicker();
    $('[name="subscriptionDeadline"]').datetimepicker();
    $('.markdown-editor').each(function() {
      $(this).markdown();
    });
    Activity.updateForm();
    for (var i = 0; i < <?= $index ?>; i++) {
        Activity.updateFieldset(i);
    }
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
