<?php $i = 0; ?>
    <div class="row">
	<div class="col-md-12">
		<button style="width:100%" onclick="window.location.href='activity/create'" class="btn btn-primary"><?php echo $this->translate('Create Activity'); ?></button>
	</div>
</div>

<div style="<?php if($i%2==0){echo("background:#CCCCCC;");}$i++; ?> margin-top:30px" class="row">
    <div class="col-md-1"><?php echo $this->translate('Id');?>:</div>
    <div class="col-md-2"><?php echo $this->translate('Name');?>:</div>
    <div class="col-md-2"><?php echo $this->translate('Start time');?>:</div>
    <div class="col-md-2"><?php echo $this->translate('End time');?>:</div>
    <div class="col-md-1"><?php echo $this->translate('Location');?>:</div>
    <div class="col-md-1"><?php echo $this->translate('Costs');?>:</div>
</div>

<?php foreach($activities as $activity):?>
    <div style="<?php if($i%2==0){echo("background:#CCCCCC;");}$i++; ?>" class="row">
        <div class="col-md-1"><?php echo $activity->get('id');?></div>
        <div class="col-md-2"><?php echo $activity->get('name');?></div>
        <div class="col-md-2"><?php echo $activity->get('beginTime')->format('Y-m-d H:i:s');?></div>
        <div class="col-md-2"><?php echo $activity->get('endTime')->format('Y-m-d H:i:s');?></div>
        <div class="col-md-1"><?php echo $activity->get('location');?></div>
        <div class="col-md-1"><?php echo $activity->get('costs');?></div>
        <div class="col-md-1"><a href="<?php echo $this->url('activity/' .(isset($admin) ? 'admin_' : ''). 'view', array( 'id' => $activity->get('id')))?>">
                <?php echo $this->translate('View');?></a>
        </div>
    </div>
<?php endforeach;?>


</table>
