<ul class="list-group">
<?php foreach($activities as $activity):?>
    <li class="list-group-item agenda-item row">
        <div class="agenda-item-heading col-md-2">
            <span class="badge">
                <span class="text-lowercase small"><?= $activity->getBeginTime()->format('M') ?></span>
                <?= $activity->getBeginTime()->format('d') ?>
            </span>
        </div>
        <div class="agenda-item-body col-md-10">
            <div class="row">
            <div class="col-md-12">
                <h4><?= $activity->getName() ?></h4>
            </div>
            <div class="col-md-8">
                <p><?= $activity->getDescription() ?></p>
            </div>
            <div class="col-md-4">
                Start: <?php echo $activity->getBeginTime()->format('Y-m-d H:i:s');?>
                End: <?php echo $activity->getEndTime()->format('Y-m-d H:i:s');?>

                Location: <?php echo $activity->getLocation();?>

                Costs: <?php echo $this->translate((string)$activity->getCosts());?>

                Subscribe before: <?php echo $activity->getSubscriptionDeadline()->format('Y-m-d H:i:s');?>

                <a href="<?php echo $this->url((isset($admin) ? 'admin_activity' : 'activity'). '/view', ['id' => $activity->getId()])?>">
                    <?php echo $this->translate('View');?>
                </a>
            </div>
            </div>
        </div>
    </li>
<?php endforeach;?>
</ul>
