<?php

declare(strict_types=1);

use Activity\Model\Activity;
use Activity\Model\SignupList as SignupListModel;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var Activity[] $activities
 */
?>
<?php if (0 !== count($activities)): ?>
    <ul class="list-group">
        <?php foreach ($activities as $activity): ?>
            <li class="list-group-item agenda-item">
                <div class="row">
                    <div class="agenda-item-heading col-md-2 hidden-xs hidden-sm">
                        <span class="badge badge-large">
                            <span class="small">
                                <?= strtr($this->dateFormat($activity->getBeginTime(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, null, $this->translate('MMM d')), array(' ' => '<br>')); ?>
                            </span>
                        </span>
                    </div>
                    <div class="agenda-item-body col-xs-12 col-md-10">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>
                                    <a href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                                        <?= $this->escapeHtml($this->localiseText($activity->getName())) ?>
                                    </a>
                                </h4>
                                <?php
                                $beginTime = $activity->getBeginTime();
                                $endTime = $activity->getEndTime();
                                $currentYear = date('Y');
                                $isSameDay = $beginTime->format('Y-m-d') === $endTime->format('Y-m-d');

                                if ($isSameDay) {
                                    $beginDayPattern = ($beginTime->format('Y') === $currentYear) ? 'EEEE d MMM. HH:mm' : 'EEEE d MMM. yyyy HH:mm';
                                    $beginDay = $this->dateFormat($beginTime, pattern: $beginDayPattern);
                                    $endDay = $this->dateFormat($endTime, pattern: 'HH:mm');
                                } else {
                                    $beginDayPattern = ($beginTime->format('Y') === $currentYear) ? 'EEE. d MMM. (HH:mm)' : 'EEE. d MMM. yyyy (HH:mm)';
                                    $endDayPattern = ($endTime->format('Y') === $currentYear) ? 'EEE. d MMM. (HH:mm)' : 'EEE. d MMM. yyyy (HH:mm)';
                                    $beginDay = $this->dateFormat($beginTime, pattern: $beginDayPattern);
                                    $endDay = $this->dateFormat($endTime, pattern: $endDayPattern);
                                }

                                $dateTimeString = sprintf('%s - %s', $beginDay, $endDay);

                                $currentTime = new DateTime('now');
                                $isOngoing = $currentTime >= $beginTime && $currentTime <= $endTime;
                                ?>
                                <p class="date-details">
                                    <?= ucfirst($dateTimeString) ?> <small class="text-muted">
                                        <?php if ($isOngoing): ?>
                                            <?= $this->translate('for') ?> <?= $timeRemaining = $this->timeDiff($currentTime, $endTime) ?>
                                        <?php elseif ($currentTime < $beginTime): ?>
                                            <?= $this->translate('in') ?> <?= $this->timeDiff($currentTime, $beginTime) ?>
                                        <?php endif; ?>
                                    </small>
                                    <?php
                                    $signupLists = $activity->getSignupLists()->toArray();
                                    $firstSignupList = reset($signupLists);
                                    $hasMoreThanOne = count($signupLists) > 1;

                                    if ($firstSignupList): ?>
                                        <?php
                                        /** @var SignupListModel $firstSignupList */
                                        $openDatePattern = ($firstSignupList->getOpenDate()->format('Y') === $currentYear) ? 'EEE. d MMM. (HH:mm)' : 'EEE. d MMM. yyyy (HH:mm)';
                                        $closeDatePattern = ($firstSignupList->getCloseDate()->format('Y') === $currentYear) ? 'EEE. d MMM. (HH:mm)' : 'EEE. d MMM. yyyy (HH:mm)';
                                        $openDateFormatted = $this->dateFormat($firstSignupList->getOpenDate(), pattern: $openDatePattern);
                                        $closeDateFormatted = $this->dateFormat($firstSignupList->getCloseDate(), pattern: $closeDatePattern);
                                        $timeDiff = $firstSignupList->getCloseDate()->diff($currentTime);

                                        if ($timeDiff->days >= 7) {
                                            $textClass = 'text-muted';
                                        } elseif ($timeDiff->days < 7 && $timeDiff->days >= 1) {
                                            $textClass = 'text-warning';
                                        } else {
                                            $textClass = 'text-danger';
                                        }
                                        ?>
                                        <br>
                                        <?php if ($currentTime > $firstSignupList->getCloseDate()): ?>
                                            <small class="text-muted">
                                                <?php sprintf(
                                                    $this->translate('Sign-up closed on: %s'),
                                                    $closeDateFormatted,
                                                ) ?>
                                            </small>
                                        <?php elseif (!$firstSignupList->isOpen()): ?>
                                            <small class="text-muted">
                                                <?= sprintf(
                                                    $this->translate('Sign-up opens: %s (in %s)'),
                                                    $openDateFormatted,
                                                    $this->timeDiff($currentTime, $firstSignupList->getOpenDate()),
                                                ) ?>
                                            </small>
                                        <?php else: ?>
                                            <small class="<?= $textClass ?>">
                                                <?= sprintf(
                                                    $this->translate('Sign-up closes: %s (in %s)'),
                                                    $closeDateFormatted,
                                                    $this->timeDiff($currentTime, $firstSignupList->getCloseDate()),
                                                ) ?>
                                            </small>
                                        <?php endif; ?>
                                        <?php if ($hasMoreThanOne): ?>
                                            <small class="text-muted">
                                                <?= $this->translate('with multiple sign-up lists') ?>
                                            </small>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </p>
                            </div>
                            <div class="col-md-12">
                                <?php foreach ($activity->getCategories() as $category): ?>
                                    <div class="chip chip-small chip-outlined">
                                        <span class="chip-label">
                                            <?= $this->escapeHtml($this->localiseText($category->getName())) ?>
                                        </span>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <div class="col-md-12 markdown">
                                <?= strip_tags(
                                    $this->markdown($this->localiseText($activity->getDescription())),
                                    ['<p>', '<del>', '<em>', '<strong>', '<a>'],
                                ) ?>
                            </div>
                            <div class="col-md-12">
                                <hr>
                                <small class="text-muted">
                                    <?= sprintf(
                                        '%s - %s',
                                        $this->escapeHtml($this->localiseText($activity->getCosts())),
                                        $this->escapeHtml($this->localiseText($activity->getLocation())),
                                    ) ?>
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><?= $this->translate('There are no activities.') ?></p>
<?php endif; ?>
