<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<ul class="list-group">
    <?php foreach ($activities as $activity): ?>
        <li class="list-group-item agenda-item">
            <div class="row">
                <div class="agenda-item-heading col-md-2">
                    <span class="badge badge-large">
                        <span class="small">
                            <?= strtr($this->dateFormat($activity->getBeginTime(), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE, null, $this->translate('MMM d')), array(' ' => '<br>')); ?>
                        </span>
                    </span>
                </div>
                <div class="agenda-item-body col-md-10">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>
                                <?php if (!isset($proposals)): ?>
                                    <a href="<?php echo $this->url((isset($admin) ? 'activity_admin_approval' : 'activity') . '/view', ['id' => $activity->getId()]) ?>">
                                        <?= $this->escapeHtml($activity->getName()->getText($lang)) ?>
                                    </a>
                                <?php else: ?>
                                    <?php $proposal = $proposals[$activity->getId()] ?>
                                    <a href="<?php echo $this->url('activity_admin_approval/proposal', ['id' => $proposal->getId()]) ?>">
                                        <?= $this->translate('Proposal to update into: ') . $this->escapeHtml($activity->getName()->getText($lang)) ?>
                                    </a>
                                <?php endif; ?>
                            </h4>
                        </div>
                        <div class="col-md-8 reveal reveal-10">
                            <p><?= strip_tags($this->markdown($activity->getDescription()->getText($lang))) ?></p>
                            <a class="reveal-button"><?= $this->translate('Continue reading') ?></a>
                        </div>
                        <div class="col-md-4">
                            <dl>
                                <dt><?= $this->translate('Start') ?></dt>
                                <dd><?= $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT); ?></dd>
                                <dt><?= $this->translate('End') ?></dt>
                                <dd><?= $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT); ?></dd>

                                <dt><?= $this->translate('Location') ?></dt>
                                <dd><?= $this->escapeHtml($activity->getLocation()->getText($lang)) ?></dd>
                                <?php if ($activity->getSubscriptionDeadline() != $activity->getEndTime()) : ?>
                                    <dt><?= $this->translate('Subscribe before') ?></dt>
                                    <dd><?= $this->dateFormat($activity->getSubscriptionDeadline(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT); ?></dd>
                                <?php endif; ?>
                                <dt><?= $this->translate('Costs') ?></dt>
                                <dd><?= $this->escapeHtml($activity->getCosts()->getText($lang)) ?></dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    <?php if (isset($moreLink)): ?>
        <li class="list-group-item agenda-item">
            <h4><a href="<?= $moreLink; ?>"><?= $this->translate('More'); ?></a></h4>
        </li>
    <?php endif; ?>
</ul>
<script type="application/javascript">
    $(".reveal-button").click(function () {
        $(this).parent().addClass("revealed");
    });
</script>
