<?php if(isset($error)):?>
<div class="alert alert-danger" role="alert"><?php echo $error;?></div>
<?php endif;?>
<?php if(isset($success)):?>
	<div class="row">
		<div class="col-md-4">
			<div class="alert alert-success" role="alert"><?php echo $this->translate('Successfully unsubscribed');?>:</div>
		</div>
	</div>
<?php endif;?>

<?php echo $this->partial('activity/activity/view.phtml', [
        'activity' => $activity,
        'isLoggedIn' => $isLoggedIn,
        'isSignedUp' => $isSignedUp,
        'canSignUp' => $canSignUp,
        'signedUp' => $signedUp,
        'signupData' => $signupData,
        'form' => $form,
        'fields' => $fields
		
]);?>
