<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('activity') ?>">
                    <?= $this->translate('Activities') ?>
                </a>
            </li>
            <li class="active">
                <?= $activity->getName() ?>
            </li>
        </ol>
    </div>
</section>

<?php if(isset($error)):?>
    <div class="alert alert-danger" role="alert">
        <div class="container">
            <span class="glyphicon glyphicon-remove"></span>&nbsp;<?= $error ?>
        </div>
    </div>
<?php endif;?>
<?php if(isset($success)):?>
    <div class="alert alert-success" role="alert">
        <div class="container">
            <span class="glyphicon glyphicon-ok"></span>&nbsp;<?= $this->translate('Successfully subscribed') ?>
        </div>
    </div>
<?php endif;?>

<?php echo $this->partial('activity/activity/view.phtml', [
        'activity' => $activity,
        'isLoggedIn' => $isLoggedIn,
        'isSignedUp' => $isSignedUp,
        'signupOpen' => $signupOpen,
	    'signedUp' => $signedUp,
        'signupData' => $signupData,
        'form' => $form,
        'signoffForm' => $signoffForm,
        'fields' => $fields,
        'breadcrumb' => true
]);?>
