<?php echo $this->doctype(); ?>
<?php
$this->scriptUrl()->requireUrl('user/pinlogin')
    ->requireUrl('activity_api/list')
    ->requireUrl('activity_api/signedup')
    ->requireUrl('user/logout')
    ->requireUrls([
        'activity_api/signup',
        'activity_api/signoff'
    ], ['id']);
?>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Raleway:700,400,300')
        ->prependStylesheet($this->basePath() . '/css/activity-touch.css')
        ->prependStylesheet($this->basePath() . '/css/gewis-theme.css')
    ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/iscroll.js')
        ->prependFile($this->basePath() . '/js/activity-touch.js')
        ->prependFile($this->basePath() . '/js/url-helper.js'); ?>

    <script type="text/javascript">
        $(document).ready(function () {
            setTimeout(function () {
                var scroller = new IScroll('#wrapper', {
                    mouseWheel: true,
                    scrollbars: true,
                    tap: true
                });
            }, 500);
        });
    </script>
</head>
<body>

<nav class="navbar navbar-gewis navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">
                <img src="<?= $this->basePath() ?>/img/gewis-branding.svg" alt="<?= $this->translate('GEWIS Logo') ?>">
            </a>
        </div>

        <ul class="nav navbar-nav">
            <li>
                <h3><?= $this->translate('Signup for GEWIS activities'); ?></h3>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right logged-in">
            <li onclick="Activity.Touch.logout()"><h3><?= $this->translate('Logout') ?></h3></a></li>
        </ul>
    </div>
</nav>
<div id="content">
    <div class="jumbotron jumbotron-mini" style="background-image: url(<?= $this->basePath() ?>/img/panorama.jpg);">
    </div>

    <div class="container-fluid">
        <div class="panel panel-primary not-logged-in">
            <div class="panel-heading">
                <strong><?= $this->translate('Log in') ?></strong>
            </div>
            <div class="panel-body">
                <div class="row">
                    <?= $this->translate('To sign up for an activity you must login using an RFID pass or your SuSOS pincode.') ?>
                    <div class="col-md-4 col-md-offset-4">
                        <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                                data-target="#loginModal">
                            <?= $this->translate('Login') ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-primary logged-in">
            <div class="panel-heading">
                <strong><?= $this->translate('Welcome') ?></strong>
            </div>
            <div class="panel-body">
                <div class="row">
                    <?= sprintf($this->translate('Welcome %s. Tap an activity to view it.'),
                        '<span id="fullName"></span>') ?>
                </div>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><strong><?= $this->translate('Upcoming activities') ?></strong></div>
        </div>
    </div>
</div>
<div id="activities" class="container-fluid">
    <div>
        <div id="wrapper">
            <div id="scroller">
                <div class="panel-body">
                    <table class="table">
                        <tbody id="activityList" class="more-padding">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="loginModalLabel"><?= $this->translate('Login') ?></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="loginFailed" role="alert">
                    <strong><?= $this->translate('Login failed') ?>,</strong>
                    <?= $this->translate('Incorrect membership number or pin') ?>
                </div>
                <form class="form-horizontal">
                    <div class="form-group form-group-lg">
                        <label class="col-sm-3 control-label"
                               for="lidnrInput"><?= $this->translate('GEWIS #') ?></label>

                        <div class="col-sm-6">
                            <input class="form-control digit-input" autocomplete="off" type="text" id="lidnrInput"
                                   placeholder="0000">
                        </div>
                    </div>
                    <div class="form-group form-group-lg">
                        <label class="col-sm-3 control-label" for="pinInput"><?= $this->translate('Pin') ?></label>

                        <div class="col-sm-6">
                            <input class="form-control digit-input" autocomplete="off" type="password" maxlength="4"
                                   id="pinInput" placeholder="****">
                        </div>
                    </div>
                </form>
                <br>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="1">1</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="2">2</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="3">3</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="4">4</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="5">5</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="6">6</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="7">7</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="8">8</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="9">9</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="-1"></button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="0">0</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="-1">&lt;--</button>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Activity Modal -->
<div class="modal fade" id="activityModal" tabindex="-1" role="dialog" aria-labelledby="activityModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="activityModalLabel">Activity</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <table>
                            <tr>
                                <td><strong><?= $this->translate('Date / time') ?></strong>
                                </td>
                                <td id="activityDateTime"></td>
                            </tr>
                            <tr>
                                <td><strong><?= $this->translate('Location') ?></strong></td>
                                <td id="activityLocation"></td>
                            </tr>
                            <tr>
                                <td><strong><?= $this->translate('Costs') ?></strong></td>
                                <td id="activityCosts"></td>
                            </tr>
                            <tr>
                                <td><strong><?= $this->translate('Attendees') ?></strong></td>
                                <td id="activityAttendeeCount"></td>
                            </tr>
                        </table>
                        <div id="activitySubscribe" class="logged-in">
                            <button
                                class="btn btn-primary btn-lg btn-block"><?= $this->translate('Subscribe') ?></button>
                        </div>
                        <div id="activityUnsubscribe" class="logged-in">
                            <button
                                class="btn btn-danger btn-lg btn-block"><?= $this->translate('Unsubscribe') ?></button>
                        </div>

                        <div id="subscribeFailed" class="alert alert-danger" style="display: none" role="alert">
                            <strong><?= $this->translate('Activity subscription failed') ?>,</strong>
                            <?= $this->translate('please try again later or use the website.') ?>
                        </div>
                        <div id="unsubscribeFailed" class="alert alert-danger" style="display: none" role="alert">
                            <strong><?= $this->translate('Failed to unsubscribe from this activity') ?>,</strong>
                            <?= $this->translate('please try again later or use the website.') ?>
                        </div>
                        <div class="not-logged-in">
                            <?= $this->translate('To sign up for an activity you must login using an RFID pass or your SuSOS pincode.') ?>
                            <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                                    data-target="#loginModal">
                                <?= $this->translate('Login') ?>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-8" id="activityDescription">

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-hover">
                            <tbody id="attendeeList">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="activityModalLabel">Logout</h4>
            </div>
            <div class="modal-body">
                <h2>You will be logged out in <span id="logoutSeconds">10</span> seconds.</h2>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php echo $this->inlineScript() ?>
<script>
    <?php foreach($this->scriptUrl()->getUrls() as $name => $url): ?>
    URLHelper.addUrl('<?= $name ?>', '<?= urldecode($url) ?>');
    <?php endforeach; ?>
</script>
<script>
    $(document).ready(function () {
        Activity.Touch.init();
    });
</script>
</body>
</html>
