<?php echo $this->doctype(); ?>
<?php
    $this->scriptUrl()->requireUrl('user/pinlogin')
                      ->requireUrl('activity_api/list');
?>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Raleway:700,400,300')
        ->prependStylesheet($this->basePath() . '/css/gewis-theme.css') ?>
    <style>
        body {
            overflow: hidden;
        }

        #wrapper {
            position: absolute;
            z-index: 1;
            top: 450px;
            bottom: 10px;
            left: 0;
            width: 100%;
            overflow: hidden;
        }

        #scroller {
            position: absolute;
            z-index: 1;
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
            width: 100%;
            -webkit-transform: translateZ(0);
            -moz-transform: translateZ(0);
            -ms-transform: translateZ(0);
            -o-transform: translateZ(0);
            transform: translateZ(0);
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
            -webkit-text-size-adjust: none;
            -moz-text-size-adjust: none;
            -ms-text-size-adjust: none;
            -o-text-size-adjust: none;
            text-size-adjust: none;
        }

        .navbar-inverse {
            color: #fff;
            background-color: #D40026;
        }

        .jumbotron-header > .container {
            height: 150px;
        }

        .panel-primary > .panel-heading {
            background-color: #D40026;
            font-size: 20px;
        }

        #activities > tbody > tr > td {
            padding-top: 20px;
            padding-bottom: 20px;
            font-size: 38px;
            overflow: hidden;
        }

        .panel-body {
            font-size: 28px;
        }

        .more-padding {
            padding-top: 200px;
            padding-bottom: 20px;
        }

        #content {
            background-color: #fff;
            width: 100%;
            z-index: 100;
            position: fixed;
            padding-top: 20px;
        }

        .container-fluid {
            padding-top: 20px;
        }

        #activityModal > .modal-dialog {
            position: absolute;
            top: 50% !important;
            transform: translate(0, -50%) !important;
            -ms-transform: translate(0, -50%) !important;
            -webkit-transform: translate(0, -50%) !important;
            margin: auto 5%;
            width: 90%;
            height: 80%;
        }

        #loginModal > .modal-dialog {
            position: absolute;
            top: 50% !important;
            transform: translate(0, -50%) !important;
            -ms-transform: translate(0, -50%) !important;
            -webkit-transform: translate(0, -50%) !important;
            margin-left: 35%;
            width: 30%;
            height: 58%;
        }

        .modal-content {
            min-height: 100%;
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .modal-body {
            position: absolute;
            top: 45px;
            bottom: 45px;
            left: 0;
            right: 0;
            overflow-y: auto;
        }

        .modal-footer {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .modal-title {
            text-align: center;

        }

        .btn-keypad {
            width: 100%;
            /* Hack to make height equal to width */
            height: 0;
            padding-bottom: 20%;
            padding-top: 15%;

            line-height: 100%;
        }

        .digit-input {
            text-align: center;
        }
    </style>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/iscroll.js')
        ->prependFile($this->basePath() . '/js/activity-touch.js')
        ->prependFile($this->basePath() . '/js/url-helper.js'); ?>

    <script type="text/javascript">
        $(document).ready(function () {
            setTimeout(function () {
                myScroll = new IScroll('#wrapper', {
                    mouseWheel: true,
                    scrollbars: true
                });
            }, 500);
        });
    </script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <h3><?= $this->translate('Signup for GEWIS activities'); ?></h3>
        </div>
    </div>
</nav>
<div id="content">
    <div class="jumbotron jumbotron-header">
        <div class="container hidden-xs">
            <br><br><br><br>
        </div>
    </div>

    <div class="container-fluid">
        <div class="panel panel-primary">
            <div class="panel-heading"><strong><?= $this->translate('Log in') ?></strong></div>
            <div class="panel-body">
                <?= $this->translate('To sign up for an activity you must login using an RFID pass or your SuSOS pincode.') ?>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#loginModal">
                    <?= $this->translate('Login') ?>
                </button>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><strong><?= $this->translate('Upcoming activities') ?></strong></div>
        </div>
    </div>
</div>
<div id="activities" class="container-fluid">
    <div>
        <div id="wrapper">
            <div id="scroller">
                <div class="panel-body">
                    <table class="table table-hover">
                        <tbody class="more-padding">
                            <tr>
                                <td>Date</td>
                                <td>Time</td>
                                <td>Activity</td>
                                <td>Price</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Login Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="loginModalLabel"><?= $this->translate('Login') ?></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" style="display: none" id="loginFailed" role="alert">
                    <strong><?= $this->translate('Login failed') ?>,</strong>
                    <?= $this->translate('Incorrect membership number or pin') ?>
                </div>
                <form class="form-horizontal">
                             <div class="form-group form-group-lg">
                                <label class="col-sm-3 control-label" for="lidnrInput"><?= $this->translate('GEWIS #') ?></label>
                                <div class="col-sm-6">
                                    <input class="form-control digit-input" autocomplete="off" type="text" id="lidnrInput" placeholder="0000">
                                </div>
                            </div>
                    <div class="form-group form-group-lg">
                        <label class="col-sm-3 control-label" for="pinInput"><?= $this->translate('Pin') ?></label>
                        <div class="col-sm-6">
                            <input class="form-control digit-input" autocomplete="off" type="password" maxlength="4" id="pinInput" placeholder="****">
                        </div>
                    </div>
                </form>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="1">1</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="2">2</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="3">3</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="4">4</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="5">5</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="6">6</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="7">7</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="8">8</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="9">9</button>
                    </div>
                </div>
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="-1"></button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="0">0</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-default btn-keypad" value="-1"><--</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Activity Modal -->
<div class="modal fade" id="activityModal" tabindex="-1" role="dialog" aria-labelledby="activityModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="activityModalLabel">Activity</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<?php echo $this->inlineScript() ?>
<script>
    <?php foreach($this->scriptUrl()->getUrls() as $name => $url): ?>
    URLHelper.addUrl('<?= $name ?>', '<?= urldecode($url) ?>');
    <?php endforeach; ?>
</script>
<script>
    $(document).ready(function () {
        Activity.Touch.init();
    });
</script>
</body>
</html>
