<?php

declare(strict_types=1);

use Activity\Form\Signup as SignupForm;
use Activity\Model\{
    Activity as ActivityModel,
    SignupField as SignupFieldModel,
};
use Application\Form\ModifyRequest as RequestForm;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ActivityModel $activity
 * @var SignupFieldModel $fields
 * @var SignupForm $form
 * @var bool $isAllowedToSubscribe
 * @var bool $isArchived
 * @var bool $isSignedUp
 * @var int $memberSignups
 * @var bool $signupOpen
 * @var RequestForm $signoffForm
 * @var bool $subscriptionCloseDatePassed
 */

// set title
$this->headTitle($this->escapeHtml($this->localiseText($activity->getName())));
$this->headTitle($this->translate('Activities'));
?>
<?php if (!isset($breadcrumb)): // only show breadcrumbs if they were not yet shown ?>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <a href="<?= $this->url('activity') ?>">
                        <?= $this->translate('Activities') ?>
                    </a>
                </li>
                <?php if (!isset($signupList)): ?>
                    <li class="active">
                        <?= $this->escapeHtml($this->localiseText($activity->getName())) ?>
                    </li>
                <?php else: ?>
                    <li>
                        <a href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                            <?= $this->escapeHtml($this->localiseText($activity->getName())) ?>
                        </a>
                    </li>
                    <li class="active">
                        <?= $this->escapeHtml($this->localiseText($signupList->getName())) ?>
                    </li>
                <?php endif; ?>
            </ol>
        </div>
    </section>
<?php endif; ?>

<section class="section">
    <div class="container">
        <div class="row">
            <?= $this->flashMessenger()->render('default', ['alert', 'alert-dismissible', 'alert-info']) ?>
            <?= $this->flashMessenger()->render('error', ['alert', 'alert-dismissible', 'alert-danger']) ?>
            <?= $this->flashMessenger()->render('info', ['alert', 'alert-dismissible', 'alert-info']) ?>
            <?= $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']) ?>
            <?= $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'alert-warning']) ?>
            <div class="col-md-12">
                <h1><?= $this->escapeHtml($this->localiseText($activity->getName())) ?></h1>
            </div>
            <div class="col-md-12">
                <?php foreach ($activity->getCategories() as $category): ?>
                    <div class="chip chip-small chip-outlined">
                                    <span class="chip-label">
                                        <?= $this->escapeHtml($this->localiseText($category->getName())) ?>
                                    </span>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="col-md-12">
                <div class="row agenda-item">
                    <div class="col-md-9">
                        <div class="agenda-item-body">
                            <p><?= $this->markdown($this->localiseText($activity->getDescription())) ?></p>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="agenda-item-details">
                            <dl>
                                <dt><?= $this->translate('Start') ?></dt>
                                <dd><?= $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT); ?></dd>

                                <dt><?= $this->translate('End') ?></dt>
                                <dd><?= $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT); ?></dd>

                                <dt><?= $this->translate('Location') ?></dt>
                                <dd><?= $this->escapeHtml($this->localiseText($activity->getLocation())) ?></dd>

                                <dt><?= $this->translate('Costs') ?></dt>
                                <dd><?= $this->escapeHtml($this->localiseText($activity->getCosts())) ?></dd>
                                <?php if ($activity->getIsMyFuture()): ?>
                                    <a href="https://myfuture.tue.nl/">
                                        <img
                                            class="img-responsive"
                                            style="max-width: 125px;"
                                            src="/img/myfuture.png"
                                        />
                                    </a>
                                <?php endif ?>

                                <?php
                                $begin = $activity->getBeginTime()->format('Ymd\THis');
                                $end = $activity->getEndTime()->format('Ymd\THis');
                                $link = 'https://calendar.google.com/calendar/render?action=TEMPLATE&';
                                $link .= http_build_query([
                                    'text' => $this->localiseText($activity->getName()),
                                    'dates' => $begin . '/' . $end,
                                    'location' => $this->localiseText($activity->getLocation()),
                                    'details' => $this->url('activity/view', ['id' => $activity->getId()], ['force_canonical' => true]),
                                ]);
                                ?>

                                <a class="btn btn-default" target="_blank" href="<?php echo $link ?>"> Google
                                    Calendar </a>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php if (isset($signupLists)): ?>
            <div class="row">
                <div class="col-md-12">
                    <h2><?= $this->translate('Sign-up Lists') ?></h2>
                </div>
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <?php foreach ($signupLists as $list): ?>
                            <li role="presentation" <?= isset($signupList) ? ($signupList->getId() === $list['id'] ? 'class="active"' : '') : '' ?>>
                                <a href="<?= $this->url('activity/view/signuplist', ['id' => $activity->getId(), 'signupList' => $list['id']]) ?>"><?= $this->escapeHtml($this->localiseText($list['name'])) ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-12">
                <?php
                $organString = $this->translate("the organizing party");
                $boardString = "<a href='mailto:cib@gewis.nl'>cib@gewis.nl</a>";
                $organ = $activity->getOrgan();

                if (null !== $organ) {
                    $organString = "<a href='" . $this->url('home/organ', ['abbr' => $organ->getAbbr(), 'type' => $organ->getType()->value]) . "''>" . $this->escapeHtml($organ->getName()) . "</a>";
                }

                if ($activity->getIsMyFuture()) {
                    $boardString = "<a href='mailto:ceb@gewis.nl'>ceb@gewis.nl</a>";
                }

                $finalText = sprintf($this->translate("Please contact %s or the board (%s) with any questions, concerns or if you are unable to attend after the deadline for unsubscribing has passed. Have fun!"), $organString, $boardString);

                if (!isset($signupList)) {
                    $finalText = sprintf($this->translate("Please contact %s or the board (%s) with any questions or concerns. Have fun!"), $organString, $boardString);
                }

                ?>
                <p>
                    <?= $finalText ?>
                </p>
            </div>
        </div>
        <?php if (isset($signupList)): ?>
            <div class="row">
                <div class="col-md-12">
                    <p>
                        <?=
                        sprintf(
                            $this->translate('This sign-up list%sis open from <strong>%s</strong> till <strong>%s</strong>.'),
                            ($signupList->getLimitedCapacity()) ? $this->translate(' <strong>has a limited capacity</strong> and ') : ' ',
                            $this->dateFormat($signupList->getOpenDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                            $this->dateFormat($signupList->getCloseDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT)
                        )
                        ?>
                    </p>
                </div>
                <div class="col-md-12">
                    <?php if ($isSignedUp) : ?>
                        <button class="btn btn-default btn-lg agenda-subscription-button" type="button"
                                data-toggle="collapse" data-target="#subscriptionForm"
                                aria-expanded="false" aria-controls="subscriptionForm">
                            <?= $this->translate('Already subscribed') ?>
                        </button>
                    <?php elseif (!$signupOpen): ?>
                        <button class="btn btn-default btn-lg agenda-subscription-button" type="button"
                                data-toggle="collapse" data-target="#subscriptionForm"
                                aria-expanded="false" disabled="disabled"
                                aria-controls="subscriptionForm">
                            <?= $this->translate('Subscription closed') ?>
                        </button>
                    <?php else: ?>
                        <button class="btn btn-primary btn-lg agenda-subscription-button collapsed" type="button"
                                data-toggle="collapse" data-target="#subscriptionForm" aria-expanded="false"
                                aria-controls="subscriptionForm">
                            <span class="fas fa-chevron-right"></span> <?= $this->translate('Subscribe now') ?>
                        </button>
                    <?php endif; ?>
                </div>
                <div class="col-md-6 collapse activity-subscription-form" id="subscriptionForm">
                    <div class="well">
                        <?php if ($isSignedUp) : ?>
                            <h2><?= $this->translate('Unsubscribe yourself') ?></h2>
                            <?php if ($subscriptionCloseDatePassed) : ?>
                                <div>
                                    <?= $this->translate('You are not allowed to unsubscribe after the deadline!') ?>
                                </div>
                            <?php else : ?>
                                <div>
                                    <?php
                                    $signoffForm->setAttribute('action', $this->url('activity/signoff', ['id' => $activity->getId(), 'signupList' => $signupList->getId()]));
                                    $signoffForm->prepare();
                                    echo $this->form()->openTag($signoffForm);
                                    echo $this->formElement($signoffForm->get('security'));
                                    $submit = $signoffForm->get('submit');
                                    $submit->setAttribute('class', 'btn btn-default');
                                    echo $this->formSubmit($submit);
                                    echo $this->form()->closeTag();
                                    ?>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($signupOpen && !$isAllowedToSubscribe): ?>
                            <h2>
                                <?= $this->translate('Subscribe yourself') ?>
                            </h2>
                            <a href="<?= $this->url('user/login', ['user_type' => 'member']) ?>">
                                <?= $this->translate('Login to subscribe') ?>
                            </a>
                            <?php if (!$signupList->getOnlyGEWIS() && null !== $form): ?>
                                <br/>
                                <?= $this->translate('Or subscribe without a GEWIS membership: ') ?>
                                <?= $this->partial('partial/signupForm', [
                                    'form' => $form,
                                    'signupList' => $signupList,
                                ])
                                ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if (null !== $form && $signupOpen && !$isSignedUp && $isAllowedToSubscribe): //display the form ?>
                            <h2>
                                <?= $this->translate('Subscribe yourself') ?>
                            </h2>
                            <?= $this->partial('partial/signupForm', [
                                'form' => $form,
                                'signupList' => $signupList,
                            ])
                            ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-md-12 table-responsive agenda-subscriptions">
                    <h2><?= $this->translate('Current subscriptions') ?></h2>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th></th>
                            <th><?= $this->translate('Name') ?> </th>
                            <?php foreach ($fields as $field): ?>
                                <th><?= $this->escapeHtml($this->localiseText($field->getName())) ?></th>
                            <?php endforeach; ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 1; ?>
                        <?php if (!$this->acl('activity_service_acl')->isAllowed('signupList', 'viewDetails')): ?>
                            <tr>
                                <td align="center" colspan="<?= count($fields) + 2 ?>">
                                    <?php
                                    if ($signupList->getDisplaySubscribedNumber()) {
                                        echo sprintf($this->translate('The number of subscribed members is currently %d.'), $memberSignups) . '<br/>';
                                    }
                                    ?>
                                    <a href="<?= $this->url('user/login', ['user_type' => 'member']) ?>">
                                        <?= $this->translate('Login to view the subscribed members.') ?>
                                    </a>
                                </td>
                            </tr>
                        <?php endif; ?>
                        <?php if (!$isArchived || $this->acl('activity_service_acl')->isAllowed('signupList', 'viewDetails')): ?>
                            <?php foreach ($signupList->getSignUps() as $signup): ?>
                                <?php if (($signup instanceof Activity\Model\ExternalSignup) || $this->acl('activity_service_acl')->isAllowed('signupList', 'viewDetails')): ?>
                                    <tr>
                                        <td><?= $this->acl('activity_service_acl')->isAllowed('signupList', 'view') || $signupList->getDisplaySubscribedNumber() ? $i : '' ?></td>
                                        <td><?= $this->escapeHtml($signup->getFullName()) ?></td>
                                        <?php foreach ($fields as $field): ?>
                                            <?php foreach ($signup->getFieldValues() as $fieldValue): ?>
                                                <?php if ($fieldValue->getField()->getId() === $field->getId()): ?>
                                                    <td>
                                                        <?php
                                                        switch ($field->getType()) {
                                                            case 0:
                                                                echo $this->escapeHtml($fieldValue->getValue());
                                                                break;
                                                            case 1:
                                                                echo $this->translate($fieldValue->getValue());
                                                                break;
                                                            case 2:
                                                                echo $fieldValue->getValue();
                                                                break;
                                                            case 3:
                                                                echo $this->localiseText($fieldValue->getOption()->getValue());
                                                                break;
                                                        }
                                                        ?>
                                                    </td>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </tr>
                                    <?php $i = $i + 1; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
