<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Company\Model\{
    Company as CompanyModel,
    JobCategory as JobCategoryModel,
};
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyModel $company
 * @var JobCategoryModel[] $jobCategories
 */

$escaper = new Laminas\Escaper\Escaper('utf-8');

// If multiple companies are on display, the title should redirect to the company page, else, it should redirect to the website
$companyURL = $this->url(
    'company/companyItem', // Route url
    ['companySlugName' => $company->getSlugName()], // Url parameters
    [], // routeOptions
    true // Reuse matched parameters
);
?>
<div class="card company-card">
    <a href="<?= $companyURL ?>">
        <img src="<?= $this->fileUrl($company->getLogo()) ?>" class="card-image"
             alt="<?= $this->translate('Logo of') ?> <?= $escaper->escapeHtmlAttr($company->getName()) ?>" />
    </a>
    <div class="card-body">
        <a href="<?= $companyURL ?>">
            <h5 class="card-title"><?= $this->escapeHtml($company->getName()) ?></h5>
        </a>
        <h6 class="card-subtitle text-muted"><?= $this->escapeHtml($this->localiseText($company->getSlogan())) ?></h6>
        <ul>
            <?php $allEmpty = true; ?>
            <?php foreach ($jobCategories as $category): ?>
                <?php if (0 < ($activeJobsInCategory = $company->getNumberOfActiveJobs($category))): ?>
                    <?php $allEmpty = false; ?>
                    <li>
                        <a href="<?= $this->url(
                            'company/companyItem/joblist',
                            [
                                'companySlugName' => $company->getSlugName(),
                                'category' => $this->localiseText($category->getSlug()),
                            ],
                        ) ?>">
                            <?= $activeJobsInCategory ?> <?= $this->escapeHtml($this->localiseText(1 === $activeJobsInCategory ? $category->getName() : $category->getPluralName())) ?>
                        </a>
                    </li>
                <?php endif ?>
            <?php endforeach; ?>
            <?php if ($allEmpty): ?>
                <a href="<?= $companyURL ?>" class="stretched-link"></a>
            <?php endif; ?>
        </ul>
    </div>
</div>
