<?php
$escaper = new Laminas\Escaper\Escaper('utf-8');

// If multiple companies are on display, the title should redirect to the company page, else, it should redirect to the website
$companyURL = $this->url('company/companyItem', // Route url
    ['slugCompanyName' => $company->getSlugName()], // Url parameters
    [], // routeOptions
    true); // Reuse matched parameters

?>
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <div class="company-grid-item grid-item col-md-12" id="company-<?= $escaper->escapeHtmlAttr($company->getId()); ?>">
        <div class="company-grid-content">
            <a href="<?= $companyURL ?>" class="company-grid-logo">
                <img class="company-logo img-responsive"
                     src="<?= $escaper->escapeHtmlAttr($this->fileUrl($company->getTranslationFromLocale($locale)->getLogo())); ?>"
                     alt="<?= $this->translate('Logo of') ?> <?= $escaper->escapeHtmlAttr($company->getName()); ?>"/>
            </a>
            <div class="company-grid-text">
                <h4 class="company-name"><a href="<?= $companyURL ?>"><?= $company->getName() ?></a></h4>
                <p class="company-slogan"><em><?= $company->getTranslationFromLocale($locale)->getSlogan(); ?></em></p>
                <ul>
                    <?php foreach ($this->jobCategories() as $category): ?>
                        <?php if ($company->getNumberOfActiveJobs($category) > 0): ?>
                            <li>
                                <a href="<?= $this->url('company/companyItem/joblist', ['slugCompanyName' => $company->getSlugName(), 'category' => $category->getSlug()]) ?>">
                                    <?= $company->getNumberOfActiveJobs($category) ?> <?= $company->getNumberOfActiveJobs($category) === 1 ? $category->getName() : $category->getPluralName() ?>
                                </a>
                            </li>
                        <?php endif ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>

