# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/assets/styles/_*.scss'
            - '*/assets/styles/**/_*.scss'
        missing_import_mode: strict

sensiolabs_typescript:
    source_dir:
        - '%kernel.project_dir%/assets/controllers'
    swc_binary: /usr/local/bin/swc
    swc_config_file: '%kernel.project_dir%/.swcrc'

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
