# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            enabled: true
            field_name: '_csrf_token'
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
