# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            enabled: true

when@test:
    framework:
        profiler:
            collect: false
