engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,dist"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- config/**/*
- public/js/*
exclude_fingerprints:
    - e948223556c67058a98b8ff9ed19d4b2