#!/usr/bin/env php
<?php

if (php_sapi_name() != 'cli') {
    throw new RuntimeException("This script can only be called from the command line.");
}

// make sure we are in the correct directory
chdir(__DIR__);

require 'bootstrap.php';

$application = ConsoleRunner::getApplication();

/* @var $cli \Symfony\Component\Console\Application */
$cli = $application->getServiceManager()->get('doctrine.cli');
exit($cli->run());
