#!/bin/sh
dir="$PWD"
cd `dirname $0`

# parse php files
find ./module -iname "*.phtml" -print0 | sort -z | xargs -r0 xgettext \
    --language=PHP \
    --from-code=UTF-8 \
    --keyword=translate \
    --keyword=translatePlural:1,2 \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --no-location \
    --sort-output \
    --package-name=GEWISweb \
    --package-version=`git describe --dirty --always` \
    --copyright-holder=GEWIS \

find ./module -iname "*.php" -print0 | sort -z | xargs -r0 xgettext \
    --language=PHP \
    --from-code=UTF-8 \
    --keyword=translate \
    --keyword=translatePlural:1,2 \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --no-location \
    --sort-output \
    --package-name=GEWISweb \
    --package-version=`git describe --dirty --always` \
    --copyright-holder=GEWIS \
    --join-existing \

xgettext module/Application/language/additional-strings \
    --language=C \
    --from-code=UTF-8 \
    --extract-all \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --no-location \
    --sort-output \
    --package-name=GEWISweb \
    --package-version=`git describe --dirty --always` \
    --copyright-holder=GEWIS \
    --join-existing \

cd ./module/Application/language/

# merge translation files
msgmerge --sort-output -U nl.po gewisweb.pot
msgmerge --sort-output -U en.po gewisweb.pot

# remove obsolete translations
msgattrib --no-obsolete -o en.po en.po
msgattrib --no-obsolete -o nl.po nl.po

cd $dir
