#!/bin/bash
dir="$PWD"
cd `dirname $0`

# parse php files
find ./module -iname "*.phtml" -print0 | sort -z | xargs -r0 xgettext \
    --language=PHP \
    --keyword=translate \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --package-name=GEWISweb \
    --package-version=0.1.0-dev \
    --copyright-holder=GEWIS \

find ./module -iname "*.php" -print0 | sort -z | xargs -r0 xgettext \
    --language=PHP \
    --keyword=translate \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --package-name=GEWISweb \
    --package-version=0.1.0-dev \
    --copyright-holder=GEWIS \
    --join-existing \

xgettext module/Application/language/additional-strings \
    --output=./module/Application/language/gewisweb.pot \
    --force-po \
    --package-name=GEWISweb \
    --package-version=0.1.0-dev \
    --copyright-holder=GEWIS \
    --join-existing \
    --language=C \
    --extract-all \

cd ./module/Application/language/

# merge translation files
msgmerge --sort-by-file -U nl.po gewisweb.pot
msgmerge --sort-by-file -U en.po gewisweb.pot

cd $dir
