<?php if (!empty($albums)): ?>
<!-- simple table here for now -->
<table class="table table-striped">
    <thead>
    <tr>
        <th>Album name</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($albums as $album): ?>
    <tr>
        <td><a href="/photo/album/<?= $album->getId(); ?>"><?= $album->getName() ?></a></td>
        <td><a href="/photo/album/<?= $album->getId(); ?>"><?= $album->getDate()->format('Y-m-d H:i') ?></a></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>