<div class="scroller scroller-left"><i class="glyphicon glyphicon-chevron-left"></i></div>
<div class="scroller scroller-right"><i class="glyphicon glyphicon-chevron-right"></i></div>
<div class="wrapper">
    <ul class="nav nav-pills year-list" id="myTab">
        <?php foreach ($years as $year): ?>
            <li role="presentation" <?= $year == $activeYear ? 'class="active"' : '' ?>>
                <a href="<?= $this->url('photo/year', array('year' => $year)); ?>"><?= $year ?>/<?= $year + 1 ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<div class="row">
    <?php if (!empty($albums)): ?>
        <?php for ($i = 0; $i < count($albums); $i++): ?>
            <?php if($albums[$i]->getPhotoCount() > 0): ?>
            <?= ($i % 4 === 0) ? "</div><div class=\"row\">" : ""; ?>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail"
                   href="<?= $this->url('photo/album', array("album_id" => $albums[$i]->getId())); ?>">
                    <img class="img-responsive" src="<?= $this->fileUrl($albums[$i]->getCoverPath()) ?>" alt="">

                    <div class="caption">
                        <?= $albums[$i]->getName(); ?>
                    </div>
                </a>

            </div>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endif; ?>
</div>
<script>
    var hidWidth;
    var scrollBarWidths = 40;

    var widthOfList = function () {
        var itemsWidth = 0;
        $('.year-list li').each(function () {
            var itemWidth = $(this).outerWidth();
            itemsWidth += itemWidth;
        });
        return itemsWidth;
    };

    var widthOfHidden = function () {
        return (($('.wrapper').outerWidth()) - widthOfList() - getLeftPosition()) - scrollBarWidths;
    };

    var getLeftPosition = function () {
        return $('.year-list').position().left;
    };

    var reAdjust = function () {
        if (($('.wrapper').outerWidth()) < widthOfList()) {
            $('.scroller-right').show();
        }
        else {
            $('.scroller-right').hide();
        }

        if (getLeftPosition() < 0) {
            $('.scroller-left').show();
        }
        else {
            $('.item').animate({left: "-=" + getLeftPosition() + 'px'}, 'slow');
            $('.scroller-left').hide();
        }
        var activeItem = $('.year-list li.active:first');
        if (activeItem.position().left + activeItem.outerWidth()
            + scrollBarWidths + getLeftPosition() > $('.scroller-right:first').position().left) {
            $('.year-list').animate({left: '+=' + (widthOfHidden() - scrollBarWidths) + 'px'}, 'slow', function () { });
            $('.scroller-left').fadeIn('slow');
            $('.scroller-right').fadeOut('slow');
        }
    }

    reAdjust();

    $(window).on('resize', function (e) {
        reAdjust();
    });

    $('.scroller-right').click(function () {

        $('.scroller-left').fadeIn('slow');
        $('.scroller-right').fadeOut('slow');

        $('.year-list').animate({left: "+=" + widthOfHidden() + "px"}, 'slow', function () {

        });
    });

    $('.scroller-left').click(function () {

        $('.scroller-right').fadeIn('slow');
        $('.scroller-left').fadeOut('slow');

        $('.year-list').animate({left: "-=" + getLeftPosition() + "px"}, 'slow', function () {

        });
    });

</script>
