<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Form\SearchAlbum as SearchAlbumForm;
use Photo\Model\Album as AlbumModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var SearchAlbumForm $form
 * @var array<int, AlbumModel[]>|null $result
 * @var string|null $prompt
 */

$this->headTitle($this->translate('Search Albums'));
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php
                $form->prepare();

                $form->setAttribute('action', $this->url('photo/search'));
                $form->setAttribute('method', 'post');
                $form->setAttribute('role', 'form');
                ?>
                <?= $this->form()->openTag($form) ?>

                <div class="form-group">
                    <?php
                    $element = $form->get('query');
                    $element->setAttribute('class', 'form-control');
                    $element->setAttribute('placeholder', $this->translate('Search query'));
                    ?>
                    <?= $this->formLabel($element) ?>
                    <?= $this->formText($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>

                <?php
                $submit = $form->get('submit');
                $submit->setLabel($this->translate('Search'));
                $submit->setAttribute('class', 'btn btn-primary');
                ?>
                <?= $this->formButton($submit) ?>

                <?= $this->form()->closeTag() ?>
            </div>
        </div>
        <?php if (isset($result)): ?>
            <div class="row">
                <?php if (empty($result)): ?>
                    <div class="col-md-12">
                        <p><?= $this->translate('No albums were found.') ?></p>
                        <ul>
                            <li><?= $this->translate('Check the spelling of your search term') ?></li>
                            <li><?= $this->translate('Try alternate words or selections') ?></li>
                            <li><?= $this->translate('Try using a more generic search term') ?></li>
                            <li><?= $this->translate('Try entering fewer keywords') ?></li>
                        </ul>
                    </div>
                <?php else: ?>
                    <?php foreach ($result as $year => $albums): ?>
                        <div class="col-md-12">
                            <h3>
                                <?= sprintf('%d/%d', $year, $year + 1)?>
                            </h3>
                            <?= $this->partial('partial/albums', ['albums' => $albums, 'prompt' => $prompt]) ?>
                            <hr>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</section>
