<?php if ($photo != null): ?>
<div clas="row">
<nav>
  <ul class="pager">
    <li class="previous"><a href="/photo/album/<?= $photo->getAlbum()->getId(); ?>"><span aria-hidden="true">&larr;</span> Return to album</a></li>
  </ul>
</nav>
</div>
    <div class="row">
        <div class="col-lg-9">
            <img class="img-responsive" src="<?= $basedir . '/' . $photo->getPath() ?>" alt="">
        </div>
        <div class="col-lg-3">
            <table class="table table-condensed">
                <tdoby>
                    <tr><td>Artist</td><td>NAME</td></tr>
                    <tr><td>Camera</td><td>NIKON D40</td></tr>
                    <tr><td>Date/time</td><td>10-12-2014 22:03:01</td></tr>
                    <tr><td>Flash</td><td>Yes</td></tr>
                    <tr><td>Focal length</td><td>22.0mm</td></tr>
                    <tr><td>Exposure time</td><td>0.0167s</td></tr>
                    <tr><td>Shutter speed</td><td>1/60s</td></tr>
                    <tr><td>Aperture</td><td>f/2.8</td></tr>
                    <tr><td>ISO</td><td>400</td></tr>
                    </tbody>
            </table>

            <nav>
                <ul class="pager">
                    <?php if (!is_null($previous)): ?>
                        <li><a href="/photo/view/<?= $previous->getId(); ?>">Previous</a></li>
                    <?php endif;
                    if (!is_null($next)): ?>
                        <li><a href="/photo/view/<?= $next->getId(); ?>">Next</a></li>
    <?php endif; ?>
                </ul>
            </nav>
        </div>
    </div>
<?php endif; ?>