<h1><?= $this->translate('Picture of the week') ?></h1>
<h4><?= $this->translate('Current picture of the week') ?></h4>
<hr>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <a href="<?= $this->url('photo/photo', array('photo_id' => $weeklyPhotos[0]->getPhoto()->getId())); ?>">
            <img class="img-responsive" src="<?= $this->fileUrl($weeklyPhotos[0]->getPhoto()->getLargeThumbPath()) ?>" alt=""/>
        </a>
    </div>
</div>

<h4><?= $this->translate('Old pictures of the week') ?></h4>
<hr>
<div class="row photos">
    <?php foreach ($weeklyPhotos as $weeklyPhoto): ?>
            <div class="thumb">
                <a class="thumbnail" href="<?= $this->url('photo/photo', array('photo_id' => $weeklyPhoto->getPhoto()->getId())); ?>">
                    <img class="img-responsive" src="<?= $this->fileUrl($weeklyPhoto->getPhoto()->getSmallThumbPath()) ?>" alt="">
                    <div class="caption">
                        <?= $this->translate('Week') ?> <?= $weeklyPhoto->getWeek()->format('W'); ?>
                    </div>
                </a>
            </div>
    <?php endforeach; ?>
</div>