<div class="row photos">
    <?php foreach ($weeklyPhotos as $weeklyPhoto): ?>
            <div class="thumb">
                <a class="thumbnail" href="<?= $this->url('photo/photo', array('photo_id' => $weeklyPhoto->getPhoto()->getId())); ?>">
                    <img class="img-responsive" src="<?= $this->photoUrl($weeklyPhoto->getPhoto()->getSmallThumbPath()) ?>" alt="">
                    <div class="caption">
                        <?= $this->translate('Week') ?> <?= $weeklyPhoto->getWeek()->format('W'); ?>
                    </div>
                </a>
            </div>

    <?php endforeach; ?>
</div>