<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var OrganModel[] $organs
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Organs'));
?>
<div id="container">
    <?= $this->translate('Select an organ to edit its information. Changes will not be displayed until they have been approved.') ?>
    <hr>
    <table class="table table-hover">
        <thead>
        <tr>
            <th><?= $this->translate('Abbreviation') ?></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Approval Status') ?></th>
            <th><?= $this->translate('Actions') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($organs as $organ): ?>
            <?php $url = $this->url('home/organ', ['abbr' => $organ->getAbbr(), 'type' => $organ->getType()->value]) ?>
            <tr>
                <td><a href="<?= $url ?>"><?= $this->escapeHtml($organ->getAbbr()) ?></a></td>
                <td><a href="<?= $url ?>"><?= $this->escapeHtml($organ->getName()) ?></a></td>
                <td>
                    <?php if (null !== ($organInformation = $organ->getDisplayableOrganInformation())): ?>
                        <span class="fas <?= $organInformation->getApproval()->getIcon() ?>"></span>
                        <?php if (!$organInformation->getUpdateProposals()->isEmpty()): ?>
                            <?= $this->translate('Update Pending') ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?= $this->translate('N/A') ?>
                    <?php endif; ?>
                </td>
                <td>

                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
