<?php

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var OrganModel[] $organs
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Organs'));
?>
<div id="container">
    <?= $this->translate('Select an organ to edit its information. Changes will not be displayed until they have been approved.') ?>
    <hr>
    <table class="table table-hover">
        <thead>
        <tr>
            <th><?= $this->translate('Abbreviation') ?></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Approval status') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($organs as $organ): ?>
            <?php $url = $this->url('admin_organ/edit', ['organ_id' => $organ->getId()]) ?>
            <tr>
                <td><a href="<?= $url ?>"><?= $this->escapeHtml($organ->getAbbr()) ?></a></td>
                <td><a href="<?= $url ?>"><?= $this->escapeHtml($organ->getName()) ?></a></td>
                <td>
                    <?php
                    foreach ($organ->getOrganInformation() as $information) {
                        if (is_null($information->getApprover())) {
                            echo '<span class="fas fa-circle-question"></span>&nbsp;';
                        } else {
                            echo '<span class="fas fa-circle-check"></span>&nbsp;';
                        }
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>
