<?php if ($type === 'highlight'):
    $element = $form->get('vacancy_id') ?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formSelect($element) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$element = $form->get('startDate');
$element->setAttribute('class', 'form-control');
if (isset($edit_highlight)) {
    $element->setAttribute('disabled', 'disabled');
}
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $form->get('expirationDate');
$element->setAttribute('class', 'form-control');
if (isset($edit_highlight)) {
    $element->setAttribute('disabled', 'disabled');
}
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php if ($type === 'featured'): ?>
    <?php
    $element = $form->get('language');
    ?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formRadio($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('article');
    $element->setAttribute('style', 'width:100%; height:10em; resize:none');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formTextArea($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
<?php endif; ?>

<?php if ($type === 'banner'):
    $element = $form->get('banner') ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formFile($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
