<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool $historical
 * @var OrganModel[] $organs
 */

// set title
$this->headTitle($this->translate('Organ list'));
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-5 col-xs-12">
                <ul class="nav nav-pills">
                    <li role="presentation" class="<?= $historical ? 'active' : '' ?>">
                        <a href="<?= $this->url('organs') ?>">
                            <?= $this->translate('Active') ?>
                        </a>
                    </li>
                    <li role="presentation" class="<?= !$historical ? 'active' : '' ?>">
                        <a href="<?= $this->url('organs/history') ?>">
                            <?= $this->translate('Abrogated') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Abbreviation') ?></th>
                            <th><?= $this->translate('Name') ?></th>
                            <th><?= $this->translate('Type') ?></th>
                            <?php if ($historical): ?>
                                <th><?= $this->translate('Abrogation Date') ?></th>
                            <?php endif; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($organs as $organ): ?>
                            <?php $url = $this->url('organs/view', ['organ' => $organ->getId()]) ?>
                            <tr>
                                <td>
                                    <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                                        <?= $organ->getAbbr() ?>
                                    </a>
                                </td>
                                <td>
                                    <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                                        <?= $organ->getName() ?>
                                    </a>
                                </td>
                                <td>
                                    <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                                        <?= $organ->getType()->getName($this->plugin('translate')->getTranslator()) ?>
                                    </a>
                                </td>
                                <?php if ($historical): ?>
                                    <td>
                                        <?= $organ->getAbrogationDate()?->format('Y-m-d') ?>
                                    </td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
