<?php

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var OrganModel[] $organs
 */

// set title
$this->headTitle($this->translate('Organ list'));
?>
<section class="section">
    <div class="container">
        <table class="table table-hover">
            <thead>
            <tr>
                <th><?= $this->translate('Abbreviation') ?></th>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Type') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($organs as $organ): ?>
                <?php $url = $this->url('organ/show', ['organ' => $organ->getId()]) ?>
                <tr>
                    <td>
                        <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                            <?= $organ->getAbbr() ?>
                        </a>
                    </td>
                    <td>
                        <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                            <?= $organ->getName() ?>
                        </a>
                    </td>
                    <td>
                        <a style="display: block; height: 100%; width:100%" href="<?= $url ?>">
                            <?= $organ->getType()->getName($this->plugin('translate')->getTranslator()) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</section>
