<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Member as MemberModel;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var array<array-key, array{member: MemberModel, functions: array<array-key, string>}> $activeMembers
 * @var MemberModel[] $inactiveMembers
 * @var MemberModel[] $oldMembers
 * @var OrganModel $organ
 */

$this->headTitle($organ->getName());
?>
<section class="section">
    <div class="container">
        <div class="row">
            <h1><?= $this->escapeHtml($organ->getName()) ?> (<?= $this->escapeHtml($organ->getAbbr()) ?>)</h1>
            <div class="col-md-4">
                <h2><?= $this->translate('Active members') ?></h2>
                <ul>
                    <?php foreach ($activeMembers as $membership): ?>
                        <li>
                            <a href="<?= $this->url(
                                'member/view',
                                ['lidnr' => $membership['member']->getLidnr()],
                            ) ?>">
                                <?= $this->escapeHtml($membership['member']->getFullName()) ?>
                            </a>
                            <?php if (!empty($membership['functions'])): ?>
                                (<?= $this->escapeHtml(
                                    implode(
                                        ', ',
                                        array_map(
                                            fn (string $value): string => $this->translate($value),
                                            $membership['functions'],
                                        ),
                                    )
                                ) ?>)
                            <?php endif ?>
                        </li>
                    <?php endforeach ?>
                </ul>

                <h2><?= $this->translate('Inactive members') ?></h2>
                <ul>
                    <?php foreach ($inactiveMembers as $membership): ?>
                        <li>
                            <a href="<?= $this->url('member/view', ['lidnr' => $membership->getLidnr()]) ?>">
                                <?= $this->escapeHtml($membership->getFullName()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>

                <h2><?= $this->translate('Old members') ?></h2>
                <ul>
                    <?php foreach ($oldMembers as $member): ?>
                        <li><?= $this->escapeHtml($member->getFullName()) ?></li>
                    <?php endforeach ?>
                </ul>
            </div>

            <div class="col-md-8">
                <h2><?= $this->translate('Organ mutations') ?></h2>
                <ul>
                    <?php foreach ($organ->getOrderedSubdecisions() as $subdecision): ?>
                        <li><?= $this->escapeHtml($subdecision->getContent()) ?></li>
                    <?php endforeach ?>
                </ul>
            </div>

        </div>
    </div>
</section>
