<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Member as MemberModel;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var array<array-key, array{member: MemberModel, functions: array<array-key, string>}> $activeMembers
 * @var MemberModel[] $inactiveMembers
 * @var MemberModel[] $oldMembers
 * @var OrganModel $organ
 */

$this->headTitle($organ->getName());
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="page-header">
                <div class="btn-toolbar pull-right">
                    <a href="<?= $this->url(
                        'home/organ',
                        [
                            'abbr' => $organ->getAbbr(),
                            'type' => $organ->getType()->value,
                        ],
                    ) ?>" class="btn btn-default">
                        <span class="fas fa-share-nodes"></span> <?= $this->translate('Go to public page') ?>
                    </a>
                </div>
                <h1><?= $this->escapeHtml($organ->getName()) ?> <small>(<?= $this->escapeHtml($organ->getAbbr()) ?>)</small></h1>
            </div>
            <div class="col-md-4">
                <?php if (!empty($activeMembers)): ?>
                    <h2><?= $this->translate('Active members') ?></h2>
                    <ul class="list-unstyled">
                        <?php foreach ($activeMembers as $membership): ?>
                            <li>
                                <a href="<?= $this->url(
                                    'member/view',
                                    ['lidnr' => $membership['member']->getLidnr()],
                                ) ?>">
                                    <?= $this->escapeHtml($membership['member']->getFullName()) ?>
                                </a>
                                <?php if (!empty($membership['functions'])): ?>
                                    (<?= $this->escapeHtml(
                                        implode(
                                            ', ',
                                            array_map(
                                                fn (string $value): string => $this->translate($value),
                                                $membership['functions'],
                                            ),
                                        )
                                    ) ?>)
                                <?php endif ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif; ?>

                <?php if (!empty($inactiveMembers)): ?>
                    <h2><?= $this->translate('Inactive members') ?></h2>
                    <ul class="list-unstyled">
                        <?php foreach ($inactiveMembers as $membership): ?>
                            <li>
                                <a href="<?= $this->url('member/view', ['lidnr' => $membership->getLidnr()]) ?>">
                                    <?= $this->escapeHtml($membership->getFullName()) ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif; ?>

                <?php if (!empty($oldMembers)): ?>
                    <h2><?= $this->translate('Old members') ?></h2>
                    <ul class="list-unstyled">
                        <?php foreach ($oldMembers as $member): ?>
                            <li><?= $this->escapeHtml($member->getFullName()) ?></li>
                        <?php endforeach ?>
                    </ul>
                <?php endif; ?>
            </div>

            <div class="col-md-8">
                <h2><?= $this->translate('Organ mutations') ?></h2>
                <ul class="list-unstyled">
                    <?php foreach ($organ->getOrderedSubdecisions() as $subdecision): ?>
                        <?php
                        $id = vsprintf('%s %s.%s.%s', [
                            $subdecision->getMeetingType()->value,
                            $subdecision->getMeetingNumber(),
                            $subdecision->getDecisionPoint(),
                            $subdecision->getDecisionNumber(),
                        ]);
                        $extendedId = $id . '.' . $subdecision->getSequence();
                        ?>
                        <li id="<?= urlencode($extendedId) ?>" class="link-permalink-container">
                            <strong class="decision-meeting">
                                <a href="<?= $this->url(
                                    'decision/meeting',
                                    [
                                        'type' => $subdecision->getMeetingType()->value,
                                        'number' => $subdecision->getMeetingNumber(),
                                    ],
                                ) ?>">
                                    <?= $id ?>
                                </a>
                            </strong>
                            <span class="decision-content">
                                <?= $this->escapeHtml($subdecision->getContent()) ?>
                                <a href="#<?= urlencode($extendedId) ?>" class="link-permalink">
                                    <span class="fa fa-link"></span>
                                </a>
                            </span>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>

        </div>
    </div>
</section>
