<?php
// set title
$this->headTitle($this->translate('Members'));
$lang = $this->plugin('translate')->getTranslator()->getLocale();

$sections = [];
$sections[$this->translate('Personal')] = [
    [$this->translate('Change password'), 'lock', $this->url('user/default', ['action' => 'password'])],
];

/** @var \Decision\Model\Meeting[] $meetings */
$meetings = $this->meetings;
?>
<div class="container">
    <section class="section">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate('Members') ?></h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <h2><?= $this->translate('Personal') ?></h2>
                <div class="grid grid-col-5">
                    <a href="<?= $this->url('member/self') ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-user"></div>
                        <div class="panel-heading"><?= $this->translate('Profile') ?></div>
                    </a>
                    <a href="<?= $this->url('user/default', ['action' => 'password']) ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-lock"></div>
                        <div class="panel-heading"><?= $this->translate('Change password') ?></div>
                    </a>
                    <a href="<?= $this->url('photo/member', ['lidnr' => $member->getLidnr(), 'page' => null]) ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-picture"></div>
                        <div class="panel-heading"><?= $this->translate('My photo\'s') ?></div>
                    </a>
                    <a href="https://gewis.nl/susos/account/websitelogin.php" class="panel panel-image">
                        <div class="glyphicon glyphicon-glass"></div>
                        <div class="panel-heading"><?= $this->translate('SuSOS') ?></div>
                    </a>
                    <a href="<?= $this->url('decision/authorizations') ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon glyphicon-bullhorn"></div>
                        <div class="panel-heading"><?= $this->translate('Authorizations') ?></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <h2><?= $this->translate('Association') ?></h2>
                <div class="grid grid-col-5">
                    <a href="<?= $this->url('organ') ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-heart"></div>
                        <div class="panel-heading"><?= $this->translate('Organs') ?></div>
                    </a>
                    <a href="<?= $this->url('decision/files', ['path' => '']) ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-download-alt"></div>
                        <div class="panel-heading"><?= $this->translate('Public archive') ?></div>
                    </a>
                    <a href="<?= $this->url('member/search') ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-search"></div>
                        <div class="panel-heading"><?= $this->translate('Find a member') ?></div>
                    </a>
                    <a href="<?= $this->url('member/dreamspark') ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-cd"></div>
                        <div class="panel-heading"><?= $this->translate('Microsoft Imagine') ?></div>
                    </a>
                    <a href="<?= $this->url('home/page', ['category' => 'links']) ?>" class="panel panel-image">
                        <div class="glyphicon glyphicon-link"></div>
                        <div class="panel-heading"><?= $this->translate('Links') ?></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-6 mt-2">
                <h2><?= $this->translate('Meetings') ?></h2>
                <?php if (!is_null($this->upcoming)): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong><?= $this->translate('Upcoming meeting') ?></strong>
                        </div>
                        <div class="panel-body">
                            <?=
                                sprintf(
                                    $this->translate('The next meeting is %s%s %s%s on %s.'),
                                    '<a href="' . $this->url('decision/meeting', [ 'type' => $this->upcoming->getType(), 'number' => $this->upcoming->getNumber() ]) . '">',
                                    $this->upcoming->getType(),
                                    $this->upcoming->getNumber(),
                                    '</a>',
                                    $this->dateFormat($this->upcoming->getDate()->getTimestamp(), IntlDateFormatter::FULL, IntlDateFormatter::NONE, $lang)
                                )
                            ?>
                        </div>
                    </div>
                    <p>
                        <?=
                            sprintf(
                                $this->translate('If you aren\'t able to attend the meeting in person but you want your voice to be heard, consider %sauthorizing another member%s to act on your behalf.'),
                                '<a href="' . $this->url('decision/authorizations') . '">',
                                '</a>'
                            )
                        ?>
                    </p>
                    <hr />
                <?php endif; ?>
                <p><?= $this->translate('Search through the list of decisions accumulated from past meetings:') ?></p>
                <form method="post" action="<?= $this->url('decision/search') ?>" class="form-inline">
                    <input type="text" name="query" class="form-control" placeholder="<?= $this->translate('Search by keyword or meeting number') ?>" />
                    <button type="submit" class="btn btn-default">
                        <?= $this->translate('Search') ?>
                    </button>
                </form>
                <hr />
                <?php foreach($meetingsCollection as $type => $meetings): ?>
                    <p><?= sprintf($this->translate('The latest %s meetings that took place:'), $type) ?></p>
                    <ul>
                        <?php foreach($meetings as $meeting): ?>
                            <li>
                                <a href="<?= $this->url('decision/meeting', [ 'type' => $meeting->getType(), 'number' => $meeting->getNumber() ]) ?>">
                                    <?=
                                        sprintf(
                                            $this->translate('%s %s on %s'),
                                            $meeting->getType(),
                                            $meeting->getNumber(),
                                            $this->dateFormat($meeting->getDate()->getTimestamp(), IntlDateFormatter::FULL, IntlDateFormatter::NONE, $lang)
                                        )
                                    ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endforeach; ?>
                <a href="<?= $this->url('decision') ?>">
                    <?= $this->translate('View all meetings') ?>
                </a>
            </div>
            <?php if ($isActive): ?>
                <div class="col-md-6 mt-2">
                    <h2><?= $this->translate('Manage') ?></h2>
                    <p><?= $this->translate('A list of helpful pages to manage the organ(s) you are part of.') ?></p>
                    <div class="grid grid-col-3">
                        <a href="<?= $this->url('admin_organ') ?>" class="panel panel-image">
                            <div class="glyphicon glyphicon-align-left"></div>
                            <div class="panel-heading"><?= $this->translate('Info') ?></div>
                        </a>
                        <a href="<?= $this->url('activity_admin') ?>" class="panel panel-image">
                            <div class="glyphicon glyphicon-tree-deciduous"></div>
                            <div class="panel-heading"><?= $this->translate('Activities') ?></div>
                        </a>
                        <a href="<?= $this->url('activity_calendar') ?>" class="panel panel-image">
                            <div class="glyphicon glyphicon-calendar"></div>
                            <div class="panel-heading"><?= $this->translate('Option calendar') ?></div>
                        </a>
                        <a href="/webmail" class="panel panel-image">
                            <div class="glyphicon glyphicon-inbox"></div>
                            <div class="panel-heading"><?= $this->translate('Webmail') ?></div>
                        </a>
                        <a href="<?= $this->url('admin') ?>" class="panel panel-image">
                            <div class="glyphicon glyphicon-cog"></div>
                            <div class="panel-heading"><?= $this->translate('Administrator') ?></div>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <h2><?= $this->translate('Regulations') ?></h2>
                <ul>
                    <li>
                        <a href="<?= $this->url('member/regulations', ['regulation' => 'borrel-reglement']) ?>">
                            <?= $this->translate('Borrelreglement') ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url('member/regulations', ['regulation' => 'computer-reglement']) ?>">
                            <?= $this->translate('Computerreglement') ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url('member/regulations', ['regulation' => 'poster-reglement']) ?>">
                            <?= $this->translate('Posterreglement') ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url('member/regulations', ['regulation' => 'sleutel-beleid']) ?>">
                            <?= $this->translate('Sleutelbeleid') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>
</div>

