<?php
// set title
$this->headTitle($this->translate('Members')); ?>

<?php

$sections = [];
$sections[$this->translate('Personal')] = [
    [$this->translate('Profile'), 'user', $this->url('member/self')],
    [$this->translate('Change password'), 'lock', $this->url('user/default', ['action' => 'password'])],
    [$this->translate('SuSOS'), 'glass', 'https://gewis.nl/susos/account/websitelogin.php'],
    [$this->translate('Find a member'), 'search', $this->url('member/search')],
    [$this->translate('Microsoft Imagine'), 'cd', $this->url('member/dreamspark')],
];

$sections[$this->translate('Meetings')] = [
    [$this->translate('Meetings'), 'folder-open', $this->url('decision')],
    [$this->translate('Decision Search'), 'search', $this->url('decision/search')],
    [$this->translate('Authorizations'), 'pencil', $this->url('decision/authorizations')],
    [$this->translate('Organs'), 'heart', $this->url('organ')],
];

if ($this->acl('decision_acl')->isAllowed('organ', 'edit')) {
    $sections[$this->translate('Active members')] = [
        [$this->translate('Option calendar'), 'calendar', $this->url('activity_calendar')],
        [$this->translate('Webmail'), 'inbox', '/webmail'],
        [$this->translate('Website admin'), 'cog', $this->url('admin')],
    ];

    $sections[$this->translate('Regulations')] = [
        [$this->translate('Borrelreglement'), 'glass', $this->url('member/regulations', ['regulation' => 'borrel-reglement'])],
        [$this->translate('Computerreglement'), 'hdd', $this->url('member/regulations', ['regulation' => 'computer-reglement'])],
        [$this->translate('Posterreglement'), 'file', $this->url('member/regulations', ['regulation' => 'poster-reglement'])],
        [$this->translate('Sleutelbeleid'), 'lock', $this->url('member/regulations', ['regulation' => 'sleutel-beleid'])],
    ];
}

?>

<section class="section">
    <div class="container">
        <h1><?= $this->translate('Members') ?></h1>

        <?php foreach ($sections as $heading => $items): ?>
            <h2><?= $heading ?></h2>
            <div class="row">
                <?php foreach ($items as $item): ?>
                    <div class="col-sm-3 col-xs-6">
                        <a href="<?= $item[2] ?>" class="panel panel-image">
                            <div class="panel-body">
                                <div class="glyphicon glyphicon-<?= $item[1] ?>"></div>
                                <h4><?= $item[0] ?></h4>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
</section>
