<?php
// set title
$this->headTitle($this->translate('Members')); ?>

<div class="container">
    <h1><?= $this->translate('Members') ?></h1>

    <h3 class="h-underline"><?= $this->translate('My info') ?></h3>
    <div class="row">
        <a href="<?= $this->url('member/self') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-user"></div>
                <h4><?= $this->translate('Profile') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('user/default', ['action' => 'password']) ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-lock"></div>
                <h4><?= $this->translate('Change password') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('member/birthdays') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-gift"></div>
                <h4><?= $this->translate('Birthdays') ?></h4>
            </div>
        </a>
        <a href="https://gewis.nl/susos/account/websitelogin.php" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-glass"></div>
                <h4><?= $this->translate('SuSOS') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('member/search') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-search"></div>
                <h4><?= $this->translate('Find a member') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('member/dreamspark') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-cd"></div>
                <h4><?= $this->translate('Microsoft Imagine') ?></h4>
            </div>
        </a>
        
    </div>
    
    <h3 class="h-underline"><?= $this->translate('Meetings') ?></h3>
    <div class="row">
        <a href="<?= $this->url('decision') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-folder-open"></div>
                <h4><?= $this->translate('Meetings') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('decision/search') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-search"></div>
                <h4><?= $this->translate('Decision Search') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('decision/authorizations') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-pencil"></div>
                <h4><?= $this->translate('Authorizations') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('organ') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-heart"></div>
                <h4><?= $this->translate('Organs') ?></h4>
            </div>
        </a>
    </div>
    
    <h3 class="h-underline"><?= $this->translate('Active members') ?></h3>
    <div class="row">
        <a href="<?= $this->url('activity_calendar') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-calendar"></div>
                <h4><?= $this->translate('Option calendar') ?></h4>
            </div>
        </a>
        <a href="<?= $this->url('admin') ?>" class="panel panel-image col-sm-3 col-xs-6">
            <div class="panel-body">
                <div class="glyphicon glyphicon-cog"></div>
                <h4><?= $this->translate('Website admin') ?></h4>
            </div>
        </a>
    </div>
</div>
