<?php
use Decision\Model\Member;
use Decision\Model\Address;

$this->headTitle($member->getFullName());
?>
<?php $this->headScript()->prependFile($this->basePath() . '/js/photo.js')
    ->prependFile($this->basePath() . '/js/masonry.pkgd.min.js')
    ->prependFile($this->basePath() . '/js/imagesloaded.pkgd.min.js');
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1><?= $member->getFullName() ?></h1>
                <table class="table table-bordered">
                    <tr>
                        <th><?= $this->translate('Membership number') ?></th>
                        <td><?= $member->getLidnr() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Initials') ?></th>
                        <td><?= $member->getInitials() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('First name') ?></th>
                        <td><?= $member->getFirstName() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Middle name') ?></th>
                        <td><?= $member->getMiddleName() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Last name') ?></th>
                        <td><?= $member->getLastName() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Gender') ?></th>
                        <td><?php
                            switch ($member->getGender()) {
                                case Member::GENDER_MALE:
                                    echo $this->translate('Male');
                                    break;
                                case Member::GENDER_FEMALE:
                                    echo $this->translate('Female');
                                    break;
                                case Member::GENDER_OTHER:
                                    echo $this->translate('Other');
                                    break;
                            }
                            ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Email') ?></th>
                        <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Birth date') ?></th>
                        <td><?= $member->getBirth()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Generation') ?></th>
                        <td><?= $member->getGeneration() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Membership type') ?></th>
                        <td><?php
                            switch ($member->getType()) {
                                case Member::TYPE_ORDINARY:
                                    echo $this->translate('Ordinary');
                                    break;
                                case Member::TYPE_PROLONGED:
                                    echo $this->translate('Prolonged');
                                    break;
                                case Member::TYPE_EXTERNAL:
                                    echo $this->translate('External');
                                    break;
                                case Member::TYPE_EXTRAORDINARY:
                                    echo $this->translate('Extraordinary');
                                    break;
                                case Member::TYPE_HONORARY:
                                    echo $this->translate('Honorary');
                                    break;
                            }
                            ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Last membership change') ?></th>
                        <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('End date of membership') ?></th>
                        <td><?= $member->getExpiration()->format('l j F Y') ?></td>
                    </tr>
                </table>

                <p>
                    <?=
                    $this->translate('If your information is no longer up to date and you would like to change it, you can contact the secretary of GEWIS.') . ' ',
                    $this->translate('Also for data removal requests, you can contact') . ' ',
                    '<a href="mailto:secretary@gewis.nl" title="' . $this->translate('Email the secretary of GEWIS') . '">' . $this->translate('the secretary of GEWIS') . '</a>'
                    ?>
                </p>

                <h3><?= $this->translate('Membership of committees and fraternities') ?></h3>
                <ul>
                    <?php foreach ($memberships as $abbr => $install): ?>
                        <li><a href="<?= $this->url('home/organ', ['type' => $install['organ']->getType(), 'abbr' =>
                                $abbr ]) ?>"><?= $abbr ?></a>
                            <?php $functions = $install['functions']; ?>
                            <?php if (!empty($functions)): ?> (<?= $functions ?>)
                            <?php endif ?></li>
                    <?php endforeach; ?>
                </ul>
                <h3><?= $this->translate('Adresses') ?></h3>
                <?php foreach ($member->getAddresses() as $address): ?>
                    <h4><?php
                        switch ($address->getType()) {
                            case Address::TYPE_HOME:
                                echo $this->translate('Home address (parents)');
                                break;
                            case Address::TYPE_STUDENT:
                                echo $this->translate('Student address');
                                break;
                            case Address::TYPE_MAIL:
                                echo $this->translate('Mail address');
                                break;
                        }
                        ?></h4>
                    <table class="table table-bordered">
                        <tr>
                            <th><?= $this->translate('Country') ?></th>
                            <td><?= $address->getCountry() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Street and number') ?></th>
                            <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('City and postal code') ?></th>
                            <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Phone number') ?></th>
                            <td><?= $address->getPhone() ?></td>
                        </tr>
                    </table>
                <?php endforeach ?>
            </div>
            <div class="col-md-6">
                <?php if ($profilePhoto != null): ?>
                    <div class="row">
                            <div class="col-sm-12 col-xs-12">
                              <a class="thumbnail" href="<?= $this->url('photo/photo', ['photo_id' => $profilePhoto->getId()]); ?>">
                                  <img class="img-responsive" src="<?= $this->fileUrl($profilePhoto->getLargeThumbPath()) ?>" alt="">
                              </a>
                            </div>
                    </div>
                    <?php if ($isExplicitProfilePhoto): ?>
                        <a type="button" class="btn btn-danger" href=<?= $this->url('photo/remove_profile_photo'); ?>>
                            <?= $this->translate('Remove this picture as your profile picture') ?>
                        </a>
                        <p><?= $this->translate('Your profile picture will be chosen automatically instead.') ?></p>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="row">
                    <div class="col-sm-6 col-xs-6">
                        <a href="<?= $this->url('photo/member', ['lidnr' => $member->getLidnr(), 'page' => null]) ?>" class="panel panel-image">
                            <div class="panel-body">
                                <div class="glyphicon glyphicon-picture"></div>
                                <h4><?= $this->translate("More of my photo's"); ?></h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $(document).ready(function () {
        Photo.initGrid();
    });
</script>
