<?php

use Decision\Model\Member;
use Laminas\I18n\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
/** @var Member $member */

$this->headTitle($this->translate('My Information'));
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1><?= $this->escapeHtml($member->getFullName()) ?></h1>
                <table class="table table-bordered">
                    <tr>
                        <th><?= $this->translate('Membership number') ?></th>
                        <td><?= $member->getLidnr() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Initials') ?></th>
                        <td><?= $this->escapeHtml($member->getInitials()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('First name') ?></th>
                        <td><?= $this->escapeHtml($member->getFirstName()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Middle name') ?></th>
                        <td><?= $this->escapeHtml($member->getMiddleName()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Last name') ?></th>
                        <td><?= $this->escapeHtml($member->getLastName()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Email') ?></th>
                        <td>
                            <?php if (null !== ($email = $member->getEmail())): ?>
                                <?php $email = $this->escapeHtml($email); ?>
                                <a href="mailto:<?= $email ?>"><?= $email ?></a>
                            <?php else: ?>
                                <?= $this->translate('Unknown') ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Birth date') ?></th>
                        <td><?= $member->getBirth()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Generation') ?></th>
                        <td><?= $member->getGeneration() ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Membership type') ?></th>
                        <td><?= $member->getType()->getName($this->plugin('translate')->getTranslator()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Last membership change') ?></th>
                        <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('End date of membership') ?></th>
                        <td><?= $member->getExpiration()->format('l j F Y') ?></td>
                    </tr>
                </table>

                <p>
                    <?=
                    $this->translate('If your information is no longer up to date and you would like to change it, you can contact the secretary of GEWIS.') . ' ',
                        $this->translate('Also for data removal requests, you can contact') . ' ',
                        '<a href="mailto:secretary@gewis.nl" title="' . $this->translate('Email the secretary of GEWIS') . '">' . $this->translate('the secretary of GEWIS') . '</a>'
                    ?>
                </p>

                <h3><?= $this->translate('Memberships of committees and fraternities') ?></h3>
                <?php if (
                    empty($memberships['current'])
                    && empty($memberships['historical'])
                ): ?>
                    <p><?= $this->translate('You have not been a member of a committee or fraternity.') ?></p>
                <?php endif; ?>
                <?php if (!empty($memberships['current'])): ?>
                    <p><?= $this->translate('You are currently a member of:') ?></p>
                    <ul>
                        <?php foreach ($memberships['current'] as $abbr => $install): ?>
                            <li>
                                <a href="<?= $this->url(
                                    'home/organ',
                                    [
                                        'type' => $install['organ']->getType()->value,
                                        'abbr' => $abbr,
                                    ],
                                ) ?>">
                                    <?= $this->escapeHtml($abbr) ?>
                                </a>
                                <?php if (!empty($install['functions'])): ?>
                                    (<?= $this->escapeHtml(implode(', ', $install['functions'])) ?>)
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php if (!empty($memberships['historical'])): ?>
                    <p><?= $this->translate('You were a member of:') ?></p>
                    <ul>
                        <?php foreach ($memberships['historical'] as $abbr => $install): ?>
                            <li>
                                <a href="<?= $this->url(
                                    'home/organ',
                                    [
                                        'type' => $install['organ']->getType()->value,
                                        'abbr' => $abbr,
                                    ],
                                ) ?>">
                                    <?= $this->escapeHtml($abbr) ?>
                                </a>
                                <?php if (!empty($install['functions'])): ?>
                                    (<?= $this->escapeHtml(implode(', ', $install['functions'])) ?>)
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>

                <h3><?= $this->translate('Addresses') ?></h3>
                <?php foreach ($member->getAddresses() as $address): ?>
                    <h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
                    <table class="table table-bordered">
                        <tr>
                            <th><?= $this->translate('Country') ?></th>
                            <td><?= $address->getCountry() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Street and number') ?></th>
                            <td>
                                <?= sprintf(
                                    $this->translate('%s %s'),
                                    $this->escapeHtml($address->getStreet()),
                                    $this->escapeHtml($address->getNumber()),
                                ) ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('City and postal code') ?></th>
                            <td>
                                <?= sprintf(
                                    $this->translate('%s %s'),
                                    $this->escapeHtml($address->getPostalCode()),
                                    $this->escapeHtml($address->getCity()),
                                ) ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Phone number') ?></th>
                            <td><?= $this->escapeHtml($address->getPhone()) ?></td>
                        </tr>
                    </table>
                <?php endforeach ?>

                <h3><?= $this->translate('External applications') ?></h3>
                <table class="table table-bordered">
                    <tr>
                        <th><?= $this->translate('App') ?></th>
                        <th><?= $this->translate('First authentication') ?></th>
                        <th><?= $this->translate('Last authentication') ?></th>
                    </tr>
                    <?php foreach ($apps as $app): ?>
                        <tr>
                            <td>
                                <a href="<?= $app[0]->getUrl() ?>" target="_blank">
                                    <?= $this->escapeHtml($app[0]->getAppId()) ?>
                                </a>
                            </td>
                            <td><?= $this->dateFormat(new DateTime($app['firstAuthentication']), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?></td>
                            <td><?= $this->dateFormat(new DateTime($app['lastAuthentication']), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <div class="col-md-6">
                <?php if ($profilePhoto != null): ?>
                    <div class="row">
                        <div class="col-sm-12 col-xs-12">
                            <a class="thumbnail"
                               href="<?= $this->url(
                                   'photo/album',
                                   [
                                       'album_id' => $member->getLidnr(),
                                       'album_type' => 'member',
                                       'photo_id' => $profilePhoto->getId(),
                                   ],
                               ) ?>">
                                <?php
                                $pAspectRatio = $profilePhoto->getAspectRatio();

                                $pLargeWidth = $photoConfig['large_thumb_size']['width'];
                                $pLargeSize = [
                                    'w' => $pLargeWidth,
                                    'h' => round($pLargeWidth * $pAspectRatio)
                                ];
                                ?>
                                <img class="img-responsive"
                                     src="<?= $this->glideUrl()->getUrl($profilePhoto->getPath(), $pLargeSize) ?>"
                                     alt="">
                            </a>
                        </div>
                    </div>
                    <?php if ($isExplicitProfilePhoto): ?>
                        <a type="button" class="btn btn-danger" href=<?= $this->url('photo/remove_profile_photo'); ?>>
                            <?= $this->translate('Remove this picture as your profile picture') ?>
                        </a>
                        <p><?= $this->translate('Your profile picture will be chosen automatically instead.') ?></p>
                    <?php endif; ?>
                <?php endif; ?>
                <div class="row">
                    <div class="col-sm-6 col-xs-6">
                        <a class="panel panel-image"
                           href="<?= $this->url(
                            'photo/album',
                            [
                                'album_id' => $member->getLidnr(),
                                'album_type' => 'member',
                            ],
                        ) ?>">
                            <div class="panel-body">
                                <div class="far fa-image big-icon"></div>
                                <h4><?= $this->translate("More of my photo's"); ?></h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
