<?php

declare(strict_types=1);

use Decision\Model\{
    AssociationYear,
    BoardMember,
    Member,
};
use Laminas\I18n\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\ProfilePhoto as ProfilePhotoModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var Member $member
 * @var array $photoConfig
 * @var ProfilePhotoModel|null $profilePhoto
 */

// set title
$this->headTitle($this->escapeHtml($member->getFullName()));
$this->headTitle($this->translate('Members'));
?>
<section class="section">
    <div class="container">
        <h1><?= $this->escapeHtml($member->getFullName()) ?></h1>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                        <tr>
                            <th><?= $this->translate('Email') ?></th>
                            <td>
                                <?php if (null !== ($email = $member->getEmail())): ?>
                                    <?php $email = $this->escapeHtml($email); ?>
                                    <a href="mailto:<?= $email ?>"><?= $email ?></a>
                                <?php else: ?>
                                    <?= $this->translate('Unknown') ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <th><?= $this->translate('Birth date') ?></th>
                        <td><?= $member->getBirth()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Generation') ?></th>
                        <td><?= $member->getGeneration() ?></td>
                    </tr>
                    <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                        <tr>
                            <th><?= $this->translate('Membership type') ?></th>
                            <td><?= $member->getType()->getName($this->plugin('translate')->getTranslator()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Has key code?') ?></th>
                            <td><?= $member->isKeyholder() ? $this->translate('Yes') : $this->translate('No') ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
                <?php
                /* @var BoardMember[] $boardInstalls */
                $boardInstalls = $member->getBoardInstallations()->toArray();

                // Ensure proper sorting of board installations; most recent installations first but keep original
                // ordering when comparing within meetings.
                usort($boardInstalls, static function(BoardMember $a, BoardMember $b) {
                    $aInstallationDec = $a->getInstallationDec();
                    $bInstallationDec = $b->getInstallationDec();

                    // While using the spaceship comparator (`<=>`) would have been fancy, we would still have needed an
                    // if statement to check against the outcome of that comparison not being zero. So we simply do it
                    // the "old-school" way.

                    // Compare the meeting numbers.
                    if ($aInstallationDec->getMeetingNumber() !== $bInstallationDec->getMeetingNumber()) {
                        return $aInstallationDec->getMeetingNumber() < $bInstallationDec->getMeetingNumber() ? 1 : -1;
                    }

                    // If the meeting numbers are the same, compare the decision points and numbers.
                    if ($aInstallationDec->getDecisionPoint() !== $bInstallationDec->getDecisionPoint()) {
                        return $aInstallationDec->getDecisionPoint() < $bInstallationDec->getDecisionPoint() ? -1 : 1;
                    }

                    if ($aInstallationDec->getDecisionNumber() !== $bInstallationDec->getDecisionNumber()) {
                        return $aInstallationDec->getDecisionNumber() < $bInstallationDec->getDecisionNumber() ? -1 : 1;
                    }

                    // If all the above are the same, compare the sequence numbers.
                    return $aInstallationDec->getSequence() < $bInstallationDec->getSequence() ? -1 : 1;
                });

                if (!empty($boardInstalls)):
                    $now = new DateTime('now');
                    $associationYear = AssociationYear::fromDate($now);
                    $start = $associationYear->getStartDate();
                    $end = $associationYear->getEndDate();
                ?>
                    <h3><?= $this->translate('Board') ?></h3>
                    <ul class="list-unstyled">
                        <?php foreach ($boardInstalls as $boardInstall): ?>
                            <?php $installDate = clone $boardInstall->getInstallDate(); ?>
                            <?php if ($now < $installDate): ?>
                                <li>
                                    <?= sprintf(
                                        $this->translate('%s is the upcoming <strong>%s</strong>.'),
                                        $this->escapeHtml($member->getFirstName()),
                                        $this->escapeHtml($this->translate($boardInstall->getFunction())),
                                    )?>
                                </li>
                            <?php elseif (
                                $start <= $installDate
                                && $now <= $end
                                && (
                                    null === $boardInstall->getReleaseDate()
                                    || null === $boardInstall->getDischargeDate()
                                )
                            ):
                            ?>
                                <li>
                                    <?= sprintf(
                                        $this->translate('%s is currently the <strong>%s</strong>.'),
                                        $this->escapeHtml($member->getFirstName()),
                                        $this->escapeHtml($this->translate($boardInstall->getFunction())),
                                    ) ?>
                                </li>
                            <?php else: ?>
                                <?php $startAssociationYear = AssociationYear::fromDate($installDate)->getYear(); ?>
                                <li>
                                    <?= sprintf(
                                        // phpcs:ignore Generic.Files.LineLength.TooLong -- user-visible strings should not be split
                                        $this->translate('%s was the <strong>%s</strong> during the association year %d/%d.'),
                                        $this->escapeHtml($member->getFirstName()),
                                        $this->escapeHtml($this->translate($boardInstall->getFunction())),
                                        $startAssociationYear,
                                        $startAssociationYear + 1,
                                    ) ?>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                <br>
                <?php endif; ?>
                <h3><?= $this->translate('Memberships of committees and fraternities') ?></h3>
                <?php if (
                    empty($memberships['current'])
                    && empty($memberships['historical'])
                ): ?>
                    <p>
                        <?= sprintf(
                            $this->translate('%s has never been part of a committee or fraternity.'),
                            $this->escapeHtml($member->getFirstName()),
                        ) ?>
                    </p>
                <?php endif; ?>
                <?php if (!empty($memberships['current'])): ?>
                    <p>
                        <?= sprintf(
                            $this->translate('%s is currently a member of:'),
                            $this->escapeHtml($member->getFirstName()),
                        ) ?>
                    </p>
                    <ul>
                        <?php foreach ($memberships['current'] as $install): ?>
                            <?php
                            $abbr = $install['organ']->getAbbr();
                            ?>
                            <li>
                                <a href="<?= $this->url(
                                    'home/organ',
                                    [
                                        'type' => $install['organ']->getType()->value,
                                        'abbr' => $abbr,
                                    ],
                                ) ?>">
                                    <?= $this->escapeHtml($abbr) ?>
                                </a>
                                <?php if (!empty($install['functions'])): ?>
                                    (<?= $this->escapeHtml(implode(', ', $install['functions'])) ?>)
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php if (!empty($memberships['historical'])): ?>
                    <p>
                        <?= sprintf(
                            $this->translate('%s was a member of:'),
                            $this->escapeHtml($member->getFirstName()),
                        ) ?>
                    </p>
                    <ul>
                        <?php foreach ($memberships['historical'] as $install): ?>
                            <?php
                            $abbr = $install['organ']->getAbbr();
                            ?>
                            <li>
                                <a href="<?= $this->url(
                                    'home/organ',
                                    [
                                        'type' => $install['organ']->getType()->value,
                                        'abbr' => $abbr,
                                    ],
                                ) ?>">
                                    <?= $this->escapeHtml($abbr) ?>
                                </a>
                                <?php if (!empty($install['functions'])): ?>
                                    (<?= $this->escapeHtml(implode(', ', $install['functions'])) ?>)
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                    <h3><?= $this->translate('Addresses') ?></h3>
                    <?php foreach ($member->getAddresses() as $address): ?>
                        <h4><<?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
                        <table class="table table-bordered">
                            <tr>
                                <th><?= $this->translate('Country') ?></th>
                                <td><?= $address->getCountry() ?></td>
                            </tr>
                            <tr>
                                <th><?= $this->translate('Street and number') ?></th>
                                <td>
                                    <?= sprintf(
                                        $this->translate('%s %s'),
                                        $this->escapeHtml($address->getStreet()),
                                        $this->escapeHtml($address->getNumber()),
                                    ) ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $this->translate('City and postal code') ?></th>
                                <td>
                                    <?= sprintf(
                                        $this->translate('%s %s'),
                                        $this->escapeHtml($address->getPostalCode()),
                                        $this->escapeHtml($address->getCity()),
                                    ) ?>
                                </td>
                            </tr>
                        </table>
                    <?php endforeach ?>
                <?php endif; ?>
            </div>
            <div class="col-md-6">
                <?php if (null !== $profilePhoto): ?>
                    <div class="row">
                        <div class="col-sm-12 col-xs-12">
                            <a class="thumbnail"
                               href="<?= $this->url(
                                   'photo/album',
                                   [
                                       'album_id' => $member->getLidnr(),
                                       'album_type' => 'member',
                                       'photo_id' => $profilePhoto->getId(),
                                   ],
                               ) ?>">
                                <?php
                                $pAspectRatio = $profilePhoto->getAspectRatio();

                                $pLargeWidth = $photoConfig['large_thumb_size']['width'];
                                $pLargeSize = [
                                    'w' => $pLargeWidth,
                                    'h' => round($pLargeWidth * $pAspectRatio)
                                ];
                                ?>
                                <img class="img-responsive"
                                     src="<?= $this->glideUrl()->getUrl($profilePhoto->getPath(), $pLargeSize) ?>"
                                     alt="">
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="row">
                    <div class="col-sm-6 col-xs-6">
                        <a class="panel panel-image"
                           href="<?= $this->url('photo/album',
                            [
                                'album_id' => $member->getLidnr(),
                                'album_type' => 'member',
                            ],
                        ) ?>">
                            <div class="panel-body">
                                <div class="far fa-image big-icon"></div>
                                <h4>
                                    <?= sprintf(
                                        $this->translate("Photo's of %s"),
                                        $this->escapeHtml($member->getFirstName()),
                                    ) ?>
                                </h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
