<?php

use Decision\Model\Member;
use Decision\Model\Address;

// set title
$this->headTitle($member->getFullName());
$this->headTitle($this->translate('Members'));
?>
<section class="section">
    <div class="container">
        <h1><?= $member->getFullName() ?></h1>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <tr>
                        <th><?= $this->translate('Gender') ?></th>
                        <td><?php
                            switch ($member->getGender()) {
                                case Member::GENDER_MALE:
                                    echo $this->translate('Male');
                                    break;
                                case Member::GENDER_FEMALE:
                                    echo $this->translate('Female');
                                    break;
                                case Member::GENDER_OTHER:
                                    echo $this->translate('Other');
                                    break;
                            }
                            ?></td>
                    </tr>
                    <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                        <tr>
                            <th><?= $this->translate('Email') ?></th>
                            <td>
                                <?php if (null !== ($email = $member->getEmail())): ?>
                                    <?php $email = $this->escapeHtml($email); ?>
                                    <a href="mailto:<?= $email ?>"><?= $email ?></a>
                                <?php else: ?>
                                    <?= $this->translate('Unknown') ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <tr>
                        <th><?= $this->translate('Birth date') ?></th>
                        <td><?= $member->getBirth()->format('l j F Y') ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Generation') ?></th>
                        <td><?= $member->getGeneration() ?></td>
                    </tr>
                    <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                        <tr>
                            <th><?= $this->translate('Membership type') ?></th>
                            <td><?= $member->getType()->getName($this->plugin('translate')->getTranslator()) ?></td>
                        </tr>
                    <?php endif; ?>
                </table>
                <h3><?= $this->translate('Membership of committees and fraternities') ?></h3>
                <ul>
                    <?php foreach ($memberships as $abbr => $install): ?>
                        <li><a
                                href="<?= $this->url('home/organ', ['type' => $install['organ']->getType(), 'abbr' =>
                                    $abbr]) ?>"
                            ><?= $abbr ?></a>
                            <?php if (isset($install['functions'])): ?>
                                (<?= $install['functions'] ?>)
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php if ($this->acl('decision_service_acl')->isAllowed('member', 'view_full')): ?>
                    <h3><?= $this->translate('Adresses') ?></h3>
                    <?php foreach ($member->getAddresses() as $address): ?>
                        <h4><?php
                            switch ($address->getType()) {
                                case Address::TYPE_HOME:
                                    echo $this->translate('Home address (parents)');
                                    break;
                                case Address::TYPE_STUDENT:
                                    echo $this->translate('Student address');
                                    break;
                                case Address::TYPE_MAIL:
                                    echo $this->translate('Mail address');
                                    break;
                            }
                            ?></h4>
                        <table class="table table-bordered">
                            <tr>
                                <th><?= $this->translate('Country') ?></th>
                                <td><?= $address->getCountry() ?></td>
                            </tr>
                            <tr>
                                <th><?= $this->translate('Street and number') ?></th>
                                <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
                            </tr>
                            <tr>
                                <th><?= $this->translate('City and postal code') ?></th>
                                <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
                            </tr>
                        </table>
                    <?php endforeach ?>
                <?php endif; ?>
            </div>
            <div class="col-md-6">
                <?php if ($profilePhoto != null): ?>
                    <div class="row">
                        <div class="col-sm-12 col-xs-12">
                            <a class="thumbnail"
                               href="<?= $this->url(
                                   'photo/album',
                                   [
                                       'album_id' => $member->getLidnr(),
                                       'album_type' => 'member',
                                       'photo_id' => $profilePhoto->getId(),
                                   ],
                               ) ?>">
                                <?php
                                $pAspectRatio = $profilePhoto->getAspectRatio();

                                $pLargeWidth = $photoConfig['large_thumb_size']['width'];
                                $pLargeSize = [
                                    'w' => $pLargeWidth,
                                    'h' => round($pLargeWidth * $pAspectRatio)
                                ];
                                ?>
                                <img class="img-responsive"
                                     src="<?= $this->glideUrl()->getUrl($profilePhoto->getPath(), $pLargeSize) ?>"
                                     alt="">
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="row">
                    <div class="col-sm-6 col-xs-6">
                        <a class="panel panel-image"
                           href="<?= $this->url('photo/album',
                            [
                                'album_id' => $member->getLidnr(),
                                'album_type' => 'member',
                            ],
                        ) ?>">
                            <div class="panel-body">
                                <div class="far fa-image big-icon"></div>
                                <h4>
                                    <?= sprintf(
                                        $this->translate("Photo's of %s"),
                                        $this->escapeHtml($member->getFirstName()),
                                    ) ?>
                                </h4>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
