<h1><?= $course->getCode() ?> - <?= $course->getName() ?></h1>

<ul>
    <li><strong>Course url:</strong> <a href="<?= $course->getUrl() ?>">
    <?= $course->getUrl() ?>
    </a></li>
</ul>

<?php $children = $course->getChildren() ?>
<?php if (!empty($children)): ?>
<h2><?= $this->translate('Course parts') ?></h2>
<ul>
<?php foreach ($course->getChildren() as $child): ?>
    <li><strong><?= $child->getCode() ?></strong> <?= $child->getName() ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<h2><?= $this->translate('Exams and summaries') ?></h2>

<ul>
<?php foreach ($course->getChildren() as $child): ?>
    <?php foreach ($child->getExams() as $exam): ?>
        <li><a href="<?= $this->url('education/course/download', [
            'code' => $exam->getCourse()->getCode(),
            'id' => $exam->getId()
            ]) ?>">
        <strong>(<?= $child->getCode() ?>)</strong>
        <?= sprintf($this->translate('Exam of %s'), $exam->getDate()->format('Y-m-d')) ?>
        </a></li>
    <?php endforeach; ?>
<?php endforeach; ?>
<?php foreach ($course->getExams() as $exam): ?>
    <li><a href="<?= $this->url('education/course/download', [
        'code' => $exam->getCourse()->getCode(),
        'id' => $exam->getId()
        ]) ?>">
    <?= sprintf($this->translate('Exam of %s'), $exam->getDate()->format('Y-m-d')) ?>
    </a></li>
<?php endforeach; ?>
</ul>
