<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Education\Form\SearchCourse as SearchCourseForm;
use Education\Model\Course as CourseModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CourseModel[]|null $courses
 * @var SearchCourseForm $form
 */

$this->headTitle($this->translate('Education'));
?>
<style>
    .row-spacing-top {
        margin-top: 2rem;
    }

    body.js .table-clickable tbody tr {
        cursor: pointer;
    }
</style>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate("Education") ?></h1>
            </div>
        </div>
        <div class="row row-spacing-top">
            <div class="col-md-12">
                <h2><?= $this->translate('Exams') ?></h2>
            </div>
            <div class="col-md-8">
                <?php
                $form->prepare();

                $form->setAttribute('action', $this->url('education'));
                $form->setAttribute('method', 'get');
                $form->setAttribute('class', '');
                $form->setAttribute('role', 'form');

                echo $this->form()->openTag($form);
                ?>
                <div class="input-group">
                    <?php
                    $element = $form->get('query');
                    $element->setAttribute('class', 'form-control');
                    $element->setAttribute('id', 'exam-search');
                    $element->setAttribute('placeholder', $this->translate('Course code or course description'));
                    ?>
                    <?= $this->formText($element) ?>
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default"
                                value="<?= $this->translate('Search') ?>"><?= $this->translate('Search') ?></button>
                    </span>
                </div>

                <?= $this->formElementErrors($element) ?>

                <?= $this->form()->closeTag(); ?>

                <br/>

                <?php if (isset($courses)): ?>
                    <?php
                    $count = count($courses);
                    ?>
                    <p>
                        <strong>
                            <?= sprintf(
                                $this->translate('Found %d %s matching your description'),
                                $count,
                                $this->translatePlural(
                                    'course',
                                    'courses',
                                    $count,
                                ),
                            ) ?>
                        </strong>
                    </p>
                <?php endif; ?>
                <?php if (!empty($courses)): ?>
                    <table class="table table-bordered table-striped table-hover table-clickable">
                        <thead>
                        <tr>
                            <td><?= $this->translate('Course code') ?></td>
                            <td><?= $this->translate('Course name') ?></td>
                            <td><?= $this->translate('Available documents') ?></td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($courses as $course): ?>
                            <?php
                            $courseLink = $this->url('education/course', ['code' => $course->getCode()]);
                            ?>
                            <tr data-link="<?= $courseLink ?>">
                                <td>
                                    <a href="<?= $courseLink ?>"
                                       title="<?= $this->translate('View available documents') ?>">
                                        <?= $course->getCode() ?>
                                    </a>
                                </td>
                                <td>
                                    <?= $course->getName() ?>
                                </td>
                                <td>
                                    <?= $course->getDocuments()->count() ?: $this->translate('None') ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>

                <p class="text-muted">
                    <?=
                    sprintf(
                        $this->translate('Do you want to contribute to the collection of old exams and summaries? Send them to the %seducation officer%s so that your (future) peers can benefit.'),
                        '<a href="mailto:co@gewis.nl" title="' . $this->translate('Mail the education officer') . '">',
                        '</a>'
                    );
                    ?>
                </p>

                <hr/>
            </div>
        </div>
        <div class="row row-spacing-top">
            <div class="col-md-12">
                <h2><?= $this->translate('Useful links') ?></h2>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="h4"><?= $this->translate('Books') ?></span>
                    </div>
                    <div class="panel-body">
                        <p><?= $this->translate('Order your course books via GEWIS to receive a discount. Specific ordering deadlines and pickup dates will be timely communicated to you via an email.') ?></p>
                    </div>
                    <div class="panel-footer panel-footer--links">
                        <a href="https://gewis.nl/boeken" title="<?= $this->translate('Visit the webshop') ?>"
                           class="panel-footer__link--primary"
                           target="_blank"><?= $this->translate('Visit webshop') ?></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span class="h4"><?= $this->translate('Tutoring') ?></span>
                    </div>
                    <div class="panel-body">
                        <p><?= $this->translate('Are you looking for someone to help you with your courses? Send an email using one of the following links and we can help you find someone to tutor you.') ?></p>
                    </div>
                    <div class="panel-footer panel-footer--links">
                        <a href="mailto:tutoringcs@gewis.nl" title="<?= $this->translate('Tutoring CS') ?>"
                           class="panel-footer__link--primary"
                           target="_blank"
                           style="margin-right:12px;"><?= $this->translate('Tutoring CS') ?></a>
                        <a href="mailto:tutoringam@gewis.nl" title="<?= $this->translate('Tutoring AM') ?>"
                           class="panel-footer__link--primary"
                           target="_blank"
                           style="margin-right:12px;"><?= $this->translate('Tutoring AM') ?></a>
                        <a href="mailto:co@gewis.nl" title="<?= $this->translate('Want to be a tutor?') ?>"
                           class="panel-footer__link--primary"
                           target="_blank"><?= $this->translate('Want to be a tutor?') ?></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row row-spacing-top">
            <div class="col-md-12">
                <h2><?= $this->translate('Complaint or suggestion about TU/e education?') ?></h2>
            </div>
            <div class="col-md-12">
                <p>
                    <?=
                    sprintf(
                        $this->translate('Do you have a complaint or suggestion concerning the education at the TU/e? Contact the %seducation officer%s to share your ideas.'),
                        '<a href="mailto:feedback@gewis.nl" title="' . $this->translate('Mail the education officer') . '">',
                        '</a>'
                    )
                    ?>
                </p>
            </div>
        </div>

        <div class="row row-spacing-top">
            <div class="col-md-12">
                <h2><?= $this->translate('Disclaimer on educational content') ?></h2>
            </div>
            <div class="col-md-12">
                <p>
                    <?=
                    $this->translate('The exams on the website of GEWIS are provided by Education & Student Affairs of the department of Mathematics and Computer Science of the TU/e.'),
                        $this->translate('If an exam has been put online without the intention of the author, please let the board of GEWIS know by sending an') . ' ',
                        '<a href="mailto:board@gewis.nl" title="' . $this->translate('Email the board of GEWIS') . '">' . $this->translate('email to the board of GEWIS') . '</a>',
                        ', ' . $this->translate('then this exam will be removed from the website. Using the summaries or exams on this website for commercial goals without the permission of the author is illegal.')
                    ?>
                </p>
            </div>
        </div>
    </div>
</section>
