<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('education'));
$form->setAttribute('method', 'get');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('query');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Search query'));
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<button type="submit" class="btn btn-default" value="Zoek">Zoek</button>

<?= $this->form()->closeTag(); ?>

<?php if (!empty($courses)): ?>
<table class="table table-striped">
    <thead>
    <tr>
        <th><?= $this->translate('Course code') ?></th>
        <th><?= $this->translate('Course description') ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($courses as $course): ?>
    <tr>
        <td><a href="<?= $this->url('education/course', array('code' => $course->getCode())) ?>" style="display: block; height: 100%; width:100%;">
<?= $course->getCode() ?>
        </a></td>
        <td><a href="<?= $this->url('education/course', array('code' => $course->getCode())) ?>" style="display: block; height: 100%; width:100%;">
<?= $course->getName() ?>
        </a></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
