<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool $canDelete
 * @var int $pageId
 */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headScript()
    ->appendFile(
        $this->basepath('js/ckeditor/ckeditor.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

if ('nl' === $lang) {
    $this->headScript()->appendFile(
        $this->basepath('js/ckeditor/translations/nl.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
}

$this->headLink()
    ->appendStylesheet($this->basepath('css/ckeditor/style.css'));

$this->scriptUrl()->requireUrl('admin_page/upload');

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Pages'), true, $this->url('admin_page'))
    ->addBreadcrumb($this->translate('Edit'));
?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>
<?= $this->form()->openTag($form); ?>
<h2><?= $this->translate('URL options') ?></h2>
<?= $this->translate(
    // phpcs:ignore Generic.Files.LineLength.TooLong -- user-visible strings should not be split
    'Make this page available at the following URLs. Providing a category is required. Always try to translate the relevant segments of the URL.',
) ?>
<br>
<?php foreach(['En', ''] as $suffix): ?>
    <?php

    $category = $form->get('category' . $suffix);
    $category->setAttribute('class', 'form-control')
        ->setAttribute('id', 'category-' . ('' === $suffix) ? 'nl' : 'en')
        ->setAttribute('required', 'required')
        ->setAttribute('placeholder', $this->translate('Category'));

    $subCategory = $form->get('subCategory' . $suffix);
    $subCategory->setAttribute('class', 'form-control')
        ->setAttribute('id', 'sub-category-' . ('' === $suffix) ? 'nl' : 'en')
        ->setAttribute('placeholder', $this->translate('Subcategory'));

    $name = $form->get('name' . $suffix);
    $name->setAttribute('class', 'form-control')
        ->setAttribute('id', 'name-' . ('' === $suffix) ? 'nl' : 'en')
        ->setAttribute('placeholder', $this->translate('Name'));

    ?>
    <div class="form-group form-inline">
        <strong>
            <?= $this->serverUrl($this->url('home', ['language' => '' === $suffix ? 'nl' : 'en'])) ?>
            <div class="<?= $this->bootstrapElementError($category) ?>" style="display: inline-block">
                <?= $this->formText($category); ?>
                <?= $this->formElementErrors($category); ?>
            </div>/
            <div class="<?= $this->bootstrapElementError($subCategory) ?>" style="display: inline-block">
                <?= $this->formText($subCategory); ?>
                <?= $this->formElementErrors($subCategory); ?>
            </div>/
            <div class="<?= $this->bootstrapElementError($name) ?>" style="display: inline-block">
                <?= $this->formText($name); ?>
                <?= $this->formElementErrors($name); ?>
            </div>
        </strong>
    </div>
<?php endforeach; ?>
<hr>

<h2><?= $this->translate('English content') ?></h2>
<?php
$element = $form->get('titleEn');
$element->setAttribute('class', 'form-control');
$element->setAttribute('id', 'title-en');
$element->setAttribute('required', 'required');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<?php
$element = $form->get('contentEn');
$element->setAttribute('id', 'content-en')
    ->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<hr>
<h2><?= $this->translate('Dutch content') ?></h2>
<?php
$element = $form->get('title');
$element->setAttribute('class', 'form-control');
$element->setAttribute('id', 'title-nl');
$element->setAttribute('required', 'required');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<?php
$element = $form->get('content');
$element->setAttribute('id', 'content-nl')
    ->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<hr>
<h3><?= $this->translate('Permissions') ?></h3>
<p>
    <?= $this->translate('Set the minimal role required to view this page. All visitors whom have this role may view the page.') ?>
</p>
<?php
$element = $form->get('requiredRole');
$element->setAttribute('class', 'form-control');
$element->setAttribute('required', 'required');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <?= $this->formLabel($element); ?>
    <?= $this->formSelect($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>
<hr>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?php if ($canDelete): ?>
    <a href="<?= $this->url('admin_page/delete', ['page_id' => $pageId]) ?>" class="btn btn-danger">
        <span class="far fa-trash-alt"></span>&nbsp;
        <?= $this->translate('Delete this page') ?>
    </a>
<?php endif ?>

<?= $this->form()->closeTag(); ?>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    GEDITOR.FullEditor
        .create(document.querySelector('#content-nl'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });

    GEDITOR.FullEditor
        .create(document.querySelector('#content-en'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });
</script>
