<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool $canDelete
 * @var int $pageId
 */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headScript()
    ->appendFile(
        $this->basePath() . '/js/ckeditor/ckeditor.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

if ('nl' === $lang) {
    $this->headScript()->appendFile(
        $this->basePath() . '/js/ckeditor/translations/nl.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
}

$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/ckeditor/style.css');

$this->scriptUrl()->requireUrl('admin_page/upload');

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Pages'), true, $this->url('admin_page'))
    ->addBreadcrumb($this->translate('Edit'));
?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>
<?= $this->form()->openTag($form); ?>
<h3><?= $this->translate('URL options') ?></h3>
<?= $this->translate('Make this page available at the following URL. Providing a category is required.') ?>
</br>
<div class="form-group form-inline">
    <?php
    $category = $form->get('category');
    $subCategory = $form->get('subCategory');
    $name = $form->get('name');

    $category->setAttribute('class', 'form-control');
    $subCategory->setAttribute('class', 'form-control');
    $name->setAttribute('class', 'form-control');

    $category->setAttribute('placeholder', 'category');
    $subCategory->setAttribute('placeholder', 'sub-category');
    $name->setAttribute('placeholder', 'name');

    $category->setAttribute('required', 'required');
    ?>
    <strong>
        <?= $this->serverUrl($this->basePath()) ?>/
        <?= $this->formText($category); ?>/
        <?= $this->formText($subCategory); ?>/
        <?= $this->formText($name); ?>
    </strong>
</div>

<?= $this->formElementErrors($category); ?>
<?= $this->formElementErrors($subCategory); ?>
<?= $this->formElementErrors($name); ?>
<hr>

<h3><?= $this->translate('English content') ?></h3>
<div class="form-group">
    <?php
    $element = $form->get('englishTitle');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('required', 'required');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<div class="form-group">
    <?php
    $element = $form->get('englishContent');
    $element->setAttribute('id', 'english-content')
        ->setAttribute('class', 'form-control');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<hr>
<h3><?= $this->translate('Dutch content') ?></h3>
<div class="form-group">
    <?php
    $element = $form->get('dutchTitle');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('required', 'required');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<div class="form-group">
    <?php
    $element = $form->get('dutchContent');
    $element->setAttribute('id', 'dutch-content')
        ->setAttribute('class', 'form-control');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<hr>
<h3><?= $this->translate('Permissions') ?></h3>
Set the minimal role required to view this page. All visitors whom have this role may view the page.
<div class="form-group">
    <?php
    $element = $form->get('requiredRole');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('required', 'required');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>
<hr>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?php if ($canDelete): ?>
    <a href="<?= $this->url('admin_page/delete', ['page_id' => $pageId]) ?>" class="btn btn-danger">
        <span class="far fa-trash-alt"></span>&nbsp;
        <?= $this->translate('Delete this page') ?>
    </a>
<?php endif ?>

<?= $this->form()->closeTag(); ?>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    ClassicEditor
        .create(document.querySelector('#dutch-content'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });

    ClassicEditor
        .create(document.querySelector('#english-content'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });
</script>
