<?php

use Application\View\HelperTrait;
use Frontpage\Model\Page as PageModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var PageModel[] $pages
 */

$this->headScript()
    ->appendFile(
        $this->basePath() . '/js/tree.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
$this->headLink()->appendStylesheet($this->basePath() . '/css/tree.css');

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Pages'));
?>
<h3><?= $this->translate('Pages') ?></h3>

<a href="<?= $this->url('admin_page/create') ?>" class="btn btn-primary">
    <span class="fas fa-plus"></span>&nbsp;
    <?= $this->translate('Create a new page') ?>
</a>
<?= $this->translate('Or select a page to edit below.') ?>
<hr>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="tree">
                    <?php
                    function showPageTree($pages, $context)
                    {
                        foreach ($pages as $category => $data): ?>
                            <li>
                                <?php if (isset($data['page'])): ?>
                                    <a
                                        href="<?= $context->url('admin_page/edit',
                                            ['page_id' => $data['page']->getId()]) ?>">
                                        <?= $category ?> (<?= $data['page']->getEnglishTitle() ?>)
                                    </a>
                                <?php else: ?>
                                    <?= $category ?>
                                <?php endif ?>

                                <?php if (!empty($data['children'])): ?>
                                    <ul>
                                        <?php showPageTree($data['children'], $context); ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php
                        endforeach;
                    }

                    showPageTree($pages, $this);
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    $(document).ready(function () {
        $('.tree').treed();
    });
</script>
