<?php $lang = 'en'; ?>
For English, please see below.<br /><br />

L.S.,<br /><br />

<?= $authorization->getAuthorizer()->getFullName()?> heeft je gemachtigd voor AV <?= $authorization->getMeetingNumber()?>.
<br/><br/>

Met vriendelijke groeten,<br />
De Web Commissie
<hr />

L.S.,<br /><br />

<?= $authorization->getAuthorizer()->getFullName()?> has authorized you for GM <?= $authorization->getMeetingNumber()?>.
<br/><br/>

With kind regards,<br />
The Web Committee
<hr />