<?php $lang = 'en'; ?>
For English, see below.

L.s.<br /><br />

Je hebt successvol <?= $authorization->getRecipient()->getFullName()?> gemachtigd voor AV <?= $authorization->getMeetingNumber()?>.
<br/><br/>

Met vriendelijke groeten,<br />
De Web Commissie
<hr />

L.s.<br /><br />

You have successfully authorized <?= $authorization->getRecipient()->getFullName()?> for GM <?= $authorization->getMeetingNumber()?>.
<br/><br/>

With kind regards,<br />
The Web Committee
<hr />