<?php $lang = 'en'; ?>
For English, please see below.<br /><br />

L.S.,<br /><br />

Je hebt <?= $authorization->getRecipient()->getFullName()?> successvol gemachtigd voor AV <?= $authorization->getMeetingNumber()?>.
<br/><br/>

Met vriendelijke groeten,<br />
De Web Commissie
<hr />

L.S.,<br /><br />

You have successfully authorized <?= $authorization->getRecipient()->getFullName()?> for GM <?= $authorization->getMeetingNumber()?>.
<br/><br/>

With kind regards,<br />
The Web Committee
<hr />