For English, please see below.<br/><br/>

L.S.,<br/><br/>

<?= $authorization->getAuthorizer()->getFullName() ?> heeft hun machtiging voor ALV <?= $authorization->getMeetingNumber() ?> ingetrokken.
<br/><br/>

Met vriendelijke groeten,<br/>
De ApplicatieBeheerCommissie
<hr/>

L.S.,<br/><br/>

<?= $authorization->getAuthorizer()->getFullName() ?> has revoked their authorization for GMM <?= $authorization->getMeetingNumber() ?>.
<br/><br/>

With kind regards,<br/>
The ApplicatieBeheerCommissie
<hr/>
