<?php $lang = 'en'; ?>
For English, please see below.<br/><br/>

L.S.,<br/><br/>

<?= $authorization->getAuthorizer()->getFullName() ?> heeft je gemachtigd voor ALV <?= $authorization->getMeetingNumber() ?>.
<br/><br/>

Met vriendelijke groeten,<br/>
De Web Commissie
<hr/>

L.S.,<br/><br/>

<?= $authorization->getAuthorizer()->getFullName() ?> has authorized you for GMM <?= $authorization->getMeetingNumber() ?>.
<br/><br/>

With kind regards,<br/>
The Web Committee
<hr/>
