<?= "Dear board member, \n"?>

<?= $this->escapeHtml($company->getName()) . " just made a change to her page, which is now waiting for your approval.\n"?>

<?= "At your convenience, please click "  . $this->serverUrl($this->url('admin_organ')) . " to approve awaiting changes. \n" ?>

<?= "Best Regards,\n\n"?>
<?="The Web Committee\n\n\n"?>

<?="This is an automated email, please do not reply to this email."?>
