<?php $lang = 'en'; ?>
For English, please see below.<br/><br/>

Lieve bestuurder,<br/><br/>

Het orgaan '<?= $this->escapeHtml($organInfo->getOrgan()->getName()) ?>' heeft een update doorgevoerd op haar pagina. Gelieve deze update te reviewen.
<br/><br/>

Klik <a href="<?= $this->serverUrl($this->url('admin_organ')) ?>">hier</a> om deze update te bekijken.
<br/><br/>

Met vriendelijke groeten,<br/>
De Web Commissie
<hr/>

Dear board member,<br/><br/>

The organ '<?= $this->escapeHtml($organInfo->getOrgan()->getName()) ?>' has made a change to her page. Please review this update.
<br/><br/>

Click <a href="<?= $this->serverUrl($this->url('admin_organ')) ?>">here</a> to view this update.
<br/><br/>

Kind Regards, <br/>
The Web Committee
