<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/poll-admin.js');
$this->scriptUrl()->requireUrls(
    [
        'admin_poll/approve',
        'admin_poll/delete'
    ],
    ['poll_id']
);
?>
<h1><?= $this->translate('Polls awaiting approval') ?></h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th><?= $this->translate('Dutch question') ?></th>
            <th><?= $this->translate('English question') ?></th>
            <th><?= $this->translate('Date') ?></th>
            <th><?= $this->translate('Submitter') ?></th>
            <th><?= $this->translate('Approver') ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($unapprovedPolls as $poll): ?>
        <?php ob_start() /* start buffer for poll options */ ?>
        <dl>
            <dt><?= $this->translate('Dutch question') ?></dt>
            <dd><?= $this->escapeHtml($poll->getDutchQuestion()) ?></dd>

            <dt><?= $this->translate('English question') ?></dt>
            <dd><?= $this->escapeHtml($poll->getEnglishQuestion()) ?></dd>
        </dl>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><?= $this->translate('Dutch option') ?></th>
                <th><?= $this->translate('English option') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($poll->getOptions() as $option): ?>
                <tr>
                    <td><?= $this->escapeHtml($option->getDutchText()) ?></td>
                    <td><?= $this->escapeHtml($option->getEnglishText()) ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
        <?php $options = ob_get_clean() /* end buffer for poll options */ ?>
        <tr id="admin-poll-<?= $poll->getId() ?>" data-options="<?= $this->escapeHtmlAttr($options) ?>">
            <td><?= $poll->getId() ?></td>
            <td><?= $this->escapeHtml($poll->getDutchQuestion()) ?></td>
            <td><?= $this->escapeHtml($poll->getEnglishQuestion()) ?></td>
            <td><?= $poll->getExpiryDate()->format('Y-m-d') ?></td>
            <td><?= $poll->getCreator()->getMember()->getFullName() ?></td>
            <td></td>
            <td>
                <button type="button" class="btn btn-success btn-xs"
                        onclick="Poll.Admin.approvePoll(<?= $poll->getId() ?>)" data-toggle="modal"
                        data-target="#approveModal">
                    <?= $this->translate('Approve') ?>
                </button>
                <button type="button" class="btn btn-danger btn-xs"
                        onclick="Poll.Admin.deletePoll(<?= $poll->getId() ?>)" data-toggle="modal"
                        data-target="#deleteModal">
                    <?= $this->translate('Delete') ?>
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<h1><?= $this->translate('Approved polls') ?></h1>
<?= $this->paginationControl(
    $paginator,
    // the scrolling style
    'elastic',
    'paginator/default',
    [
        'path' => $this->url('admin_poll')
    ]
)
?>
<?php if (!empty($paginator)): ?>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th><?= $this->translate('Dutch question') ?></th>
                <th><?= $this->translate('English question') ?></th>
                <th><?= $this->translate('Date') ?></th>
                <th><?= $this->translate('Submitter') ?></th>
                <th><?= $this->translate('Approver') ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($paginator as $poll): ?>
        <?php ob_start() /* start buffer for poll options */ ?>
        <dl>
            <dt><?= $this->translate('Dutch question') ?></dt>
            <dd><?= $this->escapeHtml($poll->getDutchQuestion()) ?></dd>

            <dt><?= $this->translate('English question') ?></dt>
            <dd><?= $this->escapeHtml($poll->getEnglishQuestion()) ?></dd>
        </dl>
        <table class="table table-striped">
            <thead>
            <tr>
                <th><?= $this->translate('Dutch option') ?></th>
                <th><?= $this->translate('English option') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($poll->getOptions() as $option): ?>
                <tr>
                    <td><?= $this->escapeHtml($option->getDutchText()) ?></td>
                    <td><?= $this->escapeHtml($option->getEnglishText()) ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
        <?php $options = ob_get_clean() /* end buffer for poll options */ ?>
            <tr id="admin-poll-<?= $poll->getId() ?>" data-options="<?= $this->escapeHtmlAttr($options) ?>">
                <td><?= $poll->getId() ?></td>
                <td><?= $this->escapeHtml($poll->getDutchQuestion()) ?></td>
                <td><?= $this->escapeHtml($poll->getEnglishQuestion()) ?></td>
                <td><?= $poll->getExpiryDate()->format('Y-m-d') ?></td>
                <td><?= $poll->getCreator()->getMember()->getFullName() ?></td>
                <td><?= $poll->getApprover()->getMember()->getFullName() ?></td>
                <td>
                    <?php if ($poll->isActive()): ?>
                    <button type="button" class="btn btn-danger btn-xs"
                            onclick="Poll.Admin.deletePoll(<?= $poll->getId() ?>)" data-toggle="modal"
                            data-target="#deleteModal">
                        <?= $this->translate('Delete') ?>
                    </button>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<!-- Delete poll modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
            </div>
            <div class="modal-body">
                <p><?= $this->translate('Are you sure you want to delete this poll?') ?> </p>
                <p class="options">
                </p>
            </div>
            <div class="modal-footer">
                <form id="deleteForm" method="POST">
                    <input type="submit" name="submit" value="<?= $this->translate('Delete poll') ?>"
                           class="btn btn-danger"/>
                    <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                </form>

            </div>
        </div>
    </div>
</div>

<!-- Approve poll modal -->
<div class="modal fade" id="approveModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Approve poll') ?></h4>
            </div>
            <div class="modal-body">
                <p><?= $this->translate('Are you sure that you want to approve this poll?') ?></p>
                <p class="options">
                </p>
                <?php
                $form = $this->approvalForm;
                $form->prepare();

                $form->setAttribute('method', 'post');
                $form->setAttribute('id', 'approvalForm');
                $form->setAttribute('role', 'form');
                ?>
                <?= $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php
                        $element = $form->get('expiryDate');
                    ?>
                    <?= $this->formLabel($element); ?>
                    <?= $this->formInput($element); ?>
                    <?= $this->formElementErrors($element); ?>
                </div>
            </div>
            <div class="modal-footer">
                <?php
                    $submit = $form->get('submit');
                    $submit->setLabel($this->translate('Approve poll'));
                    $submit->setAttribute('class', 'btn btn-success');
                ?>
                <?= $this->formButton($submit) ?>
                <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
