<h1><?= $this->translate('Polls awaiting approval') ?></h1>
<table class="table table-striped">
    <thead><tr>
        <th>#</th>
        <th><?= $this->translate('Dutch question') ?></th>
        <th><?= $this->translate('English question') ?></th>
        <th><?= $this->translate('Date') ?></th>
        <th><?= $this->translate('Submitter') ?></th>
        <th><?= $this->translate('Approver') ?></th>
        <th><?= $this->translate('Actions') ?></th>
    </tr></thead>
    <tbody>
    <?php foreach ($unapprovedPolls as $poll): ?>
        <tr>
            <td><?= $poll->getId() ?></td>
            <td><?= $poll->getDutchQuestion() ?></td>
            <td><?= $poll->getEnglishQuestion() ?></td>
            <td><?= $poll->getExpiryDate()->format('Y-m-d') ?></td>
            <td><?= $poll->getCreator()->getMember()->getFullName() ?></td>
            <td></td>
            <td>
                <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#approveModal">
                    Approve
                </button>
                <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteModal">
                    Remove
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<h1><?= $this->translate('Approved polls') ?></h1>
<?= $this->paginationControl(
    $paginator,
    // the scrolling style
    'elastic',
    'paginator/default',
    [
        'path' => $this->url('poll/history')
    ]
)
?>
<?php if (!empty($paginator)): ?>

    <table class="table table-striped">
        <tbody>
        <?php foreach ($paginator as $poll): ?>
            <tr>
                <td><?= $poll->getId() ?></td>
                <td><?= $poll->getDutchQuestion() ?></td>
                <td><?= $poll->getEnglishQuestion() ?></td>
                <td><?= $poll->getExpiryDate()->format('Y-m-d') ?></td>
                <td><?= $poll->getCreator()->getMember()->getFullName() ?></td>
                <td><?= $poll->getApprover()->getMember()->getFullName() ?></td>
                <td>
                    <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteModal">
                        Remove
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>