<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var int $number
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Meetings'))
    ->addBreadcrumb($this->translate('Authorizations'));
?>
<section class="section">
    <div class="container">
        <div class="form-group">
            <select class="form-control" id="meeting-selector">
                <?php if (!empty($meetings)): ?>
                    <?php foreach ($meetings as $meeting): ?>
                        <option
                            value="<?= $this->url(
                                'decision_admin/authorizations',
                                ['number' => $meeting->getNumber()],
                            ) ?>"
                            <?= ($meeting->getNumber() === $number) ? 'selected' : '' ?>
                        >
                            <?= sprintf(
                                $this->translate('GMM %d (%s)'),
                                $meeting->getNumber(),
                                $meeting->getDate()->format('Y-m-d')
                            ) ?>
                        </option>
                    <?php endforeach; ?>
                <?php else: ?>
                    <option selected disabled><?= $this->translate('No GMM available.') ?></option>
                <?php endif; ?>
            </select>
        </div>
        <?php if (null !== $number): ?>
            <h3><?= sprintf($this->translate('Valid authorizations for GMM %d'), $number) ?></h3>
            <?php if (!empty($valid)): ?>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td><?= $this->translate('Authorizer') ?></td>
                            <td><?= $this->translate('Recipient') ?></td>
                            <td><?= $this->translate('Created') ?></td>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($valid as $authorization): ?>
                        <tr>
                            <td><?= $authorization->getAuthorizer()->getFullName() ?></td>
                            <td><?= $authorization->getRecipient()->getFullName() ?></td>
                            <td><?= $authorization->getCreatedAt()->format('Y-m-d H:i:s') ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p><?= $this->translate('There are no valid authorizations for this GMM.') ?></p>
            <?php endif; ?>
            <hr>
            <h3><?= sprintf($this->translate('Revoked authorizations for GMM %d'), $number) ?></h3>
            <?php if (!empty($revoked)): ?>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <td><?= $this->translate('Authorizer') ?></td>
                        <td><?= $this->translate('Recipient') ?></td>
                        <td><?= $this->translate('Created') ?></td>
                        <td><?= $this->translate('Revoked') ?></td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($revoked as $authorization): ?>
                        <tr>
                            <td><?= $authorization->getAuthorizer()->getFullName() ?></td>
                            <td><?= $authorization->getRecipient()->getFullName() ?></td>
                            <td><?= $authorization->getCreatedAt()->format('Y-m-d H:i:s') ?></td>
                            <td><?= $authorization->getRevokedAt()->format('Y-m-d H:i:s') ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <p><?= $this->translate('There are no revoked authorizations for this GMM.') ?></p>
            <?php endif; ?>
        <?php elseif (!empty($meetings)): ?>
            <p><?= $this->translate('Please select a GMM to view authorizations.') ?></p>
        <?php endif; ?>
    </div>
</section>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.getElementById('meeting-selector').addEventListener('change', e => {
        window.location = e.target.value;
    });
</script>
