<?php if (isset($success) && $success): ?>
<?= $this->translate('Meeting document uploaded'); ?>
<?php endif; ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('method', 'post');

$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form); ?>
<?php
$element = $form->get('meeting');
?>
<div class="form-group">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
    <div class="col-sm-10">
        <select class="form-control" name="meeting" onchange="window.location='<?= $this->url('admin_decision/document') ?>/'+this.value">
            <?php foreach ($meetings as $m): ?>
                <option value="<?= $m->getType()?>/<?= $m->getNumber() ?>"
                <?= $m->getNumber() === intval($number) ? 'selected' : '' ?>>
                    <?= $m->getType() ?> <?= $m->getNumber() ?> (<?= $m->getDate()->format('Y-m-d') ?>)
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
    <div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Name'));
$element->setAttribute('required', 'required');
?>
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formElement($element); ?>
            <?= $this->formElementErrors($element); ?>
        </div>
    </div>

    <div class="form-group">
        <?php $fileElement = $form->get('upload'); ?>
        <label for="<?= $fileElement->getName() ?>" class="control-label col-sm-2"><?= $fileElement->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formFile($fileElement); ?>
            <?= $this->formElementErrors($fileElement); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($submit->getValue());
            $submit->setAttribute('class', 'btn btn-default');
            ?>
            <?= $this->formButton($submit) ?>
        </div>
    </div>

<?= $this->form()->closeTag(); ?>
<h3><?= $this->translate('Documents for this meeting') ?></h3>
<div class="col-sm-12">
<table class="table table-striped table-hover table-documents">
    <?php foreach ($meeting->getDocuments() as $document): ?>
    <tr>
        <td class="btn-group-move">
            <?php
            /** @var \Zend\Form\Form $form */
            $form = $this->reorderDocumentForm;

            $form->setAttributes([
                'action' => $this->url('admin_decision/position_document')
            ]);
            $form->populateValues([
                'document' => $document->getId()
            ]);
            $form->prepare();
            ?>
            <?= $this->form()->openTag($form) ?>
                <?php foreach ($form as $element): ?>
                    <?= $this->formElement($element); ?>
                <?php endforeach; ?>
            <?= $this->form()->closeTag($form) ?>
        </td>
        <td>
            <a href="<?= $this->url('decision/document', ['id' => $document->getId()]) ?>">
                <?= $document->getName() ?>
            </a>
        </td>
        <td>
            <form method="POST" action="<?= $this->url('admin_decision/delete_document') ?>">
                <input type="hidden" name="document" value="<?= $document->getId() ?>">
                <input type="submit" name="submit" value="<?= $this->translate('Delete') ?>" class="btn btn-danger btn-xs pull-right"/>
            </form>
        </td>
    </tr>
    <?php endforeach ?>
</table>
</div>
<script>
    $()
</script>