<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Form\Minutes as MinutesForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MinutesForm $form
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Meetings'))
    ->addBreadcrumb($this->translate('Minutes'));

$form->prepare();

$form->setAttribute('action', $this->url('decision_admin/default', ['action' => 'minutes']));
$form->setAttribute('method', 'post');

$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?php
    $element = $form->get('meeting');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $this->translate('Meeting'));
    $element->setAttribute('required', 'required');
    ?>
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formSelect($element); ?>
        <?= $this->formElementErrors($element); ?>
    </div>
</div>

<div class="form-group">
    <?php $fileElement = $form->get('upload'); ?>
    <label for="<?= $fileElement->getName() ?>"
           class="control-label col-sm-2"><?= $fileElement->getLabel() ?></label>
    <div class="col-sm-10">
        <?= $this->formFile($fileElement); ?>
        <?= $this->formElementErrors($fileElement); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($this->translate('Upload'));
        $submit->setAttribute('class', 'btn btn-default');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
