<?php
$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$companyURL = $this->url('company/companyItem', // Route url
    ['slugCompanyName' => $company->getSlugName()], // Url parameters
    [], // routeOptions
    true); // Reuse matched parameters
?>

<div class="col-md-3">
    <?php
    $translation = $company->getTranslationFromLocale($locale);
    if (!isset($translation)) {
        $translation = $company->getTranslations()[0];
    }
    ?>
    <a href="<?= $translation->getWebsite() ?>">
        <img class="company-logo img-responsive center-block"
             src="<?= $escaper->escapeHtmlAttr($this->fileUrl($translation->getLogo())) ?>"
             alt="<?= $this->translate('Logo of') ?> <?= $escaper->escapeHtmlAttr($company->getName()) ?>"/>
    </a>
    <div class="">
        <h4><?= $this->translate('Contact') ?></h4>
        <?php if (!empty($company->getContactName())): ?>
            <p class="company-contactName"><?= $company->getContactName() ?></p>
        <?php endif ?>
        <p class="company-address"><?= nl2br($company->getAddress()) ?></p>
        <p class="company-phone"><a href="tel:<?= rawurlencode($company->getPhone()) ?>"><?= $company->getPhone() ?></a>
        </p>
        <p class="company-website"><a href="<?= $translation->getWebsite() ?>">Visit website</a></p>
        <p class="company-email"><a
                href="mailto:<?= rawurlencode($company->getEmail()) ?>"><?= $company->getEmail() ?></a></p>
    </div>
    <?php foreach ($this->jobCategories() as $category): ?>
        <div class="company-jobs" data-amount="<?= $company->getNumberOfJobs($category) ?>">
            <?php if ($company->getNumberOfJobs($category) > 0) { ?>
                <h4><?= $category->getPluralName() ?></h4>
            <?php } ?>
            <ul class="company-jobs-list">
                <?php // TODO: jobs sorted by package, which is not useful for visitor, possibily change sorting here to be useful
                foreach ($company->getPackages() as $package):
                    if ($package->getType() === 'job'):
                        $categories = $this->jobCategories();
                        foreach ($categories as $category):
                            $jobs = $package->getJobsInCategory($category);
                            if (count($jobs) > 0):
                                ?>
                                <h4><?= $category->getPluralName() ?></h4>
                            <?php
                            endif;
                            foreach ($jobs as $job):
                                ?>
                                <li class="company-jobs-job">
                                    <a href="<?= $this->url('company/companyItem/joblist/job_item',
                                        ['slugCompanyName' => $company->getSlugName(),
                                            'slugJobName' => $job->getSlugName(),
                                            'category' => $category->getSlug(),
                                        ], [], true) ?>"><?= $job->getName(); ?></a>
                                </li>
                            <?php
                            endforeach;
                        endforeach;
                    endif;
                endforeach;
                ?>
            </ul>
        </div>
    <?php endforeach; ?>
</div>
<div class="col-md-9">
    <h4><?= $this->translate('Article') ?></h4>
    <div class="company-description text-justify markdown"><?= $this->markdown($featuredPackage->getArticle()) ?></div>
</div>
