<?php
$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$companyURL = $this->url('company/companyItem', // Route url
    ['slugCompanyName' => $company->getSlugName()], // Url parameters
    [], // routeOptions
    true); // Reuse matched parameters
?>

<div class="col-md-3">
    <?php
        $translation = $company->getTranslationFromLocale($locale);
        if (!isset($translation)) {
            $translation = $company->getTranslations()[0];
        }
    ?>
    <a href="<?= $translation->getWebsite() ?>">
        <img class="company-logo img-responsive center-block" src="<?= $escaper->escapeHtmlAttr($this->fileUrl($translation->getLogo())) ?>" alt="<?= $this->translate('Logo of') ?> <?= $escaper->escapeHtmlAttr($company->getName()) ?>" />
    </a>
    <div class="">
        <h4><?= $this->translate('Contact') ?></h4>
        <p class="company-address"><?= nl2br($company->getAddress()) ?></p>
        <p class="company-phone"><a href="tel:<?= rawurlencode($company->getPhone()) ?>"><?= $company->getPhone() ?></a></p>
        <p class="company-website"><a href="<?= $translation->getWebsite() ?>">Visit website</a></p>
        <p class="company-email"><a href="mailto:<?= rawurlencode($company->getEmail()) ?>"><?= $company->getEmail() ?></a></p>
    </div>
    <div class="company-jobs" data-amount="<?= $company->getNumberOfJobs() ?>">
        <?php if ($company->getNumberOfJobs() > 0) { ?>
            <h4><?= $this->translate('Jobs') ?></h4>
        <?php } ?>
        <ul class="company-jobs-list">
            <?php  // TODO: jobs sorted by package, which is not useful for visitor, possibily change sorting here to be useful
            foreach ($company->getPackages() as $package):
                if ($package->getType() === 'job'):
                    foreach($package->getJobs() as $job):
                        if ($job->isActive() && $job->getLanguage() === $locale): ?>
                            <li class="company-jobs-job">
                                <a href="<?= $this->url('company/companyItem/joblist/job_item',
                                    ['slugCompanyName' => $company->getSlugName(),
                                     'slugJobName' => $job->getSlugName()
                                    ], [], true) ?>"><?= $job->getName(); ?></a>
                            </li>
                            <?php
                        endif;
                    endforeach;
                endif;
            endforeach;
            ?>
        </ul>
    </div>
</div>
<div class="col-md-9">
    <h4><?= $this->translate('Article') ?></h4>
    <div class="company-description text-justify markdown"><?= $this->markdown($featuredPackage->getArticle()) ?></div>
</div>
