<?php
$escaper = new Laminas\Escaper\Escaper('utf-8');

$companyURL = $this->url(
    'company/companyItem', // Route url
    [
        'companySlugName' => $company->getSlugName(),
    ], // Url parameters
    [], // routeOptions
    true // Reuse matched parameters
);
?>

<div class="col-md-3">
    <a href="<?= $this->localiseText($company->getWebsite()) ?>">
        <img class="company-logo img-responsive center-block"
             src="<?= $this->fileUrl($company->getLogo()) ?>"
             alt="<?= $this->translate('Logo of') ?> <?= $escaper->escapeHtmlAttr($company->getName()) ?>"/>
    </a>
    <div>
        <h4><?= $this->translate('Contact') ?></h4>
        <?php if (null !== $company->getContactName()): ?>
            <p class="company-contactName">
                <?= $this->escapeHtml($company->getContactName()) ?>
            </p>
        <?php endif ?>
        <?php if (null !== $company->getContactAddress()): ?>
            <p class="company-address">
                <?= nl2br($this->escapeHtml($company->getContactAddress())) ?>
            </p>
        <?php endif; ?>
        <?php if (null !== $company->getContactPhone()): ?>
            <p class="company-phone">
                <a href="tel:<?= $escaper->escapeUrl($company->getContactPhone()) ?>">
                    <?= $this->escapeHtml($company->getContactPhone()) ?>
                </a>
            </p>
        <?php endif; ?>
        <?php if (null !== $company->getContactEmail()): ?>
            <p class="company-email">
                <a href="mailto:<?= $escaper->escapeUrl($company->getContactEmail()) ?>">
                    <?= $this->escapeHtml($company->getContactEmail()) ?>
                </a>
            </p>
        <?php endif; ?>
        <p class="company-website">
            <a href="<?= $this->localiseText($company->getWebsite()) ?>"><?= $this->translate('Visit Website') ?></a>
        </p>
    </div>
</div>
<div class="col-md-9">
    <h4><?= $this->translate('Highlighted') ?></h4>
    <div class="company-description text-justify markdown">
        <?= $this->markdown($this->localiseText($featuredPackage->getArticle())) ?>
    </div>
</div>
