<?php
$escaper = new Laminas\Escaper\Escaper('utf-8');

if (isset($this->company)) {
    $this->headTitle($this->company->getName());
}

$this->headTitle($this->localiseText($jobCategory->getPluralName()));

$this->headScript()
    ->appendFile($this->basePath() . '/js/bootstrap/tooltip.js');
?>
<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <?php if (isset($this->company)): ?>
                <li>
                    <a href="<?= $this->url(
                        'company/companyItem',
                        [
                            'companySlugName' => $company->getSlugName(),
                        ]
                    ) ?>">
                        <?= $this->escapeHtml($company->getName()) ?>
                    </a>
                </li>
            <?php endif; ?>
            <li class="active">
                <?= $this->escapeHtml($this->localiseText($jobCategory->getPluralName())) ?>
            </li>
        </ol>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->escapeHtml($this->localiseText($jobCategory->getPluralName())) ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="filter-bar">
                    <div class="form-group">
                        <label for="job-search"><span class="fas fa-search"></span></label>
                        <input
                            type="text"
                            class="form-control"
                            id="job-search"
                            placeholder="<?= $this->translate('What are you looking for?') ?>"/>
                    </div>
                    <div class="form-group">
                        <label for="job-sort"><?= $this->translate('Sort on') ?></label>
                        <select name="sort" id="job-sort" class="form-control">
                            <option value="random"><?= $this->translate('Random') ?></option>
                            <option value="posted"><?= $this->translate('Most recent') ?></option>
                        </select>
                    </div>
                    <?php if (isset($this->company)): ?>
                        <div class="form-group">
                            <label><?= $this->translate('Company') ?></label>
                            <a href="<?= $this->url(
                                'company/jobList',
                                [
                                    'category' => $this->localiseText($jobCategory->getSlug()),
                                ]
                            ) ?>" class="btn btn-default btn-filter align-middle">
                                <span class="btn-text" title="<?= $escaper->escapeHtmlAttr($company->getName()) ?>">
                                    <?= $this->escapeHtml($company->getName()) ?>
                                </span>
                                <span class="far fa-trash-alt"></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php if (empty($jobList)): ?>
            <div class="row">
                <div class="col-md-12" style="margin-top: 1em">
                    <h4>No Results</h4>
                    <p>
                        <?= sprintf(
                            $this->translate("Unfortunately, there aren't any %s at the moment."),
                            strtolower($this->escapeHtml($this->localiseText($jobCategory->getPluralName()))),
                        ) ?>
                    </p>
                </div>
            </div>
        <?php else: ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="card-grid">
                        <?php foreach ($jobList as $index => $job): ?>
                            <?php
                            $company = $job->getPackage()->getCompany();

                            $jobUrl = $this->url('company/companyItem/joblist/job_item', [
                                'companySlugName' => $company->getSlugName(),
                                'jobSlugName' => $job->getSlugName(),
                                'category' => $this->localiseText($jobCategory->getSlug()),
                            ]);
                            ?>
                            <a href="<?= $jobUrl ?>" class="card job-card" data-index="<?= $index ?>"
                               data-posted="<?= $job->getTimestamp()->format(DateTime::ATOM) ?>">
                                <div class="card-img">
                                    <img
                                        src="<?= $this->fileUrl($company->getLogo()) ?>"
                                        alt="<?= $this->escapeHtmlAttr($company->getName()) ?>"/>
                                </div>
                                <h2 class="card-title">
                                    <?= $this->escapeHtml($this->localiseText($job->getName())) ?>
                                </h2>
                                <p class="card-subtitle text-muted"><?= $this->escapeHtml($company->getName()) ?></p>
                                <?php if (null !== $this->localiseText($job->getLocation())): ?>
                                    <p class="job-location">
                                        <?= $this->escapeHtml($this->localiseText($job->getLocation())) ?>
                                    </p>
                                <?php endif; ?>
                                <div>
                                    <?php foreach ($job->getLabels() as $label): ?>
                                        <span class="label label-default job-label"
                                              data-label="<?= $escaper->escapeHtmlAttr($this->localiseText($label->getAbbreviation())) ?>"
                                              data-toggle="tooltip"
                                              title="<?= $escaper->escapeHtmlAttr($this->localiseText($label->getName())) ?>">
                                            <?= $this->escapeHtml($this->localiseText($label->getAbbreviation())) ?>
                                        </span>
                                    <?php endforeach; ?>
                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-link"><?= $this->translate('View') ?></button>
                                </div>
                            </a>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php
        $alternatives = [];
        foreach ($this->jobCategories() as $c) {
            // Don't include current category in list of alternative job categories
            if ($jobCategory->getId() === $c->getId()) {
                continue;
            }

            $alternatives[] = vsprintf('<a href="%s">%s</a>', [
                $this->url('company/jobList', ['category' => $c->getSlug()]),
                strtolower($c->getPluralName())
            ]);
        }

        $alternatives = join(', ', $alternatives);
        ?>
        <?php if (!empty($alternatives)): ?>
            <div class="row">
                <div class="col-md-4" style="margin-top: 2em">
                    <hr/>
                </div>
                <div class="col-md-12">
                    <p class="text-muted">
                        <?= sprintf($this->translate("Still haven't found what you're looking for? Take a look at %s."), $alternatives) ?>
                    </p>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
<script type="text/javascript">
    var CardGrid = function ($grid, searchElements) {
        // Pre-compute card details
        var cards = $('.card', $grid).map(function () {
            var $card = $(this);

            return {
                target: $card,
                text: $(searchElements, $card).text().toLowerCase(),
                labels: $('.job-label', $card).map(function () {
                    return $(this).data('label');
                }).get()
            };
        }).get();

        /**
         * Toggles the card visibility depending on the filter matches
         */
        var updateCardVisibility = function () {
            cards.forEach(function (card) {
                // Checks if the card matches all registered filters
                var isFullMatch = Object.values(card.isMatchOn).every(function (isMatch) {
                    return (isMatch === true);
                });

                $(card.target).toggle(isFullMatch);
            });
        };

        var sortCards = function (sortFn) {
            var sortedCards = $grid.children('.card').sort(sortFn);

            // jQuery handles moving DOM elements
            $grid.append(sortedCards);
        };

        /**
         * Registers a filter
         *
         * @param filterName   Filter's name
         * @param defaultValue If the card matches the filter by default
         */
        var registerFilter = function (filterName, defaultValue) {
            cards.forEach(function (card) {
                if (!card.hasOwnProperty('isMatchOn')) {
                    card.isMatchOn = {};
                }

                card.isMatchOn[filterName] = defaultValue;
            });
        };

        registerFilter('label', true);
        registerFilter('search', true);

        return {
            filterByLabel: function (label) {
                cards.forEach(function (card) {
                    card.isMatchOn['label'] = (card.labels.indexOf(label) > -1);
                });

                updateCardVisibility();
            },
            clearLabelFilter: function () {
                cards.forEach(function (card) {
                    card.isMatchOn['label'] = true;
                });

                updateCardVisibility();
            },
            filterByText: function (query) {
                cards.forEach(function (card) {
                    card.isMatchOn['search'] = (card.text.indexOf(query.toLowerCase()) > -1);
                });

                updateCardVisibility();
            },
            sortByDateDesc: function () {
                sortCards(function (a, b) {
                    return (new Date(a.dataset.posted) > new Date(b.dataset.posted)) ? -1 : 1;
                });
            },
            sortByDefault: function () {
                sortCards(function (a, b) {
                    return (parseInt(a.dataset.index) > parseInt(b.dataset.index)) ? 1 : -1;
                });
            }
        }
    };

    cardGrid = new CardGrid($('.card-grid'), '.card-title, .card-subtitle, .job-location');

    $("#job-search").keyup(function () {
        var query = $(this).val().trim();

        cardGrid.filterByText(query);
    });

    $("#job-label").change(function () {
        var label = $(this).val();

        if (label === "*") {
            cardGrid.clearLabelFilter();
        } else {
            cardGrid.filterByLabel(label);
        }
    });

    $("#job-sort").change(function () {
        switch ($(this).val()) {
            case 'posted':
                cardGrid.sortByDateDesc();
                break;
            default:
                cardGrid.sortByDefault();
        }
    });

    $('[data-toggle="tooltip"]').tooltip({
        viewport: {"selector": ".card-grid"}
    });
</script>
