<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

?>
<section class="">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li class="active">
                <?= $this->translate('Jobs') ?>
            </li>
        </ol>
    </div>
</section>


<div class="container">




    <div class="job-list">


    <h1><?= $this->translate('Jobs') ?></h1>

    <fieldset>
        <div class="form-group pull-right">
            <label for="filter-all"><?= $this->translate('Search') ?></label>
            <input type="text" class="form-control" id="filter-all" placeholder="<?= $this->translate('Filter results') ?>">
        </div>
        <div class="form-group pull-right">
            <label><?= $this->translate('Sort') ?></label>
            <div>
                <a><?= $this->translate('Name') ?> <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span> </a>
                &#124;
                <a><?= $this->translate('Jobs') ?></a>
            </div>
        </div>
    </fieldset>

    <?php


    foreach ($jobList as $job) {
        if ($job->isActive() && $job->getLanguage() === $locale){
    ?>
        <div class="job-list-item list-item" id="<?= $escaper->escapeHtmlAttr($job->getName()); ?>">
        <h2 class="job-name"><a href="<?= $job->getWebsite(); ?>"><?= $job->getName(); ?></a></h2>
        <div class="job-company-name"><a href="/company/<?= $job->getPackage()->getCompany()->getSlugName();?>"><?= $job->getPackage()->getCompany()->getName(); ?></a></div>
        <div class="job-phone"><a href="tel:<?= rawurlencode($job->getPhone()); ?>"><?= $job->getPhone(); ?></a></div>
        <div class="job-website"><a href="<?= rawurlencode($job->getWebsite()); ?>">Visit website</a></div>
        <div class="job-email"><a href="mailto:<?= rawurlencode($job->getEmail()); ?>"><?= $job->getEmail(); ?></a></div>
        <div class="job-description"><?= $job->getDescription(); ?></div>

        </div>
    <?php
    }}

    ?>

    <script type="text/javascript">
        /* FILTERING */

        function filter_all(term) {
            $(".company-list-item").each(function() {
                if ($(this).text().toLowerCase().indexOf(term.toLowerCase())==-1) {
                    $(this).css({display: "none"});
                } else {
                    $(this).css({display: "block"});
                }
            });
        }

        $("#filter-all").keyup(function() {
            filter_all($(this).val());
        });


        /* SORTING */

        function sort_name(order) {
            var companies = $(".job-list-item");
            companies.sort(function(a,b) {

                if (a.getElementsByClassName("job-name")[0].getElementsByTagName("a")[0].innerHTML > b.getElementsByClassName("company-name")[0].getElementsByTagName("a")[0].innerHTML) {
                    return order;
                } else {
                    return -1 * order;
                }

            });

            companies.detach().appendTo($(".job-list"));
        }

        $("#sort-column, #sort-order").change(function() {
            if ($("#sort-column").val()=="job-name") {
                sort_name($("#sort-order").val());
            }
        });
    </script>
    </div>

</div>
