<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$this->headTitle($this->translate('Companies'));

?>
<div class="container">
    <h1><?= $this->translate('Companies') ?></h1>

    <div class="company-grid row">
        <?php

        foreach ($companyList as $company) {
            echo $this->partial('partial/company/company/grid/company.phtml',
                ['company' => $company, 'locale' => $locale]);
        }

        ?>

    </div>
</div>

