<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$this->headTitle($this->translate('Companies'));

?>
<div class="container">
    <h1><?= $this->translate('Companies') ?></h1>

    <div class="row">
        <div class="col-md-3 hidden-sm">
            <div class="list-group">
                <?php
                foreach ($companyList as $company) {
                    ?>
                    <a href="<?= $this->url('company/companyItem', // Route url
                        ['slugCompanyName' => $company->getSlugName()], // Url parameters
                        [], // routeOptions
                        true); // Reuse matched parameters ?>" class="list-group-item"><?= $company->getName() ?></a>
                <?php
                }
                ?>
            </div>
        </div>
        <div class="col-md-9">
            <div class="company-grid row">
                <?php
                // Randomize the order of companies
                shuffle($companyList);
                foreach ($companyList as $company) {
                    echo $this->partial('partial/company/company/grid/company.phtml',
                        ['company' => $company, 'locale' => $locale]);
                }
                ?>
            </div>
        </div>
    </div>
</div>

