<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$this->headTitle($company->getName());
$this->headTitle($this->translate('Companies'));

?>
<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li class="active">
                <?= $company->getName(); ?>
            </li>
        </ol>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="company-list">
            <?= $this->partial('partial/company/company/list/company.phtml',
                ['company' => $company, 'locale' => $locale]) ?>
        </div>
    </div>
</section>
