<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Company\Model\Company as CompanyModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyModel $company
 */

$escaper = new Laminas\Escaper\Escaper('utf-8');

$this->headTitle($company->getName());
$this->headTitle($this->translate('Companies'));
?>
<nav class="navbar-breadcrumb" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <?= $this->escapeHtml($company->getName()) ?>
            </li>
        </ol>
    </div>
</nav>
<section class="section">
    <div class="container">
        <div class="company-list">
            <?= $this->partial(
                'partial/company/company/list/company.phtml',
                [
                    'company' => $company,
                ]
            ) ?>
        </div>
    </div>
</section>
