<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Company\Model\{
    Company as CompanyModel,
    CompanyFeaturedPackage as CompanyFeaturedPackageModel,
};
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyModel $company
 * @var CompanyFeaturedPackageModel $featuredPackage
 */

$escaper = new Laminas\Escaper\Escaper('utf-8');

$companyURL = $this->url('company/companyItem', // Route url
    [
        'companySlugName' => $company->getSlugName(),
    ], // Url parameters
    [], // routeOptions
    true // Reuse matched parameters
);
?>
<nav class="navbar-breadcrumb" aria-label="breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li class="breadcrumb-item active">
                <?= $this->translate('Featured company') ?>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <?= $this->escapeHtml($company->getName()) ?>
            </li>
        </ol>
    </div>
</nav>
<section class="section">
    <div class="container">
        <h1>
            <a href="<?= $companyURL ?>"><?= $this->escapeHtml($company->getName()) ?></a>
            <small><?= $this->translate('in the spotlight') ?></small>
        </h1>
        <?= $this->partial('./companyStory.phtml', [
            'company' => $company,
            'featuredPackage' => $featuredPackage,
        ]); ?>
    </div>
</section>
