<?php
$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$companyURL = $this->url('company/companyItem', // Route url
    ['slugCompanyName' => $company->getSlugName()], // Url parameters
    [], // routeOptions
    true); // Reuse matched parameters
?>
<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li class="active">
                <?= $this->translate('Featured company') ?>
            </li>
            <li class="active">
                <?= $this->company->getName() ?>
            </li>
        </ol>
    </div>
</section>
<section class="section">
    <div class="container">
        <h1>
            <a href="<?= $companyURL ?>"><?= $this->company->getName() ?></a>
            <small><?= $this->translate('in the spotlight') ?></small>
        </h1>
        <?=
        $this->partial('./companyStory.phtml', [
            'company' => $company,
            'featuredPackage' => $featuredPackage,
            'translator' => $this->translator,
        ]);
        ?>
    </div>
</section>
