<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Date and time') ?></h2>
        <p><?= $this->translate('Enter the start and end date and time of this activity. Optionally, when allowing people to subscribe to this activity you should also set a subscription deadline.') ?></p>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <?php
                $beginTime = $form->get('beginTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'begin-time');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($beginTime) ?>">
                    <label for="<?= $beginTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('Start date and time') ?>
                    </label>
                    <?= $this->formInput($beginTime) ?>
                    <?= $this->formElementErrors($beginTime) ?>
                </div>
            </div>
            <div class="col-md-6">
                <?php
                $endTime = $form->get('endTime')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'end-time');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($endTime) ?>">
                    <label for="<?= $endTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('End date and time') ?>
                    </label>
                    <?= $this->formInput($endTime) ?>
                    <?= $this->formElementErrors($endTime) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?php
                $subscriptionDeadline = $form->get('subscriptionDeadline')
                    ->setAttribute('disabled', 'disabled')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'subscription-deadline');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($subscriptionDeadline) ?>">
                    <label for="<?= $subscriptionDeadline->getAttribute('id') ?>" class="control-label">
                        <?= $this->translate('Subscription deadline') ?>
                    </label>
                    <?= $this->formInput($subscriptionDeadline) ?>
                    <?= $this->formElementErrors($subscriptionDeadline) ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
        <p><?= $this->translate('What is this activity about? Fill in the blanks below, please note that at least one language must be used.') ?></p>
    </div>
    <div class="col-md-6">
        <?php
        $dutchElement = $form->get('language_dutch')
            ->setAttribute('onchange', 'Activity.updateForm()')
            ->setAttribute('id', 'dutch-check')
            ->setAttribute('class', 'language-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($dutchElement) ?>">
            <label for="<?= $dutchElement->getAttribute('id') ?>" class="control-label" title="<?= $this->translate('Enable Dutch translation') ?>">
                <?php $dutchElement->setChecked(isset($languages) ? $languages['nl'] : false); ?>
                <?= $this->formCheckbox($dutchElement) ?>
                <span class="flag-icon flag-icon-nl"></span>
                <?= $this->translate('Dutch') ?>
            </label>
            <?= $this->formElementErrors($dutchElement) ?>
        </div>
        <hr>
        <?php
        $name = $form->get('name')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'name-nl');
        $nameValue = $name->getValue();
        $name->setValue(is_null($nameValue) ? '' : (is_string($nameValue) ? '' : $nameValue->getValueNL()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($name) ?>">
            <label for="<?= $name->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Name') ?>
            </label>
            <?= $this->formInput($name) ?>
            <?= $this->formElementErrors($name) ?>
        </div>
        <?php
        $location = $form->get('location')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'location-nl');
        $locationValue = $location->getValue();
        $location->setValue(is_null($locationValue) ? '' : (is_string($locationValue) ? '' : $locationValue->getValueNL()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($location) ?>">
            <label for="<?= $location->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Location') ?>
            </label>
            <?= $this->formInput($location) ?>
            <?= $this->formElementErrors($location) ?>
        </div>
        <?php
        $costs = $form->get('costs')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'cost-nl');
        $costsValue = $costs->getValue();
        $costs->setValue(is_null($costsValue) ? '' : (is_string($costsValue) ? '' : $costsValue->getValueNL()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($costs) ?>">
            <label for="<?= $costs->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Costs') ?>
            </label>
            <?= $this->formInput($costs) ?>
            <?= $this->formElementErrors($costs) ?>
        </div>
        <?php
        $description = $form->get('description')
            ->setAttribute('class', 'form-control form-control-dutch markdown-editor')
            ->setAttribute('style', 'width:100%; height:10em; resize:none')
            ->setAttribute('data-provide', 'markdown')
            ->setAttribute('id', 'description-nl');
        $descriptionValue = $description->getValue();
        $description->setValue(is_null($descriptionValue) ? '' : (is_string($descriptionValue) ? '' : $descriptionValue->getValueNL()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($description) ?>">
            <label for="<?= $description->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Description') ?>
            </label>
            <?= $this->formRow($description) ?>
            <?= $this->formElementErrors($description) ?>
        </div>
    </div>
    <div class="col-md-6">
        <?php
        $englishElement = $form->get('language_english')
            ->setAttribute('onchange', 'Activity.updateForm()')
            ->setAttribute('id', 'english-check')
            ->setAttribute('class', 'language-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($englishElement) ?>">
            <label for="<?= $englishElement->getAttribute('id') ?>" class="control-label" title="<?= $this->translate('Enable English translation') ?>">
                <?php $englishElement->setChecked(isset($languages) ? $languages['en'] : false); ?>
                <?= $this->formCheckbox($englishElement) ?>
                <span class="flag-icon flag-icon-en"></span>
                <?= $this->translate('English') ?>
            </label>
            <?= $this->formElementErrors($englishElement) ?>
        </div>
        <hr>
        <?php
        $nameEn = $form->get('nameEn')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'name-en');
        $nameValue = $nameEn->getValue();
        $nameEn->setValue(is_null($nameValue) ? '' : (is_string($nameValue) ? '' : $nameValue->getValueEN()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($nameEn) ?>">
            <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Name') ?>
            </label>
            <?= $this->formInput($nameEn) ?>
            <?= $this->formElementErrors($nameEn) ?>
        </div>
        <?php
        $locationEn = $form->get('locationEn')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'location-en');
        $locationValue = $locationEn->getValue();
        $locationEn->setValue(is_null($locationValue) ? '' : (is_string($locationValue) ? '' : $locationValue->getValueEN()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($locationEn) ?>">
            <label for="<?= $locationEn->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Location') ?>
            </label>
            <?= $this->formInput($locationEn) ?>
            <?= $this->formElementErrors($locationEn) ?>
        </div>
        <?php
        $costsEn = $form->get('costs')
            ->setAttribute('disabled', 'disabled')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'cost-en');
        $costsValue = $costsEn->getValue();
        $costsEn->setValue(is_null($costsValue) ? '' : (is_string($costsValue) ? '' : $costsValue->getValueEN()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($costsEn) ?>">
            <label for="<?= $costsEn->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Costs') ?>
            </label>
            <?= $this->formInput($costsEn) ?>
            <?= $this->formElementErrors($costsEn) ?>
        </div>
        <?php
        $descriptionEn = $form->get('description')
            ->setAttribute('class', 'form-control form-control-english markdown-editor')
            ->setAttribute('style', 'width:100%; height:10em; resize:none')
            ->setAttribute('data-provide', 'markdown')
            ->setAttribute('id', 'description-en');
        $descriptionValue = $descriptionEn->getValue();
        $descriptionEn->setValue(is_null($descriptionValue) ? '' : (is_string($descriptionValue) ? '' : $descriptionValue->getValueEN()));
        ?>
        <div class="form-group <?= $this->bootstrapElementError($descriptionEn) ?>">
            <label for="<?= $descriptionEn->getAttribute('id') ?>" class="control-label">
                <?= $this->translate('Description') ?>
            </label>
            <?= $this->formRow($descriptionEn) ?>
            <?= $this->formElementErrors($descriptionEn) ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Options') ?></h2>
        <p><?= $this->translate('Choose which options are applicable to this activity.') ?></p>
    </div>
    <div class="col-md-6">
        <?php
        $canSignUp = $form->get('canSignUp')
            ->setAttribute('onchange', 'Activity.toggleSubscription()');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($canSignUp) ?>">
            <label>
                <?= $this->formCheckbox($canSignUp) ?>
                <?= $this->translate('Enable subscriptions') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if people need to subscribe to this activity.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($canSignUp) ?>
            </label>
        </div>
        <?php
        $onlyGEWIS = $form->get('onlyGEWIS')
            ->setAttribute('onchange', 'Activity.toggleExternal()');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($onlyGEWIS) ?>">
            <label>
                <?= $this->formCheckbox($onlyGEWIS) ?>
                <?= $this->translate('Allow external participants') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this to allow people without a GEWIS account to subscribe.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($onlyGEWIS) ?>
            </label>
        </div>
        <?php
        $displaySubscribedNumber = $form->get('displaySubscribedNumber');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($displaySubscribedNumber) ?>">
            <label>
                <?= $this->formCheckbox($displaySubscribedNumber) ?>
                <?= $this->translate('Display number of subscribed members') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this to display the number of subscribed GEWIS members to external visitors.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($displaySubscribedNumber) ?>
            </label>
        </div>
        <?php
        $isFood = $form->get('isFood');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($isFood) ?>">
            <label>
                <?= $this->formCheckbox($isFood) ?>
                <?= $this->translate('This is a food subscription list') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if the activity is a food subscription list, it then won\'t be displayed on the information screens.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($isFood) ?>
            </label>
        </div>
        <?php
        $isMyFuture = $form->get('isMyFuture');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($isMyFuture) ?>">
            <label>
                <?= $this->formCheckbox($isMyFuture) ?>
                <?= $this->translate('This is a career related activity') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('If this is checked the My Future logo will be displayed on the activity page and the activity will be included on the career activities page.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($isMyFuture) ?>
            </label>
        </div>
        <?php
        $requireGEFLITST = $form->get('requireGEFLITST');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($requireGEFLITST) ?>">
            <label>
                <?= $this->formCheckbox($requireGEFLITST) ?>
                <?= $this->translate('This activity needs a GEFLITST member to take photos') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('When this is checked, GEFLITST will be notified that this activity needs a photographer.') ?>" class="fas fa-info-circle" aria-hidden="true"></span>
                <?= $this->formElementErrors($requireGEFLITST) ?>
            </label>
        </div>
    </div>
</div>
