<style>
    .spacing-top--lg { margin-top: 4rem; }
    .spacing-top--md { margin-top: 2.5rem; }
    .spacing-top--sm { margin-top: 1rem; }

    label { cursor: pointer;}
    label input[type=checkbox] { margin-right: 1.5rem; }

    .label-required:after { content: "*"; color: #d40026; }
</style>

<div class="row spacing-top--lg">
    <div class="col-md-12">
        <h2><?= $this->translate('Date and time') ?></h2>
        <p><?= $this->translate('Enter the begin and end date of the activity. Optionally, enter the ultimate date a participant can subscribe.') ?></p>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6 spacing-top--sm">
                <?php
                $beginTime = $form->get('beginTime');
                $beginTime->setAttribute('class', 'form-control')->setAttribute('id', 'begin-time');
                ?>
                <div class="form-group <?= count($beginTime->getMessages()) > 0 ? 'has-error' : '' ?>">
                    <label for="<?= $beginTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('Begin date') ?>
                    </label>
                    <?= $this->formInput($beginTime) ?>
                    <?= $this->formElementErrors($beginTime) ?>
                </div>
            </div>
            <div class="col-md-6 spacing-top--sm">
                <?php
                $endTime = $form->get('endTime');
                $endTime->setAttribute('class', 'form-control')->setAttribute('id', 'end-time');
                ?>
                <div class="form-group <?= count($endTime->getMessages()) > 0 ? 'has-error' : '' ?>">
                    <label for="<?= $endTime->getAttribute('id') ?>" class="control-label label-required">
                        <?= $this->translate('End date') ?>
                    </label>
                    <?= $this->formInput($endTime) ?>
                    <?= $this->formElementErrors($endTime) ?>
                </div>
            </div>
        </div>
        <div class="row spacing-top--md">
            <?php
            $subscriptionDeadline = $form->get('subscriptionDeadline');
            $subscriptionDeadline->setAttribute('class', 'form-control')->setAttribute('id', 'deadline-date');
            ?>
            <div class="col-md-6">
                <div class="form-group <?= count($subscriptionDeadline->getMessages()) > 0 ? 'has-error' : '' ?>">
                    <label for="<?= $subscriptionDeadline->getAttribute('id') ?>" class="control-label">
                        <?= $this->translate('Subscription deadline') ?>
                    </label>
                    <?= $this->formInput($subscriptionDeadline) ?>
                    <?= $this->formElementErrors($subscriptionDeadline) ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row spacing-top--lg">
    <div class="col-md-12">
        <h2><?= $this->translate('Translations') ?></h2>
        <p><?= $this->translate('Choose which translations you want to fill-in. At least one translation needs to be filled in.') ?></p>
    </div>
    <div class="col-md-6 spacing-top--md">
        <?php
        $dutchElement = $form->get('language_dutch');
        $dutchElement->setAttribute('onchange', 'Activity.updateForm()');
        $dutchElement->setAttribute('id', 'dutch-check');
        $dutchElement->setAttribute('class', '');
        ?>
        <div class="form-group <?= count($dutchElement->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $dutchElement->getAttribute('id') ?>" class="control-label" title="<?= $this->translate('Enable Dutch translation') ?>">
                <?php $dutchElement->setChecked(isset($languages) ? $languages['nl'] : false); ?>
                <?= $this->formCheckbox($dutchElement) ?>
                <i class="flag-icon flag-icon-nl" style="background-image: url('/img/nl.svg');"></i>
                <?= $this->translate('Dutch') ?>
            </label>
            <?= $this->formElementErrors($dutchElement) ?>
        </div>

        <hr />

        <?php
        $name = $form->get('name');
        $name->setAttribute('disabled', 'disabled');
        $name->setAttribute('class', 'form-control form-control-dutch');
        $name->setAttribute('id', 'name-nl');
        ?>
        <div class="form-group <?= count($name->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $name->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Name') ?>
            </label>
            <?= $this->formInput($name) ?>
            <?= $this->formElementErrors($name) ?>
        </div>

        <?php
        $location = $form->get('location');
        $location->setAttribute('disabled', 'disabled');
        $location->setAttribute('class', 'form-control form-control-dutch');
        $location->setAttribute('id', 'location-nl');
        ?>
        <div class="form-group<?= count($location->getMessages()) > 0 ? ' has-error' : '' ?>">
            <label for="<?= $location->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Location') ?>
            </label>
            <?= $this->formInput($location) ?>
            <?= $this->formElementErrors($location) ?>
        </div>


        <?php
        $costs = $form->get('costs');
        $costs->setAttribute('disabled', 'disabled');
        $costs->setAttribute('class', 'form-control form-control-dutch');
        $costs->setAttribute('id', 'cost-nl');
        ?>
        <div class="form-group <?= count($costs->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $costs->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Costs') ?>
            </label>
            <?= $this->formInput($costs) ?>
            <?= $this->formElementErrors($costs) ?>
        </div>

        <?php
        $description = $form->get('description');
        $description->setAttribute('class', 'form-control form-control-dutch markdown-editor');
        $description->setAttribute('style', 'width:100%; height:10em; resize:none');
        $description->setAttribute('data-provide', 'markdown');
        $description->setAttribute('id', 'description-nl');
        ?>
        <div class="form-group <?= count($description->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $description->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Description') ?>
            </label>
            <?= $this->formRow($description) ?>
            <?= $this->formElementErrors($description) ?>
        </div>
    </div>

    <div class="col-md-6 spacing-top--md">
        <?php
        $englishElement = $form->get('language_english');
        $englishElement->setAttribute('onchange', 'Activity.updateForm()');
        $englishElement->setAttribute('id', 'english-check');
        $englishElement->setAttribute('class', '');
        ?>
        <div class="form-group <?= count($englishElement->getMessages()) > 0 ? 'has-error' : '' ?>">

            <label for="<?= $englishElement->getAttribute('id') ?>" class="control-label" title="<?= $this->translate('Enable Dutch translation') ?>">
                <?php $englishElement->setChecked(isset($languages) ? $languages['en'] : false); ?>
                <?= $this->formCheckbox($englishElement) ?>
                <i class="flag-icon flag-icon-en" style="background-image: url('/img/en.svg');"></i>
                <?= $this->translate('English') ?>
            </label>
            <?= $this->formElementErrors($englishElement) ?>
        </div>

        <hr />

        <?php
        $nameEn = $form->get('nameEn');
        $nameEn->setAttribute('disabled', 'disabled');
        $nameEn->setAttribute('class', 'form-control form-control-english');
        $nameEn->setAttribute('id', 'name-en');
        ?>
        <div class="form-group <?= count($nameEn->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Name') ?>
            </label>
            <?= $this->formInput($nameEn) ?>
            <?= $this->formElementErrors($nameEn) ?>
        </div>

        <?php
        $locationEn = $form->get('locationEn');
        $locationEn->setAttribute('disabled', 'disabled');
        $locationEn->setAttribute('class', 'form-control form-control-english');
        $locationEn->setAttribute('id', 'location-en');
        ?>
        <div class="form-group <?= count($locationEn->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $locationEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Location') ?>
            </label>
            <?= $this->formInput($locationEn) ?>
            <?= $this->formElementErrors($locationEn) ?>
        </div>

        <?php
        $costsEn = $form->get('costsEn');
        $costsEn->setAttribute('disabled', 'disabled');
        $costsEn->setAttribute('class', 'form-control form-control-english');
        $costsEn->setAttribute('id', 'cost-en');
        ?>
        <div class="form-group <?= count($costsEn->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $costsEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Costs') ?>
            </label>
            <?= $this->formInput($costsEn) ?>
            <?= $this->formElementErrors($costsEn) ?>
        </div>

        <?php
        $descriptionEn = $form->get('descriptionEn');
        $descriptionEn->setAttribute('class', 'form-control form-control-english markdown-editor');
        $descriptionEn->setAttribute('style', 'width:100%; height:10em; resize:none');
        $descriptionEn->setAttribute('data-provide', 'markdown');
        $descriptionEn->setAttribute('id', 'description-en');
        ?>
        <div class="form-group <?= count($descriptionEn->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $descriptionEn->getAttribute('id') ?>" class="control-label label-required">
                <?= $this->translate('Description') ?>
            </label>
            <?= $this->formRow($descriptionEn) ?>
            <?= $this->formElementErrors($descriptionEn) ?>
        </div>
    </div>
</div>

<div class="row spacing-top--lg">
    <div class="col-md-12">
        <h2><?= $this->translate('Options') ?></h2>
        <p>Choose which options are applicable to the activity.</p>

        <?php
        $canSignUp = $form->get('canSignUp');
        $canSignUp->setAttribute('id', 'can-sign-up');
        ?>
        <div class="form-group <?= count($canSignUp->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $canSignUp->getAttribute('id') ?>">
                <?= $this->formCheckbox($canSignUp) ?>
                <?= $this->translate('Enable subscriptions') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if people need to subscribe to this activity.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?= $this->formElementErrors($canSignUp) ?>
            </label>
        </div>

        <?php
            $onlyGEWIS = $form->get('onlyGEWIS');
            $onlyGEWIS->setAttribute('onchange', 'Activity.toggleExternal()')->setAttribute('id', 'only-gewis');
        ?>
        <div class="form-group <?= count($onlyGEWIS->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $onlyGEWIS->getAttribute('id') ?>">
                <?= $this->formCheckbox($onlyGEWIS) ?>
                <?= $this->translate('Allow external participants') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this to allow people without a GEWIS account to subscribe.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?= $this->formElementErrors($onlyGEWIS) ?>
            </label>
        </div>

        <?php
            $displaySubscribedNumber = $form->get('displaySubscribedNumber');
            $displaySubscribedNumber->setAttribute('id', 'display-subscriber-number');
        ?>
        <div class="form-group <?= count($displaySubscribedNumber->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $displaySubscribedNumber->getAttribute('id') ?>">
                <?= $this->formCheckbox($displaySubscribedNumber) ?>
                <?= $this->translate('Display number of subscribed members') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this to display the number of subscribed GEWIS members to external visitors.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?= $this->formElementErrors($displaySubscribedNumber) ?>
            </label>
        </div>

        <?php
        $isFood = $form->get('isFood');
        $isFood->setAttribute('id', 'is-food');
        ?>
        <div class="form-group <?= count($isFood->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $isFood->getAttribute('id') ?>">
                <?= $this->formCheckbox($isFood) ?>
                <?= $this->translate('This is a food subscription list') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Select this if the activity is a food subscription list, it then won\'t be displayed on the information screens.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?= $this->formElementErrors($isFood) ?>
            </label>
        </div>

        <?php
        $isMyFuture = $form->get('isMyFuture');
        $isMyFuture->setAttribute('id', 'is-my-future');
        ?>
        <div class="form-group <?= count($isMyFuture->getMessages()) > 0 ? 'has-error' : '' ?>">
            <label for="<?= $isMyFuture->getAttribute('id') ?>">
                <?= $this->formCheckbox($isMyFuture) ?>
                <?= $this->translate('This is a career related activity') ?>
                <span data-toggle="tooltip" data-placement="right" title="<?= $this->translate('If this is checked the My Future logo will be displayed on the activity page and the activity will be included on the career activities page.') ?>" class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <?= $this->formElementErrors($isMyFuture) ?>
            </label>
        </div>
    </div>
</div>
