<div class="field" id="additionalField<?= $this->index ?>">
    <div class="row">
        <?php
        $element = $this->fs->get('type')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'type-field')
            ->setAttribute('onchange', 'Activity.updateFieldset(' . $this->index. ')');
        ?>
        <div class="col-md-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $this->fs->get('name')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'field-name-nl');
        ?>
        <div class="col-md-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                    <?= $element->getLabel() ?>
                    <span class="flag-icon flag-icon-nl"></span>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $this->fs->get('nameEn')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'field-name-en');
        ?>
        <div class="col-md-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                    <?= $element->getLabel() ?>
                    <span class="flag-icon flag-icon-en"></span>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row field-dependant type-2" style="display:none;">
        <?php
        $element = $this->fs->get('min. value')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'min-value-field');
        ?>
        <div class="col-md-4 col-md-offset-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label label-required">
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $this->fs->get('max. value')
            ->setAttribute('class', 'form-control')
            ->setAttribute('id', 'max-value-field');
        ?>
        <div class="col-md-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label label-required">
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-8 col-md-offset-4">
            <p><?= $this->translate('Please note that numbers are not dependant on the selected language(s).') ?></p>
        </div>
    </div>
    <div class="row field-dependant type-3" style="display:none;">
        <?php
        $element = $this->fs->get('options')
            ->setAttribute('class', 'form-control form-control-dutch')
            ->setAttribute('id', 'field-options-nl');
        ?>
        <div class="col-md-4 col-md-offset-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $this->fs->get('optionsEn')
            ->setAttribute('class', 'form-control form-control-english')
            ->setAttribute('id', 'field-options-en');
        ?>
        <div class="col-md-4">
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
</div>
