<div class="option" id="additionalOption<?= $this->index ?>">
    <div class="form-group form-inline">
        <h3><?= $this->translate('Option') ?></h3>
        <div class="form-group form-inline">
            <?php
            $beginTime = $this->fs->get('beginTime');
            $beginTime->setAttribute('class', 'form-control')->setAttribute('id', 'begin-time' . $this->index);
            $endTime = $this->fs->get('endTime');
            $endTime->setAttribute('class', 'form-control')->setAttribute('id', 'end-time' . $this->index);
            ?>
            <div class="form-group<?= count($beginTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $beginTime->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('From') ?>
                </label>
                <div class="col-sm-10">
                    <?= $this->formInput($beginTime) ?>
                    <?= $this->formElementErrors($beginTime) ?>
                </div>
            </div>

            <div class="form-group<?= count($endTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $endTime->getAttribute('id') ?>" class="control-label col-sm-2">
                    <?= $this->translate('Until') ?>
                </label>
                <div class="col-sm-10">
                    <?= $this->formInput($endTime) ?>
                    <?= $this->formElementErrors($endTime) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group form-inline">
        <?php
        $element = $this->fs->get('type');
        $element->setAttribute('class', 'form-control');
        $element->setAttribute('id', 'type-field');
        $element->setAttribute('placeholder', $element->getLabel());
        ?>
        <div class="form-group">
            <label for="<?= $element->getAttribute('id') ?>" class="control-label col-sm-4"><?= $element->getLabel()
                ?></label>
            <div class="col-sm-10">
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <hr>
</div>

<script>
    $("#begin-time<?= $this->index ?>").datetimepicker();
    $("#end-time<?= $this->index ?>").datetimepicker();
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>
