<div class="row field" id="additionalField<?= $this->index ?>">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-9 col-md-offset-3">
                <hr>
            </div>
            <div class="col-md-3 col-md-offset-3">
                <?php
                $element = $this->signupListField->get('type')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'type-field')
                    ->setAttribute('onchange', 'Activity.updateField(' . $this->listIndex . ', ' . $this->index . ')');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                    <label for="<?= $element->getAttribute('id') ?>" class="control-label">
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formSelect($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-3">
                <?php
                $name = $this->signupListField->get('name')
                    ->setAttribute('class', 'form-control form-control-dutch')
                    ->setAttribute('id', 'field-name-nl');
                $name->setValue($this->localisedTextElement($name));
                ?>
                <div class="form-group <?= $this->bootstrapElementError($name) ?>">
                    <label for="<?= $name->getAttribute('id') ?>" class="control-label">
                        <?= $name->getLabel() ?>
                        <span class="flag-icon flag-icon-nl"></span>
                    </label>
                    <?= $this->formInput($name) ?>
                    <?= $this->formElementErrors($name) ?>
                </div>
            </div>
            <div class="col-md-3">
                <?php
                $nameEn = $this->signupListField->get('nameEn')
                    ->setAttribute('class', 'form-control form-control-english')
                    ->setAttribute('id', 'field-name-en');
                $nameEn->setValue($this->localisedTextElement($nameEn));
                ?>
                <div class="form-group <?= $this->bootstrapElementError($nameEn) ?>">
                    <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label">
                        <?= $nameEn->getLabel() ?>
                        <span class="flag-icon flag-icon-en"></span>
                    </label>
                    <?= $this->formInput($nameEn) ?>
                    <?= $this->formElementErrors($nameEn) ?>
                </div>
            </div>
        </div>
        <div class="row field-dependant type-2" style="display:none;">
            <div class="col-md-3 col-md-offset-6">
                <?php
                $element = $this->signupListField->get('minimumValue')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'min-value-field');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                    <label for="<?= $element->getAttribute('id') ?>" class="control-label label-required">
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-3">
                <?php
                $element = $this->signupListField->get('maximumValue')
                    ->setAttribute('class', 'form-control')
                    ->setAttribute('id', 'max-value-field');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                    <label for="<?= $element->getAttribute('id') ?>" class="control-label label-required">
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-6 col-md-offset-6">
                <p><?= $this->translate('Please note that numbers are not dependant on the selected language(s).') ?></p>
            </div>
        </div>
        <div class="row field-dependant type-3" style="display:none;">
            <div class="col-md-3 col-md-offset-6">
                <?php
                $options = $this->signupListField->get('options')
                    ->setAttribute('class', 'form-control form-control-dutch')
                    ->setAttribute('id', 'field-options-nl');
                $optionsValue = $options->getValue();

                if (empty($optionsValue)) {
                    $options->setValue('');
                } elseif (is_string($optionsValue)) {
                    $options->setValue($optionsValue);
                } else {
                    $options->setValue(implode(',', array_filter($optionsValue)));
                }
                ?>
                <div class="form-group <?= $this->bootstrapElementError($options) ?>">
                    <label for="<?= $options->getAttribute('id') ?>" class="control-label">
                        <?= $options->getLabel() ?>
                    </label>
                    <?= $this->formInput($options) ?>
                    <?= $this->formElementErrors($options) ?>
                </div>
            </div>
            <div class="col-md-3">
                <?php
                $optionsEn = $this->signupListField->get('optionsEn')
                    ->setAttribute('class', 'form-control form-control-english')
                    ->setAttribute('id', 'field-options-en');
                $optionsValue = $optionsEn->getValue();

                if (empty($optionsValue)) {
                    $optionsEn->setValue('');
                } elseif (is_string($optionsValue)) {
                    $optionsEn->setValue($optionsValue);
                } else {
                    $optionsEn->setValue(implode(',', array_filter($optionsValue)));
                }
                ?>
                <div class="form-group <?= $this->bootstrapElementError($optionsEn) ?>">
                    <label for="<?= $optionsEn->getAttribute('id') ?>" class="control-label">
                        <?= $optionsEn->getLabel() ?>
                    </label>
                    <?= $this->formInput($optionsEn) ?>
                    <?= $this->formElementErrors($optionsEn) ?>
                </div>
            </div>
        </div>
    </div>
</div>
