<?php

declare(strict_types=1);

use Activity\Form\Signup as SignupForm;
use Activity\Model\SignupList as SignupListModel;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var SignupForm $form
 * @var SignupListModel $signupList
 * @var ?bool $update
 */

$showCaptcha = false;
$showName = false;

switch ($form->getType()) {
    case SignupForm::USER:
        $agreementText = $this->translate('By subscribing to this activity, you agree to the terms outlined in the');
        $sensitiveStartText = $this->translate('Your sign-up will be visible to other members and graduates.');
        $submitUrl = $this->url(
            'activity/signup',
            [
                'id' => $signupList->getActivity()->getId(),
                'signupList' => $signupList->getId(),
            ],
        );

        if (isset($update)) {
            $submitText = $this->translate('Update subscription');
        } else {
            $submitText = $this->translate('Confirm subscription');
        }

        break;
    case SignupForm::EXTERNAL_USER:
        $agreementText = $this->translate('By subscribing to this activity, you agree to the terms outlined in the');
        $sensitiveStartText = $this->translate('Your sign-up will be visible to all visitors of the website.');
        $submitUrl = $this->url(
            'activity/externalSignup',
            [
                'id' => $signupList->getActivity()->getId(),
                'signupList' => $signupList->getId(),
            ],
        );
        $submitText = $this->translate('Subscribe as external participant');
        $showCaptcha = true;
        $showName = true;
        break;
    case SignupForm::EXTERNAL_ADMIN:
        $agreementText = $this->translate('By subscribing an external participant to this activity, they must agree to the terms outlined in the');
        $sensitiveStartText = $this->translate('The sign-up of this external participant will be visible to all visitors of the website.');
        $submitUrl = $this->url(
            'activity_admin/adminSignup',
            [
                'id' => $signupList->getActivity()->getId(),
                'signupList' => $signupList->getId(),
            ],
        );
        $submitText = $this->translate('Subscribe an external participant');
        $showName = true;
        break;
}

function formElementRender(
    $element,
    $label,
    $id,
    $sensitive,
    $context,
): string {
    $element->setAttribute('id', $id);
    $elementType = (new ReflectionClass($element))->getShortName();

    if (!in_array($elementType, ['Radio', 'Checkbox'])) {
        $element->setAttribute('class', 'form-control');
    }

    if ($sensitive) {
        // Mark this field as sensitive.
        $label .= '¹';
    }

    $result = '<div class="form-group' . (count($element->getMessages()) > 0 ? ' has-error' : '') . '">';
    $result .= '<label for="' . $element->getAttribute('id') . '" class="control-label label-required">' . $label . '</label>';

    if (in_array($elementType, ['Radio'])) {
        $context->formRadio()->setSeparator('</div><div class="radio">');
        $result .= '<div class="radio">' . $context->formRadio($element) . '</div>';
    } else {
        $result .= $context->formRow($element);
    }

    $result .= '</div>';

    return $result;
}

?>

<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                    <?= sprintf(
                        $this->translate('Subscribe to \'%s\''),
                        $this->escapeHtml($this->localiseText($signupList->getName())),
                    ) ?>
                </h4>
            </div>
            <?php
            $form->setAttribute('action', $submitUrl);
            $form->setAttribute('class', 'form-signup');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
                <div class="modal-body">
                    <?php if ($showCaptcha): ?>
                        <p>
                            <strong>
                                <?= sprintf(
                                    $this->translate('Do you have a GEWIS account? <a href="%s">Log in to subscribe.</a>'),
                                    $this->url(
                                        'user/login',
                                        ['user_type' => 'member'],
                                        ['query' => ['redirect_to' => base64_encode($this->serverUrl(true))]],
                                    ),
                                ) ?>
                            </strong> <?= $this->translate('Or subscribe without a GEWIS membership: ') ?>
                        </p>
                    <?php endif; ?>

                    <?php if ($showName): ?>
                        <?= formElementRender($form->get('fullName'), $this->translate('Full name'), 'fullName', false, $this) ?>
                        <?= formElementRender($form->get('email'), $this->translate('E-mail Address'), 'email', true, $this) ?>
                    <?php endif; ?>

                    <?php if ($showCaptcha): ?>
                        <?= formElementRender($form->get('captcha'), $this->translate('CAPTCHA'), 'captcha', false, $this) ?>
                    <?php endif; ?>

                    <?php foreach ($signupList->getFields() as $field): ?>
                        <?= formElementRender(
                            $form->get(strval($field->getId())),
                            $this->escapeHtml($this->localiseText($field->getName())),
                            $field->getId(),
                            $field->isSensitive(),
                            $this,
                        ) ?>
                    <?php endforeach; ?>

                    <p>
                        <?= $agreementText ?> <a href="https://gewis.nl/data/regulations/activity-policy.pdf" target="_blank">
                            <?= $this->translate('Activity Policy') ?></a> <?= $this->translate('and') ?>
                        <a href="https://gewis.nl/data/regulations/alcohol-policy.pdf" target="_blank">
                            <?= $this->translate('Alcohol Policy') ?></a>.
                    </p>

                    <p class="text-muted">
                        <em>
                            <?= $sensitiveStartText ?> <?= $this->translate('Fields that are marked with an \'¹\' will only be shared with the board and the organiser of the activity.') ?>
                        </em>
                    </p>
                </div>
                <div class="modal-footer">
                    <?php
                    $submit = $form->get('submit');
                    $submit->setAttribute('class', 'btn btn-primary');
                    $submit->setAttribute('value', $submitText);
                    echo $this->formElement($form->get('security'));
                    echo $this->formSubmit($submit);
                    ?>
                    <button type="button" class="btn" data-dismiss="modal">
                        <?= $this->translate('Cancel') ?>
                    </button>
                </div>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
</div>
