<section class="section">
    <div class="container">
        <?php if (!empty($this->exception->getMessage())): ?>
            <h2><?= $this->exception->getMessage() ?></h2>
        <?php else: ?>
            <h2><?= $this->translate('You do not have the required privileges to view this page') ?></h2>
        <?php endif; ?>
        <?php if ($this->identity() === null): ?>
            <p><?= $this->translate('You might be able to view this page by logging in') ?></p>
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1 col-md-7 col-md-offset-2 col-lg-6 col-lg-offset-3">
                    <a href="<?= $this->url('user') ?>">
                        <span class="fas fa-user"></span>
                        <?= $this->translate('Login') ?>
                    </a>
                </div>
            </div>

        <?php endif; ?>
    </div>
</section>
