<?php

declare(strict_types=1);

use Application\Model\Enums\AuthTypes;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AuthTypes $authType
 * @var AuthTypes|null $expectedAuthType
 */
?>
<section class="section">
    <div class="container">
        <h2><?= $this->translate('403 Forbidden') ?></h2>
        <?php if (!isset($expectedAuthType)): ?>
            <?= $this->escapeHtml($exception->getMessage()) ?>
        <?php else: ?>
            <p>
                <?= sprintf(
                    $this->translate('You are currently logged in as <strong>%s</strong>. However, to access this page you need to be logged in as a <strong>%s</strong>.'),
                    $authType->getName($this->plugin('translate')->getTranslator()),
                    $expectedAuthType->getName($this->plugin('translate')->getTranslator()),
                )?>
            </p>
            <a href="<?= $this->url('user/logout') ?>">
                <?= $this->translate('Logout') ?>
            </a>
        <?php endif; ?>
    </div>
</section>
