<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<section class="section">
    <div class="container">
        <h2><?= $this->translate('500 Internal Server Error') ?></h2>
        <?= $this->translate('If this keeps occurring, please contact the ApplicatieBeheerCommissie.') ?>
    </div>
</section>
