<?php
$this->headTitle($this->translate('Login'));
?>
<section class="section">
    <div class="container">
        <?php if (isset($this->login) && $this->login): ?>
            <?= $this->translate('You are logged in.') ?>
        <?php else: ?>
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1 col-md-7 col-md-offset-2 col-lg-6 col-lg-offset-3">
                    <?= $this->partial('partial/login.phtml', ['form' => $form]) ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
