<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\CompanyUserLogin as CompanyUserLoginForm;
use User\Form\UserLogin as UserLoginForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyUserLoginForm|UserLoginForm $form
 * @var string $userType
 */

$this->headTitle($this->translate('Log in'));

$isMember = ('member' === $userType);
?>
<section class="section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-sm-offset-1 col-md-7 col-md-offset-2 col-lg-6 col-lg-offset-3">
                <div class="panel">
                    <div class="panel-navigation">
                        <ul class="nav nav-tabs nav-justified nav-login">
                            <li class="nav-item">
                                <a href="<?= $this->url('user/login', ['user_type' => 'member']) ?>"
                                   class="nav-link<?= $isMember ? ' active' : '' ?>"
                                >
                                    <?= $this->translate('Member') ?>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="<?= $this->url('user/login', ['user_type' => 'company'], true) ?>"
                                   class="nav-link<?= !$isMember ? ' active' : '' ?>"
                                >
                                    <?= $this->translate('Company') ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="panel-heading">
                        <h3><?= $this->translate('Login') ?></h3>
                    </div>
                    <?php if ($isMember): ?>
                        <?= $this->partial('partial/login/member.phtml', ['form' => $form]) ?>
                    <?php else: ?>
                        <?= $this->partial('partial/login/company.phtml', ['form' => $form]) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>
