<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('user/default', array('action' => 'register')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('lidnr');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Membership number'));
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
</div>
<div class="form-group">
<?php
$element = $form->get('email');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('E-mail address'));
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Register'));
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
