<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\{
    CompanyUserReset as CompanyUserResetForm,
    UserReset as UserResetForm,
};

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyUserResetForm|UserResetForm $form
 * @var string $userType
 */

$this->headTitle($this->translate('Reset password'));
?>
<section class="section">
    <div class="container">
        <?php if (isset($reset) && $reset): ?>
            <?= $this->translate('An e-mail has been sent with instructions for resetting your password. If you have not received an e-mail, try again in 20 minutes.') ?>
        <?php else: ?>
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1 col-md-7 col-md-offset-2 col-lg-6 col-lg-offset-3">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3><?= $this->translate('Reset password') ?></h3>
                        </div>
                        <div class="panel-body">
                            <?php if ('member' === $userType): ?>
                                <?= $this->partial('partial/reset/member.phtml', ['form' => $form]) ?>
                            <?php else: ?>
                                <?= $this->partial('partial/reset/company.phtml', ['form' => $form]) ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
