<h1><?= $this->translate('Update Proposals');?> </h1>
<?= $this->partial('activity/activity/list.phtml', [
    'activities' => $updatedActivities,
    'proposals' => $updateProposals,
    'admin' => true,
    'moreLink' => null,
])
?>

<h1><?php echo $this->translate('Unapproved Activities');?> </h1>
<?php
echo $this->partial('activity/activity/list.phtml', [
    'activities' => $unapprovedActivities,
    'admin' => true,
    'moreLink' => $moreUnapprovedActivities ? $this->url('activity_admin_approval/queue_unapproved', ['page' => 1]) : null,
]);
?>

<h1><?php echo $this->translate('Approved Activities')?></h1>
<?php
echo $this->partial('activity/activity/list.phtml', [
    'activities' => $approvedActivities,
    'admin' => true,
    'moreLink' => $moreApprovedActivities ? $this->url('activity_admin_approval/queue_approved', ['page' => 1]) : null,
]);
?>

<h1><?php echo $this->translate('Disapproved Activities');?></h1>
<?php
echo $this->partial('activity/activity/list.phtml', [
    'activities' => $disapprovedActivities,
    'admin' => true,
    'moreLink' => $moreDisapprovedActivities ? $this->url('activity_admin_approval/queue_disapproved', ['page' => 1]) : null,
]);
?>