<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->escapeHtml($activity->getName()->getText($lang)) ?></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
        <p>
            <?=
                sprintf(
                    $this->translate('This is activity <strong>#%d</strong>, it starts on <strong>%s</strong> and ends on <strong>%s</strong>.'),
                        $activity->getId(),
                        $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                        $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT)
                );
            ?>
            <?= $this->translate('More information about this activity is available below.') ?>
        </p>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div class="row">
                    <div class="col-md-6">
                        <strong>
                            <span class="flag-icon flag-icon-nl"></span>
                            <?= $this->translate('Dutch') ?>
                        </strong>
                        <hr>
                    </div>
                    <div class="col-md-6">
                        <strong>
                            <span class="flag-icon flag-icon-en"></span>
                            <?= $this->translate('English') ?>
                        </strong>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Name') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getName()->getValueNL()) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getName()->getValueEN()) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Location') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getLocation()->getValueNL()) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getLocation()->getValueEN()) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Costs') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getCosts()->getValueNL()) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getCosts()->getValueEN()) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Description') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getDescription()->getValueNL()) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($activity->getDescription()->getValueEN()) ?>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <a href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                    <?= $this->translate('View details / subscriptions') ?>
                </a>
            </div>
        </div>
        <hr>
    </div>
</div>
<?php if ($activity->getSignupLists()->count() > 0): ?>
    <div class="row">
        <div class="col-md-12">
            <h2><?= $this->translate('Signup lists') ?></h2>
        </div>
        <div class="col-md-10 col-md-offset-2">
            <div class="row">
                <div class="col-md-6">
                    <strong>
                        <span class="flag-icon flag-icon-nl"></span>
                        <?= $this->translate('Dutch') ?>
                    </strong>
                    <hr>
                </div>
                <div class="col-md-6">
                    <strong>
                        <span class="flag-icon flag-icon-en"></span>
                        <?= $this->translate('English') ?>
                    </strong>
                    <hr>
                </div>
            </div>
        </div>
        <?php foreach ($activity->getSignupLists() as $signupList): ?>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Name') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($signupList->getName()->getValueNL()) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->escapeHtml($signupList->getName()->getValueEN()) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Open date and time') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->dateFormat($signupList->getOpenDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->dateFormat($signupList->getOpenDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Close date and time') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $this->dateFormat($signupList->getCloseDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                    </div>
                    <div class="col-md-5">
                        <?= $this->dateFormat($signupList->getCloseDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('GEWIS members only') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $signupList->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No") ?>
                    </div>
                    <div class="col-md-5">
                        <?= $signupList->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No"); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <strong><?= $this->translate('Display GEWIS member count') ?></strong>
                    </div>
                    <div class="col-md-5">
                        <?= $signupList->getDisplaySubscribedNumber() ? $this->translate("Yes") : $this->translate("No") ?>
                    </div>
                    <div class="col-md-5">
                        <?= $signupList->getDisplaySubscribedNumber() ? $this->translate("Yes") : $this->translate("No"); ?>
                    </div>
                </div>
                <?php if ($signupList->getFields()->count() > 0): ?>
                    <div class="row">
                        <div class="col-md-12">
                            <h5><?= $this->translate('Additional fields') ?></h5>
                        </div>
                    </div>
                    <?php foreach ($signupList->getFields() as $field): ?>
                        <div class="row">
                            <div class="col-md-10 col-md-offset-2">
                                <hr>
                            </div>
                            <div class="col-md-2">
                                <strong><?= $this->translate('Name') ?></strong>
                            </div>
                            <div class="col-md-5">
                                <?= $this->escapeHtml($field->getName()->getValueNL()) ?>
                            </div>
                            <div class="col-md-5">
                                <?= $this->escapeHtml($field->getName()->getValueEN()) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <strong><?= $this->translate('Type') ?></strong>
                            </div>
                            <?php for ($i = 0; $i < 2; $i++): ?>
                                <div class="col-md-5">
                                    <?php
                                    switch ($field->getType()) {
                                        case 0:
                                            echo $this->translate('Text');
                                            break;
                                        case 1:
                                            echo $this->translate('Yes/No');
                                            break;
                                        case 2:
                                            echo $this->translate('Number');
                                            break;
                                        case 3:
                                            echo $this->translate('Choice');
                                            break;
                                    }
                                    ?>
                                </div>
                            <?php endfor; ?>
                        </div>
                        <?php if ($field->getType() === 2): ?>
                            <div class="row">
                                <div class="col-md-2">
                                    <strong><?= $this->translate('Min. value') ?></strong>
                                </div>
                                <?php for ($i = 0; $i < 2; $i++): ?>
                                    <div class="col-md-5">
                                        <?= $field->getMinimumValue() ?>
                                    </div>
                                <?php endfor; ?>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <strong><?= $this->translate('Max. value') ?></strong>
                                </div>
                                <?php for ($i = 0; $i < 2; $i++): ?>
                                    <div class="col-md-5">
                                        <?= $field->getMaximumValue() ?>
                                    </div>
                                <?php endfor; ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($field->getType() === 3): ?>
                            <div class="row">
                                <div class="col-md-2">
                                    <strong><?= $this->translate('Options') ?></strong>
                                </div>
                                <div class="col-md-10">
                                    <div class="row">
                                        <?php foreach ($field->getOptions() as $option): ?>
                                            <div class="col-md-6">
                                                <?= $this->escapeHtml($option->getValue()->getValueNL()) ?>
                                            </div>
                                            <div class="col-md-6">
                                                <?= $this->escapeHtml($option->getValue()->getValueEN()) ?>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
                <hr>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Approval') ?></h2>
    </div>
    <?php if ($activity->getStatus() === \Activity\Model\Activity::STATUS_TO_APPROVE): ?>
        <div class="col-md-2">
            <?php $approvalForm->setAttribute('action', $this->url('activity_admin_approval/approve', ['id' => $activity->getId()]));
            $approvalForm->prepare();
            echo $this->form()->openTag($approvalForm);
            echo $this->formElement($approvalForm->get('security'));
            $submit = $approvalForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            $submit->setAttribute('value', $this->translate('Approve'));
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
        <div class="col-md-2">
            <?php $disapprovalForm->setAttribute('action', $this->url('activity_admin_approval/disapprove', ['id' => $activity->getId()]));
            $disapprovalForm->prepare();
            echo $this->form()->openTag($disapprovalForm);
            echo $this->formElement($disapprovalForm->get('security'));
            $submit = $disapprovalForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            $submit->setAttribute('value', $this->translate('Disapprove'));
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_APPROVED): ?>
        <div class="col-md-2">
            <?php $resetForm->setAttribute('action', $this->url('activity_admin_approval/reset', ['id' => $activity->getId()]));
            $resetForm->prepare();
            echo $this->form()->openTag($resetForm);
            echo $this->formElement($resetForm->get('security'));
            $submit = $resetForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_DISAPPROVED): ?>
        <div class="col-md-2">
            <?php $resetForm->setAttribute('action', $this->url('activity_admin_approval/reset', ['id' => $activity->getId()]));
            $resetForm->prepare();
            echo $this->form()->openTag($resetForm);
            echo $this->formElement($resetForm->get('security'));
            $submit = $resetForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php endif; ?>
</div>
