<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headTitle($this->escapeHtml($activity->getName()->getText($lang)));
$this->headTitle($this->translate('Approval'));
?>
<div class="row admin-activity admin-activity-overview">
    <div class="col-md-12">
        <h2><?= $this->translate('Information') ?></h2>
        <p>
            <?php
            $organisingParty = "";
            if (!is_null($activity->getOrgan()) && !is_null($activity->getCompany())) {
                $organisingParty = $this->escapeHtml($activity->getOrgan()->getName()) . ' ';
                $organisingParty .= $this->translate('and') . ' ';
                $organisingParty .= $this->escapeHtml($activity->getCompany()->getName());
            } else if (!is_null($activity->getOrgan())) {
                $organisingParty = $this->escapeHtml($activity->getOrgan()->getName());
            } else if (!is_null($activity->getCompany())) {
                $organisingParty = $this->escapeHtml($activity->getCompany()->getName());
            } else {
                $organisingParty = $this->escapeHtml($activity->getCreator()->getMember()->getFullName());
            }
            
            echo sprintf(
                    $this->translate('This is activity <b>#%d</b>, organised by <b>%s</b>, and it will start on <b>%s</b> and end on <b>%s</b>.'),
                        $activity->getId(),
                        $organisingParty,
                        $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT),
                        $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT)
                );
            ?>
            <?= $this->translate('More information about this activity is available below.') ?>
        </p>
    </div>
    <div class="col-md-10 col-md-offset-2 overview-header">
        <div class="row">
            <div class="col-md-6">
                <span class="flag-icon flag-icon-nl"></span>
                <b><?= $this->translate('Dutch') ?></b>
                <hr>
            </div>
            <div class="col-md-6">
                <span class="flag-icon flag-icon-en"></span>
                <b><?= $this->translate('English') ?></b>
                <hr>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-2 overview-sidebar">
                <b><?= $this->translate('Name') ?></b>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-nl"></span>
                    <b><?= $this->translate('Name') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getName()->getValueNL()) ?>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-en"></span>
                    <b><?= $this->translate('Name') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getName()->getValueEN()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 overview-sidebar">
                <b><?= $this->translate('Location') ?></b>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-nl"></span>
                    <b><?= $this->translate('Location') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getLocation()->getValueNL()) ?>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-en"></span>
                    <b><?= $this->translate('Location') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getLocation()->getValueEN()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 overview-sidebar">
                <b><?= $this->translate('Costs') ?></b>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-nl"></span>
                    <b><?= $this->translate('Costs') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getCosts()->getValueNL()) ?>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-en"></span>
                    <b><?= $this->translate('Costs') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getCosts()->getValueEN()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 overview-sidebar">
                <b><?= $this->translate('Description') ?></b>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-nl"></span>
                    <b><?= $this->translate('Description') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getDescription()->getValueNL()) ?>
            </div>
            <div class="col-md-5">
                <span class="activity-property">
                    <span class="flag-icon flag-icon-en"></span>
                    <b><?= $this->translate('Description') ?>:</b>
                </span>
                <?= $this->escapeHtml($activity->getDescription()->getValueEN()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                    <?= $this->translate('View details / subscriptions') ?>
                </a>
            </div>
        </div>
        <hr>
    </div>
<?php if ($activity->getCategories()->count() > 0): ?>
    <div class="col-md-12">
        <h2><?= $this->translate('Activity Categories') ?></h2>
    </div>
    <div class="col-md-12">
        <?php foreach ($activity->getCategories() as $category): ?>
            <div class="chip">
                <span class="chip-label">
                    <?= $this->escapeHtml($category->getName()->getText($lang)) ?>
                </span>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($activity->getSignupLists()->count() > 0): ?>
    <div class="col-md-12">
        <h2><?= $this->translate('Signup Lists') ?></h2>
    </div>
    <div class="col-md-10 col-md-offset-2 overview-header">
        <div class="row">
            <div class="col-md-6">
                <span class="flag-icon flag-icon-nl"></span>
                <b><?= $this->translate('Dutch') ?></b>
                <hr>
            </div>
            <div class="col-md-6">
                <span class="flag-icon flag-icon-en"></span>
                <b><?= $this->translate('English') ?></b>
                <hr>
            </div>
        </div>
    </div>
    <?php foreach ($activity->getSignupLists() as $signupList): ?>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-2 overview-sidebar">
                    <b><?= $this->translate('Name') ?></b>
                </div>
                <div class="col-md-5">
                    <span class="activity-property">
                        <span class="flag-icon flag-icon-nl"></span>
                        <b><?= $this->translate('Name') ?>:</b>
                    </span>
                    <?= $this->escapeHtml($signupList->getName()->getValueNL()) ?>
                </div>
                <div class="col-md-5">
                    <span class="activity-property">
                        <span class="flag-icon flag-icon-en"></span>
                        <b><?= $this->translate('Name') ?>:</b>
                    </span>
                    <?= $this->escapeHtml($signupList->getName()->getValueEN()) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <b><?= $this->translate('Open date and time') ?></b>
                </div>
                <div class="col-md-5">
                    <?= $this->dateFormat($signupList->getOpenDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                </div>
                <div class="col-md-5 overview-sidebar">
                    <?= $this->dateFormat($signupList->getOpenDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <b><?= $this->translate('Close date and time') ?></b>
                </div>
                <div class="col-md-5">
                    <?= $this->dateFormat($signupList->getCloseDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                </div>
                <div class="col-md-5 overview-sidebar">
                    <?= $this->dateFormat($signupList->getCloseDate(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <b><?= $this->translate('GEWIS members only') ?></b>
                </div>
                <div class="col-md-5">
                    <?= $signupList->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No") ?>
                </div>
                <div class="col-md-5 overview-sidebar">
                    <?= $signupList->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No"); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <b><?= $this->translate('Display GEWIS member count') ?></b>
                </div>
                <div class="col-md-5">
                    <?= $signupList->getDisplaySubscribedNumber() ? $this->translate("Yes") : $this->translate("No") ?>
                </div>
                <div class="col-md-5 overview-sidebar">
                    <?= $signupList->getDisplaySubscribedNumber() ? $this->translate("Yes") : $this->translate("No"); ?>
                </div>
            </div>
            <?php if ($signupList->getFields()->count() > 0): ?>
                <div class="row">
                    <div class="col-md-10 col-md-offset-2">
                        <i><?= $this->translate('This signup list contains additional fields which require input from subscribers, they are shown below.') ?></i>
                    </div>
                </div>
                <?php foreach ($signupList->getFields() as $field): ?>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-2">
                            <hr>
                        </div>
                        <div class="col-md-2 overview-sidebar">
                            <b><?= $this->translate('Name') ?></b>
                        </div>
                        <div class="col-md-5">
                            <span class="activity-property">
                                <span class="flag-icon flag-icon-nl"></span>
                                <b><?= $this->translate('Name') ?>:</b>
                            </span>
                            <?= $this->escapeHtml($field->getName()->getValueNL()) ?>
                        </div>
                        <div class="col-md-5">
                            <span class="activity-property">
                                <span class="flag-icon flag-icon-en"></span>
                                <b><?= $this->translate('Name') ?>:</b>
                            </span>
                            <?= $this->escapeHtml($field->getName()->getValueEN()) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <b><?= $this->translate('Type') ?></b>
                        </div>
                        <?php for ($i = 0; $i < 2; $i++): ?>
                            <div class="col-md-5 <?= ($i == 1) ? 'overview-sidebar' : '' ?>">
                                <?php
                                switch ($field->getType()) {
                                    case 0:
                                        echo $this->translate('Text');
                                        break;
                                    case 1:
                                        echo $this->translate('Yes/No');
                                        break;
                                    case 2:
                                        echo $this->translate('Number');
                                        break;
                                    case 3:
                                        echo $this->translate('Choice');
                                        break;
                                }
                                ?>
                            </div>
                        <?php endfor; ?>
                    </div>
                    <?php if ($field->getType() === 2): ?>
                        <div class="row">
                            <div class="col-md-2">
                                <b><?= $this->translate('Min. value') ?></b>
                            </div>
                            <?php for ($i = 0; $i < 2; $i++): ?>
                                <div class="col-md-5 <?= ($i == 1) ? 'overview-sidebar' : '' ?>">
                                    <?= $field->getMinimumValue() ?>
                                </div>
                            <?php endfor; ?>
                        </div>
                        <div class="row">
                            <div class="col-md-2">
                                <b><?= $this->translate('Max. value') ?></b>
                            </div>
                            <?php for ($i = 0; $i < 2; $i++): ?>
                                <div class="col-md-5 <?= ($i == 1) ? 'overview-sidebar' : '' ?>">
                                    <?= $field->getMaximumValue() ?>
                                </div>
                            <?php endfor; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($field->getType() === 3): ?>
                        <div class="row">
                            <div class="col-md-2">
                                <b><?= $this->translate('Options') ?></b>
                            </div>
                            <div class="col-md-10">
                                <div class="row">
                                    <?php foreach ($field->getOptions() as $option): ?>
                                        <div class="col-md-6">
                                            <span class="activity-property">
                                                <span class="flag-icon flag-icon-nl"></span>
                                            </span>
                                            <?= $this->escapeHtml($option->getValue()->getValueNL()) ?>
                                        </div>
                                        <div class="col-md-6">
                                            <span class="activity-property">
                                                <span class="flag-icon flag-icon-en"></span>
                                            </span>
                                            <?= $this->escapeHtml($option->getValue()->getValueEN()) ?>
                                        </div>
                                        <br>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <hr>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
    <div class="col-md-12">
        <h2><?= $this->translate('Approval') ?></h2>
    </div>
    <?php if ($activity->getStatus() === \Activity\Model\Activity::STATUS_TO_APPROVE): ?>
        <div class="col-md-2">
            <?php $approvalForm->setAttribute('action', $this->url('activity_admin_approval/approve', ['id' => $activity->getId()]));
            $approvalForm->prepare();
            echo $this->form()->openTag($approvalForm);
            echo $this->formElement($approvalForm->get('security'));
            $submit = $approvalForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            $submit->setAttribute('value', $this->translate('Approve'));
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
        <div class="col-md-2">
            <?php $disapprovalForm->setAttribute('action', $this->url('activity_admin_approval/disapprove', ['id' => $activity->getId()]));
            $disapprovalForm->prepare();
            echo $this->form()->openTag($disapprovalForm);
            echo $this->formElement($disapprovalForm->get('security'));
            $submit = $disapprovalForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            $submit->setAttribute('value', $this->translate('Disapprove'));
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_APPROVED): ?>
        <div class="col-md-2">
            <?php $resetForm->setAttribute('action', $this->url('activity_admin_approval/reset', ['id' => $activity->getId()]));
            $resetForm->prepare();
            echo $this->form()->openTag($resetForm);
            echo $this->formElement($resetForm->get('security'));
            $submit = $resetForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_DISAPPROVED): ?>
        <div class="col-md-2">
            <?php $resetForm->setAttribute('action', $this->url('activity_admin_approval/reset', ['id' => $activity->getId()]));
            $resetForm->prepare();
            echo $this->form()->openTag($resetForm);
            echo $this->formElement($resetForm->get('security'));
            $submit = $resetForm->get('submit');
            $submit->setAttribute('class', 'btn btn-default');
            echo $this->formSubmit($submit);
            echo $this->form()->closeTag();
            ?>
        </div>
    <?php endif; ?>
</div>
