<?php

use Activity\Form\ActivityCategory as ActivityCategoryForm;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var string $action
 * @var ActivityCategoryForm $form
 */

$this->headTitle($action);
$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Activity Categories'), true, $this->url('activity_admin_categories'))
    ->addBreadcrumb($action);

$this->headScript()
    ->prependFile(
        $this->basePath() . '/js/activity-create.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basePath() . '/js/bootstrap/tooltip.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

$form->prepare();
$form->setAttribute('class', 'form-activity');
?>
<div class="row">
    <div class="col-md-12">
        <h2><?= $action ?></h2>
    </div>
    <?= $this->form()->openTag($form) ?>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <?php
                $checkboxDutch = $form->get('language_dutch')
                    ->setAttribute('id', 'dutch-check')
                    ->setAttribute('class', 'language-control');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($checkboxDutch) ?>">
                    <label for="<?= $checkboxDutch->getAttribute('id') ?>" class="control-label"
                           title="<?= $this->translate('Enable Dutch Translations') ?>">
                        <?= $this->formCheckbox($checkboxDutch) ?>
                        <span class="flag-icon flag-icon-nl"></span>
                        <?= $this->translate('Dutch') ?>
                    </label>
                    <?= $this->formElementErrors($checkboxDutch) ?>
                </div>
                <hr>
            </div>
            <div class="col-md-12">
                <?php
                $name = $form->get('name')
                    ->setAttribute('disabled', 'disabled')
                    ->setAttribute('class', 'form-control form-control-dutch')
                    ->setAttribute('id', 'name-nl');
                $name->setValue($this->localisedTextElement($name));
                ?>
                <div class="form-group <?= $this->bootstrapElementError($name) ?>">
                    <label for="<?= $name->getAttribute('id') ?>" class="control-label">
                        <?= $this->translate('Name') ?>
                    </label>
                    <?= $this->formText($name) ?>
                    <?= $this->formElementErrors($name) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <?php
                $checkboxEnglish = $form->get('language_english')
                    ->setAttribute('id', 'english-check')
                    ->setAttribute('class', 'language-control');
                ?>
                <div class="form-group <?= $this->bootstrapElementError($checkboxEnglish) ?>">
                    <label for="<?= $checkboxEnglish->getAttribute('id') ?>" class="control-label"
                           title="<?= $this->translate('Enable English Translations') ?>">
                        <?= $this->formCheckbox($checkboxEnglish) ?>
                        <span class="flag-icon flag-icon-en"></span>
                        <?= $this->translate('English') ?>
                    </label>
                    <?= $this->formElementErrors($checkboxEnglish) ?>
                </div>
                <hr>
            </div>
            <div class="col-md-12">
                <?php
                $nameEn = $form->get('nameEn')
                    ->setAttribute('disabled', 'disabled')
                    ->setAttribute('class', 'form-control form-control-english')
                    ->setAttribute('id', 'name-en');
                $nameEn->setValue($this->localisedTextElement($nameEn));
                ?>
                <div class="form-group <?= $this->bootstrapElementError($nameEn) ?>">
                    <label for="<?= $nameEn->getAttribute('id') ?>" class="control-label">
                        <?= $this->translate('Name') ?>
                    </label>
                    <?= $this->formText($nameEn) ?>
                    <?= $this->formElementErrors($nameEn) ?>
                </div>
            </div>
        </div>
        <br>
    </div>
    <div class="col-md-12">
        <?php
        $submit = $form->get('submit')
            ->setLabel($action)
            ->setAttribute('class', 'btn btn-primary');
        ?>
        <div class="form-group">
            <?= $this->formButton($submit) ?>
        </div>
    </div>
    <?= $this->form()->closeTag($form) ?>
</div>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    Activity.updateForm();

    document.querySelectorAll('.language-control').forEach(checkbox => {
        checkbox.addEventListener('click', () => {
            Activity.updateForm();
        });
    });
</script>
