<?php
$this->inlineScript()
    ->appendFile(
        $this->basePath() . '/js/dropzone-min.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
$this->headLink()->appendStylesheet($this->basePath() . '/css/dropzone.css');

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Education'), true, $this->url('admin_education'))
    ->addBreadcrumb($this->translate('Upload Exams'));
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Upload exams') ?>
            <hr>
            <div class="panel panel-default">
                <form action="<?= $this->url('admin_education/bulk_upload_exam') ?>"
                      class="dropzone" id="exam-dropzone"></form>
            </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url('admin_education/bulk_edit_exam') ?>"
           class="btn btn-primary"><?= $this->translate('Finalize exam uploads') ?></a>
    </div>
</div>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.addEventListener("DOMContentLoaded", function() {
        Dropzone.options.examDropzone = {
            acceptedFiles: 'application/pdf',
        };
        Dropzone.discover();
    });
</script>
