<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

$this->inlineScript()
    ->appendFile(
        $this->basepath('js/dropzone-min.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
$this->headLink()->appendStylesheet($this->basepath('css/dropzone.css'));

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Education'), true, $this->url('admin_education'))
    ->addBreadcrumb($this->translate('Upload Summaries'));
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Upload summaries') ?>
            <hr>
            <div class="panel">
                <form action="<?= $this->url('admin_education/bulk_upload_summary') ?>"
                      class="dropzone" id="summary-dropzone"></form>
            </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <a href="<?= $this->url('admin_education/bulk_edit_summary') ?>"
           class="btn btn-primary"><?= $this->translate('Finalize summary uploads') ?></a>
    </div>
</div>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.addEventListener("DOMContentLoaded", function() {
        Dropzone.options.summaryDropzone = {
            acceptedFiles: 'application/pdf',
        };
        Dropzone.discover();
    });
</script>
