<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/dropzone.js');
$this->headLink()->prependStylesheet($this->basePath() . '/css/dropzone.css');
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Upload exams') ?>
        <hr>
        <div class="panel panel-default">
        <form action="<?= $this->url('admin_education/default', array(
            'action' => 'bulk'
        )) ?>" class="dropzone panel-body"></form>
        </div>
    </div>
</div>
