<?php
$form->prepare();

$form->setAttribute('action', $this->url('admin_education/default', array('action' => 'edit')));
$form->setAttribute('method', 'post');

$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>

<?php
$exams = $form->get('exams');
?>
<?php foreach ($exams->getIterator() as $fs): ?>
    <div class="form-group">
        <h3 class="col-sm-offset-2 col-sm-10"><?= $this->escapeHtml($fs->get('file')->getValue()) ?></h2>
    </div>
    <?= $this->formHidden($fs->get('file')) ?>

    <div class="form-group">
<?php
$element = $fs->get('course');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
        </div>
    </div>

    <div class="form-group">
<?php
$element = $fs->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
        </div>
    </div>

<?php endforeach ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
