<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Education\Form\Bulk as BulkForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var array $config
 * @var BulkForm $form
 */

$this->inlineScript()
    ->appendFile(
        $this->basepath('js/education-admin.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

$this->scriptUrl()->requireUrl('admin_education/delete_temp', ['type', 'filename']);

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Education'), true, $this->url('admin_education'))
    ->addBreadcrumb($this->translate('Edit Exam'));
?>
<?php if (isset($success) && $success): ?>
    <?= $this->translate('Upload of all exams was finished.') ?>
<?php elseif (count($form->get('documents')->getIterator()) == 0): ?>
    <?= $this->translate('There are no exams to be edited. Upload exams to edit them.') ?>
<?php else: ?>
    <?php
    $form->prepare();

    $form->setAttribute('action', $this->url('admin_education/bulk_edit_exam'));
    $form->setAttribute('method', 'post');

    $form->setAttribute('class', 'form-horizontal');
    ?>
    <?= $this->form()->openTag($form) ?>

    <?php
    $exams = $form->get('documents');
    ?>
    <?php foreach ($exams->getIterator() as $fs): ?>
        <div>
            <div class="form-group">
                <h3 class="col-sm-offset-2 col-sm-10">
                    <a target="_blank"
                       href="<?= $this->basePath($config['public_exam_dir'] . '/' . $this->escapeHtmlAttr($fs->get('file')->getValue())) ?>">
                        <?= $this->escapeHtml($fs->get('file')->getValue()) ?>
                    </a>
                    <a data-file-value="<?= $this->escapeHtmlAttr($fs->get('file')->getValue()) ?>"
                       class="btn btn-xs btn-danger pull-right delete-temp-exam">
                        <?= $this->translate('Delete') ?>
                    </a>
                </h3>
            </div>
            <?= $this->formHidden($fs->get('file')) ?>

            <?php
            $element = $fs->get('course');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getName() ?>"
                       class="control-label col-sm-2"><?= $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?= $this->formText($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>

            <?php
            $element = $fs->get('date');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getName() ?>"
                       class="control-label col-sm-2"><?= $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?= $this->formDate($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>

            <?php
            $element = $fs->get('examType');
            $element->setAttribute('class', 'form-control');
            ?>
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getName() ?>"
                       class="control-label col-sm-2"><?= $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?= $this->formSelect($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <?php
            $element = $fs->get('language');
            $element->setAttribute('class', 'form-control');
            ?>
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getName() ?>"
                       class="control-label col-sm-2"><?= $element->getLabel() ?></label>
                <div class="col-sm-10">
                    <?= $this->formSelect($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <?php
            $element = $fs->get('scanned');
            $element->setAttribute('class', 'form-control');
            ?>
            <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                    <?= $element->getLabel() ?>
                    <span data-toggle="tooltip" data-placement="right"
                          title="<?= $this->translate('Check this if the document is scanned, as this will enable higher quality downloads. Please note that enabling setting this for non-scanned documents will significantly impact the ability to download the document.') ?>"
                          class="fas fa-info-circle" aria-hidden="true"></span>
                </label>
                <div class="col-sm-10">
                    <?= $this->formCheckbox($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    <?php endforeach ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <?= $this->formSubmit($submit) ?>
        </div>
    </div>

    <?= $this->form()->closeTag() ?>
<?php endif ?>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.querySelectorAll('.delete-temp-exam').forEach(exam => {
        exam.addEventListener('click', e => {
            e.preventDefault();

            Education.Admin.deleteTemp('exam', e.target.dataset.fileValue, e.target);
        });
    });
</script>
