<?php
$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Education'), true, $this->url('admin_education'))
    ->addBreadcrumb($this->translate('Courses'), true, $this->url('admin_education/course'))
    ->addBreadcrumb(
        $this->escapeHtml($course->getCode()),
        true,
        $this->url('admin_education/course/edit', ['course' => $course->getCode()]),
    )
    ->addBreadcrumb($this->translate('Edit'));
?>

<?php
$form->prepare();

$form->setAttribute('action', $this->url('admin_education/course/edit', ['course' => $course->getCode()]));
$form->setAttribute('method', 'post');
?>
<?= $this->form()->openTag($form) ?>

<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Edit Course') ?></h1>
    </div>
    <div class="col-md-12">
        <?php
        $element = $form->get('code');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label label-required">
                <?= $element->getLabel() ?>
            </label>
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <div class="col-md-12">
        <?php
        $element = $form->get('name');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label label-required">
                <?= $element->getLabel() ?>
            </label>
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <?php
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary pull-right');
            ?>
            <?= $this->formSubmit($submit) ?>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
