<?php if (isset($this->success) && $this->success): ?>
<?= $this->translate('Summary successfully uploaded!') ?>
<?php else: ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('admin_education/default', ['action' => 'summary']));
$form->setAttribute('method', 'post');

$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form); ?>

<?php
$element = $form->get('course');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('author');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('language');
$element->setAttribute('class', 'form-control');
?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formSelect($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('upload');
?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2"><?= $element->getLabel() ?></label>
        <div class="col-sm-10">
            <?= $this->formFile($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($this->translate('Upload'));
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
<?php endif ?>
