<?php if (isset($this->success) && $this->success): ?>
<?= $this->translate('Exam successfully uploaded!') ?>
<?php else: ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('admin_education/default', ['action' => 'upload']));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-group">
<?php
$element = $form->get('course');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Course code'));
$element->setAttribute('required', 'required');
?>
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $this->formElementErrors($element); ?>
    </div>

    <div class="form-group">
<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('required', 'required');
?>
        <?php echo $this->formLabel($element); ?>
        <?php echo $this->formInput($element); ?>
        <?php echo $this->formElementErrors($element); ?>
    </div>

    <div class="form-group">
        <?php $fileElement = $form->get('upload'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Upload'));
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?php echo $this->form()->closeTag(); ?>
<?php endif; ?>
