<?php
$form->prepare();

$form->setAttribute('action', $this->url('user/password/reset', ['user_type' => 'company']));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form); ?>
<?php
$email = $form->get('email');
$email->setAttribute('id', 'email');
$email->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($email) ?>">
    <label for="<?= $email->getAttribute('id') ?>"
           class="control-label col-sm-5"><?= $email->getLabel() ?></label>
    <div class="col-sm-7">
        <?= $this->formInput($email) ?>
        <?= $this->formElementErrors($email); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-5 col-sm-7">
        <?= $this->formElement($form->get('security')) ?>
        <?php
        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');
        $submit->setValue($this->translate('Reset password'));
        ?>
        <?= $this->formRow($submit); ?>
    </div>
</div>

<?= $this->form()->closeTag($form); ?>
