<?php

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\UserReset as UserResetForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var UserResetForm $form
 */

$form->prepare();

$form->setAttribute('action', $this->url('user/password/reset', ['user_type' => 'member']));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form); ?>
<?php
$element = $form->get('lidnr');
$element->setAttribute('id', 'lidnr');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getAttribute('id') ?>"
           class="control-label col-sm-5"><?= $element->getLabel() ?></label>
    <div class="col-sm-7">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
    </div>
</div>

<?php
$element = $form->get('email');
$element->setAttribute('id', 'email');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getAttribute('id') ?>"
           class="control-label col-sm-5"><?= $element->getLabel() ?></label>
    <div class="col-sm-7">
        <?= $this->formEmail($element) ?>
        <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
    </div>
</div>
<p>
    <?= $this->translate('Have you forgotten your e-mail address and do you want to change it? Ask the secretary by going to GEWIS (preferred) or by sending an e-mail.') ?>
</p>
<div class="form-group">
    <div class="col-sm-offset-5 col-sm-7">
        <?= $this->formElement($form->get('security')) ?>
        <?php
        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');
        $submit->setValue($this->translate('Reset password'));
        ?>
        <?= $this->formRow($submit); ?>
    </div>
</div>

<?= $this->form()->closeTag($form); ?>
