<div class="container">
    <section class="section">
        <div class="row">
            <div class="col-md-12">
                <h1>Add highlight</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3><? echo "You have currently got " . $company->getHighlightCredits() . " days left to highlight a vacancy."; ?></h3>
            </div>
        </div>
        <?php
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->partial('partial/company/company/editors/package.phtml', ['form' => $form, 'type' => 'highlight']);
        echo $this->form()->closeTag($form);?>

        <!--Active vacancies feed -->
        <div class="row mt-3">
            <div class="col-md-6 mt-2">
                <h2><?= $this->translate('Active highlights') ?></h2>

                <?php if (count($currentHighlights) > 0): ?>
                    <div class="panel panel-default">
                        <?php foreach ($currentHighlights as &$highlight): ?>
                            <div class="panel-heading">
                                <strong><?= $this->translate($highlight['name']) ?></strong>
                            </div>
                            <div class="panel-body">
                                <?= $this->translate($highlight['expires']->format('Y-m-d') )?>
                                <a href="<?= $this->url('companyaccount/dummy') ?>">go to vacancy</a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <hr/>
                <?php endif; ?>

                <?php if (count($currentHighlights) === 0): ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->translate("Currently there are no active highlights, you can add a highlight above")?>
                        </div>
                    </div>
                <?php endif; ?>


            </div>
        </div>
    </section>
</div>
