<?php
// set title
$this->headTitle($this->translate('Company Account'));

?>

<div class="container">
    <section class="section">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate('Company') ?></h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <h2><?= $this->translate('Personal') ?></h2>
                <div class="grid grid-col-5">
                    <a href="<?= $this->url('companyaccount/dummy') ?>" class="panel panel-image align-middle">
                        <div class="big-icon fas fa-user"></div>
                        <div class="panel-heading"><?= $this->translate('Profile') ?></div>
                    </a>
                    <a href="<?= $this->url('companyaccount/dummy') ?>"
                       class="panel panel-image align-middle">
                        <div class="big-icon fas fa-lock"></div>
                        <div class="panel-heading"><?= $this->translate('Change password') ?></div>
                    </a>
                    <a href="<?= $this->url('user/default', ['action' => 'companyLogout']) ?>"
                       class="panel panel-image align-middle">
                        <div class="big-icon fas fa-lock"></div>
                        <div class="panel-heading"><?= $this->translate('Logout') ?></div>
                    </a>
                    <a href="<?= $this->url('companyaccount/settings') ?>"class="panel panel-image align-middle">
                        <div class="big-icon fas fa-cog"></div>
                        <div class="panel-heading"><?= $this->translate('Settings') ?></div>
                    </a>

                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <h2><?= $this->translate('Company content') ?></h2>
                <div class="grid grid-col-5">
                    <a href="<?= $this->url('companyaccount/vacancies') ?>" class="panel panel-image align-middle">
                        <div class="big-icon fas fa-list"></div>
                        <div class="panel-heading"><?= $this->translate('Vacancies') ?></div>
                    </a>
                    <a href="<?= $this->url('companyaccount/dummy') ?>"
                       class="panel panel-image align-middle">
                        <div class="big-icon fas fa-list"></div>
                        <div class="panel-heading"><?= $this->translate('Activities') ?></div>
                    </a>
                    <a href="<?= $this->url('companyaccount/bannerupload') ?>" class="panel panel-image align-middle">
                        <div class="big-icon fas fa-flag"></div>
                        <div class="panel-heading"><?= $this->translate('Banner') ?></div>
                    </a>
                    <a href="<?= $this->url('companyaccount/dummy') ?>" class="panel panel-image align-middle">
                        <div class="big-icon fas fa-check"></div>
                        <div class="panel-heading"><?= $this->translate('Highlight') ?></div>
                    </a>
                </div>
            </div>
        </div>

        <!--Active vacancies feed -->
        <div class="row mt-3">
            <div class="col-md-6 mt-2">
                <h2><?= $this->translate('Active vacancies') ?></h2>

                <?php if (count($vacancies) > 0): ?>
                    <div class="panel panel-default">
                        <?php foreach ($vacancies as &$vacancy): ?>
                        <div class="panel-heading">
                            <strong><?= $this->translate($vacancy->getName()) ?></strong>
                        </div>
                        <div class="panel-body">
                           <?= $this->translate($vacancy->getDescription())?>
                            <a href="<?= $this->url('companyaccount/dummy') ?>">go to vacancy</a>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <hr/>
                <?php endif; ?>

                <?php if (count($vacancies) === 0): ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?= $this->translate("Currently there are no active vacancies,")?>
                        <a href="<?= $this->url('companyaccount/vacancies/createvacancy') ?>">add new vacancy.</a>
                    </div>
                </div>
                <?php endif; ?>


            </div>
        </div>

    </section>
</div>
