<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Vacancies</h1>
            </div>
        </div>
        <ul class="nav nav-pills head-menu">
<!--            --><?php //if ($this->acl('company_acl')->isAllowed('company', 'listall')): ?>
                <li>
                    <a href="<?= $this->url('companyaccount/vacancies/createvacancy') ?>">
                        <?= $this->translate('Create new Vacancy') ?>
                    </a>
                </li>
<!--            --><?php //endif; ?>
<!--            --><?php //if ($this->acl('company_acl')->isAllowed('company', 'listall')): ?>
                <li>
                    <a href="<?= $this->url('companyaccount/vacancies/editvacancy') ?>">
                        <?= $this->translate('Edit existing Vacancy') ?>
                    </a>
                </li>
<!--            --><?php //endif; ?>
        </ul>

        <hr/>

        <?= $this->content ?>
    </div>
</section>
