<?php

use Application\Model\Enums\Languages;

?>
For English, see below.

L.s.<br/><br/>

Er is een nieuwe activiteit aangemaakt op de GEWIS website.

<h3><?= $this->escapeHtml($activity->getName()->getText(Languages::Dutch)) ?></h3>

<p><?= $this->escapeHtml($activity->getDescription()->getText(Languages::Dutch)) ?></p>

<table>
    <tr>
        <td><strong>Starttijd:</strong></td>
        <td><?= $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT, 'nl'); ?></td>
    </tr>
    <tr>
        <td><strong>Eindtijd</strong></td>
        <td><?= $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT), 'nl'; ?></td>
    </tr>
    <tr>
        <td><strong>Locatie:</strong></td>
        <td><?= $this->escapeHtml($activity->getLocation()->getText(Languages::Dutch)) ?></td>
    </tr>
    <tr>
        <td><strong>Kosten:</strong></td>
        <td><?= $this->escapeHtml($activity->getCosts()->getText(Languages::Dutch)) ?></td>
    </tr>
</table>
<br/>
Klik <a
    href="<?= $this->serverUrl($this->url('activity_admin_approval/view', ['id' => $activity->getId()])) ?>">hier</a> om deze activiteit goed/af te keuren.
<br/><br/>

Met vriendelijke groeten,<br/>
De ApplicatieBeheerCommissie
<hr/>

L.s.<br/><br/>

A new activity was created at the GEWIS website. See below for details.

<h1><?= $this->escapeHtml($activity->getName()->getText(Languages::English)) ?></h1>

<p><?= $this->escapeHtml($activity->getDescription()->getText(Languages::English)) ?></p>

<table>
    <tr>
        <td><strong>Starting time:</strong></td>
        <td><?= $this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT, 'en'); ?></td>
    </tr>
    <tr>
        <td><strong>Ending time:</strong></td>
        <td><?= $this->dateFormat($activity->getEndTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT, 'en'); ?></td>
    </tr>
    <tr>
        <td><strong>Location:</strong></td>
        <td><?= $this->escapeHtml($activity->getLocation()->getText(Languages::English)) ?></td>
    </tr>
    <tr>
        <td><strong>Costs:</strong></td>
        <td><?= $this->escapeHtml($activity->getCosts()->getText(Languages::English)) ?></td>
    </tr>
</table>
<br/>
Click <a
    href="<?= $this->serverUrl($this->url('activity_admin_approval/view', ['id' => $activity->getId()])) ?>">here</a> to approve/disapprove this activity.
<br/><br/>

Kind Regards, <br/>
The ApplicatieBeheerCommissie
