<?php $lang = 'en'; ?>
For English, see below.

L.s.<br /><br />

Er is een nieuwe activiteit aangemaakt op de GEWIS website waarvoor een fotograaf van GEFLITST nodig is.

<h3><?= $this->escapeHtml($activity->getName()) ?></h3>

<p><?= $this->escapeHtml($activity->getDescription()) ?></p>

<br/>

Het orgaan dat deze activiteit heeft aangemaakt kan worden bereikt via dit e-mailadres: <?= $this->escapeHtml($activity->getResourceOrgan()->getOrganInformation()['email']) ?>
<br/><br/>

Met vriendelijke groeten,<br />
De Web Commissie
<hr />

L.s.<br /><br />

A new activity has been created on the GEWIS website that needs a photographer of GEFLITST.

<h3><?= $this->escapeHtml($activity->getName()) ?></h3>

<p><?= $this->escapeHtml($activity->getDescription()) ?></p>

<br/>

The organ that created this activity can be reached via this e-mail address: <?= $this->escapeHtml($activity->getResourceOrgan()->getOrganInformation()['email']) ?>
<br/><br/>

With kind regards,<br />
The Web Committee
<hr />