<?php

use Activity\Form\ActivityCalendarProposal as ActivityCalendarProposalForm;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ActivityCalendarProposalForm $form
 */

$this->headTitle($this->translate('Create activity proposal'));
$this->headScript()
    ->appendFile(
        $this->basePath() . '/js/proposal-create.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

$form->prepare();
$form->setAttribute('class', 'form-activity');
?>
<section class="section">
    <div class="container">
        <?= $this->form()->openTag($form) ?>
            <div class="row">
                <div class="col-md-12">
                    <h1><?= $this->translate('Option calendar') ?></h1>
                    <h2><?= $this->translate('Propose options for an activity') ?></h2>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h2><?= $this->translate('Organisation') ?></h2>
                            <p><?= $this->translate('Select the organ for which the options are and in which option period the options should be planned.')?></p>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php
                                    $period = $form->get('period')
                                        ->setAttribute('class', 'form-control')
                                    ?>
                                    <div class="form-group <?= $this->bootstrapElementError($period) ?>">
                                        <label for="<?= $period->getAttribute('id') ?>" class="control-label label-required">
                                            <?= $this->translate('Period') ?>
                                        </label>
                                        <?= $this->formSelect($period) ?>
                                        <?= $this->formElementErrors($period) ?>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <?php
                                    $organ = $form->get('organ')
                                        ->setAttribute('class', 'form-control')
                                    ?>
                                    <div class="form-group <?= $this->bootstrapElementError($organ) ?>">
                                        <label
                                            for="<?= $organ->getAttribute('id') ?>"
                                            class="control-label label-required">
                                            <?= $this->translate('Committee / fraternity') ?>
                                        </label>
                                        <?= $this->formSelect($organ) ?>
                                        <?= $this->formElementErrors($organ) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <h2><?= $this->translate('Details') ?></h2>
                            <p><?= $this->translate('Select the organ for which the options are and in which option period the options should be planned.')?></p>
                            <div class="row">
                                <div class="col-md-6">
                                    <?php
                                    $inputName = $form->get('name')
                                        ->setAttribute('class', 'form-control')
                                        ->setAttribute('id', 'input-name')
                                    ?>
                                    <div class="form-group <?= $this->bootstrapElementError($inputName) ?>">
                                        <label
                                            for="<?= $inputName->getAttribute('id') ?>"
                                            class="control-label<?= $form->getInputFilter()->get('name')->isRequired() ? ' label-required' : '' ?>">
                                            <?= $this->translate('Name') ?>
                                        </label>
                                        <?= $this->formText($inputName) ?>
                                        <?= $this->formElementErrors($inputName) ?>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <?php
                                    $inputDescription = $form->get('description')
                                        ->setAttribute('class', 'form-control')
                                        ->setAttribute('id', 'input-description')
                                    ?>
                                    <div class="form-group <?= $this->bootstrapElementError($inputDescription) ?>">
                                        <label
                                            for="<?= $inputDescription->getAttribute('id') ?>"
                                            class="control-label<?= $form->getInputFilter()->get('description')->isRequired() ? ' label-required' : '' ?>">
                                            <?= $this->translate('Description') ?>
                                        </label>
                                        <?= $this->formTextarea($inputDescription) ?>
                                        <?= $this->formElementErrors($inputDescription) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h2><?= $this->translate('Options') ?></h2>
                    <p><?= $this->translate('Add options for your activity proposal.') ?></p>
                </div>
                <div class="col-md-12">
                    <?php
                    /* render template for options */
                    $fs = $form->get('options')->getTemplateElement();
                    ob_start();
                    echo $this->partial('partial/option.phtml', ['fs' => $fs, 'index' => '__index__']);
                    $tpl = trim(ob_get_clean())
                    ?>
                    <fieldset id="additionalOptions">
                        <span class="template" data-template="<?= $this->escapeHtmlAttr($tpl) ?>"></span>
                        <?php
                        $index = 0;
                        foreach ($form->get('options')->getIterator() as $fs) {
                            echo $this->partial('partial/option.phtml', ['fs' => $fs, 'index' => $index]);
                            $index++;
                        }
                        ?>
                        <div class="form-group spacing-top--md option-menu">
                            <button class="btn btn-success add-option" type="button">
                                <span class="fas fa-plus"></span>
                                <?= $this->translate('Add an option') ?>
                            </button>
                            <button class="btn btn-danger remove-option" type="button">
                                <span class="fas fa-minus"></span>
                                <?= $this->translate('Remove the last option') ?>
                            </button>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <input type="submit" class="btn btn-primary" value="<?= $this->translate('Submit') ?>"/>
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</section>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    Proposal.updateForm();

    for (let i = 0; i < <?= $index ?>; i++) {
        Proposal.updateOption(i);
    }

    document.querySelector('.add-option').addEventListener('click', () => {
        Proposal.addOption();
    });
    document.querySelector('.remove-option').addEventListener('click', () => {
        Proposal.removeOption();
    });

    document.addEventListener('change', (e) => {
        if (e.target.classList.contains('begin-time')) {
            let id = e.target.dataset.beginOptionId;
            let end = document.querySelector('[data-end-option-id="' + id + '"]');

            if ('' === end.value) {
                end.value = e.target.value;
            }
        }
    });
</script>
