<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/calendar.min.js')
    ->prependFile($this->basePath() . '/js/language/nl-NL.js')
    ->prependFile($this->basePath() . '/js/underscore-min.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/calendar.min.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$form->prepare();
?>
<div class="container option-calendar">
    <div class="row">
        <h1><?= $this->translate('Option calendar') ?></h1>
        <?= $this->translate('Welcome on the page of the digital Option Calendar. In the calendar below you can place options for GEWIS activities, just like this was done before on the paper version of the option calendar. The red dots indicate activities that are already in the GEWIS agenda, the blue dots are options for activities. If you insert an option, please give it a clear name, such that it is clear where the option is for.') ?>
        <br/>
        <?= $this->translate('There are a few rules:') ?>
        <ul>
            <li><?= $this->translate('No more than 3 options for the same activity are allowed.') ?></li>
            <li><?= $this->translate('The first to put an option on a particular date, has the first dibs on this date. If an option stays in the option calendar for more than 3 weeks without a budget being sent to the board, then the option gets deleted and the next one in line gets the chance to use this date for an activity.') ?></li>
        </ul>
    </div>
    <hr>
    <div class="row">
        <div class="pull-left">
            <div class="btn-group">
                <button class="btn btn-primary" data-calendar-nav="prev">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                </button>
                <button class="btn btn-default" data-calendar-nav="today">
                    <?= $this->translate("Today") ?>
                </button>
                <button class="btn btn-primary" data-calendar-nav="next">
                    <i class="glyphicon glyphicon-chevron-right"></i>
                </button>
            </div>
            <div class="btn-group">
                <button class="btn btn-default" data-calendar-view="year">
                    <?= $this->translate("Year") ?>
                </button>
                <button class="btn btn-default active" data-calendar-view="month">
                    <?= $this->translate("Month") ?>
                </button>
            </div>

            <h3 class="calendarTitleHeader"><span id="calendarTitle"></span></h3>
        </div>
        <div class="pull-right">
            <div class="dropdown pull-right<?= $optionError ? ' open' : '' ?>">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span class="hidden-xs"><?= $this->translate('Add option') ?></span>
                </button>
                <div class="dropdown-menu">
                    <form class="form" method="post">
                        <?php
                        $name = $form->get('name');
                        $name->setAttribute('class', 'form-control');
                        ?>
                        <div class="form-group<?= count($name->getMessages()) > 0 ? ' has-error' : '' ?>">
                            <label for="<?= $name->getName() ?>">
                                <?= $this->translate('Name') ?>
                            </label>
                            <?= $this->formInput($name) ?>
                            <?= $this->formElementErrors($name) ?>
                        </div>
                        <?php
                        $beginTime = $form->get('beginTime');
                        $beginTime->setAttribute('class', 'form-control datepicker');
                        $endTime = $form->get('endTime');
                        $endTime->setAttribute('class', 'form-control datepicker');
                        ?>
                        <div class="form-group<?= count($beginTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                            <label for="<?= $beginTime->getName() ?>"><?= $this->translate('From') ?></label>
                            <?= $this->formInput($beginTime) ?>
                            <?= $this->formElementErrors($beginTime) ?>
                        </div>

                        <div class="form-group<?= count($endTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                            <label for="<?= $endTime->getName() ?>"><?= $this->translate('Until') ?></label>
                            <?= $this->formInput($endTime) ?>
                            <?= $this->formElementErrors($endTime) ?>
                        </div>
                        <?php
                        $organ = $form->get('organ');
                        $organ->setAttribute('class', 'form-control');
                        ?>
                        <div class="form-group<?= count($organ->getMessages()) > 0 ? ' has-error' : '' ?>">
                            <label for="<?= $organ->getName(); ?>">
                                <?= $this->translate('Organizing committee / fraternity') ?>
                            </label>
                            <?= $this->formSelect($organ) ?>
                            <?= $this->formElementErrors($organ) ?>
                        </div>
                        <button type="submit" class="btn btn-primary"><?= $this->translate('Submit') ?></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="calendar" class="calendar-control"></div>
    </div>
    <div class="row">
        <h2><?= $this->translate('My options') ?></h2>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th><?= $this->translate('Creator') ?></th>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Created at') ?></th>
                <th><?= $this->translate('Start') ?></th>
                <th><?= $this->translate('End') ?></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($editableOptions as $option): ?>
                <tr<?= $option->getDeletedBy() === null ? '' : ' class="danger"' ?>>

                    <td><?= $option->getOrgan() === null ? $option->getCreator()->getMember()->getFullName() : $option->getOrgan()->getAbbr() ?></td>
                    <td><?= $this->escapeHtml($option->getName()) ?></td>
                    <td><?= $option->getCreationTime()->format('d-m-Y') ?></td>
                    <td><?= $option->getBeginTime()->format('d-m-Y H:i') ?></td>
                    <td><?= $option->getEndTime()->format('d-m-Y H:i') ?></td>
                    <td>
                        <?php if($option->getDeletedBy() === null): ?>
                            <a class="btn btn-xs btn-delete btn-danger" href="javascript:showDeleteModal(<?= $option->getId() ?>)">
                                <i class="glyphicon glyphicon-trash"></i>&nbsp;<?= $this->translate('Delete') ?>
                            </a>
                        <?php else: ?>
                            <strong><?= $this->translate('Deleted by') ?> <?= $option->getDeletedBy()->getMember()->getFullName() ?></strong>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?= $this->translate('Delete option') ?></h4>
                </div>
                <div class="modal-body">
                    <p><?= $this->translate('Are you sure you want to delete this option?') ?></p>
                </div>
                <div class="modal-footer">
                    <form method="post" action="delete" class="form form-inline form-delete">
                        <input type="hidden" name="option_id" id="deleteOptionId"/>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i>&nbsp;<?= $this->translate('Delete') ?></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('.datepicker').datetimepicker();
    var calendar;
    var timeMin = new Date();
    timeMin.setDate(timeMin.getDate() - 180);
    timeMinString = timeMin.toISOString();
    var calendarItems = [
        <?php foreach($options as $option): ?>
        {
            "isPlanned": "false",
            "isOwner": <?= in_array($option, $editableOptions) ? 'true' : 'false' ?>,
            "id": "<?= $option->getId() ?>",
            "title": "<?= $this->escapeHtml($option->getName()) ?>",
            "organizer": "<?= $option->getOrgan() === null ? $option->getCreator()->getMember()->getFullName() : $option->getOrgan()->getAbbr() ?>",
            "url": "#",
            "class": "event-info",
            "start": <?= $option->getBeginTime()->getTimestamp() * 1000 ?>,
            "end": <?= $option->getEndTime()->getTimestamp() * 1000?>
        },
        <?php endforeach ?>
    ];
    $.getJSON('https://www.googleapis.com/calendar/v3/calendars/<?= $calendarKey ?>@group.calendar.google.com/events?key=<?= $APIKey ?>&maxResults=2500&showDeleted=false&timeMin=' + timeMinString, function(data) {
        $.each( data.items, function( key, item ) {
            if (item.status != 'cancelled') {
                calendarItems.push({
                    "isPlanned": "true",
                    "isOwner": false,
                    "id": item.id,
                    "title": item.summary,
                    "url": item.htmlLink,
                    "class": "event-important",
                    "start": (new Date(item.start.dateTime !== undefined ? item.start.dateTime : item.start.date)).getTime(),
                    "end": (new Date(item.end.dateTime !== undefined ? item.end.dateTime : item.end.date)).getTime(),
                });
            }
        });
        initCalendar();
    }).error(function() { initCalendar() });


    function initCalendar() {
        calendar = $("#calendar").calendar(
            {
                tmpl_path: "<?= $this->basePath() ?>/tmpls/",
                tmpl_cache: false,
                events_source: function () { return calendarItems; },
                views: {
                    year: {
                        slide_events: 1,
                        enable: 1
                    },
                    month: {
                        slide_events: 1,
                        enable: 1
                    },
                    week: {
                        enable: 0
                    },
                    day: {
                        enable: 0
                    }
                },
                onAfterViewLoad: function(view) {
                    $('#calendarTitle').text(this.getTitle());
                },
            });
        <?php if ($this->plugin('translate')->getTranslator()->getLocale() === 'nl'): ?>
        calendar.setLanguage('nl-NL');
        calendar.view();
        <?php endif ?>
    }

    function showDeleteModal(optionId) {
        $('#deleteOptionId').val(optionId);
        $('#deleteModal').modal('show');
    }

    $('.btn-group button[data-calendar-nav]').each(function() {
        var $this = $(this);
        $this.click(function() {
            calendar.navigate($this.data('calendar-nav'));
        });
    });
    $('.btn-group button[data-calendar-view]').each(function() {
        var $this = $(this);
        $this.click(function() {
            $('.active').removeClass('active');
            $this.addClass('active');
            calendar.view($this.data('calendar-view'));
        });
    });
</script>
