<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/calendar.min.js')
    ->prependFile($this->basePath() . '/js/underscore-min.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/calendar.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
?>
<style>
    .row-offset-top {
        margin-top: 20px;
    }

    .dropdown-spacing {
        padding: 10px;
    }
</style>
<div class="container">
    <div class="row">
        <h1><?= $this->translate("Calendar") ?></h1>
    </div>

    <div class="row">
        <div class="pull-left">
            <div class="btn-group">
                <button class="btn btn-primary" data-calendar-nav="prev"><i class="glyphicon glyphicon-chevron-left"></i></button>
                <button class="btn btn-default" data-calendar-nav="today"><?= $this->translate("Today") ?></button>
                <button class="btn btn-primary" data-calendar-nav="next"><i class="glyphicon glyphicon-chevron-right"></i></button>
            </div>
            <div class="btn-group">
                <button class="btn btn-default" data-calendar-view="year">Year</button>
                <button class="btn btn-default active" data-calendar-view="month">Month</button>
            </div>
        </div>
        <div class="pull-right">
            <div class="dropdown pull-right">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-plus"></i>
                    <?= $this->translate('Add option') ?>
                </button>
                <div class="dropdown-menu dropdown-spacing">
                    <form class="form" style="width: 300px;">
                        <div class="form-group">
                            <label for="name"><?= $this->translate("Name") ?></label>
                            <input type="text" class="form-control" name="name" id="name" required />
                        </div>
                        <div class="form-group">
                            <label for="beginTime"><?= $this->translate("From") ?></label>
                            <input type="datetime" class="form-control" name="beginTime" id="beginTime" required />
                        </div>
                        <div class="form-group">
                            <label for="endTime"><?= $this->translate("To") ?></label>
                            <input type="datetime" class="form-control" name="endTime" id="endTime" required />
                        </div>
                        <div class="form-group">
                            <label for="organiser"><?= $this->translate("Organiser") ?></label>
                            <input type="text" class="form-control" name="organiser" id="organiser" required />
                        </div>
                        <button type="submit" class="btn btn-primary"><?= $this->translate('Submit') ?></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row row-offset-top">
        <div id="calendar"></div>
    </div>
</div>
<script type="text/javascript">
    $("#beginTime").datetimepicker();
    $("#endTime").datetimepicker();


    var calendar = $("#calendar").calendar(
        {
            tmpl_path: "/tmpls/",
            events_source: function () { return [
                <?php foreach($data->items as $item): ?>
                <?php if ($item->status != 'cancelled'): ?>
                {
                    "isPlanned": "true",
                    "isOwner": "true",
                    "id": "<?= $item->id ?>",
                    "title": "<?= isset($item->summary) ? htmlentities($item->summary) : ''?>",
                    "url": "<?= isset($item->htmlLink) ?$item->htmlLink : '' ?>",
                    "class": "event-important",
                    "start": <?= isset($item->start->dateTime) ? (strtotime($item->start->dateTime)) * 1000 : (strtotime($item->start->date))?>, // Milliseconds
                    "end": <?= isset($item->end->dateTime) ? (strtotime($item->end->dateTime)) * 1000 : (strtotime($item->end->date)) ?> // Milliseconds
                },
                <?php endif ?>
                <?php endforeach ?>
            ]; },
            views: {
                year: {
                    slide_events: 1,
                    enable: 1
                },
                month: {
                    slide_events: 1,
                    enable: 1
                },
                week: {
                    enable: 0
                },
                day: {
                    enable: 0
                }
            }
        });

    $('.btn-group button[data-calendar-nav]').each(function() {
        var $this = $(this);
        $this.click(function() {
            calendar.navigate($this.data('calendar-nav'));
        });
    });

    $('.btn-group button[data-calendar-view]').each(function() {
        var $this = $(this);
        $this.click(function() {
            calendar.view($this.data('calendar-view'));
        });
    });
</script>
