<div class="container">
<h1><?= $this->translate('Committees') ?></h1>
    <?= $this->translate('GEWIS has many different committees, learn more about them below!') ?>
    <div class="row">

            <?php foreach ($organs as $organ) {
                echo $this->partial('partial/organ-card.phtml', [
                    'organ' => $organ
                ]);
            }

            ?>
    </div>
</div>

