<?php
// set title
$this->headTitle($this->translate('Committees')); ?>

<section class="section">
    <div class="container">
        <h1><?= $this->translate('Committees') ?></h1>
        <?= $this->translate('GEWIS has many different committees, learn more about them below!') ?>
        <div class="row">

            <?php foreach ($committees as $committee) {
                echo $this->partial('partial/organ-card.phtml', [
                    'organ' => $committee,
                    'lang' => $this->plugin('translate')->getTranslator()->getLocale()
                ]);
            }

            ?>
        </div>
    </div>
</section>
