<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var OrganModel[] $activeFraternitites
 * @var OrganModel[] $abrogatedFraternities
 */

$this->headTitle($this->translate('Fraternities'));
?>
<section class="section">
    <div class="container">
        <h1><?= $this->translate('Fraternities') ?></h1>
        <p><?= $this->translate('Study association GEWIS obviously has several fraternities which contribute to the atmosphere at GEWIS and organize fun activities. Some fraternities have retired, but luckily new fraternities continue to be founded.') ?></p>
        <p><?= $this->translate('The currently active fraternities of GEWIS (in arbitrary order)') ?></p>
        <div class="card-grid">
            <?php
            $lang = $this->plugin('translate')->getTranslator()->getLocale();

            shuffle($activeFraternities);
            foreach ($activeFraternities as $fraternity) {
                echo $this->partial('partial/organ-card.phtml', [
                    'organ' => $fraternity,
                    'lang' => $lang,
                ]);
            }
            ?>
        </div>
        <hr>
        <h3><?= $this->translate('Retired fraternities') ?></h3>
        <p><?= $this->translate('The following fraternities have retired:') ?></p>
        <div class="card-grid">
            <?php
            $lang = $this->plugin('translate')->getTranslator()->getLocale();
            foreach ($abrogatedFraternities as $fraternity) {
                echo $this->partial('partial/organ-card.phtml', [
                    'organ' => $fraternity,
                    'lang' => $lang,
                ]);
            }
            ?>
        </div>
    </div>
</section>
