<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();
$organInformation = $organ->getApprovedOrganInformation();
function getOrganDescription($organInformation, $lang)
{
    if (is_null($organInformation)) {
        return '';
    }

    if ($lang === 'en') {
        if (strlen($organInformation->getEnglishDescription()) > 0) {
            return $organInformation->getEnglishDescription();
        }

        if (strlen($organInformation->getShortEnglishDescription()) > 0) {
            return $organInformation->getShortEnglishDescription();
        }
    }

    if (strlen($organInformation->getDutchDescription()) > 0) {
        return $organInformation->getDutchDescription();
    }

    if (strlen($organInformation->getShortDutchDescription()) > 0) {
        return $organInformation->getShortDutchDescription();
    }

    return '';

}

?>
<div class="container">
    <?php if (!is_null($organInformation) && !is_null($organInformation->getCoverPath())): ?>
        <div class="col-md-12 organ-banner"
             style="background-image: url('<?= $this->fileUrl($organInformation->getCoverPath()) ?>')">
        </div>
    <?php endif ?>
    <div class="row">
        <div class="col-md-8">
            <h1><?= $organ->getName() ?></h1>
            <?php echo getOrganDescription($organInformation, $lang) ?>
        </div>
        <div class="col-md-4">
            <table class="table">
                <?php if (!is_null($organInformation) && $this->acl('decision_acl')->isAllowed('organ', 'view')): ?>
                    <tr>
                        <td><span class="glyphicon glyphicon-envelope"></span>&nbsp;<?= $this->translate('Email') ?></td>
                        <td>
                            <a href="mailto:<?= $organInformation->getEmail() ?>">
                                <?= $organInformation->getEmail() ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if (!is_null($organInformation) && strlen($organInformation->getWebsite()) > 0): ?>
                    <tr>
                        <td><span class="glyphicon glyphicon-link"></span>&nbsp;<?= $this->translate('Website') ?></td>
                        <td>
                            <a href="<?= $organInformation->getWebsite() ?>">
                                <?= $organInformation->getWebsite() ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
            </table>
            <div class="panel panel-default agenda">
                <div class="panel-heading">
                    <h4><?= sprintf($this->translate('%s\'s activities'), $organ->getAbbr()) ?></h4>
                </div>
                <div class="panel-body">
                    <div class="list-group">

                    </div>


                </div>
                <div class="panel-footer">
                    <a href="<?= $this->url('activity') ?>">
                        <?= $this->translate('Complete agenda') ?>
                        <span class="glyphicon glyphicon-arrow-right"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h1><?= $this->translate('Members') ?></h1>
        </div>
    </div>
</div>