<?php

declare(strict_types=1);

use Activity\Model\Activity;
use Application\View\HelperTrait;
use Decision\Model\{
    Enums\OrganTypes,
    Member as MemberModel,
    Organ as OrganModel,
};
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var Activity[] $activities
 * @var array<array-key, array{member: MemberModel, functions: array<array-key, string>}> $activeMembers
 * @var array<array-key, MemberModel> $inactiveMembers
 * @var array<array-key, MemberModel> $oldMembers
 * @var OrganModel $organ
 */

// set title
$this->headTitle($organ->getName());

$lang = $this->plugin('translate')->getTranslator()->getLocale();
$organInformation = $organ->getApprovedOrganInformation();
function getOrganDescription($organInformation, $lang)
{
    if (null !== $organInformation) {
        if ($lang === 'en') {
            if (strlen($organInformation->getEnglishDescription()) > 0) {
                return $organInformation->getEnglishDescription();
            }

            if (strlen($organInformation->getShortEnglishDescription()) > 0) {
                return $organInformation->getShortEnglishDescription();
            }
        }

        if (strlen($organInformation->getDutchDescription()) > 0) {
            return $organInformation->getDutchDescription();
        }

        if (strlen($organInformation->getShortDutchDescription()) > 0) {
            return $organInformation->getShortDutchDescription();
        }
    }

    return '';

}

?>
<?php if (!isset($breadcrumb)): // only show breadcrumbs if they were not yet shown ?>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="active">
                    <?php if (OrganTypes::Fraternity === $organ->getType()): ?>
                        <a href="<?= $this->url('home/fraternity_list') ?>">
                            <?= $this->translate('Fraternities') ?>
                        </a>
                    <?php elseif (OrganTypes::Committee === $organ->getType()): ?>
                        <a href="<?= $this->url('home/committee_list') ?>">
                            <?= $this->translate('Committees') ?>
                        </a>
                    <?php elseif (OrganTypes::AVC === $organ->getType()): ?>
                        <?= $this->translate('GMM Committees') ?>
                    <?php elseif (OrganTypes::AVW === $organ->getType()): ?>
                        <?= $this->translate('GMM Taskforces') ?>
                    <?php elseif (OrganTypes::KCC === $organ->getType()): ?>
                        <?= $this->translate('Financial Audit Committees') ?>
                    <?php elseif (OrganTypes::RvA === $organ->getType()): ?>
                        <?= $this->translate('Advisory Boards') ?>
                    <?php endif; ?>
                </li>
                <li class="active">
                    <?= $this->escapeHtml($organ->getName()) ?>
                </li>
            </ol>
        </div>
    </section>
<?php endif; ?>
<section class="section">
    <div class="container">
        <?php if (null !== $organInformation && null !== $organInformation->getCoverPath()): ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="organ-banner"
                         style="background-image: url('<?= $this->fileUrl($organInformation->getCoverPath()) ?>')">
                    </div>
                </div>
            </div>
            <br>
        <?php endif ?>
        <div class="row">
            <div class="col-md-8">
                <h1 class="h-wrap"><?= $organ->getName() ?></h1>
                <?php echo getOrganDescription($organInformation, $lang) ?>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?= $this->escapeHtml($organ->getAbbr()) ?></h3>
                    </div>
                    <div class="list-group">
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                <?= $this->translate('Foundation') ?>
                            </h4>
                            <p class="list-group-item-text text-muted">
                                <?= $this->dateFormat($organ->getFoundationDate(), IntlDateFormatter::LONG) ?>
                            </p>
                        </div>
                        <?php if ($organ->isAbrogated()): ?>
                            <div class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <?= $this->translate('Abrogation') ?>
                                </h4>
                                <p class="list-group-item-text text-muted">
                                    <?= $this->dateFormat($organ->getAbrogationDate(), IntlDateFormatter::LONG) ?>
                                </p>
                            </div>
                        <?php endif; ?>
                        <?php if ($this->acl('decision_service_acl')->isAllowed('organ', 'view') && null !== $organInformation): ?>
                            <div class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <?= $this->translate('Email') ?>
                                </h4>
                                <a class="list-group-item-text" href="mailto:<?= $organInformation->getEmail() ?>">
                                    <?= $this->escapeHtml($organInformation->getEmail()) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                        <?php if (null !== $organInformation && strlen($organInformation->getWebsite()) > 0): ?>
                            <div class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <?= $this->translate('Website') ?>
                                </h4>
                                <a class="list-group-item-text" href="<?= $organInformation->getWebsite() ?>" target="_blank">
                                    <?= $this->escapeHtml($organInformation->getWebsite()) ?>
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="panel panel-default agenda">
                    <div class="panel-heading">
                        <h3><?= $this->translate('Activities') ?></h3>
                    </div>
                    <div class="list-group">
                        <?php if (empty($activities)): ?>
                            <p class="list-group-item" href="#">
                                <span class="list-group-item-text text-muted">
                                    <?= $this->translate('No activities planned') ?>
                                </span>
                            </p>
                        <?php else: ?>
                            <?php foreach ($activities as $activity): ?>
                                <a class="list-group-item"
                                   href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">

                                    <h4 class="list-group-item-heading"><?= $this->localiseText($activity->getName()) ?></h4>
                                    <p class="list-group-item-text text-muted"><?= ucfirst($this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT)); ?></p>
                                </a>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="panel-footer">
                        <a href="<?= $this->url('activity') ?>" class="panel-footer__link">
                            <?= $this->translate('Complete agenda') ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php if ($this->acl('decision_service_acl')->isAllowed('organ', 'view')): ?>
                    <?php if (!$organ->isAbrogated()): ?>
                        <h1><?= $this->translate('Active members') ?></h1>
                        <ul>
                            <?php foreach ($activeMembers as $membership): ?>
                                <li>
                                    <a href="<?= $this->url(
                                        'member/view',
                                        ['lidnr' => $membership['member']->getLidnr()],
                                    ) ?>">
                                        <?= $membership['member']->getFullName() ?>
                                        <?php if (!empty($membership['functions'])): ?>
                                            (<?= implode(
                                                ', ',
                                                array_map(
                                                    fn (string $value): string => $this->translate($value),
                                                    $membership['functions'],
                                                ),
                                            ) ?>)
                                        <?php endif ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php else: ?>
                        <h1><?= $this->translate('Old members') ?></h1>
                        <ul>
                            <?php foreach ($oldMembers as $member): ?>
                                <li>
                                    <a href="<?= $this->url(
                                        'member/view',
                                        ['lidnr' => $member->getLidnr()],
                                    ) ?>">
                                        <?= $member->getFullName() ?>
                                    </a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    <?php endif; ?>
                <?php else: ?>
                    <?= $this->translate('Login to view more information') ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
