<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Company\Form\Job as JobForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var string $companySlugName
 * @var JobForm $form
 * @var bool $isCompany
 */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headTitle($this->translate('Add Job'));

$this->headScript()
    ->appendFile(
        $this->basepath('js/company-admin.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/job-create.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/ckeditor/ckeditor.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

if ('nl' === $lang) {
    $this->headScript()->appendFile(
        $this->basepath('js/ckeditor/translations/nl.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
}

$this->headLink()
    ->appendStylesheet($this->basepath('css/ckeditor/style.css'));

if ($isCompany) {
    // company_account/upload
    $uploadPath = '/company/upload';
} else {
    // company_admin/company/edit/upload
    $uploadPath = '/admin/career/company/edit/' . $companySlugName . '/upload';
}

$form->prepare();
$form->setAttribute('class', 'form-company');
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Add Job') ?></h1>
    </div>
</div>
<hr>
<?= $this->form()->openTag($form) ?>
<?= $this->partial(
    'partial/company/admin/editors/job.phtml',
    [
        'form' => $form,
    ],
) ?>
<div class="row">
    <div class="col-md-12">
        <?php
        $submit = $form->get('submit')
            ->setValue($this->translate('Add Job'))
            ->setAttribute('class', 'btn btn-primary pull-right');
        ?>
        <div class="form-group">
            <?= $this->formSubmit($submit) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    Company.Admin.updateForm();
    Job.updateAllLabels();
    $('label[for^="labels-"]').on('click', function () {
        Job.toggleLabel($(this).data('label-id'));
    });

    GEDITOR.MarkdownCompanyEditor
        .create(document.querySelector('#description-nl'), {
            language: '<?= $lang ?>',
            simpleUpload: {
                uploadUrl: '<?= $uploadPath ?>'
            }
        })
        .catch(error => {
            console.error(error);
        });

    GEDITOR.MarkdownCompanyEditor
        .create(document.querySelector('#description-en'), {
            language: '<?= $lang ?>',
            simpleUpload: {
                uploadUrl: '<?= $uploadPath ?>'
            }
        })
        .catch(error => {
            console.error(error);
        });
</script>
