<?php 
$form=$companyEditForm;
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<dl>
<?php $element = $form->get('startDate') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('expirationDate');?>
    <dt><?= $element->getOption('label'); ?></dt>
    <dd>
        <?= $this->formElement($element); ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('published') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php if ($type === 'banner'):
    $element = $form->get('banner')?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php endif;?>
<?php if ($type === 'featured'):?>
    <?php$element = $form->get('language')?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
    <?php$element = $form->get('article')?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php endif;?>

<?= $this->formRow($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
