<?php 
//use Company\Form\EditCompany as EditCompanyForm;
//$companyEditForm = new EditCompanyForm();
$form = $companyEditForm;
//$form = $this->form($companyEditForm);
?>
<h1> <?= $this->translate('Add Company'); ?> </h1>
<?= $this->form()->openTag($form) ?>
<?php echo $this->partial('partial/company/admin/editors/company.phtml', array(
    'form' => $form)); ?>
<?= $this->formRow($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
