<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Company\Form\Company as CompanyForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyForm $form
 */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headTitle($this->translate('Create Company'));

$this->headScript()
    ->appendFile(
        $this->basepath('js/company-admin.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    )
    ->appendFile(
        $this->basepath('js/ckeditor/ckeditor.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

if ('nl' === $lang) {
    $this->headScript()->appendFile(
        $this->basepath('js/ckeditor/translations/nl.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
}

$this->headLink()
    ->appendStylesheet($this->basepath('css/ckeditor/style.css'));

$form->prepare();
$form->setAttribute('class', 'form-company');
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Create Company') ?></h1>
    </div>
</div>
<hr>
<?= $this->form()->openTag($form) ?>
<?= $this->partial(
    'partial/company/admin/editors/company.phtml',
    [
        'form' => $form,
    ],
) ?>
<div class="row">
    <div class="col-md-12">
        <?php
        $submit = $form->get('submit')
            ->setValue($this->translate('Create Company'))
            ->setAttribute('class', 'btn btn-primary pull-right');
        ?>
        <div class="form-group">
            <?= $this->formSubmit($submit) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    Company.Admin.updateForm();

    GEDITOR.MarkdownCompanyEditor
        .create(document.querySelector('#description-nl'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });

    GEDITOR.MarkdownCompanyEditor
        .create(document.querySelector('#description-en'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });
</script>
