<?php
$this->headTitle($this->translate('Approve vacancy'));
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-markdown.min.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap-markdown.js')
    ->prependFile($this->basePath() . '/js/activity-create.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');

$form->setAttribute('class', 'form-horizontal');
$form->prepare();

?>

<?= $this->form()->openTag($form) ?>

<div class="row">
</div>
<?php foreach ($form->getLanguages() as $lang):
    $langDesc = $languages[$lang]
    ?>
    <div class="col-md-6">
        <h1><?= $this->translate($langDesc);?></h1>
        <?php
        $fieldset = $form->get('jobs')->get($lang);
        ?>
        <?php
        $element = $fieldset->get('id');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('active');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formCheckbox($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('name');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('slugName');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('description');
        $element->setAttribute('class', 'form-control form-control-dutch markdown-editor');
        $element->setAttribute('style', 'width:100%; height:10em; resize:none');
        $element->setAttribute('data-provide', 'markdown');
        ?>
        <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
            <label for="<?= $element->getAttribute('id') ?>" class="control-label col-sm-2" style="margin-top:10px">
            </label>
            <div class="col-sm-10">
                <?= $this->formRow($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('teaser');
        $element->setAttribute('style', 'width:100%; height:10em; resize:none');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formTextArea($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php
        $element = $fieldset->get('attachment_file');
        $element->setAttribute('style', 'width:100%; height:3em; resize:none');
        $element->setAttribute('class', 'form-control');
        ?>
        <div class="form-group <?= $this->bootstrapElementError($element) ?>">
            <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
                <?= $element->getOption('label') ?>
            </label>
            <div class="col-sm-10">
                <?= $this->formElement($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <?php if (isset($job) && !is_null($job->getAttachment())): ?>
            <div class="form-group">
                <label class="control-label col-sm-2">
                    <?= $this->translate('Current attachment') ?>
                </label>
                <div class="col-sm-10">
                    <a class="btn btn-default" href="<?= $this->fileUrl($job->getAttachment()); ?>">
                        <?= $this->translate('View attachment'); ?>
                    </a>
                </div>
            </div>

        <?php endif; ?>
    </div>
<?php endforeach; ?>
<div class="col-md-12">
    <br>
    <?php
    $element = $form->get('category');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('hours');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('sectors');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formElement($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('startingDate');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('contactName');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('phone');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('email');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <?php
    $element = $form->get('website');
    $element->setAttribute('class', 'form-control');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-1">
            <?= $element->getOption('label') ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php $element = $form->get('sendEmail');?>
    <div class="checkbox">
        <label>
            <?= $this->formCheckbox($element) ?>
            <?= $element->getOption('label') ?>
            <?= $this->formElementErrors($element) ?>

        </label>
    </div>

    <?php
    $submit = $form->get('submit');
    $submit->setLabel($this->translate('Accept'));
    $submit->setAttribute('class', 'btn btn-primary pull-right');
    ?>
    <div class="form-group">
        <?= $this->formButton($submit) ?>
        <button type="submit" class="btn btn-primary pull-right" name="reject">
            <?= $this->translate('Reject') ?>
        </button>
    </div>
</div>

<?php
$element = $form->get('labels');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formMultiCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
