<?php
$this->headTitle($this->translate('Approve profile'));
$this->headScript()
    ->prependFile($this->basePath() . '/js/company-admin.js');
$this->scriptUrl()->requireUrls(
    [
        'admin_company/editCompany/editPackage/deletePackage'
    ],
    ['slugCompanyName', 'packageId']
);

?>
<h1><?= $this->translate("Approve profile"); ?></h1>

<div class="row">
    <div class="col-md-6">
        <h2><?= $this->translate('Dutch logo') ?></h2>
        <?php $translation = $company->getTranslationFromLocale('nl'); ?>
        <?php if (!is_null($translation)): ?>
            <img class="img-responsive" src="<?= $this->fileUrl($company->getArrayCopy()['nl_logo']) ?>"/>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <h2><?= $this->translate('English logo') ?></h2>
        <?php $company->getTranslationFromLocale('en'); ?>
        <?php if (!is_null($translation)): ?>
            <img class="img-responsive" src="<?= $this->fileUrl($company->getArrayCopy()['en_logo']) ?>"/>
        <?php endif; ?>
    </div>
</div>
<hr>
<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>
<?php $element = $form->get('sendEmail');?>
<div class="checkbox">
    <label>
        <?= $this->formCheckbox($element) ?>
        <?= $element->getOption('label') ?>
        <?= $this->formElementErrors($element) ?>

    </label>
</div>
<?= $this->partial('partial/company/admin/editors/company.phtml',
    ['form' => $form]
); ?>
<br>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Accept'));
$submit->setAttribute('class', 'btn btn-primary pull-right');


?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
    <button type="submit" class="btn btn-primary pull-right" name="reject">
        <?= $this->translate('Reject') ?>
    </button>
</div>

<?php


?>

<?= $this->form()->closeTag(); ?>






