<?php
$this->headTitle($this->translate('Approval page'));

?>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped ">
            <thead>
            <tr>
                <th>
                    <?= $this->translate('Company name') ?>
                </th>
                <th>
                    <?= $this->translate('Approval type') ?>
                </th>
                <th>
                    <?= $this->translate('Approval status') ?>
                </th>
                <th>
                    <?= $this->translate('Actions') ?>
                </th>
            </tr>
            </thead>
            <tbody class="company-list">
                <?php foreach ($pendingApprovals as &$pendingApproval): ?>
                <tr>
                    <th>
                        <?= $pendingApproval->getCompany()->getName() ?>
                    </th>
                    <th>
                        <?php
                        if($pendingApproval->getType() === "vacancy"){
                            echo $this->translate("Vacancy, name: ") . $pendingApproval->getVacancyApproval()->getName();

                        }else if($pendingApproval->getType() === "banner"){
                            echo $this->translate("Banner");
                        }else if($pendingApproval->getType() === "profile"){
                            echo $this->translate("Profile");
                        }
                        ?>
                    </th>
                    <th>
                        <?php
                        if($pendingApproval->getStatus()){
                            echo $this->translate("Rejected");
                        }else{
                            echo $this->translate("Waiting for approval");
                        }

                        ?>
                    </th>
                    <th>
                        <?php
                        //values use to delete approval
                        $deleteValue = ["type" => $pendingApproval->getType(), "approvalId" => $pendingApproval->getId()];

                        $slugName = $pendingApproval->getCompany()->getSlugName();

                        if(!empty($pendingApproval->getVacancyApproval())) {
                            $vacancyApprovalId = $pendingApproval->getVacancyApproval()->getLanguageNeutralId();
                        }

                        $url = "/admin/company/";  //url to approval view page

                        //determing type and setup correct link and deletion values
                        if($pendingApproval->getType() === "profile") {
                            $url .= "approval-profile/" . $pendingApproval->getProfileApproval()->getId();
                            $deleteValue["companyId"] = $pendingApproval->getCompany()->getId();
                            $deleteValue["profileApprovalId"] = $pendingApproval->getProfileApproval()->getId();
                        }elseif($pendingApproval->getType() === "vacancy"){
                            $url .= "approval-vacancy/" . $vacancyApprovalId;
                            $deleteValue["packageId"] = $pendingApproval->getVacancyApproval()->getPackage()->getId();
                            $deleteValue["languageNeutralId"] = $pendingApproval->getVacancyApproval()->getLanguageNeutralId();
                        }elseif($pendingApproval->getType() == "banner"){
                            $url .= "approval-banner/" . $pendingApproval->getId();
                        }

                        $deleteValue = json_encode($deleteValue);   //convert deletion values to string

                        ?>
                        <form action='' method="post">
                        <button type="button" class="btn btn-primary btn-xs" onclick="location.href='<?= $url;  ?>';">
                            <?= $this->translate('View request') ?>
                        </button>
                        <button type="submit" class="btn btn-danger btn-xs" name="delete" value='<?= $deleteValue;?>'>
                            <?= $this->translate('Delete request') ?>
                        </button>
                        </form>
                    </th>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <th><?= $this->translate('Company name') ?></th>
                <th><?= $this->translate('Approval type') ?></th>
                <th><?= $this->translate('Approval status') ?></th>
                <th><?= $this->translate('Actions') ?></th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
