<?php
?>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped ">
            <thead>
            <tr>
                <th>
                    <?= $this->translate('Company name') ?>
                </th>
                <th>
                    <?= $this->translate('Approval type') ?>
                </th>
                <th>
                    <?= $this->translate('To content') ?>
                </th>
                <th>
                    <?= $this->translate('Actions') ?>
                </th>
            </tr>
            </thead>
            <tbody class="company-list">
            <tr>
                <th>
                    Phillips
                </th>
                <th>
                    Vacancy
                </th>
                <th>
                    link
                </th>
                <th>
                    <button type="button" class="btn btn-danger btn-xs">
                        <?= $this->translate('Approve') ?>
                    </button>

                    <button type="button" class="btn btn-danger btn-xs">
                        <?= $this->translate('Reject') ?>
                    </button>
                </th>

            </tr>


            </tbody>
            <tfoot>
            <tr>
                <th><?= $this->translate('Company name') ?></th>
                <th><?= $this->translate('Approval type') ?></th>
                <th><?= $this->translate('To content') ?></th>
                <th><?= $this->translate('Actions') ?></th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
