<?php $locale = $this->translator->getLocale(); ?>
<h1> <?=$this->translate("Delete");?> </h1>
<?=$this->translate("Do you really want to delete this packet? This will delete all containing Jobs. Instead, you can also disable the 'published' option of this packet to just hide it.");?>
<?php echo $packet->getId();
    //$this->partial('partial/company/company/list/company.phtml', 
    //array('islist' => false, 'company' => $company, 'locale' => $locale)); 
    ?>


 <form action="<?= $this->url('admin_company/editCompany/editPacket/deletePacket', array('slugCompanyName' => $slugName, 'packetID' => $packet->getId()))?>" method="post">
 <div>
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>

