<?php $locale = $this->translator->getLocale(); ?>
<h1> <?=$this->translate("Delete");?> </h1>
<?=$this->translate("Do you really want to delete this package? This will delete all containing Jobs. Instead, you can also disable the 'published' option of this package to just hide it.");?>
<?php echo $package->getId();
    ?>


 <form action="<?= $this->url('admin_company/editCompany/editPackage/deletePackage', array('slugCompanyName' => $slugName, 'packageID' => $package->getId()))?>" method="post">
 <div>
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>

