<?php $locale = $this->translator->getLocale(); ?>
<?php if (count($companies) != 1){
        echo $this->translate("Error: company not found");
        return;
    }
    else{
        $company = $companies[0];
    }
?>
<h1> <?=$this->translate("Delete");?> </h1>
<?=$this->translate("Do you really want to delete this company?");?>
<?=$this->partial('partial/company/company/list/company.phtml', 
    ['islist' => false, 'company' => $company, 'locale' => $locale]); ?>

 <form action="<?= $this->url('admin_company/deleteCompany', ['slugCompanyName' => $company->getSlugName()])?>" method="post">
 <div>
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>

