<div class="company-edit-editor">
<?php
if (!isset($company)){
        echo "Company not found";
}
else{ 
    if (isset($asciiJobName)){
        echo($this->partial('company/admin/editJob.phtml',array('asciiJobName'=>$asciiJobName)));
    } else{ 
        echo($this->partial('company/admin/editCompany.phtml',array('companyEditForm'=>$companyEditForm,'company'=>$company)));
    } 
} 

?>
    
</div>
