<?php 
//use Company\Form\EditCompany as EditCompanyForm;
//$companyEditForm = new EditCompanyForm();
$form=$companyEditForm;
//$form=$this->form($companyEditForm);
?>

<?= $this->form()->openTag($form) ?>
<dl>
<?php $element = $form->get('name') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

<?php $element = $form->get('address') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('website') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('description') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('logo') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('phone') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('email') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('slogan') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

</dl>

<?= $this->formRow($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>

<table class=joblist>

<?php if(!empty($joblist)){ foreach($joblist as $job){ ?>
<tr><td><?= $job->getName(); ?></td> 
    <td><a href="#id">delete</a></td>
</tr>
<?php } } else{ print("Empty");}?>
</table>
<br/>
<a href=<?= $this->url("admin_company/default", array("action"=>"addJob","asciiCompanyName"=>$company->getAsciiName()));?>>Add job</a>
