<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/company-admin.js');
$this->scriptUrl()->requireUrls(
    [
        'admin_company/editCompany/editPackage/deletePackage'
    ],
    ['slugCompanyName', 'packageId']
);
foreach ($categoryList as $category):?>
    <div class="row">
        <h1><?= $this->translate($category->getName());?></h1>
        <div class="col-md-12">
            <table class="table table-striped ">
                <thead>
                <tr>
                    <th>
                        <?= $this->translate('Company') ?>
                    </th>
                    <th>
                        <?= $this->translate('Vacancy name') ?>
                    </th>
                    <th>
                        <?= $this->translate('Starting date') ?>
                    </th>
                    <th>
                        <?= $this->translate('Expiration date') ?>
                    </th>
                    <th>
                        <?= $this->translate('Action') ?>
                    </th>
                </tr>
                </thead>
                <?php foreach ($highlightList as $highlight): ?>
                <?php if ($highlight['jobCategoryLnId'] == $category->getLanguageNeutralId()): ?>
                <tr>
                    <th>
                        <?= $highlight['name'] ?>
                    </th>
                    <th>
                        <?= $highlight['vacancy_name'] ?>
                    </th>
                    <th>
                        <?= $highlight['starts']->format('Y-m-d')  ?>
                    </th>
                    <th>
                        <?= $highlight['expires']->format('Y-m-d')  ?>
                    </th>

                    <th>
                        <a class="btn btn-xs btn-primary" href="<?= $this->url("admin_company/editCompany/editPackage",
                            [
                                "slugCompanyName" => $highlight['slugName'],
                                "packageId" => $highlight['id']
                            ]
                        ); ?>">
                            <?= $this->translate('edit'); ?></a>
                        <button type="button" class="btn btn-danger btn-xs"
                                onclick="Company.Admin.deletePackage('<?= $highlight['slugName'] ?>', '<?= $highlight['id'] ?>')"
                                data-toggle="modal"
                                data-target="#deleteModal">
                            <?= $this->translate('Delete') ?>
                        </button>
                    </th>
                </tr>
                <?php endif; ?>
                <?php endforeach;?>
            </table>
            <!-- Delete package modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
                        </div>
                        <div class="modal-body">
                            <p><?= $this->translate('Are you sure you want to delete this package?') ?> </p>
                            <p class="options">
                            </p>
                        </div>
                        <div class="modal-footer">
                            <form id="deleteForm" method="POST">
                                <input type="submit" name="submit" value="<?= $this->translate('Delete package') ?>"
                                       class="btn btn-danger"/>
                                <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>


