<?php 
$form = $companyEditForm;
if (is_null($company)){
    echo "Company not found";
    return;
}
?>
<h1> <?= $this->translate('Edit Company'); ?> </h1>
<div class="row">
    <div class="col-md-6">
        <h2><?= $this->translate('Dutch logo') ?></h2>
        <?php $translation = $company->getTranslationFromLocale('nl'); ?>
        <?php if (!is_null($translation)): ?>
            <img class="img-responsive" src="<?= $this->fileUrl($translation->getLogo()) ?>"/>
        <?php endif; ?>
    </div>
    <div class="col-md-6">
        <h2><?= $this->translate('English logo') ?></h2>
        <?php $translation = $company->getTranslationFromLocale('en'); ?>
        <?php if (!is_null($translation)): ?>
            <img class="img-responsive" src="<?= $this->fileUrl($translation->getLogo()) ?>"/>
        <?php endif; ?>
    </div>
</div>
<?php $form->prepare() ?>
<?= $this->form()->openTag($form) ?>
<?= $this->partial('partial/company/admin/editors/company.phtml', 
        ['form' => $form]
    ); ?>
<br>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
<?= $this->form()->closeTag(); ?>

<h2> <?= $this->translate('Packages') ?> </h2>
<table class="packagelist">
        <tr>
            <th>
                        <?= $this->translate('Package'); ?>
            </th>
            <th>
                        <?= $this->translate('Active'); ?>
            </th>
            <th>
                        <?= $this->translate('Jobs'); ?>
            </th>
        </tr>
    <?php if ($company->getNumberOfPackages() > 0) { 
        foreach($company->getPackages() as $package) { ?>
            <tr>
                <td>
                    <a href="<?= $this->url("admin_company/editCompany/editPackage",
                                            [
                                                  "slugCompanyName" => $company->getSlugName(),
                                                  "packageID" => $package->getId(),
                                            ]
                                           ); ?>">
                        <?= $this->translate('edit'); ?></a>
                    <a href="<?= $this->url("admin_company/editCompany/editPackage/deletePackage",
                                            [
                                                  "slugCompanyName" => $company->getSlugName(),
                                                  "packageID" => $package->getId(),
                                            ]
                                           ); ?>"> <?= $this->translate('delete'); ?></a>
                    </a>
                </td> 
                <td>
                    <?php echo $package->isActive() ? 'true' : 'false'?>
                </td>
                <td>
                    <?php if ($package->getType() === 'banner') {
                              echo $this->translate('Banner');
                          } else if ($package->getType() == 'featured'){
                              echo $this->translate('Featured Package');
                          } else {
                              echo count($package->getJobs()) ;
                          } ?>
                <td>
                </td>
            </tr>
    <?php 
        } 
    } else { print("Empty"); }
    ?>
</table>
<br/>
<a href="<?= $this->url("admin_company/editCompany/addPackage", 
                        ["type"          =>"job",
                         "slugCompanyName" => $company->getSlugName()]
                       ); ?>">
    <?= $this->translate('Add Job package'); ?>
</a>
<br/>
<a href="<?= $this->url("admin_company/editCompany/addPackage", 
                        ["type"          =>"featured",
                         "slugCompanyName" => $company->getSlugName()]
                       ); ?>">
    <?= $this->translate('Add featured package'); ?>
</a>
<br/>
<a href="<?= $this->url("admin_company/editCompany/addPackage",
                        ["type"          =>"banner",
                         "slugCompanyName" => $company->getSlugName()]
                       ); ?>">
    <?= $this->translate('Add Banner package'); ?>
</a>
