<?php
$form->setAttribute('class', 'form-horizontal');
$this->headScript()
    ->prependFile($this->basePath() . '/js/job-create.js');
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<div class="row">
<?php foreach($form->getLanguages() as $lang):
$langDesc = $languages[$lang]
?>
<div class="col-md-6">
<h1><?= $this->translate($langDesc);?></h1>
<?php
$fieldset = $form->get('jobs')->get($lang);
?>
<?php
$element = $fieldset->get('id');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('name');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('slugName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('website');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('category');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('description');
$element->setAttribute('style', 'width:100%; height:10em; resize:none');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formTextArea($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('active');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('contactName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('phone');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('email');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('attachment_file');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php if (isset($job) && !is_null($job->getAttachment())): ?>
<div class="form-group">
    <label class="control-label col-sm-2">
        <?= $this->translate('Current attachment') ?>
    </label>
    <div class="col-sm-10">
        <a class="btn btn-default" href="<?= $this->fileUrl($job->getAttachment()); ?>" >
            <?= $this->translate('View attachment'); ?>
        </a>
    </div>
</div>

<?php endif;?>
</div>
<?php endforeach;?>
</div>

<div class="row spacing-top--lg">
    <div class="col-md-12">
        <h3><?= $this->translate('Options') ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
        /* render template for labels */
        $fs = $form->get('labels')->getTemplateElement();
        ob_start();
        echo $this->partial('partial/company/admin/job-label.phtml', ['fs' => $fs, 'index' => '__index__']);
        $tpl = trim(ob_get_clean())
        ?>
        <fieldset id="additionalLabels">
            <span class="template" data-template="<?= $this->escapeHtmlAttr($tpl) ?>"></span>
            <?php
            $index = 0;
            foreach ($form->get('labels')->getIterator() as $fs) {
                echo $this->partial('partial/company/admin/job-label.phtml', ['fs' => $fs, 'index' => $index]);
                $index++;
            }
            ?>
            <div class="form-group add-option spacing-top--md">
                <button class="btn btn-success" type="button" onclick="return Job.addLabel()">
                    <span class="glyphicon glyphicon-plus"></span>
                    <?= $this->translate('Add a label') ?>
                </button>
            </div>
            <div class="form-group remove-option">
                <button class="btn btn-danger" type="button" onclick="return Job.removeLabel()">
                    <span class="glyphicon glyphicon-minus"></span>
                    <?= $this->translate('Remove the last label') ?>
                </button>
            </div>
        </fieldset>
    </div>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
<?= $this->form()->closeTag(); ?>
