<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<div class="row">
<?php foreach($form->getLanguages() as $lang):
$langDesc = $languages[$lang]
?>
<div class="col-md-6">
<h1><?= $this->translate($langDesc);?></h1>
<?php
$fieldset = $form->get('jobs')->get($lang);
?>
<?php
$element = $fieldset->get('id');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('name');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('slugName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('website');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('category');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('description');
$element->setAttribute('style', 'width:100%; height:10em; resize:none');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formTextArea($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('active');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('contactName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('phone');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('email');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('attachment_file');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php if (isset($job) && !is_null($job->getAttachment())): ?>
<div class="form-group">
    <label class="control-label col-sm-2">
        <?= $this->translate('Current attachment') ?>
    </label>
    <div class="col-sm-10">
        <a class="btn btn-default" href="<?= $this->fileUrl($job->getAttachment()); ?>" >
            <?= $this->translate('View attachment'); ?>
        </a>
    </div>
</div>

<?php endif;?>
</div>
<?php endforeach;?>
</div>

<?php
$element = $form->get('labels');
?>
<div class="form-group <?= $this->bootstrapElementError($element) ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formMultiCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
<?= $this->form()->closeTag(); ?>
