<?php
$this->headTitle($this->translate('Edit Company'));
$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Career'), true, $this->url('company_admin'))
    ->addBreadcrumb($company->getName(), true, $this->url(
        'company_admin/company/edit',
        [
            'companySlugName' => $company->getSlugName(),
        ],
    ));

$this->headScript()
    ->appendFile(
        $this->basePath() . '/js/company-create.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

$this->inlineScript()
    ->appendFile(
        $this->basePath() . '/js/company-admin.js',
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

$this->scriptUrl()->requireUrls(
    [
        'company_admin/company/edit/package/delete'
    ],
    ['companySlugName', 'packageId']
);

$form->prepare();
$form->setAttribute('class', 'form-company');
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= sprintf($this->translate('Edit %s'), $this->escapeHtml($company->getName())) ?></h1>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Packages') ?></h2>
    </div>
    <div class="col-md-12">
        <a class="btn btn-success" href="<?= $this->url(
            'company_admin/company/edit/package/add',
            [
                'type' => 'job',
                'companySlugName' => $company->getSlugName(),
            ],
        ); ?>">
            <span class="fas fa-plus"></span>
            <?= $this->translate('Add Job Package'); ?>
        </a>
        <a class="btn btn-success" href="<?= $this->url(
            'company_admin/company/edit/package/add',
            [
                'type' => 'featured',
                'companySlugName' => $company->getSlugName(),
            ],
        ); ?>">
            <span class="fas fa-asterisk"></span>
            <?= $this->translate('Add Spotlight Package'); ?>
        </a>
        <a class="btn btn-success" href="<?= $this->url(
            'company_admin/company/edit/package/add',
            [
                'type' => 'banner',
                'companySlugName' => $company->getSlugName(),
            ],
        ); ?>">
            <span class="fas fa-image"></span>
            <?= $this->translate('Add Banner Package'); ?>
        </a>
    </div>
    <?php
    if ($company->getPackages()->count() > 0):
    ?>
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>
                        <?= $this->translate('Contract Number') ?>
                    </th>
                    <th>
                        <?= $this->translate('Active'); ?>
                    </th>
                    <th>
                        <?= $this->translate('Start date'); ?>
                    </th>
                    <th>
                        <?= $this->translate('Expiration date'); ?>
                    </th>
                    <th>
                        <?= $this->translate('Jobs / Type'); ?>
                    </th>
                    <th>
                        <?= $this->translate('Actions'); ?>
                    </th>
                </tr>
                </thead>
                <?php foreach ($company->getPackages() as $package): ?>
                    <tr>
                        <td>
                            <?= $package->getContractNumber() ?? '-' ?>
                        </td>
                        <td>
                            <?= $package->isActive() ? $this->translate('Yes') : $this->translate('No') ?>
                        </td>
                        <td>
                            <?= $package->getStartingDate()->format('d-m-Y') ?>
                        </td>
                        <td>
                            <?= $package->getExpirationDate()->format('d-m-Y') ?>
                        </td>
                        <td>
                            <?php if ($package->getType() === 'banner') {
                                echo $this->translate('Banner Package');
                            } else {
                                if ($package->getType() == 'featured') {
                                    echo $this->translate('Featured Package');
                                } else {
                                    echo $package->getJobs()->count();
                                }
                            } ?>
                        </td>
                        <td>
                            <a class="btn btn-xs btn-primary" href="<?= $this->url(
                                'company_admin/company/edit/package/edit',
                                [
                                    'companySlugName' => $company->getSlugName(),
                                    'packageId' => $package->getId(),
                                ]
                            ); ?>">
                                <?= $this->translate('Edit'); ?></a>
                            <button type="button" class="btn btn-danger btn-xs delete-package"
                                    data-toggle="modal" data-target="#deleteModal"
                                    data-slug-name="<?= $company->getSlugName() ?>"
                                    data-package-id="<?= $package->getId() ?>">
                                <?= $this->translate('Delete') ?>
                            </button>

                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    <?php
    endif;
    ?>
</div>
<hr>
<?= $this->form()->openTag($form) ?>
<?= $this->partial(
    'partial/company/admin/editors/company.phtml',
    [
        'form' => $form,
        'companyLogo' => $company->getLogo(),
    ]
); ?>
<div class="row">
    <div class="col-md-12">
        <?php
        $submit = $form->get('submit')
            ->setValue($this->translate('Update Company'))
            ->setAttribute('class', 'btn btn-primary pull-right');
        ?>
        <div class="form-group">
            <?= $this->formSubmit($submit) ?>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
<!-- Delete package modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
            </div>
            <div class="modal-body">
                <p><?= $this->translate('Are you sure you want to delete this package?') ?> </p>
                <p class="options">
                </p>
            </div>
            <div class="modal-footer">
                <form id="deleteForm" method="POST">
                    <input type="submit" name="submit" value="<?= $this->translate('Delete package') ?>"
                           class="btn btn-danger"/>
                    <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                </form>

            </div>
        </div>
    </div>
</div>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    Company.updateForm();

    document.querySelectorAll('.delete-package').forEach(package => {
        package.addEventListener('click', e => {
            Company.Admin.deletePackage(e.target.dataset.slugName, e.target.dataset.packageId);
        });
    });
</script>
