<?php 
$form = $packageEditForm;
?>
<?php $form->prepare()?>
<?= $this->form()->openTag($form) ?>
<dl>
<?php $element = $form->get('id') ?>
    <?= $this->formElement($element) ?>
<?php $element = $form->get('startDate') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('expirationDate');?>
    <dt><?= $element->getOption('label'); ?></dt>
    <dd>
        <?= $this->formElement($element); ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php $element = $form->get('published') ?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>

<?php if ($type === 'banner'):
    $element = $form->get('banner')?>
        <img src=<?= $this->fileUrl($package->getImage()) ?>><?= $this->translate('Company Logo') ?></img>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php endif;?>
<?php if ($type === 'featured'):?>
    <?php$element = $form->get('language')?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
    <?php$element = $form->get('article')?>
    <dt><?= $element->getOption('label') ?></dt>
    <dd>
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element); ?>
    </dd>
<?php endif;?>

<?= $this->formRow($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>

<?php if ($type === 'job') { ?>
<h2> <?= $this->translate('Jobs') ?> </h2>
<table class="packagelist">
        <tr>
            <th>
                        <?= $this->translate('Job'); ?>
            </th>
            <th>
                        <?= $this->translate('Active'); ?>
            </th>
        </tr>

    <?php if (!empty($package->getJobs())) { 
        foreach($package->getJobs() as $job) { ?>
            <tr>
                <td>
                    <a href="<?= $this->url("admin_company/editCompany/editPackage/editJob",
                                            [
                                                  "slugCompanyName" => $companyName,
                                                  "packageID" => $package->getId(),
                                                  "jobName" => $job->getSlugName(),
                                            ]
                                           ); ?>">
                        <?= $this->translate('edit'); ?></a>
                </td> 
                <td>
                    <?php echo $job->isActive() ? 'true' : 'false'?>
                </td>
            </tr>
    <?php 
        } 
    } else { print("Empty"); }
    ?>
</table>
<br/>
<a href="<?= $this->url("admin_company/editCompany/editPackage/addJob", 
    ["slugCompanyName" => $companyName, 'packageID' => $package->getId()]); ?>">
    <?= $this->translate('Add job'); ?>
</a>
<?php }?>
