<?php
    $this->headScript()->prependFile($this->basePath() . '/js/company-admin.js');
    $this->scriptUrl()->requireUrls(
        ['admin_company/deleteCompany'],
        ['slugCompanyName']
    );
?>
<?php if (array_sum(array_map("count", $packageFuture)) != 0):?>
<div class="row">
    <div class="col-md-9">
    <?php endif ?>

        <div class="row">
            <div class="col-md-10">
                <div class="form-group">
                    <input type="text" class="form-control" onkeyup="Company.Admin.filterCompanies()" id="filterCompanies" placeholder="Filter...">
                </div>
            </div>
            <div class="col-md-2">
                <a class="btn btn-success" href=<?=$this->url('admin_company/default', ['action' => 'addCompany'])?>>
                    <span class="glyphicon glyphicon-plus"></span><?=$this->translate('Add Company');?>
                </a>
            </div>
        </div>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        <?= $this->translate('Name') ?>
                        <a onclick="Company.Admin.sortCompaniesByName(1)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByName(-1)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Jobs') ?>
                        <a onclick="Company.Admin.sortCompaniesByColumn(1, 1)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByColumn(-1, 1)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Active jobs') ?>
                        <a onclick="Company.Admin.sortCompaniesByColumn(1, 2)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByColumn(-1, 2)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Banner active') ?>
                        <a onclick="Company.Admin.sortCompaniesByColumn(1, 3)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByColumn(-1, 3)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Featured in language') ?>
                        <a onclick="Company.Admin.sortCompaniesByColumn(1, 4)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByColumn(-1, 4)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Expired packages') ?>
                        <a onclick="Company.Admin.sortCompaniesByColumn(1, 5)"><span class="glyphicon glyphicon-arrow-up"></span></a>
                        <a onclick="Company.Admin.sortCompaniesByColumn(-1, 5)"><span class="glyphicon glyphicon-arrow-down"></span></a>
                    </th>
                    <th>
                        <?= $this->translate('Actions') ?>
                    </th>
                </tr>
            </thead>
            <tbody class="company-list">
                <?php
                    foreach ($companyList as $company):
                        $editUrl = $this->url('admin_company/editCompany',
                        ['slugCompanyName' => $company->getSlugName()]);
                   ?>
                   <tr class="company-list-item
                       <?= $company->getHidden() ? ' danger' : '' ?>
                       <?= $company->getNumberOfExpiredPackages() > 0 ? ' warning' : '' ?>">
                       <td class="company-name"><a href=<?= $editUrl; ?>><?= $company->getName(); ?></a></td>
                       <td><?= $company->getNumberOfJobs(); ?></td>
                       <td><?= $company->getNumberOfActiveJobs(); ?></td>
                       <td><?= $company->isBannerActive() ? $this->translate('Yes') : $this->translate('No'); ?></td>
                       <td><?php $languages = $company->getFeaturedLanguages(); echo $languages ? implode(' ' . $this->translate('and') . ' ', $languages) : $this->translate('none'); ?></td>
                       <td><?= $company->getNumberOfExpiredPackages(); ?></td>
                       <td>
                           <button type="button" class="btn btn-danger btn-xs"
                                                 onclick="Company.Admin.deleteCompany('<?= $company->getSlugName() ?>')"
                                                 data-toggle="modal"
                                                 data-target="#deleteModal">
                               <?= $this->translate('Delete') ?>
                           </button>
                       </td>
                   </tr>
                   <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                    <th><?= $this->translate('Name') ?></th>
                    <th><?= $this->translate('Jobs') ?></th>
                    <th><?= $this->translate('Active jobs') ?></th>
                    <th><?= $this->translate('Banner active') ?></th>
                    <th><?= $this->translate('Featured in language') ?></th>
                    <th><?= $this->translate('Expired packages') ?></th>
                    <th><?= $this->translate('Actions') ?></th>
                </tr>
            </tfoot>
        </table>

        <!-- Delete company modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                                                                 aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
                    </div>
                    <div class="modal-body">
                        <p><?= sprintf($this->translate('Are you sure you want to delete %s?'),
                        '<strong id="deleteCompanyName"></strong>') ?> </p>
                        <p class="options">
                        </p>
                    </div>
                    <div class="modal-footer">
                        <form id="deleteForm" method="POST">
                            <input type="submit" name="submit" value="<?= $this->translate('Delete company') ?>"
                                                               class="btn btn-danger"/>
                                                               <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

<?php if (array_sum(array_map("count", $packageFuture)) != 0):?>
    </div>
    <div class="col-md-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <?= $this->translate("Package changes next month") ?>
            </div>
            <div class="panel-body">
                <?php foreach ($packageFuture[0] as $package): ?>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <?= $package->getCompany()->getName() ?>
                        </div>
                        <div class="panel-body">
                        <?php
                        $type = $package->getType();
                            switch ($type){
                                case "banner":
                                    $packageType = $this->translate("Banner Package");
                                    break;
                                case "featured":
                                    $packageType = $this->translate("Featured Package");
                                    break;
                                case "job":
                                    $packageType = sprintf($this->translate("Job Package(%s active)"), $package->getNumberOfActiveJobs());
                                    break;
                            }
                            $company = $package->getCompany();
                            $companySlugName = $company->getSlugName();
                            $companyName = $company->getName();
                        ?>
                        <?= sprintf(
                            $this->translate("%s for company %s will start at %s"),
                            "<a href='" . $this->url('admin_company/editCompany/editPackage', ['slugCompanyName' => $companySlugName, 'packageID' => $package->getId()]) . "'> " . $packageType . "</a>",
                            "<a href=" . $this->url('admin_company/editCompany', ['slugCompanyName' => $companySlugName]) . ">" . $companyName . "</a>",
                            $package->getStartingDate()->format("l d M"))
                        ?>
                        </div>
                    </div>
                <?php endforeach ?>
                <?php foreach ($packageFuture[1] as $package): ?>
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <?= $package->getCompany()->getName() ?>
                        </div>
                        <div class="panel-body">
                        <?php
                        $type = $package->getType();
                            switch ($type){
                                case "banner":
                                    $packageType = $this->translate("Banner Package");
                                    break;
                                case "featured":
                                    $packageType = $this->translate("Featured Package");
                                    break;
                                case "job":
                                    $packageType = sprintf($this->translate("Job Package(%s active)"), $package->getNumberOfActiveJobs());
                                    break;
                            }
                            $company = $package->getCompany();
                            $companySlugName = $company->getSlugName();
                            $companyName = $company->getName();
                        ?>
                        <?= sprintf(
                            $this->translate("%s for company %s will expire at %s"),
                            "<a href='" . $this->url('admin_company/editCompany/editPackage', ['slugCompanyName' => $companySlugName, 'packageID' => $package->getId()]) . "'> " . $packageType . "</a>",
                            "<a href=" . $this->url('admin_company/editCompany', ['slugCompanyName' => $companySlugName]) . ">" . $companyName . "</a>",
                            $package->getExpirationDate()->format("l d M"))
                        ?>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</div>
<?php endif ?>

