<?php $organInformation = $organ->getApprovedOrganInformation() ?>
<div class="col-md-3">
    <a href="<?= $this->url('home/organ', ['abbr' => $organ->getAbbr(), 'type' => $organ->getType()])?>">
        <div class="card">
            <div class="card-image">
            <?php if (!is_null($organInformation) && !is_null($organInformation->getThumbnailPath())): ?>
                <img class="img-responsive" src="<?= $this->fileUrl($organInformation->getThumbnailPath()) ?>">
            <?php endif ?>
                    <span class="card-title"><?= $organ->getAbbr() ?></span>
                <div class="card-details">
                    <?php if (!is_null($organInformation)): ?>
                        <?= $lang === 'en' ? $organInformation->getShortEnglishDescription() : $organInformation->getShortDutchDescription() ?>
                    <?php endif;?>
                </div>
            </div><!-- card image -->

            <div class="card-content">
                <span><?= $organ->getName() ?>
                        <?php if (!is_null($organInformation) && $this->acl('decision_acl')->isAllowed('organ', 'view')): ?>
                            <a href="mailto:<?= $organInformation->getEmail() ?>" class="pull-right">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </a> &nbsp;
                        <?php endif; ?>
                        <?php if (!is_null($organInformation) && strlen($organInformation->getWebsite()) > 0): ?>
                            <a href="<?= $organInformation->getWebsite() ?>" class="pull-right">
                                <span class="glyphicon glyphicon-link"></span>
                            </a>
                        <?php endif; ?>
                </span>
            </div><!-- card content -->

        </div>
    </a>
</div>