<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Model\Organ as OrganModel;
use Decision\Service\AclService as DecisionAclService;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var string $lang
 * @var OrganModel $organ
 */

$organInformation = $organ->getApprovedOrganInformation()
?>
<div class="card">
    <a href="<?= $this->url(
        'home/organ',
        [
            'abbr' => $organ->getAbbr(),
            'type' => $organ->getType()->value,
        ],
    ) ?>" class="stretched-link"></a>
    <?php if (null !== $organInformation && null !== $organInformation->getThumbnailPath()): ?>
        <img class="card-image" src="<?= $this->fileUrl($organInformation->getThumbnailPath()) ?>" alt="">
    <?php else: ?>
        <img class="carg-image" src="/img/missing_cover.svg" alt="">
    <?php endif ?>
    <div class="card-body">
        <h5 class="card-title"><?= $this->escapeHtml($organ->getAbbr()) ?></h5>
        <h6 class="card-subtitle text-muted"><?= $this->escapeHtml($organ->getName()) ?></h6>
        <p class="card-text">
            <?php if (null !== $organInformation): ?>
                <?= $this->escapeHtml($lang === 'en' ? $organInformation->getShortEnglishDescription() : $organInformation->getShortDutchDescription()) ?>
            <?php endif; ?>
        </p>
    </div>
    <?php if (null !== $organInformation): ?>
        <div class="card-footer text-muted">
            <hr>
            <?php if ($this->acl(DecisionAclService::class)->isAllowed('organ', 'view')): ?>
                <span class="fas fa-envelope"></span>
            <?php endif; ?>
            <?php if (strlen($organInformation->getWebsite()) > 0): ?>
                <span class="fas fa-globe"></span>
            <?php endif; ?>
            <!-- TODO: GH-1907 -->
        </div>
    <?php endif; ?>
</div>
