<?php
$totalVotes = 0;
foreach ($poll->getOptions() as $option) {
    $totalVotes += $option->getVotesCount();
}

$percentages = [];
foreach ($poll->getOptions() as $option) {
    if ($totalVotes > 0) {
        $percentages[$option->getId()] = round($option->getVotesCount() / $totalVotes * 100);
    } else {
        $percentages[$option->getId()] = 0;
    }
}
$lang = $this->plugin('translate')->getTranslator()->getLocale();
?>
<p><em><?= ($lang === 'en') ? $poll->getEnglishQuestion() : $this->poll->getDutchQuestion() ?></em></p>
<form action="<?= $this->url('poll/vote', ['poll_id' => $poll->getId()]) ?>" method="post" class="form-horizontal">
    <?php foreach ($this->poll->getOptions() as $option): ?>
        <div class="form-group">
            <div class="col-md-6">
                <?php if ($canVote): ?>
                <div class="radio">
                    <label>
                        <input type="radio" value="<?= $option->getId() ?>" name="option" />
                        <?php endif; ?>
                        <?php $voted = !is_null($userVote) && $option->getId() === $userVote->getPollOption()->getId(); ?>
                        <?= $voted ? '<strong>' : '' ?>
                        <?= $this->escapeHtml(($lang === 'en') ? $option->getEnglishText() : $option->getDutchText()) ?>
                        <?= $voted ? '</strong>' : '' ?>
                        <?php if ($canVote): ?>
                    </label>
                </div>
                <?php endif; ?>
            </div>

            <?php if($showResults || !$canVote): ?>
            <div class="col-md-5">
                <div class="progress">
                    <div class="progress-bar poll-bar" role="progressbar"
                         aria-valuenow="<?= $percentages[$option->getId()] ?>"
                         aria-valuemin="0" aria-valuemax="100"
                         style="min-width: 2em; width: <?= $percentages[$option->getId()] ?>%;">
                        <?= $percentages[$option->getId()] ?>%
                    </div>
                </div>
            </div>
            <div class="col-md-1 text-right">
                <?= sprintf($this->translate($option->getVotesCount() === 1 ? '1 vote' :'%d votes'), $option->getVotesCount()) ?>
            </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    <div class="form-group">
        <div class="col-md-12">
            <?php if ($canVote): ?>
                <button type="submit" class="btn btn-large btn-primary">Vote</button>
            <?php endif; ?>
        </div>
    </div>
</form>
