<h4><?= ($this->lang === 'en') ? $poll->getEnglishQuestion() : $this->poll->getDutchQuestion() ?></h4>
<form action="<?= $this->url('poll/vote', array('poll_id' => $poll->getId())) ?>" method="post">
<?php foreach ($this->poll->getOptions() as $option): ?>
    <div class="row">
        <div class="col-md-5">
            <?php if ($canVote): ?>
            <div class="radio">
                <label>

                    <input type="radio" value="<?= $option->getId() ?>" name="option"/>
                    <?php endif; ?>
                    <strong>
                        <?= ($this->lang === 'en') ? $option->getEnglishText() : $option->getDutchText() ?>
                    </strong>
                    <?php if ($canVote): ?>
                </label>
            </div>
        <?php endif; ?>
        </div>
        <div class="col-md-6">
            <div class="progress">
                <div class="progress-bar poll-bar" role="progressbar"
                     aria-valuenow="<?= $this->percentages[$option->getId()] ?>"
                     aria-valuemin="0" aria-valuemax="100"
                     style="min-width: 2em; width: <?= $this->percentages[$option->getId()] ?>%;">
                    <?= $this->percentages[$option->getId()] ?>%
                </div>
            </div>
        </div>
        <div class="col-md-1">
            <span class="pull-right"><?= sprintf($this->translate('%d votes'), $option->getVotesCount()) ?></span>
        </div>
    </div>
<?php endforeach; ?>
<p>
    <button type="submit" class="btn btn-large btn-success">Vote</button>
</p>
</form>