<h3><?= $this->translate('Photos') ?></h3>

<div class="photo-grid">
    <div class="grid-sizer"></div>
    <div class="gutter-sizer"></div>
    <?php foreach($this->tags as $tag): ?>
            <div class="photo-grid-item photo-grid-item-photo">
                <a href="<?= $this->url('photo/photo', ['photo_id' => $item->getId()]); ?>">
                    <?php
                    $image = $tag->getPhoto()->getSmallThumbPath();
                    $size = getimagesize('public/data/' . $image);
                    ?>
                    <img data-width="<?= $size[0] ?>" data-height="<?= $size[1] ?>" src="<?= $this->fileUrl($tag->getPhoto()->getSmallThumbPath()) ?>">
                </a>
            </div>
    <?php endforeach; ?>
</div>
