<h3><?= $this->translate('Photos') ?></h3>

<div class="row">
    <?php foreach($this->tags as $tag): ?>
    <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <a class="thumbnail" href="<?= $this->url('photo/photo', array('photo_id' => $tag->getPhoto()->getId())); ?>">
            <img class="img-responsive" src="<?= $this->basePath() . $this->basedir . '/' . $tag->getPhoto()->getSmallThumbPath() ?>" alt="">
        </a>
    </div>
    <?php endforeach; ?>
</div>