<div class="option spacing-top--sm" id="additionalOption<?= $this->index ?>">
    <div class="row">
        <div class="col-md-3">
            <?php $inputType = $this->fs->get('label')
                ->setAttribute('class', 'form-control')
                ->setAttribute('id', 'type-field-' . $this->index);
            ?>
            <div class="form-group <?= $this->bootstrapElementError($inputType) ?>">
                <label for="<?= $inputType->getAttribute('id') ?>" class="control-label label-required">
                    <?= $this->translate('Label') ?>
                </label>
                <?= $this->formSelect($inputType) ?>
                <?= $this->formElementErrors($inputType) ?>
            </div>
        </div>
    </div>
    <hr/>
</div>
