<?php

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\ApiAppAuthorisation as ApiAppAuthorisationForm;
use User\Model\Enums\JWTClaims;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ApiAppAuthorisationForm $form
 * @var JWTClaims[] $claims
 */

$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'pull-right');
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 col-md-7 col-md-offset-2 col-lg-6 col-lg-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>
                            <?= sprintf(
                                $this->translate('Authorize %s to use your account?'),
                                $this->escapeHtml($this->app),
                            ) ?>
                        </h3>
                    </div>
                    <div class="panel-body">
                        <?php if ($this->remind): ?>
                            <p>
                                <?= sprintf(
                                    $this->translate('It has been more than 90 days since you last used <strong>%s</strong>. As a reminder, the application has access to:'),
                                    $this->escapeHtml($this->app),
                                ) ?>
                            </p>
                        <?php else: ?>
                            <p><?= $this->translate('The application will get the following information:') ?></p>
                        <?php endif; ?>
                        <ul>
                            <?php foreach ($claims as $claim): ?>
                                <li><?= $claim->getName($this->plugin('translate')->getTranslator()) ?></li>
                            <?php endforeach; ?>
                        </ul>
                        <?= $this->form()->openTag($form); ?>
                        <?php if (!$this->remind): ?>
                            <?= $this->formSubmit($form->get('cancel')); ?>
                            <?= $this->formSubmit($form->get('authorise')); ?>
                        <?php else: ?>
                            <?= $this->formSubmit($form->get('continue')); ?>
                        <?php endif; ?>
                        <?= $this->formElement($form->get('security')) ?>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
