<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('GEWIS Website'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Raleway:700,400,300')
                        ->prependStylesheet($this->basePath() . '/css/gewis-theme.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath() . '/js/url-helper.js')
        ; ?>

    </head>
    <body>
<?php
function isActive($view, array $condition)
{
    $viewModel = current($view->viewModel()->getCurrent()->getChildren());
    $script = explode('/', $viewModel->getTemplate());
    foreach ($condition as $key => $cond) {
        if (null !== $cond && $script[$key] != $cond) {
            return false;
        }
    }
    return true;
}
function getIsActiveClass($view, array $condition)
{
    return isActive($view, $condition) ? 'active' : '';
}
?>
        <nav class="navbar navbar-gewis navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">
                        <!-- TODO: Replace with SVG -->
                        <img src="<?= $this->basePath() ?>/img/logo-header.png" alt="GEWIS Logo">
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <!-- TODO: Fix "association" active class -->
                        <li class="hidden-sm <?= getIsActiveClass($this, ['vereniging']) ?>"><a href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>"><?= $this->translate('Association') ?></a></li>
                        <li class="hidden-xs hidden-md hidden-lg dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <?= $this->translate('Association') ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>"><?= $this->translate('Association') ?></a></li>
                                <li><a href="<?= $this->url('activity') ?>"><?= $this->translate('Activities') ?></a></li>
                                <li><a href="<?= $this->url('photo') ?>"><?= $this->translate('Photos') ?></a></li>
                                <?php if (null !== $this->identity()): ?>
                                    <li><a href="<?= $this->url('decision') ?>"><?= $this->translate('Members') ?></a></li>
                                <?php endif ?>
                            </ul>
                        </li>
                        <li class="<?= getIsActiveClass($this, ['company']) ?>"><a href="<?= $this->url('company') ?>"><?= $this->translate('Companies') ?></a></li>
                        <li class="<?= getIsActiveClass($this, ['education']) ?>"><a href="<?= $this->url('education') ?>"><?= $this->translate('Education') ?></a></li>
                        <li class="hidden-sm <?= getIsActiveClass($this, ['activity']) ?>"><a href="<?= $this->url('activity') ?>"><?= $this->translate('Activities') ?></a></li>
                        <li class="hidden-sm <?= getIsActiveClass($this, ['photo']) ?>"><a href="<?= $this->url('photo') ?>"><?= $this->translate('Photos') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if (null === $this->identity()): ?>
                            <li class="dropdown">
                                <a href="<?= $this->url('user') ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= $this->translate('Login') ?></a>
                                <div class="dropdown-menu dropdown-login">
                                    <form action="#" method="post">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Lidnummer of email adres">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control" placeholder="Wachtwoord">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                                    </form>
                                </div>
                            </li>
                        <?php else: ?>
                            <li class="hidden-sm <?= getIsActiveClass($this, ['decision']) ?>"><a href="#"><?= $this->translate('Members') ?></a></li>
                            <?php $member = $this->identity()->getMember() ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="visible-lg-inline"><?= $this->translate('Signed in as') ?> </span><?= $member->getFirstName() ?>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?= $this->url('member') ?>"><?= $this->translate('My information') ?></a></li>
                                    <li><a href="#">SuSOS</a></li>
                                    <li><a href="<?= $this->url('user/default', [
                                        'action' => 'logout'
                                        ]) ?>"><?= $this->translate('Logout') ?></a></li>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="content-container">
            <?php echo $this->content; ?>
        </div>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2 col-md-1">
                        <img src="<?= $this->basePath() ?>/img/logo-footer.png"/>
                    </div>
                    <div class="col-sm-10 col-md-7">
                        <div class="row">
                            <div class="col-sm-12">
                                <p>&copy; 2013
                                    - <?php echo date('Y') ?> <?= $this->translate("by WebCommissie GEWIS.") ?> <?php echo $this->translate('All rights reserved.') ?></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <h3>Bezoekadres</h3>
                                <address>
                                    Studievereniging GEWIS<br>
                                    MF 3.155<br>
                                    De Groene Loper 5<br>
                                    5612 AZ Eindhoven<br>
                                    Nederland
                                </address>
                            </div>
                            <div class="col-sm-4">
                                <h3>Postadres</h3>
                                <address>
                                    Studievereniging GEWIS<br>
                                    MF 3.155<br>
                                    Postbus 513<br>
                                    5600 MB Eindhoven<br>
                                    Nederland
                                </address>
                            </div>
                            <div class="col-sm-4">
                                <i class="glyphicon glyphicon-earphone"></i> <a href="tel:+31402472815">+31 (0)40 247 2815</a><br>
                                <i class="glyphicon glyphicon-envelope"></i> <a href="mailto:bestuur@gewis.nl">bestuur@gewis.nl</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
        <script>
            <?php foreach($this->scriptUrl()->getUrls() as $name => $url): ?>
            URLHelper.addUrl('<?= $name ?>', '<?= urldecode($url) ?>');
            <?php endforeach; ?>
        </script>
    </body>
</html>
