<div class="row">
    <div class="col-lg-12">
        <h1><?= $this->translate('Photo admin') ?></h1><hr>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">

                <a class="thumbnail" href="/photo/view/54">
                    <img class="img-responsive" src="/data/photo/1b/a05e12b96e2df74ef39984f04097d14e8dece4.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/55">
                    <img class="img-responsive" src="/data/photo/74/0ccbd6c74680ae1dcfdf7ec093b8c9f874499d.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/56">
                    <img class="img-responsive" src="/data/photo/69/9d8f50453bb8c0a489ad8b6ff1e6845bc87f77.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/57">
                    <img class="img-responsive" src="/data/photo/bb/ec39ea06147060040ee5d029a2a00ea7c8f833.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/58">
                    <img class="img-responsive" src="/data/photo/fb/c60c4d7e3bb30a73fe0ae0519d085c3594493f.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/59">
                    <img class="img-responsive" src="/data/photo/ba/ec8e046d3b4924aae1d2df75e42ed318489ac4.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/60">
                    <img class="img-responsive" src="/data/photo/e9/daa6fe97caa75e65b80c71e99ca4469d981905.jpg" alt="">
                </a>

                <a class="thumbnail" href="/photo/view/61">
                    <img class="img-responsive" src="/data/photo/22/157d65ba2016f7e4ee66ca74377eba30c4f49c.jpg" alt="">
                </a>




            </div>
        </div>
    </div>

    <div class="col-lg-9">
        <ol class="breadcrumb">
            <li><a href="#">2014-2015</a></li>
            <li><a href="#">Test album #2</a></li>
            <li><a>Super awesome sub album #4</a></li>
            <li class="active">Photo #59</li>
        </ol>
        <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span>&nbsp;<?= $this->translate('Modify details') ?></button> 
        <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;<?= $this->translate('Move photo') ?></button> 
        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span>&nbsp;<?= $this->translate('Delete photo') ?></button>

        <hr>

        <img class="img-responsive" src="/data/photo/74/0ccbd6c74680ae1dcfdf7ec093b8c9f874499d.jpg" alt="">
        <row>
            <div class="col-lg-6">
                <h4>Metadata</h4>
                <table class="table table-condensed">
                <tbody><tr><td>Artist</td><td>GEFLITST</td></tr>
                    <tr><td>Camera</td><td>NIKON D40</td></tr>
                    <tr><td>Date/time</td><td>2015-01-01 01:01:14</td></tr>
                    <tr><td>Flash</td><td>Nee</td></tr>
                    <tr><td>Focal length</td><td>31</td></tr>
                    <tr><td>Exposure time</td><td>0</td></tr>
                    <tr><td>Shutter speed</td><td>1/160</td></tr>
                    <tr><td>Aperture</td><td>f/2.8</td></tr>
                    <tr><td>ISO</td><td>900</td></tr>
                    </tbody>
            </table>
            </div>
            
            <div class="col-lg-6">
                <h4>Tags</h4>
            </div>
        </row>
    </div>
</div>