<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\Album as AlbumModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool|null $admin
 * @var AlbumModel[] $albums
 * @var array $config
 * @var string|null $prompt
 */

$admin = $admin ?? null;
$prompt = $prompt ?? null;
?>
<div class="card-grid <?= $admin ? 'admin-grid' : '' ?>">
    <?php foreach ($albums as $album): ?>
        <?php if ($album->getPhotoCount() > 0 || $admin): ?>
            <?= $this->partial('partial/album-card.phtml', ['album' => $album, 'admin' => $admin, 'config' => $config, 'prompt' => $prompt]) ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
