<?php if($this->acl('photo_acl')->isAllowed('photo', 'view_metadata')): ?>

<div style="font-size: 22px;">
<?= is_null($this->photo->getArtist()) ? $this->translate("Unknown") : $this->escapeHtmlAttr($this->photo->getArtist()) ?>
</div>
<?= $this->photo->getDateTime()->format('Y-m-d H:i:s'); ?>

<table class="table table-condensed">
    <tbody>
    <tr>
        <td colspan="2"><?= $this->translate('Camera') ?></td>
        <td>
            <span class="icon icon-camera" style="font-size: 18px">
                <?= is_null($this->photo->getCamera()) ? $this->translate("Unknown") : $this->escapeHtmlAttr($this->photo->getCamera()) ?>
            </span>
        </td>
    </tr>
    <tr>
        <td><?= $this->translate('Flash') ?></td>
        <td><?= $this->photo->getFlash() ? $this->translate('Yes') : $this->translate('No') ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('Focal length') ?></td>
        <td><?= is_null($this->photo->getFocalLength()) ? $this->translate("Unknown") : $this->photo->getFocalLength() ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('Exposure time') ?></td>
        <td><?= is_null($this->photo->getExposureTime()) ? $this->translate("Unknown") : $this->photo->getExposureTime() ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('Shutter speed') ?></td>
        <td><?= is_null($this->photo->getShutterSpeed()) ? $this->translate("Unknown") : $this->photo->getShutterSpeed() ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('Aperture') ?></td>
        <td><?= is_null($this->photo->getAperture()) ? $this->translate("Unknown") : $this->photo->getAperture() ?></td>
    </tr>
    <tr>
        <td><?= $this->translate('ISO') ?></td>
        <td><?= is_null($this->photo->getIso()) ? $this->translate("Unknown") : $this->photo->getIso() ?></td>
    </tr>
    </tbody>
</table>
<?php endif; ?>