<?php if($this->acl('photo_acl')->isAllowed('photo', 'view_metadata')): ?>
<table class="table table-condensed">
    <tbody>
    <tr>
        <td>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <?= $this->translate('Artist') ?>
        </td>
        <td><?= is_null($this->photo->getArtist()) ? $this->translate("Unknown") : $this->escapeHtmlAttr($this->photo->getArtist()) ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
            <?= $this->translate('Camera') ?>
        </td>
        <td><?= is_null($this->photo->getCamera()) ? $this->translate("Unknown") : $this->escapeHtmlAttr($this->photo->getCamera()) ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
            <?= $this->translate('Date/time') ?>
        </td>
        <td><?= $this->photo->getDateTime()->format('Y-m-d H:i:s'); ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
            <?= $this->translate('Flash') ?>
        </td>
        <td><?= $this->photo->getFlash() ? $this->translate('Yes') : $this->translate('No') ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            <?= $this->translate('Focal length') ?>
        </td>
        <td><?= is_null($this->photo->getFocalLength()) ? $this->translate("Unknown") : $this->photo->getFocalLength() ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-adjust" aria-hidden="true"></span>
            <?= $this->translate('Exposure time') ?>
        </td>
        <td><?= is_null($this->photo->getExposureTime()) ? $this->translate("Unknown") : $this->photo->getExposureTime() ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            <?= $this->translate('Shutter speed') ?>
        </td>
        <td><?= is_null($this->photo->getShutterSpeed()) ? $this->translate("Unknown") : $this->photo->getShutterSpeed() ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            <?= $this->translate('Aperture') ?>
        </td>
        <td><?= is_null($this->photo->getAperture()) ? $this->translate("Unknown") : $this->photo->getAperture() ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-sunglasses" aria-hidden="true"></span>
            <?= $this->translate('ISO') ?>
        </td>
        <td><?= is_null($this->photo->getIso()) ? $this->translate("Unknown") : $this->photo->getIso() ?></td>
    </tr>
    <tr>
        <td>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <?= $this->translate('Location') ?>
        </td>
        <td>
            <?= is_null($this->photo->getLongitude()) || is_null($this->photo->getLatitude()) ?
                $this->translate("Unknown") : "<a target='_blank'
				href='https://www.google.com/maps/?q={$this->photo->getLatitude()},{$this->photo->getLongitude()}'>
				{$this->translate("View on map")}</a>"
            ?>
        </td>
    </tr>
    </tbody>
</table>
<?php endif; ?>