<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\Photo as PhotoModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var PhotoModel $photo
 */
?>
<table class="table table-condensed">
    <tbody>
        <tr>
            <td>
                <span class="fas fa-user" aria-hidden="true"></span>
                <?= $this->translate('Artist') ?>
            </td>
            <td><?= null === $photo->getArtist() ? $this->translate('Unknown') : $this->escapeHtmlAttr($photo->getArtist()) ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-camera" aria-hidden="true"></span>
                <?= $this->translate('Camera') ?>
            </td>
            <td><?= null === $photo->getCamera() ? $this->translate('Unknown') : $this->escapeHtmlAttr($photo->getCamera()) ?></td>
        </tr>
        <tr>
            <td>
                <span class="far fa-calendar-alt" aria-hidden="true"></span>
                <?= $this->translate('Date/time') ?>
            </td>
            <td><?= $photo->getDateTime()->format('Y-m-d H:i:s'); ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-bolt" aria-hidden="true"></span>
                <?= $this->translate('Flash') ?>
            </td>
            <td><?= $photo->getFlash() ? $this->translate('Yes') : $this->translate('No') ?></td>
        </tr>
        <tr>
            <td>
                <span class="far fa-eye" aria-hidden="true"></span>
                <?= $this->translate('Focal length') ?>
            </td>
            <td><?= null === $photo->getFocalLength() ? $this->translate('Unknown') : $photo->getFocalLength() ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-adjust" aria-hidden="true"></span>
                <?= $this->translate('Exposure time') ?>
            </td>
            <td><?= null === $photo->getExposureTime() ? $this->translate('Unknown') : $photo->getExposureTime() ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-stopwatch" aria-hidden="true"></span>
                <?= $this->translate('Shutter speed') ?>
            </td>
            <td><?= null === $photo->getShutterSpeed() ? $this->translate('Unknown') : $photo->getShutterSpeed() ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-cog" aria-hidden="true"></span>
                <?= $this->translate('Aperture') ?>
            </td>
            <td><?= null === $photo->getAperture() ? $this->translate('Unknown') : $photo->getAperture() ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-glasses" aria-hidden="true"></span>
                <?= $this->translate('ISO') ?>
            </td>
            <td><?= null === $photo->getIso() ? $this->translate('Unknown') : $photo->getIso() ?></td>
        </tr>
        <tr>
            <td>
                <span class="fas fa-map-marker-alt" aria-hidden="true"></span>
                <?= $this->translate('Location') ?>
            </td>
            <td>
                <?php if (null === $photo->getLatitude() || null === $photo->getLongitude()): ?>
                    <?= $this->translate('Unknown') ?>
                <?php else: ?>
                    <a href="<?=
                        sprintf(
                            'https://www.openstreetmap.org/?mlat=%1$F&mlon=%2$F#map=17/%1$F/%2$F',
                            $photo->getLatitude(),
                            $photo->getLongitude(),
                        )
                    ?>">
                        <?= $this->translate('View on map') ?>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    </tbody>
</table>
