<?php if($this->isAllowed('view', 'tag')): ?>
<div>
    <h4><?= $this->translate('People in this photo') ?></h4>
    <ul id="tagList">
        <?php foreach ($this->photo->getTags() as $tag): ?>
            <li>
                <a href="#"><?= $tag->getMember()->getFullName() ?></a>&nbsp;
                <a href="<?= $this->url('photo/photo/tag/remove',
                    array('photo_id' => $this->photo->getId(), 'lidnr' => $tag->getMember()->getLidnr())); ?>"
                   class="remove-tag">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php if($this->isAllowed('add', 'tag')): ?>
<div>
    <form action="<?= $this->url('photo/photo/tag/add',
        array('photo_id' => $this->photo->getId(), 'lidnr' => 'lidnr')); ?>" id="tagForm" class="form-inline">
        <div class="form-group">
            <label for="tagSearch"><?= $this->translate('Tag someone') ?></label>
            <input type="text" class="form-control" name="tagSearch" id="tagSearch">
        </div>
    </form>
</div>
<?php endif; ?>