<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Photo\Model\Photo as PhotoModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var PhotoModel $photo
 */

$this->scriptUrl()->requireUrl('photo/photo/tag/remove', ['photo_id', 'lidnr'])
    ->requireUrl('member/view', ['lidnr']);
?>
<?php if ($this->acl('photo_service_acl')->isAllowed('tag', 'view')): ?>
    <?php
    $tagCount = $photo->getTags()->count();
    $i = 1;
    ?>
    <span class="tag-title <?= (0 === $tagCount) ? 'hidden' : '' ?>"><?= $this->translate('In this photo:') ?></span>
    <span class="no-tag-title <?= (0 !== $tagCount) ? 'hidden' : '' ?>"><?= $this->translate('No one has been tagged in this photo yet. Tag someone you recognise now!')?></span>
    <div class="tagList" data-tag-list="<?= $photo->getId() ?>">
        <?php foreach ($photo->getTags() as $tag): ?>
            <span>
                <a href="<?= $this->url(
                    'photo/album',
                    [
                        'album_id' => $tag->getMember()->getLidnr(),
                        'album_type' => 'member',
                    ],
                ) ?>">
                    <?= $this->escapeHtml($tag->getMember()->getFullName()) ?>
                </a>&nbsp;
                <a class="remove-tag" data-tag-id="<?= $tag->getId() ?>"
                   href="<?= $this->url(
                    'photo/photo/tag/remove',
                    [
                        'photo_id' => $photo->getId(),
                        'lidnr' => $tag->getMember()->getLidnr(),
                    ],
                ); ?>">
                    <span class="fas fa-times" aria-hidden="true"></span>
                </a>
                <?php
                $i++;
                if ($i < $tagCount) {
                    echo ',&nbsp';
                }
                if ($i == $tagCount) {
                    echo $this->translate('and');
                }
                ?>
            </span>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if ($this->acl('photo_service_acl')->isAllowed('tag', 'add')): ?>
    <div class="form-group">
        <label for="tagSearch"><span class="fas fa-plus"></span> <?= $this->translate('Tag someone') ?>:</label>
        <input type="text" data-url="<?= $this->url(
            'photo/photo/tag/add',
            [
                'photo_id' => $photo->getId(),
                'lidnr' => 'lidnr',
            ],
        ); ?>" id="tagSearch" class="tagSearch" name="tagSearch">
    </div>
<?php endif; ?>
