<?php
$this->scriptUrl()->requireUrl('photo/photo/tag/remove', ['photo_id', 'lidnr'])
                  ->requireUrl('member/view', ['lidnr']);
?>
<?php if($this->acl('photo_acl')->isAllowed('tag', 'view')): ?>
<div>
    <strong><?= $this->photo->getAlbum()->getName() ?></strong>
    <?= $this->photo->getTags()->count() ? 'with' : '' ?>
        <?php foreach ($this->photo->getTags() as $tag): ?>

                <a href="<?= $this->url('photo/member', ['lidnr' => $tag->getMember()->getLidnr(), 'page' => null]) ?>">
                    <?= $tag->getMember()->getFullName() ?>
                </a>&nbsp;
                <a href="<?= $this->url('photo/photo/tag/remove',
                    ['photo_id' => $this->photo->getId(), 'lidnr' => $tag->getMember()->getLidnr()]); ?>"
                   class="remove-tag">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>,

        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php if(false && $this->acl('photo_acl')->isAllowed('tag', 'add')): ?>
<div>
    <form action="<?= $this->url('photo/photo/tag/add',
        ['photo_id' => $this->photo->getId(), 'lidnr' => 'lidnr']); ?>" id="tagForm" class="form-inline">
        <div class="form-group">
            <label for="tagSearch"><?= $this->translate('Tag someone') ?></label>
            <input type="text" class="form-control" name="tagSearch" id="tagSearch">
        </div>
    </form>
</div>
<?php endif; ?>
