<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\CompanyUserLogin as CompanyUserLoginForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var CompanyUserLoginForm $form
 * @var string $redirectTo
 */

$form->prepare();

$form->setAttribute(
    'action',
    $this->url(
        'user/login',
        ['user_type' => 'company'],
        ['query' => ['redirect_to' => $redirectTo]],
    ),
);
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<div class="panel-body">
    <?= $this->form()->openTag($form) ?>
    <?php
    $email = $form->get('email');
    $email->setAttribute('id', 'email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('autocomplete', 'username');
    // TODO: Re-enable login after re-enabling the creation of company accounts.
    $email->setAttribute('disabled', 'disabled');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($email) ?>">
        <label for="<?= $email->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $email->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formEmail($email) ?>
            <?= $this->formElementErrors($email, ['class' => 'help-block']); ?>
        </div>
    </div>
    <?php
    $password = $form->get('password');
    $password->setAttribute('id', 'password');
    $password->setAttribute('class', 'form-control');
    $password->setAttribute('autocomplete', 'current-password');
    // TODO: Re-enable login after re-enabling the creation of company accounts.
    $password->setAttribute('disabled', 'disabled');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($password) ?>">
        <label for="<?= $password->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $password->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formPassword($password) ?>
            <?= $this->formElementErrors($password, ['class' => 'help-block']); ?>
            <a href="<?= $this->url('user/password/reset', ['user_type' => 'company']) ?>">
                <?= $this->translate('Forgot password?') ?>
            </a>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <?php
            echo $this->formElement($form->get('security'));
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');
            // TODO: Re-enable login after re-enabling the creation of company accounts.
            $submit->setAttribute('disabled', 'disabled');
            ?>
            <?= $this->formRow($submit); ?>
        </div>
    </div>

    <?= $this->form()->closeTag(); ?>
</div>
