<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\UserLogin as UserLoginForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var UserLoginForm $form
 * @var string $redirectTo
 */

$form->prepare();
$form->setAttribute(
    'action',
    $this->url(
        'user/login',
        ['user_type' => 'member'],
        ['query' => ['redirect_to' => $redirectTo]],
    ),
);
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<div class="panel-body">
    <?php
    $month = intval((new DateTime())->format('n'));
    if (8 === $month || 9 === $month):
    ?>
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-info">
                    <p>
                        <?= sprintf(
                            $this->translate('Recently joined GEWIS? Before you can log in, you need to activate your account and set a password, %sclick here%s to do so.'),
                            '<a href="' . $this->url('user/activate') . '">',
                            '</a>',
                        ) ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?= $this->form()->openTag($form) ?>
    <?php
    $element = $form->get('login');
    $element->setAttribute('id', 'login');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('autocomplete', 'username');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $element->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
        </div>
    </div>
    <?php
    $element = $form->get('password');
    $element->setAttribute('id', 'password');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('autocomplete', 'current-password');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $element->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formPassword($element) ?>
            <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
            <a href="<?= $this->url('user/password/reset', ['user_type' => 'member']) ?>">
                <?= $this->translate('Forgot password?') ?>
            </a>
        </div>
    </div>
    <?php
    $element = $form->get('remember');
    $element->setAttribute('checked', 'checked');
    ?>
    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <label>
                <?= $this->formCheckbox($element) ?>
                <?= $element->getLabel() ?>
            </label>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <?php
            echo $this->formElement($form->get('security'));
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <?= $this->formRow($submit); ?>
        </div>
    </div>

    <?= $this->form()->closeTag(); ?>
</div>
<div class="panel-footer">
    <p>
        <?= sprintf(
            $this->translate('Are you a member but do not yet have an account for the website? %sClick here%s to request its activation.'),
            '<a href="' . $this->url('user/activate') . '">',
            '</a>',
        ) ?>
    </p>
</div>
