<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Form\UserLogin as UserLoginForm;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var UserLoginForm $form
 * @var string $redirectTo
 */

$form->prepare();
$form->setAttribute(
    'action',
    $this->url(
        'user/login',
        ['user_type' => 'member'],
        ['query' => ['redirect_to' => $redirectTo]],
    ),
);
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<div class="panel-body">
    <?= $this->form()->openTag($form) ?>
    <?php
    $element = $form->get('login');
    $element->setAttribute('id', 'login');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('autocomplete', 'username');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $element->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
        </div>
    </div>
    <?php
    $element = $form->get('password');
    $element->setAttribute('id', 'password');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('autocomplete', 'current-password');
    ?>
    <div class="form-group <?= $this->bootstrapElementError($element) ?>">
        <label for="<?= $element->getAttribute('id') ?>"
               class="control-label col-sm-5"><?= $element->getLabel() ?></label>
        <div class="col-sm-7">
            <?= $this->formPassword($element) ?>
            <?= $this->formElementErrors($element, ['class' => 'help-block']); ?>
        </div>
    </div>
    <?php
    $element = $form->get('remember');
    $element->setAttribute('checked', 'checked');
    ?>
    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <label>
                <?= $this->formCheckbox($element) ?>
                <?= $element->getLabel() ?>
            </label>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-7">
            <?php
            echo $this->formElement($form->get('security'));
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <?= $this->formRow($submit); ?>
        </div>
    </div>

    <?= $this->form()->closeTag(); ?>
</div>
<div class="panel-footer">
    <?php $url = $this->url('user/register'); ?>
    <p>
        <?= sprintf($this->translate("If you don't have an account yet, go to the %sRegistration page%s"), '<a href="' . $url . '">', '</a>') ?>
    </p>
    <?php $url = $this->url('user/password/reset', ['user_type' => 'member']); ?>
    <p>
        <?= sprintf($this->translate("If you forgot your password, go to the %sPassword reset page%s"), '<a href="' . $url . '">', '</a>') ?>
    </p>
</div>
