<?php $lang = $this->plugin('translate')->getTranslator()->getLocale();

// set title
$this->headTitle($this->escapeHtml($activity->getName()));
$this->headTitle($this->translate('Activities')); ?>


<?php if (!isset($breadcrumb)): // only show breadcrumbs if they were not yet shown ?>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <a href="<?= $this->url('activity') ?>">
                        <?= $this->translate('Activities') ?>
                    </a>
                </li>
                <li class="active">
                    <?= $this->escapeHtml($activity->getName()) ?>
                </li>
            </ol>
        </div>
    </section>
<?php endif; ?>

<div class="container">
    <h1><?= $this->translate('Subscription email adresses for activity ') . ' ' . $this->escapeHtml($activity->getName()) ?></h1>

    <table class="table">
        <thead>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Email') ?></th>
        </thead>
        <tbody>
            <?php
                $mailAllString = '';
                foreach ($activity->getSignUps() as $signUp):
                    $email = $signUp->getEmail();
                    $mailAllString .= ',' . $email;
                ?>
                <tr>
                    <td><?= $signUp->getFullName() ?></td>
                    <td>
                        <a href="mailto:<?= $email ?>">
                            <?= $email ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach;?>
        </tbody>
        <tfoot>
            <td></td>
            <td>
                <a href="mailto:<?= $mailAllString ?>">
                    <?= $this->translate('Mail everybody') ?>
                </a>
            </td>
        </tfoot>
    </table>
</div>
