<?php $lang = $this->plugin('translate')->getTranslator()->getLocale();

// set title
$this->headTitle($activity->getName());
$this->headTitle($this->translate('Activities')); ?>


<?php if (!isset($breadcrumb)): // only show breadcrumbs if they were not yet shown ?>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li>
                    <a href="<?= $this->url('activity') ?>">
                        <?= $this->translate('Activities') ?>
                    </a>
                </li>
                <li class="active">
                    <?= $activity->getName() ?>
                </li>
            </ol>
        </div>
    </section>
<?php endif; ?>

<div class="container">
    <?= $this->partial('activity/organizer/exportTable.phtml', [
            'activity' => $activity,
            'signupData' => $signupData
    ]);?>

    <a href="<?php echo $this->url('organizer_activity/exportpdf', ['id' => $activity->getId()])?>"><?= $this->translate('Download as pdf');?></a>
</div>