<?php
$this->headTitle($this->translate('Update activity'));
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/activity-create.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');
$form->prepare();
?>
<div class="container">
    <?= $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col-md-12">
            <h1><?= $this->translate('Update an activity') ?></h1>
            <hr>
            <h3><?= $this->translate('Display languages') ?></h3>
            <?php
            $dutchElement = $form->get('language_dutch');
            $dutchElement->setAttribute('onchange', 'Activity.updateForm()');
            $dutchElement->setAttribute('class', 'form-control');
            $englishElement = $form->get('language_english');
            $englishElement->setAttribute('onchange', 'Activity.updateForm()');
            $englishElement->setAttribute('class', 'form-control');
            ?>
            <div class="form-group form-inline">
                <div class="form-group<?= count($dutchElement->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $dutchElement->getName() ?>" class="control-label col-sm-2"><?= $this->translate('Dutch') ?></label>
                    <div class="col-sm-10">
                        <?php $dutchElement->setChecked($languages['nl']); ?>
                        <?= $this->formCheckbox($dutchElement) ?>
                        <?= $this->formElementErrors($dutchElement) ?>
                    </div>
                </div>
                <div class="form-group<?= count($englishElement->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $englishElement->getName() ?>" class="control-label col-sm-2"><?= $this->translate('English') ?></label>
                    <div class="col-sm-10">
                        <?php $englishElement->setChecked($languages['en']); ?>
                        <?= $this->formCheckbox($englishElement) ?>
                        <?= $this->formElementErrors($englishElement) ?>
                    </div>
                </div>
            </div>
            <h3><?= $this->translate('Time and date') ?></h3>
            <div class="form-group form-inline">
                <?php
                $beginTime = $form->get('beginTime');
                $beginTime->setAttribute('class', 'form-control');
                $endTime = $form->get('endTime');
                $endTime->setAttribute('class', 'form-control');
                ?>
                <div class="form-group<?= count($beginTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $beginTime->getName() ?>" class="control-label col-sm-2"><?= $this->translate('From') ?></label>
                    <div class="col-sm-10">
                        <?= $this->formInput($beginTime) ?>
                        <?= $this->formElementErrors($beginTime) ?>
                    </div>
                </div>

                <div class="form-group<?= count($endTime->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $endTime->getName() ?>" class="control-label col-sm-2"><?= $this->translate('Until') ?></label>
                    <div class="col-sm-10">
                        <?= $this->formInput($endTime) ?>
                        <?= $this->formElementErrors($endTime) ?>
                    </div>
                </div>
            </div>
            <?php
            $subscriptionDeadline = $form->get('subscriptionDeadline');
            $subscriptionDeadline->setAttribute('class', 'form-control');
            ?>
            <div class="form-group<?= count($subscriptionDeadline->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $subscriptionDeadline->getName() ?>" class="control-label col-sm-2"><?= $this->translate('Subscription deadline') ?></label>
                <div class="col-sm-10">
                    <?= $this->formInput($subscriptionDeadline) ?>
                    <?= $this->formElementErrors($subscriptionDeadline) ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h3>Dutch</h3>
            <?php
            $name = $form->get('name');
            $name->setAttribute('disabled', 'disabled');
            $name->setAttribute('class', 'form-control form-control-dutch');
            ?>
            <div class="form-group<?= count($name->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $name->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Name') ?>
                </label>
                <?= $this->formInput($name) ?>
                <?= $this->formElementErrors($name) ?>
            </div>
            <?php
            $location = $form->get('location');
            $location->setAttribute('disabled', 'disabled');
            $location->setAttribute('class', 'form-control form-control-dutch');
            ?>
            <div class="form-group<?= count($location->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $location->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Location') ?>
                </label>
                <?= $this->formInput($location) ?>
                <?= $this->formElementErrors($location) ?>
            </div>
            <?php
            $costs = $form->get('costs');
            $costs->setAttribute('disabled', 'disabled');
            $costs->setAttribute('class', 'form-control form-control-dutch');
            ?>
            <div class="form-group<?= count($costs->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $costs->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Costs') ?>
                </label>
                <?= $this->formInput($costs) ?>
                <?= $this->formElementErrors($costs) ?>
            </div>
            <?php
            $description = $form->get('description');
            $description->setAttribute('disabled', 'disabled');
            $description->setAttribute('class', 'form-control form-control-dutch');
            $description->setAttribute('style', 'width:100%; height:10em; resize:none');
            ?>
            <div class="form-group<?= count($description->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $description->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Description') ?>
                </label>
                <?= $this->formRow($description) ?>
                <?= $this->formElementErrors($description) ?>
            </div>
        </div>
        <div class="col-md-6">
            <h3>English</h3>
            <?php
            $nameEn = $form->get('nameEn');
            $nameEn->setAttribute('disabled', 'disabled');
            $nameEn->setAttribute('class', 'form-control form-control-english');
            ?>
            <div class="form-group<?= count($nameEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $nameEn->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Name') ?>
                </label>
                <?= $this->formInput($nameEn) ?>
                <?= $this->formElementErrors($nameEn) ?>
            </div>
            <?php
            $locationEn = $form->get('locationEn');
            $locationEn->setAttribute('disabled', 'disabled');
            $locationEn->setAttribute('class', 'form-control form-control-english');
            ?>
            <div class="form-group<?= count($locationEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $locationEn->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Location') ?>
                </label>
                <?= $this->formInput($locationEn) ?>
                <?= $this->formElementErrors($locationEn) ?>
            </div>
            <?php
            $costsEn = $form->get('costsEn');
            $costsEn->setAttribute('disabled', 'disabled');
            $costsEn->setAttribute('class', 'form-control form-control-english');
            ?>
            <div class="form-group<?= count($costsEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $costsEn->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Costs') ?>
                </label>
                <?= $this->formInput($costsEn) ?>
                <?= $this->formElementErrors($costsEn) ?>
            </div>
            <?php
            $descriptionEn = $form->get('descriptionEn');
            $descriptionEn->setAttribute('disabled', 'disabled');
            $descriptionEn->setAttribute('class', 'form-control form-control-english');
            $descriptionEn->setAttribute('style', 'width:100%; height:10em; resize:none');
            ?>
            <div class="form-group<?= count($descriptionEn->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $descriptionEn->getName() ?>" class="control-label col-sm-2">
                    <?= $this->translate('Description') ?>
                </label>
                <?= $this->formRow($descriptionEn) ?>
                <?= $this->formElementErrors($descriptionEn) ?>
            </div>
        </div>
        <div class="col-md-12">
            <?php
            $canSignUp = $form->get('canSignUp');
            ?>
            <div class="form-group<?= count($canSignUp->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label>
                    <?= $this->translate('Enable subscriptions') ?>
                    <?= $this->formCheckbox($canSignUp) ?>
                    <?= $this->formElementErrors($canSignUp) ?>
                </label>
            <?php
            $organ = $form->get('organ');
            $organ->setAttribute('class', 'form-control');
            //$organ->setAttribute('disabled', 'disabled');
            ?>
            <div class="form-group<?= count($organ->getMessages()) > 0 ? ' has-error' : '' ?>">
                <label for="<?= $organ->getName(); ?>" class="control-label col-sm-2">
                    <?= $this->translate('Organizing committee / fraternity') ?>
                </label>
                <div class="col-sm-10">
                    <?= $this->formSelect($organ) ?>
                    <?= $this->formElementErrors($organ) ?>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($this->translate('Update activity'));
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <div class="form-group">
                <?= $this->formButton($submit) ?>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<script>
    $('[name="beginTime"]').datetimepicker();
    $('[name="endTime"]').datetimepicker();
    $('[name="subscriptionDeadline"]').datetimepicker();
    Activity.updateForm();
    for (var i = 0; i < <?= $index ?>; i++) {
        Activity.updateFieldset(i);
    }    
</script>
