<?php

declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * phpcs:disable Generic.Files.LineLength.TooLong
 */
final class Version20241020212355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration after adding support for Doctrine migrations.';
    }

    public function up(Schema $schema): void
    {
        // phpcs:disable SlevomatCodingStandard.Functions.RequireMultiLineCall.RequiredMultiLineCall
        $this->addSql('CREATE TABLE Activity (id INT AUTO_INCREMENT NOT NULL, name_id INT NOT NULL, location_id INT NOT NULL, costs_id INT NOT NULL, approver_id INT DEFAULT NULL, creator_id INT NOT NULL, description_id INT NOT NULL, organ_id INT DEFAULT NULL, company_id INT DEFAULT NULL, beginTime DATETIME NOT NULL, endTime DATETIME NOT NULL, status INT NOT NULL, isMyFuture TINYINT(1) NOT NULL, requireGEFLITST TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_55026B0C71179CD6 (name_id), UNIQUE INDEX UNIQ_55026B0C64D218E (location_id), UNIQUE INDEX UNIQ_55026B0C27D66E0D (costs_id), INDEX IDX_55026B0CBB23766C (approver_id), INDEX IDX_55026B0C61220EA6 (creator_id), UNIQUE INDEX UNIQ_55026B0CD9F966B (description_id), INDEX IDX_55026B0CE4445171 (organ_id), INDEX IDX_55026B0C979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityCategoryAssignment (activity_id INT NOT NULL, activitycategory_id INT NOT NULL, INDEX IDX_480AC9B381C06096 (activity_id), INDEX IDX_480AC9B324EF5392 (activitycategory_id), PRIMARY KEY(activity_id, activitycategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityCalendarOption (id INT AUTO_INCREMENT NOT NULL, proposal_id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, beginTime DATETIME NOT NULL, endTime DATETIME NOT NULL, modifiedBy_id INT DEFAULT NULL, INDEX IDX_503F8985F4792058 (proposal_id), INDEX IDX_503F8985D6A05076 (modifiedBy_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityCategory (id INT AUTO_INCREMENT NOT NULL, name_id INT NOT NULL, UNIQUE INDEX UNIQ_9C1F977771179CD6 (name_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityLocalisedText (id INT AUTO_INCREMENT NOT NULL, valueEN LONGTEXT DEFAULT NULL, valueNL LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityOptionCreationPeriod (id INT AUTO_INCREMENT NOT NULL, beginPlanningTime DATETIME NOT NULL, endPlanningTime DATETIME NOT NULL, beginOptionTime DATETIME NOT NULL, endOptionTime DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityOptionProposal (id INT AUTO_INCREMENT NOT NULL, creator_id INT NOT NULL, organ_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, creationTime DATETIME NOT NULL, organAlt VARCHAR(255) DEFAULT NULL, INDEX IDX_C15663DD61220EA6 (creator_id), INDEX IDX_C15663DDE4445171 (organ_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ActivityUpdateProposal (id INT AUTO_INCREMENT NOT NULL, old_id INT NOT NULL, new_id INT NOT NULL, INDEX IDX_9E136D5139E6FA16 (old_id), INDEX IDX_9E136D51BD06B3B3 (new_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Address (type VARCHAR(255) NOT NULL, lidnr INT NOT NULL, country VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, number VARCHAR(255) NOT NULL, postalCode VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, INDEX IDX_C2F3561DD665E01D (lidnr), PRIMARY KEY(lidnr, type)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Album (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, startDateTime DATETIME DEFAULT NULL, endDateTime DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, coverPath VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, INDEX IDX_F8594147727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ApiApp (id INT AUTO_INCREMENT NOT NULL, appId VARCHAR(255) NOT NULL, secret VARCHAR(255) NOT NULL, callback VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, claims LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ApiAppAuthentication (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, app_id INT NOT NULL, time DATETIME NOT NULL, INDEX IDX_D9FD7EB6A76ED395 (user_id), INDEX IDX_D9FD7EB67987212D (app_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ApiUser (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ApprovableText (id INT AUTO_INCREMENT NOT NULL, message VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Authorization (id INT AUTO_INCREMENT NOT NULL, authorizer INT DEFAULT NULL, recipient INT DEFAULT NULL, meetingNumber INT NOT NULL, createdAt DATETIME NOT NULL, revokedAt DATETIME DEFAULT NULL, INDEX IDX_C913C01A34A1C897 (authorizer), INDEX IDX_C913C01A6804FB49 (recipient), UNIQUE INDEX auth_idx (authorizer, recipient, meetingNumber, revokedAt), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE BoardMember (id INT AUTO_INCREMENT NOT NULL, lidnr INT NOT NULL, r_meeting_type VARCHAR(255) DEFAULT NULL, r_meeting_number INT DEFAULT NULL, r_decision_point INT DEFAULT NULL, r_decision_number INT DEFAULT NULL, r_sequence INT DEFAULT NULL, function VARCHAR(255) NOT NULL, installDate DATE NOT NULL, releaseDate DATE DEFAULT NULL, dischargeDate DATE DEFAULT NULL, INDEX IDX_D9517B2ED665E01D (lidnr), UNIQUE INDEX installationDec_uniq (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Company (id INT AUTO_INCREMENT NOT NULL, slogan_id INT NOT NULL, description_id INT NOT NULL, website_id INT NOT NULL, approver_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slugName VARCHAR(255) NOT NULL, representativeName VARCHAR(255) NOT NULL, representativeEmail VARCHAR(255) NOT NULL, contactName VARCHAR(255) DEFAULT NULL, contactAddress VARCHAR(255) DEFAULT NULL, contactEmail VARCHAR(255) DEFAULT NULL, contactPhone VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, approved INT NOT NULL, approvedAt DATETIME DEFAULT NULL, isUpdate TINYINT(1) NOT NULL, approvableText_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_800230D326C79F4B (slogan_id), UNIQUE INDEX UNIQ_800230D3D9F966B (description_id), UNIQUE INDEX UNIQ_800230D318F45C82 (website_id), INDEX IDX_800230D3BB23766C (approver_id), UNIQUE INDEX UNIQ_800230D3502BCAA2 (approvableText_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CompanyLocalisedText (id INT AUTO_INCREMENT NOT NULL, valueEN LONGTEXT DEFAULT NULL, valueNL LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CompanyPackage (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, article_id INT DEFAULT NULL, contractNumber VARCHAR(255) DEFAULT NULL, starts DATE NOT NULL, expires DATE NOT NULL, published TINYINT(1) NOT NULL, packageType VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, INDEX IDX_181DA527979B1AD6 (company_id), INDEX IDX_181DA5277294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CompanyUpdate (id INT AUTO_INCREMENT NOT NULL, original_id INT NOT NULL, proposal_id INT NOT NULL, INDEX IDX_E13E3542108B7592 (original_id), UNIQUE INDEX UNIQ_E13E3542F4792058 (proposal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CompanyUser (id INT NOT NULL, password VARCHAR(255) NOT NULL, passwordChangedOn DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Course (code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(code)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SimilarCourse (course_code VARCHAR(255) NOT NULL, similar_course_code VARCHAR(255) NOT NULL, INDEX IDX_C56C679ABFB7ED9E (course_code), INDEX IDX_C56C679ACD579B90 (similar_course_code), PRIMARY KEY(course_code, similar_course_code)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE CourseDocument (id INT AUTO_INCREMENT NOT NULL, course_code VARCHAR(255) NOT NULL, date DATE NOT NULL, language VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, scanned TINYINT(1) NOT NULL, type VARCHAR(255) NOT NULL, examType VARCHAR(255) DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, INDEX IDX_90F07469BFB7ED9E (course_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Decision (meeting_type VARCHAR(255) NOT NULL, meeting_number INT NOT NULL, point INT NOT NULL, number INT NOT NULL, content LONGTEXT NOT NULL, INDEX IDX_7DDADC1E602FAFFB96F82E16 (meeting_type, meeting_number), PRIMARY KEY(meeting_type, meeting_number, point, number)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE FrontpageLocalisedText (id INT AUTO_INCREMENT NOT NULL, valueEN LONGTEXT DEFAULT NULL, valueNL LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Job (id INT AUTO_INCREMENT NOT NULL, name_id INT NOT NULL, location_id INT NOT NULL, website_id INT NOT NULL, description_id INT NOT NULL, attachment_id INT NOT NULL, package_id INT NOT NULL, category_id INT NOT NULL, approver_id INT DEFAULT NULL, slugName VARCHAR(255) NOT NULL, published TINYINT(1) NOT NULL, contactName VARCHAR(255) DEFAULT NULL, contactPhone VARCHAR(255) DEFAULT NULL, contactEmail VARCHAR(255) DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, approved INT NOT NULL, approvedAt DATETIME DEFAULT NULL, isUpdate TINYINT(1) NOT NULL, approvableText_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_C395A61871179CD6 (name_id), UNIQUE INDEX UNIQ_C395A61864D218E (location_id), UNIQUE INDEX UNIQ_C395A61818F45C82 (website_id), UNIQUE INDEX UNIQ_C395A618D9F966B (description_id), UNIQUE INDEX UNIQ_C395A618464E68B (attachment_id), INDEX IDX_C395A618F44CABFF (package_id), INDEX IDX_C395A61812469DE2 (category_id), INDEX IDX_C395A618BB23766C (approver_id), UNIQUE INDEX UNIQ_C395A618502BCAA2 (approvableText_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE JobLabelAssignment (job_id INT NOT NULL, joblabel_id INT NOT NULL, INDEX IDX_42CB55B5BE04EA9 (job_id), INDEX IDX_42CB55B5DD1E79DF (joblabel_id), PRIMARY KEY(job_id, joblabel_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE JobCategory (id INT AUTO_INCREMENT NOT NULL, name_id INT NOT NULL, slug_id INT NOT NULL, hidden TINYINT(1) NOT NULL, pluralName_id INT NOT NULL, UNIQUE INDEX UNIQ_9701A2A671179CD6 (name_id), UNIQUE INDEX UNIQ_9701A2A6A8BEABC (pluralName_id), UNIQUE INDEX UNIQ_9701A2A6311966CE (slug_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE JobLabel (id INT AUTO_INCREMENT NOT NULL, name_id INT NOT NULL, abbreviation_id INT NOT NULL, UNIQUE INDEX UNIQ_ECF91BE071179CD6 (name_id), UNIQUE INDEX UNIQ_ECF91BE0BF69284D (abbreviation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE JobUpdate (id INT AUTO_INCREMENT NOT NULL, original_id INT NOT NULL, proposal_id INT NOT NULL, INDEX IDX_961CE301108B7592 (original_id), UNIQUE INDEX UNIQ_961CE301F4792058 (proposal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Keyholder (id INT AUTO_INCREMENT NOT NULL, lidnr INT NOT NULL, r_meeting_type VARCHAR(255) DEFAULT NULL, r_meeting_number INT DEFAULT NULL, r_decision_point INT DEFAULT NULL, r_decision_number INT DEFAULT NULL, r_sequence INT DEFAULT NULL, expirationDate DATE NOT NULL, withdrawnDate DATE DEFAULT NULL, INDEX IDX_3C5F7B4DD665E01D (lidnr), UNIQUE INDEX grantingDec_uniq (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE LoginAttempt (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, company_id INT DEFAULT NULL, ip VARCHAR(255) NOT NULL, time DATETIME NOT NULL, INDEX IDX_C137201BA76ED395 (user_id), INDEX IDX_C137201B979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MailingList (name VARCHAR(255) NOT NULL, nl_description LONGTEXT NOT NULL, en_description LONGTEXT NOT NULL, onForm TINYINT(1) NOT NULL, defaultSub TINYINT(1) NOT NULL, PRIMARY KEY(name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MaxActivities (id INT AUTO_INCREMENT NOT NULL, organ_id INT NOT NULL, period_id INT DEFAULT NULL, value INT NOT NULL, INDEX IDX_1BE5E0C5E4445171 (organ_id), INDEX IDX_1BE5E0C5EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Meeting (type VARCHAR(255) NOT NULL, number INT NOT NULL, date DATE NOT NULL, PRIMARY KEY(type, number)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MeetingDocument (id INT AUTO_INCREMENT NOT NULL, meeting_type VARCHAR(255) DEFAULT NULL, meeting_number INT DEFAULT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, displayPosition INT DEFAULT 0 NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, INDEX IDX_45407F4E602FAFFB96F82E16 (meeting_type, meeting_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE MeetingMinutes (meeting_type VARCHAR(255) NOT NULL, meeting_number INT NOT NULL, path VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, UNIQUE INDEX meeting_uniq (meeting_type, meeting_number), PRIMARY KEY(meeting_type, meeting_number)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Member (lidnr INT NOT NULL, email VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) NOT NULL, middleName VARCHAR(255) NOT NULL, initials VARCHAR(255) NOT NULL, firstName VARCHAR(255) NOT NULL, generation INT NOT NULL, type VARCHAR(255) NOT NULL, changedOn DATE NOT NULL, membershipEndsOn DATE DEFAULT NULL, birth DATE NOT NULL, expiration DATE NOT NULL, paid INT NOT NULL, supremum VARCHAR(255) DEFAULT NULL, hidden TINYINT(1) DEFAULT 0 NOT NULL, authenticationKey VARCHAR(255) DEFAULT NULL, deleted TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(lidnr)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE members_mailinglists (lidnr INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_5AD357D9D665E01D (lidnr), INDEX IDX_5AD357D95E237E06 (name), PRIMARY KEY(lidnr, name)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE NewCompanyUser (id INT NOT NULL, code VARCHAR(255) NOT NULL, time DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE NewUser (lidnr INT NOT NULL, code VARCHAR(255) NOT NULL, time DATETIME DEFAULT NULL, PRIMARY KEY(lidnr)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE NewsItem (id INT AUTO_INCREMENT NOT NULL, date DATE NOT NULL, dutchTitle VARCHAR(255) NOT NULL, englishTitle VARCHAR(255) NOT NULL, englishContent LONGTEXT NOT NULL, dutchContent LONGTEXT NOT NULL, pinned TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Organ (id INT AUTO_INCREMENT NOT NULL, r_meeting_type VARCHAR(255) DEFAULT NULL, r_meeting_number INT DEFAULT NULL, r_decision_point INT DEFAULT NULL, r_decision_number INT DEFAULT NULL, r_sequence INT DEFAULT NULL, abbr VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, foundationDate DATE NOT NULL, abrogationDate DATE DEFAULT NULL, UNIQUE INDEX foundation_uniq (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE organs_subdecisions (organ_id INT NOT NULL, meeting_type VARCHAR(255) NOT NULL, meeting_number INT NOT NULL, decision_point INT NOT NULL, decision_number INT NOT NULL, subdecision_sequence INT NOT NULL, INDEX IDX_6177E308E4445171 (organ_id), INDEX IDX_6177E308602FAFFB96F82E1690E0342DEF6BE237DD50EB88 (meeting_type, meeting_number, decision_point, decision_number, subdecision_sequence), PRIMARY KEY(organ_id, meeting_type, meeting_number, decision_point, decision_number, subdecision_sequence)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE OrganInformation (id INT AUTO_INCREMENT NOT NULL, organ_id INT NOT NULL, approver_id INT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, shortDutchDescription VARCHAR(255) DEFAULT NULL, dutchDescription LONGTEXT DEFAULT NULL, shortEnglishDescription VARCHAR(255) DEFAULT NULL, englishDescription LONGTEXT DEFAULT NULL, coverPath VARCHAR(255) DEFAULT NULL, thumbnailPath VARCHAR(255) DEFAULT NULL, INDEX IDX_DD810E34E4445171 (organ_id), INDEX IDX_DD810E34BB23766C (approver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE OrganMember (id INT AUTO_INCREMENT NOT NULL, organ_id INT DEFAULT NULL, lidnr INT DEFAULT NULL, r_meeting_type VARCHAR(255) DEFAULT NULL, r_meeting_number INT DEFAULT NULL, r_decision_point INT DEFAULT NULL, r_decision_number INT DEFAULT NULL, r_sequence INT DEFAULT NULL, function VARCHAR(255) NOT NULL, installDate DATE NOT NULL, dischargeDate DATE DEFAULT NULL, INDEX IDX_E5CB2C7DE4445171 (organ_id), INDEX IDX_E5CB2C7DD665E01D (lidnr), UNIQUE INDEX installation_uniq (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Page (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, name_id INT NOT NULL, title_id INT NOT NULL, content_id INT NOT NULL, requiredRole VARCHAR(255) NOT NULL, subCategory_id INT NOT NULL, UNIQUE INDEX UNIQ_B438191E12469DE2 (category_id), UNIQUE INDEX UNIQ_B438191EDB5A7180 (subCategory_id), UNIQUE INDEX UNIQ_B438191E71179CD6 (name_id), UNIQUE INDEX UNIQ_B438191EA9F87BD (title_id), UNIQUE INDEX UNIQ_B438191E84A0A3ED (content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Photo (id INT AUTO_INCREMENT NOT NULL, album_id INT NOT NULL, dateTime DATETIME NOT NULL, artist VARCHAR(255) DEFAULT NULL, camera VARCHAR(255) DEFAULT NULL, flash TINYINT(1) DEFAULT NULL, focalLength DOUBLE PRECISION DEFAULT NULL, exposureTime DOUBLE PRECISION DEFAULT NULL, shutterSpeed VARCHAR(255) DEFAULT NULL, aperture VARCHAR(255) DEFAULT NULL, iso SMALLINT DEFAULT NULL, path VARCHAR(255) NOT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, aspectRatio DOUBLE PRECISION DEFAULT NULL, INDEX IDX_D576AB1C1137ABCF (album_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Poll (id INT AUTO_INCREMENT NOT NULL, question_id INT NOT NULL, creator_id INT NOT NULL, approver_id INT DEFAULT NULL, expiryDate DATE NOT NULL, UNIQUE INDEX UNIQ_248E557B1E27F6BF (question_id), INDEX IDX_248E557B61220EA6 (creator_id), INDEX IDX_248E557BBB23766C (approver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PollComment (id INT AUTO_INCREMENT NOT NULL, poll_id INT NOT NULL, user_lidnr INT NOT NULL, author VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, createdOn DATETIME NOT NULL, INDEX IDX_C86340FF3C947C0F (poll_id), INDEX IDX_C86340FF34A71B45 (user_lidnr), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PollOption (id INT AUTO_INCREMENT NOT NULL, poll_id INT NOT NULL, text_id INT NOT NULL, anonymousVotes INT DEFAULT 0 NOT NULL, INDEX IDX_FEFE970B3C947C0F (poll_id), UNIQUE INDEX UNIQ_FEFE970B698D3548 (text_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE PollVote (option_id INT NOT NULL, user_id INT NOT NULL, poll_id INT NOT NULL, INDEX IDX_B568B0883C947C0F (poll_id), INDEX IDX_B568B088A7C41D6F (option_id), INDEX IDX_B568B088A76ED395 (user_id), UNIQUE INDEX vote_idx (poll_id, user_id), PRIMARY KEY(option_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ProfilePhoto (id INT AUTO_INCREMENT NOT NULL, photo_id INT NOT NULL, member_id INT NOT NULL, dateTime DATETIME NOT NULL, explicit TINYINT(1) NOT NULL, INDEX IDX_26AA8F6B7E9E4C8C (photo_id), UNIQUE INDEX UNIQ_26AA8F6B7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Signup (id INT AUTO_INCREMENT NOT NULL, signuplist_id INT NOT NULL, user_lidnr INT DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, type VARCHAR(255) NOT NULL, fullName VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, INDEX IDX_490F1BD9BDD669D6 (signuplist_id), INDEX IDX_490F1BD934A71B45 (user_lidnr), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SignupField (id INT AUTO_INCREMENT NOT NULL, signuplist_id INT NOT NULL, name_id INT NOT NULL, isSensitive TINYINT(1) NOT NULL, type INT NOT NULL, minimumValue INT DEFAULT NULL, maximumValue INT DEFAULT NULL, INDEX IDX_B32E149BBDD669D6 (signuplist_id), UNIQUE INDEX UNIQ_B32E149B71179CD6 (name_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SignupFieldValue (id INT AUTO_INCREMENT NOT NULL, field_id INT NOT NULL, signup_id INT NOT NULL, option_id INT DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, INDEX IDX_58203768443707B0 (field_id), INDEX IDX_582037685F619F6E (signup_id), INDEX IDX_58203768A7C41D6F (option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SignupList (id INT AUTO_INCREMENT NOT NULL, activity_id INT NOT NULL, name_id INT NOT NULL, openDate DATETIME NOT NULL, closeDate DATETIME NOT NULL, onlyGEWIS TINYINT(1) NOT NULL, displaySubscribedNumber TINYINT(1) NOT NULL, limitedCapacity TINYINT(1) NOT NULL, INDEX IDX_274D085F81C06096 (activity_id), UNIQUE INDEX UNIQ_274D085F71179CD6 (name_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SignupOption (id INT AUTO_INCREMENT NOT NULL, field_id INT NOT NULL, value_id INT NOT NULL, INDEX IDX_580348EB443707B0 (field_id), UNIQUE INDEX UNIQ_580348EBF920BBA2 (value_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE SubDecision (meeting_type VARCHAR(255) NOT NULL, meeting_number INT NOT NULL, decision_point INT NOT NULL, decision_number INT NOT NULL, sequence INT NOT NULL, lidnr INT DEFAULT NULL, r_meeting_type VARCHAR(255) DEFAULT NULL, r_meeting_number INT DEFAULT NULL, r_decision_point INT DEFAULT NULL, r_decision_number INT DEFAULT NULL, r_sequence INT DEFAULT NULL, content LONGTEXT NOT NULL, type VARCHAR(255) NOT NULL, abbr VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, organType VARCHAR(255) DEFAULT NULL, function VARCHAR(255) DEFAULT NULL, version VARCHAR(32) DEFAULT NULL, date DATE DEFAULT NULL, approval TINYINT(1) DEFAULT NULL, changes TINYINT(1) DEFAULT NULL, until DATE DEFAULT NULL, withdrawnOn DATE DEFAULT NULL, INDEX IDX_F0D6EE40602FAFFB96F82E1690E0342DEF6BE237 (meeting_type, meeting_number, decision_point, decision_number), INDEX IDX_F0D6EE40D665E01D (lidnr), INDEX IDX_F0D6EE40EFBA85FF292FAD512F37B76A76CE1878B79BB36 (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence), INDEX IDX_F0D6EE40EFBA85FF292FAD512F37B76A76CE187 (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number), PRIMARY KEY(meeting_type, meeting_number, decision_point, decision_number, sequence)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Tag (id INT AUTO_INCREMENT NOT NULL, photo_id INT NOT NULL, member_id INT NOT NULL, INDEX IDX_3BC4F1637E9E4C8C (photo_id), INDEX IDX_3BC4F1637597D3FE (member_id), UNIQUE INDEX tag_idx (photo_id, member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE User (lidnr INT NOT NULL, password VARCHAR(255) NOT NULL, passwordChangedOn DATETIME DEFAULT NULL, PRIMARY KEY(lidnr)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE UserRole (id INT AUTO_INCREMENT NOT NULL, lidnr_id INT NOT NULL, role VARCHAR(255) NOT NULL, expiration DATETIME DEFAULT NULL, INDEX IDX_A8503F73111993FE (lidnr_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE Vote (id INT AUTO_INCREMENT NOT NULL, photo_id INT NOT NULL, voter_id INT NOT NULL, dateTime DATETIME NOT NULL, INDEX IDX_FA222A5A7E9E4C8C (photo_id), INDEX IDX_FA222A5AEBB4B8AD (voter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE WeeklyPhoto (id INT AUTO_INCREMENT NOT NULL, photo_id INT NOT NULL, week DATE NOT NULL, UNIQUE INDEX UNIQ_E5D6E8E07E9E4C8C (photo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0C71179CD6 FOREIGN KEY (name_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0C64D218E FOREIGN KEY (location_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0C27D66E0D FOREIGN KEY (costs_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0CBB23766C FOREIGN KEY (approver_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0C61220EA6 FOREIGN KEY (creator_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0CD9F966B FOREIGN KEY (description_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0CE4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE Activity ADD CONSTRAINT FK_55026B0C979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE ActivityCategoryAssignment ADD CONSTRAINT FK_480AC9B381C06096 FOREIGN KEY (activity_id) REFERENCES Activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ActivityCategoryAssignment ADD CONSTRAINT FK_480AC9B324EF5392 FOREIGN KEY (activitycategory_id) REFERENCES ActivityCategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ActivityCalendarOption ADD CONSTRAINT FK_503F8985F4792058 FOREIGN KEY (proposal_id) REFERENCES ActivityOptionProposal (id)');
        $this->addSql('ALTER TABLE ActivityCalendarOption ADD CONSTRAINT FK_503F8985D6A05076 FOREIGN KEY (modifiedBy_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE ActivityCategory ADD CONSTRAINT FK_9C1F977771179CD6 FOREIGN KEY (name_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE ActivityOptionProposal ADD CONSTRAINT FK_C15663DD61220EA6 FOREIGN KEY (creator_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE ActivityOptionProposal ADD CONSTRAINT FK_C15663DDE4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE ActivityUpdateProposal ADD CONSTRAINT FK_9E136D5139E6FA16 FOREIGN KEY (old_id) REFERENCES Activity (id)');
        $this->addSql('ALTER TABLE ActivityUpdateProposal ADD CONSTRAINT FK_9E136D51BD06B3B3 FOREIGN KEY (new_id) REFERENCES Activity (id)');
        $this->addSql('ALTER TABLE Address ADD CONSTRAINT FK_C2F3561DD665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Album ADD CONSTRAINT FK_F8594147727ACA70 FOREIGN KEY (parent_id) REFERENCES Album (id)');
        $this->addSql('ALTER TABLE ApiAppAuthentication ADD CONSTRAINT FK_D9FD7EB6A76ED395 FOREIGN KEY (user_id) REFERENCES User (lidnr)');
        $this->addSql('ALTER TABLE ApiAppAuthentication ADD CONSTRAINT FK_D9FD7EB67987212D FOREIGN KEY (app_id) REFERENCES ApiApp (id)');
        $this->addSql('ALTER TABLE Authorization ADD CONSTRAINT FK_C913C01A34A1C897 FOREIGN KEY (authorizer) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Authorization ADD CONSTRAINT FK_C913C01A6804FB49 FOREIGN KEY (recipient) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE BoardMember ADD CONSTRAINT FK_D9517B2ED665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE BoardMember ADD CONSTRAINT FK_D9517B2EEFBA85FF292FAD512F37B76A76CE1878B79BB36 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D326C79F4B FOREIGN KEY (slogan_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D3D9F966B FOREIGN KEY (description_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D318F45C82 FOREIGN KEY (website_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D3BB23766C FOREIGN KEY (approver_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Company ADD CONSTRAINT FK_800230D3502BCAA2 FOREIGN KEY (approvableText_id) REFERENCES ApprovableText (id)');
        $this->addSql('ALTER TABLE CompanyPackage ADD CONSTRAINT FK_181DA527979B1AD6 FOREIGN KEY (company_id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE CompanyPackage ADD CONSTRAINT FK_181DA5277294869C FOREIGN KEY (article_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE CompanyUpdate ADD CONSTRAINT FK_E13E3542108B7592 FOREIGN KEY (original_id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE CompanyUpdate ADD CONSTRAINT FK_E13E3542F4792058 FOREIGN KEY (proposal_id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE CompanyUser ADD CONSTRAINT FK_E2A56B32BF396750 FOREIGN KEY (id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE SimilarCourse ADD CONSTRAINT FK_C56C679ABFB7ED9E FOREIGN KEY (course_code) REFERENCES Course (code)');
        $this->addSql('ALTER TABLE SimilarCourse ADD CONSTRAINT FK_C56C679ACD579B90 FOREIGN KEY (similar_course_code) REFERENCES Course (code)');
        $this->addSql('ALTER TABLE CourseDocument ADD CONSTRAINT FK_90F07469BFB7ED9E FOREIGN KEY (course_code) REFERENCES Course (code)');
        $this->addSql('ALTER TABLE Decision ADD CONSTRAINT FK_7DDADC1E602FAFFB96F82E16 FOREIGN KEY (meeting_type, meeting_number) REFERENCES Meeting (type, number)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A61871179CD6 FOREIGN KEY (name_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A61864D218E FOREIGN KEY (location_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A61818F45C82 FOREIGN KEY (website_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A618D9F966B FOREIGN KEY (description_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A618464E68B FOREIGN KEY (attachment_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A618F44CABFF FOREIGN KEY (package_id) REFERENCES CompanyPackage (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A61812469DE2 FOREIGN KEY (category_id) REFERENCES JobCategory (id)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A618BB23766C FOREIGN KEY (approver_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Job ADD CONSTRAINT FK_C395A618502BCAA2 FOREIGN KEY (approvableText_id) REFERENCES ApprovableText (id)');
        $this->addSql('ALTER TABLE JobLabelAssignment ADD CONSTRAINT FK_42CB55B5BE04EA9 FOREIGN KEY (job_id) REFERENCES Job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE JobLabelAssignment ADD CONSTRAINT FK_42CB55B5DD1E79DF FOREIGN KEY (joblabel_id) REFERENCES JobLabel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE JobCategory ADD CONSTRAINT FK_9701A2A671179CD6 FOREIGN KEY (name_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE JobCategory ADD CONSTRAINT FK_9701A2A6A8BEABC FOREIGN KEY (pluralName_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE JobCategory ADD CONSTRAINT FK_9701A2A6311966CE FOREIGN KEY (slug_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE JobLabel ADD CONSTRAINT FK_ECF91BE071179CD6 FOREIGN KEY (name_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE JobLabel ADD CONSTRAINT FK_ECF91BE0BF69284D FOREIGN KEY (abbreviation_id) REFERENCES CompanyLocalisedText (id)');
        $this->addSql('ALTER TABLE JobUpdate ADD CONSTRAINT FK_961CE301108B7592 FOREIGN KEY (original_id) REFERENCES Job (id)');
        $this->addSql('ALTER TABLE JobUpdate ADD CONSTRAINT FK_961CE301F4792058 FOREIGN KEY (proposal_id) REFERENCES Job (id)');
        $this->addSql('ALTER TABLE Keyholder ADD CONSTRAINT FK_3C5F7B4DD665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Keyholder ADD CONSTRAINT FK_3C5F7B4DEFBA85FF292FAD512F37B76A76CE1878B79BB36 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE LoginAttempt ADD CONSTRAINT FK_C137201BA76ED395 FOREIGN KEY (user_id) REFERENCES User (lidnr)');
        $this->addSql('ALTER TABLE LoginAttempt ADD CONSTRAINT FK_C137201B979B1AD6 FOREIGN KEY (company_id) REFERENCES CompanyUser (id)');
        $this->addSql('ALTER TABLE MaxActivities ADD CONSTRAINT FK_1BE5E0C5E4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE MaxActivities ADD CONSTRAINT FK_1BE5E0C5EC8B7ADE FOREIGN KEY (period_id) REFERENCES ActivityOptionCreationPeriod (id)');
        $this->addSql('ALTER TABLE MeetingDocument ADD CONSTRAINT FK_45407F4E602FAFFB96F82E16 FOREIGN KEY (meeting_type, meeting_number) REFERENCES Meeting (type, number)');
        $this->addSql('ALTER TABLE MeetingMinutes ADD CONSTRAINT FK_5BE9DD26602FAFFB96F82E16 FOREIGN KEY (meeting_type, meeting_number) REFERENCES Meeting (type, number)');
        $this->addSql('ALTER TABLE members_mailinglists ADD CONSTRAINT FK_5AD357D9D665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE members_mailinglists ADD CONSTRAINT FK_5AD357D95E237E06 FOREIGN KEY (name) REFERENCES MailingList (name)');
        $this->addSql('ALTER TABLE NewCompanyUser ADD CONSTRAINT FK_91B5005EBF396750 FOREIGN KEY (id) REFERENCES Company (id)');
        $this->addSql('ALTER TABLE NewUser ADD CONSTRAINT FK_9676D507D665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Organ ADD CONSTRAINT FK_46C39B8EEFBA85FF292FAD512F37B76A76CE1878B79BB36 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE organs_subdecisions ADD CONSTRAINT FK_6177E308E4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE organs_subdecisions ADD CONSTRAINT FK_6177E308602FAFFB96F82E1690E0342DEF6BE237DD50EB88 FOREIGN KEY (meeting_type, meeting_number, decision_point, decision_number, subdecision_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE OrganInformation ADD CONSTRAINT FK_DD810E34E4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE OrganInformation ADD CONSTRAINT FK_DD810E34BB23766C FOREIGN KEY (approver_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE OrganMember ADD CONSTRAINT FK_E5CB2C7DE4445171 FOREIGN KEY (organ_id) REFERENCES Organ (id)');
        $this->addSql('ALTER TABLE OrganMember ADD CONSTRAINT FK_E5CB2C7DD665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE OrganMember ADD CONSTRAINT FK_E5CB2C7DEFBA85FF292FAD512F37B76A76CE1878B79BB36 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE Page ADD CONSTRAINT FK_B438191E12469DE2 FOREIGN KEY (category_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Page ADD CONSTRAINT FK_B438191EDB5A7180 FOREIGN KEY (subCategory_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Page ADD CONSTRAINT FK_B438191E71179CD6 FOREIGN KEY (name_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Page ADD CONSTRAINT FK_B438191EA9F87BD FOREIGN KEY (title_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Page ADD CONSTRAINT FK_B438191E84A0A3ED FOREIGN KEY (content_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Photo ADD CONSTRAINT FK_D576AB1C1137ABCF FOREIGN KEY (album_id) REFERENCES Album (id)');
        $this->addSql('ALTER TABLE Poll ADD CONSTRAINT FK_248E557B1E27F6BF FOREIGN KEY (question_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE Poll ADD CONSTRAINT FK_248E557B61220EA6 FOREIGN KEY (creator_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Poll ADD CONSTRAINT FK_248E557BBB23766C FOREIGN KEY (approver_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE PollComment ADD CONSTRAINT FK_C86340FF3C947C0F FOREIGN KEY (poll_id) REFERENCES Poll (id)');
        $this->addSql('ALTER TABLE PollComment ADD CONSTRAINT FK_C86340FF34A71B45 FOREIGN KEY (user_lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE PollOption ADD CONSTRAINT FK_FEFE970B3C947C0F FOREIGN KEY (poll_id) REFERENCES Poll (id)');
        $this->addSql('ALTER TABLE PollOption ADD CONSTRAINT FK_FEFE970B698D3548 FOREIGN KEY (text_id) REFERENCES FrontpageLocalisedText (id)');
        $this->addSql('ALTER TABLE PollVote ADD CONSTRAINT FK_B568B0883C947C0F FOREIGN KEY (poll_id) REFERENCES Poll (id)');
        $this->addSql('ALTER TABLE PollVote ADD CONSTRAINT FK_B568B088A7C41D6F FOREIGN KEY (option_id) REFERENCES PollOption (id)');
        $this->addSql('ALTER TABLE PollVote ADD CONSTRAINT FK_B568B088A76ED395 FOREIGN KEY (user_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE ProfilePhoto ADD CONSTRAINT FK_26AA8F6B7E9E4C8C FOREIGN KEY (photo_id) REFERENCES Photo (id)');
        $this->addSql('ALTER TABLE ProfilePhoto ADD CONSTRAINT FK_26AA8F6B7597D3FE FOREIGN KEY (member_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE Signup ADD CONSTRAINT FK_490F1BD9BDD669D6 FOREIGN KEY (signuplist_id) REFERENCES SignupList (id)');
        $this->addSql('ALTER TABLE Signup ADD CONSTRAINT FK_490F1BD934A71B45 FOREIGN KEY (user_lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE SignupField ADD CONSTRAINT FK_B32E149BBDD669D6 FOREIGN KEY (signuplist_id) REFERENCES SignupList (id)');
        $this->addSql('ALTER TABLE SignupField ADD CONSTRAINT FK_B32E149B71179CD6 FOREIGN KEY (name_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE SignupFieldValue ADD CONSTRAINT FK_58203768443707B0 FOREIGN KEY (field_id) REFERENCES SignupField (id)');
        $this->addSql('ALTER TABLE SignupFieldValue ADD CONSTRAINT FK_582037685F619F6E FOREIGN KEY (signup_id) REFERENCES Signup (id)');
        $this->addSql('ALTER TABLE SignupFieldValue ADD CONSTRAINT FK_58203768A7C41D6F FOREIGN KEY (option_id) REFERENCES SignupOption (id)');
        $this->addSql('ALTER TABLE SignupList ADD CONSTRAINT FK_274D085F81C06096 FOREIGN KEY (activity_id) REFERENCES Activity (id)');
        $this->addSql('ALTER TABLE SignupList ADD CONSTRAINT FK_274D085F71179CD6 FOREIGN KEY (name_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE SignupOption ADD CONSTRAINT FK_580348EB443707B0 FOREIGN KEY (field_id) REFERENCES SignupField (id)');
        $this->addSql('ALTER TABLE SignupOption ADD CONSTRAINT FK_580348EBF920BBA2 FOREIGN KEY (value_id) REFERENCES ActivityLocalisedText (id)');
        $this->addSql('ALTER TABLE SubDecision ADD CONSTRAINT FK_F0D6EE40602FAFFB96F82E1690E0342DEF6BE237 FOREIGN KEY (meeting_type, meeting_number, decision_point, decision_number) REFERENCES Decision (meeting_type, meeting_number, point, number)');
        $this->addSql('ALTER TABLE SubDecision ADD CONSTRAINT FK_F0D6EE40D665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE SubDecision ADD CONSTRAINT FK_F0D6EE40EFBA85FF292FAD512F37B76A76CE1878B79BB36 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number, r_sequence) REFERENCES SubDecision (meeting_type, meeting_number, decision_point, decision_number, sequence)');
        $this->addSql('ALTER TABLE SubDecision ADD CONSTRAINT FK_F0D6EE40EFBA85FF292FAD512F37B76A76CE187 FOREIGN KEY (r_meeting_type, r_meeting_number, r_decision_point, r_decision_number) REFERENCES Decision (meeting_type, meeting_number, point, number)');
        $this->addSql('ALTER TABLE Tag ADD CONSTRAINT FK_3BC4F1637E9E4C8C FOREIGN KEY (photo_id) REFERENCES Photo (id)');
        $this->addSql('ALTER TABLE Tag ADD CONSTRAINT FK_3BC4F1637597D3FE FOREIGN KEY (member_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE User ADD CONSTRAINT FK_2DA17977D665E01D FOREIGN KEY (lidnr) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE UserRole ADD CONSTRAINT FK_A8503F73111993FE FOREIGN KEY (lidnr_id) REFERENCES User (lidnr)');
        $this->addSql('ALTER TABLE Vote ADD CONSTRAINT FK_FA222A5A7E9E4C8C FOREIGN KEY (photo_id) REFERENCES Photo (id)');
        $this->addSql('ALTER TABLE Vote ADD CONSTRAINT FK_FA222A5AEBB4B8AD FOREIGN KEY (voter_id) REFERENCES Member (lidnr)');
        $this->addSql('ALTER TABLE WeeklyPhoto ADD CONSTRAINT FK_E5D6E8E07E9E4C8C FOREIGN KEY (photo_id) REFERENCES Photo (id)');
        // phpcs:enable SlevomatCodingStandard.Functions.RequireMultiLineCall.RequiredMultiLineCall
    }

    public function down(Schema $schema): void
    {
        // phpcs:disable SlevomatCodingStandard.Functions.RequireMultiLineCall.RequiredMultiLineCall
        $this->throwIrreversibleMigrationException();
        // phpcs:enable SlevomatCodingStandard.Functions.RequireMultiLineCall.RequiredMultiLineCall
    }
}
