<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate("Add banner") ?></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3><?= sprintf($this->translate("You have currently got %s days left to place a banner."), $company->getBannerCredits()) ?></h3>
            </div>
        </div>
        <?php
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->partial('partial/company/company/editors/package.phtml', ['form' => $form, 'type' => 'banner']);
        echo $this->form()->closeTag($form);?>
    </div>
</section>
