<div class="container">
    <section class="section">
        <div class="row">
            <div class="col-md-12">
                <h1>Add highlight</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3><? echo "You have currently got " . $company->getHighlightCredits() . " days left to highlight a vacancy."; ?></h3>
            </div>
        </div>
        <?php
        $form->setAttribute('class', 'form-horizontal');
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->partial('partial/company/company/editors/package.phtml', ['form' => $form, 'type' => 'highlight']);
        echo $this->form()->closeTag($form);?>

        <div class="row">
            <div class="col-md-8">

                <h2><?= $this->translate('Active highlights') ?></h2>
                <?php if (count($currentHighlights) > 0): ?>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>
                                <?= $this->translate('Name'); ?>
                            </th>
                            <th>
                                <?= $this->translate('Expiration date'); ?>
                            </th>
                            <th>
                                <?= $this->translate('Actions')?>
                            </th>
                        </tr>
                        </thead>
                        <?php foreach ($currentHighlights as &$highlight): ?>
                            <tr>
                                <td>
                                    <?php echo $this->translate($highlight['name']) ?>
                                </td>
                                <td>
                                    <?php echo $this->translate($highlight['expires']->format('Y-m-d') )?>
                                </td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="<?= $this->url("admin_company/editCompany/editPackage",
                                        [
                                            "slugCompanyName" => $company->getSlugName(),
                                            "packageId" => $highlight['id']
                                        ]
                                    ); ?>">
                                        <?= $this->translate('edit'); ?></a>
                                    <button type="button" class="btn btn-danger btn-xs"
                                            onclick="Company.Admin.deletePackage('<?= $company->getSlugName() ?>', '<?= $highlight['id'] ?>')"
                                            data-toggle="modal"
                                            data-target="#deleteModal">
                                        <?= $this->translate('Delete') ?>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                            aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title"><?= $this->translate('Delete confirmation') ?></h4>
                                </div>
                                <div class="modal-body">
                                    <p><?= $this->translate('Are you sure you want to delete this package?') ?> </p>
                                    <p class="options">
                                    </p>
                                </div>
                                <div class="modal-footer">
                                    <form id="deleteForm" method="POST">
                                        <input type="submit" name="submit" value="<?= $this->translate('Delete package') ?>"
                                               class="btn btn-danger"/>
                                        <button type="button" class="btn" data-dismiss="modal"><?= $this->translate('Cancel') ?></button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if (count($currentHighlights) === 0): ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->translate("Currently there are no active highlights, you can add a highlight above")?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </section>
</div>
