<?php
// set title
$this->headTitle($this->translate('Company Account'));

$accountStyle = "panel-image-disabled"; //Style for vacancies and activities buttons (used to specify disabled and enabled style)
$bannerStyle = "panel-image";  //Style for banner button (used to specify disabled and enabled style)
$highlightStyle = "panel-image";  //Style for highlight button (used to specify disabled and enabled style)

$accountActive = False; //False if account is inactive
$bannerActive = True;  //False if banner credits are 0
$highlightActive = True;  //False if highlight credits are 0

//determine whether the account is active or not
$now = new DateTime();
if (!empty($companyPackageInfo)) {
    if ($companyPackageInfo[0]->getExpirationDate() > $now) {
        $accountActive = True;
        $accountStyle = "panel-image";
    }
}

//determine if banner upload is active
if ($companyInfo[0]->getBannerCredits() <= 0 || !$accountActive){
    $bannerActive = False;
    $bannerStyle = "panel-image-disabled";
}

//determine if highlightling is active
if ($companyInfo[0]->getHighLightCredits() <= 0 || !$accountActive){
    $highlightActive = False;
    $highlightStyle = "panel-image-disabled";
}

?>

<div class="container">
    <section class="section">
        <div class="row">

            <?php if (!empty($companyPackageInfo)):
                $diff = $now->diff($companyPackageInfo[0]->getExpirationDate());

                //If vacancy package will expire within one month display notification
                if ($diff->m === 0 && $diff->d >= 0 && $companyPackageInfo[0]->getExpirationDate() >= $now): ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <strong><?= $this->translate("Vacancy package will expire within one month!") ?></strong>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php
            //If vacancy package has expired display notification
            if (!$accountActive): ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <strong><?= $this->translate("Vacancy package has expired, please contact an administrator.") ?></strong>
                    </div>
                </div>
            <?php endif; ?>


            <div class="col-md-12">
                <h1><?= $this->translate('Company') ?></h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-md-12">
                <h2><?= $this->translate('Personal') ?></h2>
                <div class="grid grid-col-5">


                    <a href="<?= $this->url('companyaccount/profile') ?>" class="panel panel-image align-middle"
                       id="inactiveMessage">
                        <div class="big-icon fas fa-user"></div>
                        <div class="panel-heading"><?= $this->translate('Profile') ?></div>
                    </a>


                    <a href="<?= $this->url('user/default', ['action' => 'passwordCompany']) ?>"
                       class="panel panel-image align-middle">
                        <div class="big-icon fas fa-lock"></div>
                        <div class="panel-heading"><?= $this->translate('Change password') ?></div>
                    </a>

                    <a href="<?= $this->url('user/default', ['action' => 'companyLogout']) ?>"
                       class="panel panel-image align-middle">
                        <div class="big-icon fas fa-lock"></div>
                        <div class="panel-heading"><?= $this->translate('Logout') ?></div>
                    </a>

                    <a href="<?= $this->url('companyaccount/settings') ?>" class="panel panel-image align-middle">
                        <div class="big-icon fas fa-cog"></div>
                        <div class="panel-heading"><?= $this->translate('Settings') ?></div>
                    </a>

                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12">
                <h2><?= $this->translate('Company content') ?></h2>
                <div class="grid grid-col-5">

                    <div class="panel-disabled">
                    <a class="<?= "panel $accountStyle align-middle" ?>"
                       <?php if ($accountActive): ?>href="<?= $this->url('companyaccount/vacancies') ?>"<?php endif; ?>>
                        <div  class="big-icon fas fa-list"></div>
                        <div  class="panel-heading"><?= $this->translate('Vacancies') ?></div>
                    </a>
                        <?php if (!$accountActive): ?>
                            <div class="panel-warning"><div class="panel-warning-text"><?= $this->translate("Disabled, vacancy package has expired.") ?></div></div>
                        <?php endif; ?>
                    </div>
                    <div class="panel-disabled">
                    <a  class="<?= "panel $bannerStyle align-middle" ?>"
                       <?php if ($bannerActive && $accountActive): ?>href="<?= $this->url('companyaccount/bannerupload') ?>"<?php endif; ?>>

                        <div class="big-icon fas fa-flag"></div>
                        <div class="panel-heading"><?= $this->translate('Banner') ?></div>
                    </a>
                        <?php if (!$bannerActive || !$accountActive): ?>
                            <div class="panel-warning">
                                <div class="panel-warning-text">
                                    <?php if (!$bannerActive && $accountActive){
                                        echo $this->translate("Disabled, no more banner days left.");
                                    }elseif(!$accountActive){
                                        echo $this->translate("Disabled, vacancy package has expired.");
                                    } ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <div class="panel-disabled">
                    <a class="<?= "panel $highlightStyle align-middle" ?>"
                       <?php if ($highlightActive && $accountActive): ?>href="<?= $this->url('companyaccount/highlight') ?>"<?php endif; ?>>

                        <div class="big-icon fas fa-check"></div>
                        <div class="panel-heading"><?= $this->translate("Highlight vacancies") ?></div>
                    </a>
                        <?php if (!$highlightActive || !$accountActive): ?>
                            <div class="panel-warning">
                                <div class="panel-warning-text">
                                    <?php if (!$highlightActive && $accountActive){
                                        echo $this->translate("Disabled, no more highlight days left.");
                                    }elseif(!$accountActive){
                                        echo $this->translate("Disabled, vacancy package has expired.");
                                    } ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>

                </div>
            </div>
        </div>

        <!--Active vacancies feed -->
        <div class="row mt-3">
            <div class="col-md-6 mt-2">
                <h2><?= $this->translate('Vacancies') ?></h2>

                <?php if (count($vacancies) > 0): ?>
                    <div class="panel panel-default">
                        <?php foreach ($vacancies as &$vacancy): ?>
                            <div class="panel-heading">
                                <strong><?= $this->translate($vacancy->getName()) ?></strong>
                                <div align="right">
                                <?php if ($approved[$vacancy->getId()]) {
                                    echo $this->translate("Approved");
                                } else {
                                    echo $this->translate("Awaiting Approval");
                                }?>
                                </div>
                            </div>
                            <div class="panel-body">

<!--                                --><?//= $this->translate($vacancy->getDescription()) ?>
                                <a href="<?= $this->url("companyaccount/vacancies/editvacancy",
                                    [
                                        "slugCompanyName" => $vacancy->getCompany()->getSlugName(),
                                        "packageId" => $vacancy->getPackage()->getId(),
                                        "languageNeutralJobId" => $vacancy->getLanguageNeutralId(),
                                    ]
                                ); ?>"><?= $this->translate("go to vacancy") ?></a>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <hr/>
                <?php endif; ?>

                <?php if (count($vacancies) === 0): ?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <?= $this->translate("Currently there are no active vacancies, ") ?>
                            <a href="<?= $this->url('companyaccount/vacancies/createvacancy') ?>"><?= $this->translate("add new vacancy.") ?></a>
                        </div>
                    </div>
                <?php endif; ?>

            </div>
        </div>

    </section>
</div>
