<!-- Position correctly using section and div -->
<section class="section">
    <div class="container">

        <!-- Title -->
        <h1><?= $this->translate('Edit Profile'); ?></h1>

        <!-- Logos shown at top of the form -->
        <div class="row">
            <div class="col-md-6">
                <h2><?= $this->translate('Dutch logo') ?></h2>
                <?php $translation = $company->getTranslationFromLocale('nl'); ?>
                <?php if (!is_null($translation)): ?>
                    <img class="img-responsive" src="<?= $this->fileUrl($translation->getLogo()) ?>"/>
                <?php endif; ?>
            </div>
            <div class="col-md-6">
                <h2><?= $this->translate('English logo') ?></h2>
                <?php $translation = $company->getTranslationFromLocale('en'); ?>
                <?php if (!is_null($translation)): ?>
                    <img class="img-responsive" src="<?= $this->fileUrl($translation->getLogo()) ?>"/>
                <?php endif; ?>
            </div>
        </div>
        <hr>
        <!-- Prepare the form -->
        <?php $form->prepare() ?>
        <?= $this->form()->openTag($form) ?>
        <!-- Add the form -->
        <?= $this->partial('partial/company/admin/editors/company.phtml',
            ['form' => $form]
        ); ?>
        <br>
        <?php
        // Save button
        $submit = $form->get('submit');
        $submit->setLabel($this->translate('Save'));
        $submit->setAttribute('class', 'btn btn-primary pull-right');
        ?>
        <div class="form-group">
            <?= $this->formButton($submit) ?>
        </div>
        <?= $this->form()->closeTag(); ?>

        <!-- pop-up message to appear when clicking save -->
        <div class="modal fade" id="changeModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <!-- pop-up header/ title -->
                    <div class="modal-header">
                        <h4 class="modal-title"><?= $this->translate('Changes submitted') ?></h4>
                    </div>
                    <!-- pop-up text -->
                    <div class="modal-body">
                        <p><?= $this->translate('Your changes have successfully been submitted and are now awaiting approval.') ?> </p>
                        <p><?= $this->translate('You will be redirected in 5 seconds.') ?> </p>
                        <p class="options">
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>


