<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<html>
    <body>
        <?php if (isset($signupList)): ?>
            <h1><?= $this->translate('Details for activity') . ' ' . $activity->getName()->getText($lang) . ' - ' . $signupList->getName()->getText($lang) ?></h1>
        <?php else: ?>
            <h1><?= $this->translate('Details for activity') . ' ' . $activity->getName()->getText($lang) ?></h1>
        <?php endif; ?>
        <?php if (isset($signupList)): ?>
            <?= $this->partial('activity/admin/participantsTable.phtml', [
                'activity' => $activity,
                'signupList' => $signupList,
                'detailed' => true,
                'pdf' => true,
            ]); ?>
        <?php else: ?>
            <?= $this->partial('activity/admin/participantsTable.phtml', [
                'activity' => $activity,
                'pdf' => true,
            ]); ?>
        <?php endif; ?>
    </body>
</html>
