<?php
/* An activity overview list. Parameters:
 * $header
 * $activities
 * $admin
 */
?>
<h1><?= $header ?></h1>
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th><?= $this->translate('Dutch name') ?></th>
        <th><?= $this->translate('English name') ?></th>
        <th><?= $this->translate('Start date') ?></th>
        <th><?= $this->translate('Subscriptions') ?></th>
        <th><?= $this->translate('Organ') ?></th>
        <th><?= $this->translate('Submitter') ?></th>
        <th><?= $this->translate('Update status') ?></th>
        <?php if (!$admin): ?>
        <th><?= $this->translate('Approved') ?></th>
        <?php endif ?>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($activities as $activity): ?>
        <tr>
            <td><?= $activity->getId() ?></td>
            <td><a href="<?= $this->url('activity/view',['id' => $activity->getId()]) ?>"><?= $this->escapeHtml($activity->getName()->getValueNL()) ?></a></td>
            <td><a href="<?= $this->url('activity/view',['id' => $activity->getId()]) ?>"><?= $this->escapeHtml($activity->getName()->getValueEN()) ?></a></td>
            <td><?= $activity->getBeginTime()->format('Y-m-d') ?></td>
            <td><?= is_null($activity->getSignups()) ? 0 : count($activity->getSignups()) ?></td>
            <td><?= is_null($activity->getOrgan()) ? $this->translate('None') : $this->escapeHtml($activity->getOrgan()->getAbbr())  ?></td>
            <td><?= $this->escapeHtml($activity->getCreator()->getMember()->getFullName()) ?></td>
            <?php if($admin): ?>
            <td><?= $activity->getUpdateProposal()->count() === 0 ? '(-)' :
                    '<a href="' . $this->url('activity_admin_approval/proposal', ['id' => $activity->getUpdateProposal()->first()->getId()]) .'">' . $this->translate('Update pending') . '</a>' ?></td>
            <?php else: ?>
            <td><?= $activity->getUpdateProposal()->count() === 0 ? '(-)' : $this->translate('Update pending') ?></td>
            <?php endif; ?>
            <?php if (!$admin): ?>
            <td>
                <?php $icons = ['question-sign', 'ok-sign',  'remove-sign'] ?>
                <span class="glyphicon glyphicon-<?= $icons[$activity->getStatus() -1]?>"></span>&nbsp;
            </td>
            <?php endif ?>
            <td>
                <a class="btn btn-primary btn-xs" href="<?= $this->url('activity_admin/update', ['id' => $activity->getId()]) ?>"><?= $this->translate('Edit') ?></a>
                <?php if($admin): ?>
                <a class="btn btn-primary btn-xs" href="<?= $this->url('activity_admin_approval/view', ['id' => $activity->getId()]) ?>"><?= $this->translate('(dis)approve') ?></a>
                <?php endif; ?>
                <a class="btn btn-primary btn-xs" href="<?= $this->url('activity_admin/participants', ['id' => $activity->getId()]) ?>"><?= $this->translate('Participants') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

