<?php $lang = $this->plugin('translate')->getTranslator()->getLocale(); ?>
<table class="table table-bordered" style="width: 100%" border="1">
    <thead>
        <tr>
            <th></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Email') ?></th>
            <th><?= $this->translate('Type') ?></th>
            <?php foreach ($activity->getFields() as $field): ?>
                <th><?= $this->escapeHtml($field->getName()->getText($lang)) ?></th>
            <?php endforeach; ?>
        </tr>
    </thead>
    <?php $i = 1; $mailAllString = ''; ?>
    <?php foreach($activity->getSignUps() as $signup): ?>
        <tr>
            <td><?php echo $i; $i = $i + 1; $email = $this->escapeHtml($signup->getEmail()); $mailAllString .= $email . '; '; ?></td>
            <td><?= $this->escapeHtml($signup->getFullName()) ?></td>
            <td>
                <a href="mailto:<?= $email ?>">
                    <?= $email ?>
                </a>
            </td>
            <?php if ($signup instanceof Activity\Model\UserActivitySignup): ?>
            <td><?= $this->translate('User')?></td>
            <?php else: ?>
            <td>
                <?= $this->translate('External')?>
                <?php $externalSignoffForm->setAttribute('action', $this->url('activity_admin/externalSignoff', ['id' => $signup->getId()]));
                $externalSignoffForm->prepare();
                echo $this->form()->openTag($externalSignoffForm);
                echo $this->formElement($externalSignoffForm->get('security'));
                $submit = $externalSignoffForm->get('submit');
                $submit->setAttribute('class', 'btn btn-primary btn-xs');
                echo $this->formSubmit($submit);
                echo $this->form()->closeTag();
                ?>
            </td>
            <?php endif; ?>
            <?php foreach ($activity->getFields() as $field): ?>
                <?php foreach($signup->getFieldValues() as $fieldValue):?>
                    <?php if ($fieldValue->getField()->getId() === $field->getId()): ?>
                        <td>
                            <?php
                            switch ($field->getType()) {
                                case 0:
                                    echo $this->escapeHtml($fieldValue->getValue());
                                    break;
                                case 1:
                                    if ($fieldValue->getValue()) {
                                        echo $this->translate('Yes');
                                    } else {
                                        echo $this->translate('No');
                                    }
                                    break;
                                case 2:
                                    echo $fieldValue->getValue();
                                    break;
                                case 3:
                                    if ($lang === 'nl') {
                                        echo $fieldValue->getOption()->getValue();
                                    } else {
                                        echo $fieldValue->getOption()->getValueEn();
                                    }
                                    break;
                            }
                            ?>
                        </td>
                    <?php endif; ?>
                <?php endforeach;?>
            <?php endforeach; ?>
        </tr>
    <?php endforeach;?>
    </tbody>
   <tfoot>
       <tr>
        <td></td>
        <td></td>
        <td>
            <a href="mailto:?bcc=<?= substr($mailAllString, 0, -2) ?>">
                <?= $this->translate('Mail everybody') ?>
            </a>
        </td>
        <td></td>
        <?php foreach ($activity->getFields() as $field): ?>
            <td></td>
        <?php endforeach; ?>
        </tr>
    </tfoot>
</table>
