<?php

declare(strict_types=1);

use Activity\Model\Activity as ActivityModel;
use Application\Form\ModifyRequest as RequestForm;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ActivityModel $activity
 * @var bool $canSeeTimeOfSignup
 * @var RequestForm $externalSignoffForm
 */

// set title
$this->headTitle($this->escapeHtml($this->localiseText($activity->getName())));
$this->headTitle($this->translate('Participants'));

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Activities'), true, $this->url('activity_admin'))
    ->addBreadcrumb($this->localiseText($activity->getName()), true, $this->url(
        'activity_admin_approval/view',
        [
            'id' => $activity->getId()
        ],
    ))
    ->addBreadcrumb($this->translate('Participants'));
?>
<div class="row admin-section">
    <div class="col-md-12">
        <h1><?= $this->escapeHtml($this->localiseText($activity->getName())) ?></h1>
    </div>
</div>
<?php if (isset($signupLists)): ?>
    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs">
                <li role="presentation" <?= isset($signupList) ? '' : 'class="active"' ?>>
                    <a href="<?= $this->url('activity_admin/participants', ['id' => $activity->getId()]) ?>"><?= $this->translate('General') ?></a>
                </li>
                <?php foreach ($signupLists as $list): ?>
                    <li role="presentation" <?= isset($signupList) ? ($signupList->getId() === $list['id'] ? 'class="active"' : '') : '' ?>>
                        <a href="<?= $this->url('activity_admin/participants', ['id' => $activity->getId(), 'signupList' => $list['id']]) ?>"><?= $this->escapeHtml($this->localiseText($list['name'])) ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-12">
        <?php if (!isset($signupList)): ?>
            <p><?= $this->translate('Here you can find everyone who signed up for this activity (may contain duplicates). Using the tabs above you can navigate to the different sign-up lists of this activity. From there you can remove external participants and (when supplied) view additional signup information from each participant.') ?></p>
        <?php else: ?>
            <p><?= $this->translate('Here you can find everyone who signed up to this sign-up list. Here you can add or remove external participants and view detailed information regarding the signup of all participants. Please note that fields that are marked with an \'¹\' contain sensitive data and should be treated with the utmost care to prevent unauthorized access or disclosure.') ?></p>
        <?php endif; ?>
    </div>
    <div class="col-md-12">
        <h2><?= $this->translate('Participants') ?></h2>
    </div>
    <div class="col-md-12">
        <?php if (isset($signupList)): ?>
            <?= $this->partial('activity/admin/participantsTable.phtml', [
                'activity' => $activity,
                'signupList' => $signupList,
                'detailed' => true,
                'canSeeTimeOfSignup' => $canSeeTimeOfSignup,
                'externalSignoffForm' => $externalSignoffForm,
            ]); ?>
        <?php else: ?>
            <?= $this->partial('activity/admin/participantsTable.phtml', [
                'activity' => $activity,
            ]); ?>
        <?php endif; ?>
    </div>
    <div class="col-md-12">
        <?php if (isset($externalSignupForm)): //display the external signup form ?>
            <button class="btn btn-primary btn-lg" type="button" data-toggle="modal"
                    data-target="#signupModal" aria-hidden="true" aria-controls="signupModal">
                <span class="fas fa-user-plus"></span> <?= $this->translate('Subscribe external participant') ?>
            </button>
            <?= $this->partial('partial/signupForm', [
                'form' => $externalSignupForm,
                'activity' => $activity,
                'signupList' => $signupList,
            ])
            ?>
            <?php if (isset($reopen) && $reopen): ?>
                <script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
                    document.addEventListener("DOMContentLoaded", function() {
                        $('#signupModal').modal('show');
                    });
                </script>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
