<?php

declare(strict_types=1);

use Activity\Model\Activity as ActivityModel;
use Activity\Model\UserSignup;
use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ActivityModel $activity
 */

?>
<?php
$activityApproved = ActivityModel::STATUS_APPROVED === $activity->getStatus();
$attendanceModeTimeStarted = new DateTime() > $activity->getBeginTime()->modify('-30 min');
$attendanceModeTimeEnded = new DateTime() > $activity->getEndTime()->modify('+30 min');
?>
<div data-controller="participants-table"
    <?php if (isset($signupList)): ?>
    data-participants-table-mark-present-url-value="<?= $this->escapeHtml($this->url(
                                                        'activity_admin/markPresent',
                                                        ['id' => -1],
                                                    )) ?>"
    data-participants-table-draw-url-value="<?= $this->escapeHtml($this->url('activity_admin/draw')) ?>"
    <?php endif ?>>
    <table class="table table-bordered" style="width: 100%" border="1">
        <thead>
            <tr>
                <th>#</th>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Email') ?></th>
                <?php if ((
                    $activityApproved &&
                    $attendanceModeTimeStarted &&
                    !$attendanceModeTimeEnded
                ) || (
                    isset($signupList) &&
                    $signupList?->isPresenceTaken()
                )): ?>
                    <th><?= $this->translate('Presence') ?></th>
                <?php endif ?>
                <th><?= $this->translate('Type') ?></th>
                <th><?= $this->translate('Generation') ?></th>
                <?php
                if (isset($canSeeTimeOfSignup) && $canSeeTimeOfSignup): ?>
                    <th><?= $this->translate('Date and time') ?></th>
                <?php
                endif; ?>
                <?php
                if (!isset($signupList)): ?>
                    <th><?= $this->translate('Sign-up List') ?></th>
                <?php
                endif; ?>
                <?php
                if (isset($detailed) && isset($signupList)): ?>
                    <?php
                    foreach ($signupList->getFields() as $field): ?>
                        <th>
                            <?= $this->escapeHtml($this->localiseText($field->getName())) . ($field->isSensitive() ? '¹' : '') ?>
                        </th>
                    <?php
                    endforeach; ?>
                <?php
                endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            $allEmailAddresses = []; ?>
            <?php
            if (!isset($signupList)) {
                $iterator = [];
                foreach ($activity->getSignupLists() as $list) {
                    foreach ($list->getSignups() as $signup) {
                        $iterator[] = $signup;
                    }
                }
            } else {
                $iterator = $signupList->getSignUps();
            } ?>
            <?php
            foreach ($iterator as $signup): ?>
                <tr
                    data-participants-table-target="row"
                    data-search-id="<?= $this->escapeHtml($signup->getId()) ?>"
                    data-search-name="<?= $this->escapeHtml(json_encode(explode(" ", $signup->getFullName()))) ?>"
                    data-search-email="<?= $this->escapeHtml($signup->getEmail()) ?>"
                    data-present="<?= $this->escapeHtml($signup->isPresent()) ?>">
                    <td>
                        <?php
                        echo $i;
                        $i = $i + 1;

                        $email = $signup->getEmail();
                        if (null !== $email) {
                            $email = $this->escapeHtml($email);
                            $allEmailAddresses[] = $email;
                        }
                        ?>
                    </td>
                    <td data-participants-table-controller-name-value="<?= $this->escapeHtml($signup->getFullName()) ?>">
                        <?= $this->escapeHtml($signup->getFullName()) ?>
                    </td>
                    <td>
                        <?php
                        if (null !== $email): ?>
                            <a href="mailto:<?= $email ?>">
                                <?= $email ?>
                            </a>
                        <?php
                        else: ?>
                            <?= $this->translate('Unknown') ?>
                        <?php
                        endif; ?>
                    </td>
                    <?php if ((
                        $activityApproved &&
                        $attendanceModeTimeStarted &&
                        !$attendanceModeTimeEnded
                    ) || (
                        isset($signupList) &&
                        $signupList?->isPresenceTaken()
                    )): ?>
                        <td
                            style="text-align: center;"
                            data-participants-table-target="presenceCell"
                            data-row-id="<?= $this->escapeHtml($signup->getId()) ?>">
                            <?php if ($signup->isPresent()) : ?>
                                <span
                                    class=" fas fa-check"
                                    style="color: forestgreen"></span>
                            <?php endif ?>
                            <?php if (!$signup->isDrawn() && !$signup->isPresent()): ?>
                                <span
                                    class=" fas fa-x"
                                    style="color: red"></span>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                    <?php
                    if ($signup instanceof UserSignup): ?>
                        <td>
                            <?= sprintf(
                                $this->translate('User (%s)'),
                                $signup->getUser()->getType()->getName($this->plugin('translate')->getTranslator()),
                            ); ?>
                        </td>
                        <td><?= $signup->getUser()->getGeneration() ?></td>
                    <?php
                    else: ?>
                        <td>
                            <?= $this->translate('External') ?>
                            <?php
                            if (isset($externalSignoffForm)): ?>
                                <?php
                                $externalSignoffForm->setAttribute(
                                    'action',
                                    $this->url('activity_admin/externalSignoff', ['id' => $signup->getId()])
                                );
                                $externalSignoffForm->prepare();
                                echo $this->form()->openTag($externalSignoffForm);
                                echo $this->formElement($externalSignoffForm->get('security'));
                                $submit = $externalSignoffForm->get('submit');
                                $submit->setAttribute('class', 'btn btn-primary btn-xs');
                                echo $this->formSubmit($submit);
                                echo $this->form()->closeTag();
                                ?>
                            <?php
                            endif; ?>
                        </td>
                        <td><?= $this->translate('N/A') ?></td>
                    <?php
                    endif; ?>
                    <?php
                    if (isset($canSeeTimeOfSignup) && $canSeeTimeOfSignup): ?>
                        <td><?= $signup->getCreatedAt()->format('Y-m-d H:i:s') ?></td>
                    <?php
                    endif; ?>
                    <?php
                    if (!isset($signupList)): ?>
                        <td><?= $this->escapeHtml($this->localiseText($signup->getSignupList()->getName())) ?></td>
                    <?php
                    endif; ?>
                    <?php
                    if (isset($detailed)): ?>
                        <?php
                        foreach ($signupList->getFields() as $field): ?>
                            <?php
                            foreach ($signup->getFieldValues() as $fieldValue): ?>
                                <?php
                                if ($fieldValue->getField()->getId() === $field->getId()): ?>
                                    <td>
                                        <?php
                                        switch ($field->getType()) {
                                            case 0:
                                                echo $this->escapeHtml($fieldValue->getValue());
                                                break;
                                            case 1:
                                                if ($fieldValue->getValue() === "Yes") {
                                                    echo $this->translate('Yes');
                                                } else {
                                                    echo $this->translate('No');
                                                }
                                                break;
                                            case 2:
                                                echo $fieldValue->getValue();
                                                break;
                                            case 3:
                                                echo $this->localiseText($fieldValue->getOption()->getValue());
                                                break;
                                        }
                                        ?>
                                    </td>
                                <?php
                                endif; ?>
                            <?php
                            endforeach; ?>
                        <?php
                        endforeach; ?>
                    <?php
                    endif; ?>
                </tr>
            <?php
            endforeach; ?>
        </tbody>
    </table>
    <?php if (!isset($pdf)): ?>
        <div class="row">
            <div class="col-md-12">
                <h2><?= $this->translate('Additional actions') ?></h2>
            </div>
            <div class="col-md-12">
                <a href="mailto:?bcc=<?= implode('; ', array_unique($allEmailAddresses)) ?>">
                    <?= $this->translate('Mail everybody') ?>
                </a>
            </div>
        </div>
    <?php endif; ?>
    <?php if (isset($signupList) && $activityApproved && !$attendanceModeTimeEnded): ?>
        <button class="btn btn-primary btn-lg" type="button"
            aria-hidden="true" data-action="click->participants-table#showDrawModal">
            <span class="fas fa-pencil"></span> <?= $this->translate('Draw') ?>
        </button>
        <div style="height: 3px"></div>
        <dialog class="draw-modal" data-participants-table-target="drawModal">
            <header class="header"><h2>Draw</h2></header>
            <div class="body">
                <p><?= $this->translate('Put the names of the people that have been drawn out in the text area. Please put one full name per line, without any additional commas.') ?></p>
                <textarea rows="8" cols="30" data-participants-table-target="drawTextarea"></textarea>
            </div>
            <footer class="footer">
                <div class="btn btn-outline-secondary"data-action="click->participants-table#closeDrawModal"><?= $this->translate('Cancel') ?></div>
                <div class="btn btn-primary"data-action="click->participants-table#submitDraw"><?= $this->translate('Confirm') ?></div>
            </footer>
        </dialog>
    <?php endif; ?>
    <?php if (isset($signupList) && $activityApproved && $attendanceModeTimeStarted && !$attendanceModeTimeEnded): ?>
        <button class="btn btn-primary btn-lg" type="button"
            aria-hidden="true" data-action="click->participants-table#enterAttendanceMode">
            <span class="fas fa-list"></span> <?= $this->translate('Attendance mode') ?>
        </button>
        <div style="height: 3px"></div>
    <?php endif; ?>
    <div
        data-participants-table-target="searchView"
        class="attendance-mode hidden"
        data-action="keydown.esc->participants-table#leaveAttendanceMode">
        <div class="header">
            <label for="searchbar">
            </label>
            <input
                type="text"
                class="searchbar"
                id="searchbar"
                placeholder="<?= $this->translate('Search for name or email') ?>"
                data-participants-table-target="searchBar"
                data-action="input->participants-table#updateSearchResults">
        </div>
        <div class="result-list" data-participants-table-target="resultList">

        </div>
        <div class="exit-button" data-action="click->participants-table#leaveAttendanceMode">
            <span class="fa fa-arrow-right-from-bracket"></span>
        </div>
        <div class="hidden" data-participants-table-target="presentTableCell">
            <span
                class="fas fa-check"
                style="color: forestgreen"></span>
        </div>
    </div>
</div>
