<?php
$this->headTitle($this->translate('Update activity'));
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/bootstrap-markdown.min.css')
    ->prependStylesheet($this->basePath() . '/css/jquery.datetimepicker.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap-markdown.js')
    ->prependFile($this->basePath() . '/js/activity-create.js')
    ->prependFile($this->basePath() . '/js/jquery.datetimepicker.full.min.js');

$form->prepare();
$form->setAttribute('class', 'form-activity');
?>
<section class="section">
    <div class="container">
        <?= $this->form()->openTag($form) ?>
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate('Update an activity') ?></h1>
            </div>
        </div>
        <hr>
        <?= $this->partial('partial/create', [ 'form' => $form ]) ?>
        <div class="row">
            <div class="col-md-12">
                <?php
                $submit = $form->get('submit')
                    ->setLabel($this->translate('Update Activity'))
                    ->setAttribute('class', 'btn btn-primary');
                ?>
                <div class="form-group">
                    <?= $this->formButton($submit) ?>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</section>

<script>
    $('[name="beginTime"]').datetimepicker();
    $('[name="endTime"]').datetimepicker();
    $('.markdown-editor').each(function() {
      $(this).markdown(
        {
          resize: "both",
          iconlibrary: "fa"
        }
      );
    });
    $(window).load(Activity.updateForm);
</script>
