<div class="container">

<?php if ($admin): ?>
<?= $this->partial('activity/admin/list.phtml', [
    'header' => 'Unapproved Activities',
    'activities' => $unapprovedActivities,
    'admin' => true,
])
?>

<?= $this->partial('activity/admin/list.phtml', [
    'header' => 'Approved Activities',
    'activities' => $approvedActivities,
    'admin' => true,
])
?>

<?= $this->partial('activity/admin/list.phtml', [
    'header' => 'Disapproved Activities',
    'activities' => $disapprovedActivities,
    'admin' => true,
])
?>

<?php else: ?>
<?= $this->partial('activity/admin/list.phtml', [
    'header' => 'Upcoming Activities',
    'activities' => $upcomingActivities,
    'admin' => false,
])
?>
<?php endif; ?>

<h1><?= $this->translate('Old activities') ?></h1>
<?= $this->paginationControl(
    $oldActivityPaginator,
    // the scrolling style
    'elastic',
    'paginator/default',
    [
        'path' => $this->url('activity_admin')
    ]
)
?>
<?php if (!empty($oldActivityPaginator)): ?>
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th><?= $this->translate('Dutch name') ?></th>
        <th><?= $this->translate('English name') ?></th>
        <th><?= $this->translate('Start date') ?></th>
        <th><?= $this->translate('Subscriptions') ?></th>
        <th><?= $this->translate('Organ') ?></th>
        <th><?= $this->translate('Submitter') ?></th>
        <th><?= $this->translate('Approval status') ?></th>
        <?php if ($admin): ?>
        <th></th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>

    <?php foreach($oldActivityPaginator as $activity): ?>
        <tr>
            <td><?= $activity->getId() ?></td>
            <td><a href="<?= $this->url('activity/view',['id' => $activity->getId()]) ?>"><?= $activity->getName() ?></a></td>
            <td><a href="<?= $this->url('activity/view',['id' => $activity->getId()]) ?>"><?= $activity->getNameEn() ?></a></td>
            <td><?= $activity->getBeginTime()->format('Y-m-d') ?></td>
            <td><?= is_null($activity->getSignups()) ? 0 : count($activity->getSignups()) ?></td>
            <td><?= is_null($activity->getOrgan()) ? $this->translate('None') : $activity->getOrgan()->getAbbr()  ?></td>
            <td><?= $activity->getCreator()->getMember()->getFullName() ?></td>
            <td><?= $activity->getStatus() . ($activity->getUpdateProposal()->count() === 0 ? '' : $this->translate('(Update pending)')) ?></td>
            <?php if ($admin): ?>
            <td>
                 <a href="<?= $this->url('activity_admin/update', ['id' => $activity->getId()]) ?>"><?= $this->translate('Update') ?></a>
            </td>
            <?php endif; ?>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

<?php endif; ?>
</div>