<table class="table table-striped">
    <thead>
    <tr>
        <td></td>
        <td><?= $this->translate('Dutch') ?></td>
        <td><?= $this->translate('English') ?></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?php echo $this->translate('Activity id'); ?></td>
        <td><?php echo $this->escapeHtml($activity->getId()); ?></td>
        <td></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Name'); ?></td>
        <td><?php echo $this->escapeHtml($activity->getName()); ?></td>
        <td><?php echo $this->escapeHtml($activity->getNameEn()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Start time'); ?></td>
        <td><?php echo $activity->getBeginTime()->format('Y-m-d H:i') ?></td>
        <td></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('End time'); ?></td>
        <td><?php echo $activity->getEndTime()->format('Y-m-d H:i') ?></td>
        <td></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Location'); ?></td>
        <td><?php echo $this->escapeHtml($activity->getLocation()); ?></td>
        <td><?php echo $this->escapeHtml($activity->getLocationEn()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Costs'); ?></td>
        <td><?php echo $this->escapeHtml($activity->getCosts()); ?></td>
        <td><?php echo $this->escapeHtml($activity->getCostsEn()); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Subscribe'); ?></td>
        <td><?php echo $activity->getCanSignUp() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Only GEWIS'); ?></td>
        <td><?php echo $activity->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
    </tr>

    <?php if ($activity->getStatus() === \Activity\Model\Activity::STATUS_TO_APPROVE): ?>
        <tr>
            <td>
                <a href="<?php echo $this->url('admin_activity/approve', ['id' => $activity->getId()]) ?>">
                    <?php echo $this->translate('Approve'); ?>
                </a>
            </td>
            <td>
                <a href="<?php echo $this->url('admin_activity/disapprove', ['id' => $activity->getId()]) ?>">
                    <?php echo $this->translate('Disapprove'); ?>
                </a>
            </td>
            <td></td>
        </tr>

    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_APPROVED): ?>
        <tr>
            <td>
            </td>
            <td>
                <a href="<?php echo $this->url('admin_activity/reset', ['id' => $activity->getId()]) ?>">
                    <?php echo $this->translate('Revoke approval'); ?>
                </a>
            </td>
            <td></td>
        </tr>

    <?php elseif ($activity->getStatus() === \Activity\Model\Activity::STATUS_DISAPPROVED): ?>
        <tr>
            <td>
            </td>
            <td>
                <a href="<?php echo $this->url('admin_activity/reset', ['id' => $activity->getId()]) ?>">
                    <?php echo $this->translate('Revoke disapproval'); ?>
                </a>
            </td>
            <td></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td>
            <a href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                <?= $this->translate('View details / subscriptions') ?>
            </a>
        </td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>
