<!-- This probably isn't very cosher, but I cannot into css. 
     Someone who can: feel free to clean up -->
<style>
    .modified{
        background-color: #ffff99;
    }
</style>
<?php 
    $new = $proposal->getNew();
    $old = $proposal->getOld();
    function updateTd($new, $old, $context){
        return ($old==$new ? 
            '<td>' . $context->escapeHtml($new) :
            '<td class=\'modified\'>' . $context->escapeHtml($new)) . '</td>';
    }
?>
<table class="table table-striped">
    <thead>
    <tr>
        <td></td>
        <td><?= $this->translate('Original Dutch') ?></td>
        <td><?= $this->translate('Updated Dutch') ?></td>        
        <td><?= $this->translate('Orignal English') ?></td>
        <td><?= $this->translate('Updated English') ?></td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?= $this->translate('Activity id'); ?></td>
        <td><?= $this->escapeHtml($old->getId()); ?></td>
        <td></td>
        <td></td>
        <td></td>        
    </tr>
    <tr>
        <td><?= $this->translate('Name'); ?></td>
        <td><?= $this->escapeHtml($old->getName()); ?></td>
        <?= updateTd($new->getName(), $old->getName(), $this) ?>
        <td><?= $this->escapeHtml($old->getNameEn(), $this); ?></td>
        <?= updateTd($new->getNameEn(), $old->getNameEn(), $this) ?>
    </tr>
    <tr>
        <td><?= $this->translate('Start time'); ?></td>
        <td><?= $old->getBeginTime()->format('Y-m-d H:i') ?></td>
        <?= updateTd($new->getBeginTime()->format('Y-m-d H:i') , $old->getBeginTime()->format('Y-m-d H:i'), $this) ?>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td><?= $this->translate('End time'); ?></td>
        <td><?= $old->getEndTime()->format('Y-m-d H:i') ?></td>
        <?= updateTd($new->getEndTime()->format('Y-m-d H:i') , $old->getEndTime()->format('Y-m-d H:i'), $this) ?>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td><?= $this->translate('Location'); ?></td>
        <td><?= $this->escapeHtml($old->getLocation()); ?></td>
        <?= updateTd($new->getLocation(), $old->getLocation(), $this) ?>
        <td><?= $this->escapeHtml($old->getLocationEn()); ?></td>
        <?= updateTd($new->getLocationEn(), $old->getLocationEn(), $this) ?>
    </tr>
    <tr>
        <td><?= $this->translate('Costs'); ?></td>
        <td><?= $this->escapeHtml($old->getCosts()); ?></td>
        <?= updateTd($new->getCosts(), $old->getCosts(), $this) ?>
        <td><?= $this->escapeHtml($old->getCostsEn()); ?></td>
        <?= updateTd($new->getCostsEn(), $old->getCostsEn(), $this) ?>
    </tr>
    <tr>
        <td><?= $this->translate('Subscribe'); ?></td>
        <td><?= $old->getCanSignUp() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
        <td><?= $new->getCanSignUp() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
    </tr>
    <tr>
        <td><?= $this->translate('Only GEWIS'); ?></td>
        <td><?= $old->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
        <td><?= $new->getOnlyGEWIS() ? $this->translate("Yes") : $this->translate("No"); ?></td>
        <td></td>
    </tr>

    <tr>
        <td>
            <a href="<?= $this->url('admin_activity/apply_proposal', ['id' => $proposal->getId()]) ?>">
                <?= $this->translate('Apply update'); ?>
            </a>
        </td>
        <td>
            <a href="<?= $this->url('admin_activity/revoke_proposal', ['id' => $proposal->getId()]) ?>">
                <?= $this->translate('Revoke update'); ?>
            </a>
        </td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>
            <a href="<?= $this->url('activity/view', ['id' => $old->getId()]) ?>">
                <?= $this->translate('View details / subscriptions of old activity') ?>
            </a>
        </td>
        <td>
            <a href="<?= $this->url('activity/view', ['id' => $new->getId()]) ?>">
                <?= $this->translate('View details of updated activity') ?>
        </td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </tbody>
</table>
<div class="col-md-8">
    <?= $this->translate('Original Dutch description') ?>
    <p><?= nl2br($this->escapeHtml($old->getDescription())) ?></p>
</div>
<div class="col-md-8">
    <?= $this->translate('Updated Dutch description') ?>
    <p><?= nl2br($this->escapeHtml($new->getDescription())) ?></p>
</div>
<div class="col-md-8">
    <?= $this->translate('Original English description') ?>
    <p><?= nl2br($this->escapeHtml($old->getDescriptionEn())) ?></p>
</div>
<div class="col-md-8">
    <?= $this->translate('Updated English description') ?>
    <p><?= nl2br($this->escapeHtml($new->getDescriptionEn())) ?></p>
</div>