<?php $this->headScript()->prependFile($this->basePath() . '/js/photo.js'); ?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $album->getName(); ?></h1>
    </div>
</div>
<?= $this->paginationControl(
    $this->paginator,
    // the scrolling style
    'elastic',
    'partial/paginator.phtml',
    array(
        'path' => '/photo/album/' . $album->getId()
    )
)
?>
<div class="row">
    <?php foreach ($paginator as $item): ?>
        <?php if ($item->getResourceId() === 'album'): ?>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/photo/album/<?= $item->getId(); ?>">
                    <img class="img-responsive" src="<?= $basedir . '/' . $item->getCoverPath() ?>" alt="">

                    <div class="caption">
                        <?= $item->getName(); ?>
                    </div>
                </a>
            </div>
        <?php else: ?>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/photo/view/<?= $item->getId(); ?>">
                    <img class="img-responsive" src="<?= $basedir . '/' . $item->getSmallThumbPath() ?>" alt="">
                </a>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
</div>







