<?= sprintf($this->translate('Dear %s,'), $company->getContactName()) . "\n" ?>

<?= $this->translate('You have been registered on the website of Study association GEWIS, with the following information:') . "\n" ?>

- <?= $this->translate('Company name:') ?> <?= $company->getName() . "\n" ?>
- <?= $this->translate('Contact email address:') ?> <?= $company->getContactEmail() . "\n" ?>

<?= $this->translate('You can activate your account on the following link:') . "\n" ?>

<?= $this->serverUrl($this->url('user/activate-company', ['code' => $newcompany->getCode()])) . "\n" ?>

<?= $this->translate('Your activation code is:') ?> <?= $newcompany->getCode() . "\n" ?>

<?= $this->translate('Best Regards,') . "\n" ?>

<?= $this->translate('WebCommissie GEWIS') ?>
