For English, please see below.<br/><br/>


<?= sprintf('Beste %s,', $member->getFullName()) ?><br/><br/>

Je bent geregistreerd op de website van de Studievereniging GEWIS, met de volgende informatie:
Lidnummer: <?= $user->getLidnr() ?>
Email adres: <?= $user->getEmail() ?>

Je kunt je account activeren met de volgende link:
<?= $this->serverUrl($this->url('user/activate', ['code' => $user->getCode()])) ?>

Je activatie code is: <?= $user->getCode() ?>

Met vriendelijke groeten,<br/>
De Web Commissie
<hr/>

<?= sprintf('Dear %s,', $member->getFullName()) ?><br/><br/>

You have been registered on the website of Study association GEWIS, with the following information:
Membership number: <?= $user->getLidnr() ?>
Email address: <?= $user->getEmail() ?>

You can activate your account on the following link:
<?= $this->serverUrl($this->url('user/activate', ['code' => $user->getCode()])) ?>

Your activation code is: <?= $user->getCode() ?>

With kind regards,<br/>
The Web Committee
<hr/>
