<?= sprintf($this->translate('Dear %s,'), $member->getFullName()) . "\n" ?>

<?= $this->translate('You have been registered on the website of Study association GEWIS, with the following information:') . "\n" ?>

- <?= $this->translate('Membership number:') ?> <?= $user->getLidnr() . "\n" ?>
- <?= $this->translate('Email address:') ?> <?= $user->getEmail() . "\n" ?>

<?= $this->translate('You can activate your account on the following link:') . "\n" ?>

<?= $this->serverUrl($this->url('user/activate', array('code' => $user->getCode()))) . "\n" ?>

<?= $this->translate('Your activation code is:') ?> <?= $user->getCode() . "\n" ?>

<?= $this->translate('Best Regards,') . "\n" ?>

<?= $this->translate('WebCommissie GEWIS') ?>
