<?= "--- Dutch version below ---\n\n" ?>

<?= sprintf($this->translate('Dear %s,'), $member->getContactName()) . "\n" ?>

<?= $this->translate('A password reset was requested for your account.') . "\n" ?>

<?= $this->translate('You can reset your password on the following link:') . "\n" ?>

<?= $this->serverUrl($this->url('user/activate-company', ['code' => $user->getCode()])) . "\n" ?>

<?= $this->translate('Best Regards,') . "\n" ?>

<?= $this->translate('WebCommissie GEWIS') ?>


<?= "--- Dutch version ---\n\n" ?>

<?= sprintf($this->translate('Beste %s,'), $member->getContactName()) . "\n" ?>

<?= $this->translate('Een wachtwoord reset is aangevraagd voor uw account.') . "\n" ?>

<?= $this->translate('U kunt uw wachtwoord opnieuw instellen via de volgende link:') . "\n" ?>

<?= $this->serverUrl($this->url('user/activate-company', ['code' => $user->getCode()])) . "\n" ?>

<?= $this->translate('Met vriendelijke groeten,') . "\n" ?>

<?= $this->translate('De Web Commissie') ?>
