For English, please see below.<br/><br/>


<?= sprintf('Beste %s,', $member->getFullName()) ?><br/><br/>

Er is geprobeerd het wachtwoord van je account te resetten.

Je kunt je account resetten met de volgende link:
<?= $this->serverUrl($this->url('user/activate', ['user_type' => 'member', 'code' => $user->getCode()])) ?>

Je reset code is: <?= $user->getCode() ?>

Met vriendelijke groeten,<br/>
De ApplicatieBeheerCommissie
<hr/>

<?= sprintf('Dear %s,', $member->getFullName()) ?><br/><br/>

A password reset was requested for your account.

You can reset your password on the following link:
<?= $this->serverUrl($this->url('user/activate', ['user_type' => 'member', 'code' => $user->getCode()])) ?>

Your reset code is: <?= $user->getCode() ?>

With kind regards,<br/>
The ApplicatieBeheerCommissie
<hr/>
