<?php 
$escaper = new Zend\Escaper\Escaper('utf-8');
?>
    <div class="company-list-item list-item" id="<?= $escaper->escapeHtmlAttr($company->getName()); ?>">
<?php  // Display title
echo("<h2 class='company-name'><a href='"); 

// If multiple companies are on display, the title should redirect to the company page, else, it should redirect to the website
if ($islist==true) {

    //echo ("company/");  
    //echo($company->getSlugName()); 
    echo ($this->url('company/companyItem', // Route url
        ['slugCompanyName' => $company->getSlugName()] // Url parameters
        ,array[] // routeOptions
        ,true)); // Reuse matched parameters
}
else {
    echo($company->getTranslationFromLocale($locale)->getWebsite());
}
echo("'>"); 
echo ($company->getName()); // Text of the title
echo ("</a></h2>") ?>

    <div class="company-slogan"><?= $company->getTranslationFromLocale($locale)->getSlogan(); ?></div>
    <div class="company-logo"><img src="<?= print("hoi"); #$escaper->escapeHtmlAttr($company->getTranslationFromLocale($locale)->getLogo()); ?>" alt="Logo of <?= $escaper->escapeHtmlAttr($company->getName()); ?>" /></div>
    <div class="company-address"><?= $company->getAddress(); ?></div>
    <div class="company-phone"><a href="tel:<?= rawurlencode($company->getPhone()); ?>"><?= $company->getPhone(); ?></a></div>
    <div class="company-website"><a href="<?= $company->getTranslationFromLocale($locale)->getWebsite(); ?>">Visit website</a></div>
    <div class="company-email"><a href="mailto:<?= rawurlencode($company->getEmail()); ?>"><?= $company->getEmail(); ?></a></div>
    <div class="company-jobs" data-amount="<?php echo $company->getNumberOfJobs(); ?>">
        <ul class="company-jobs-list">
        <?php if ($company->getPackets()[0] != null) foreach($company->getPackets()[0]->getJobs() as $job) { ?>
        <li class="company-jobs-job"><a href="<?=$this->url('company/companyItem/joblist/job_item',
            ['slugCompanyName' => $company->getSlugName(),
            'slugJobName' => $job->getSlugName()),[],true) ?>"><?= $job->getName(); ?></a></li>
        <?php } ?>
        </ul>
    </div>
    <div class="company-description"><?= $company->getTranslationFromLocale($locale)->getDescription(); ?></div>

    </div>
