<?php
/**
 * local_vars = [$folderName, $folder, $path, $trailingSlash]
 */
$escaper = new Zend\Escaper\Escaper('utf-8');
//construct breadcrumbs
$offset = 0;
$pathPrefixes = [];
while (($pos = strpos($path, '/', $offset)) !== false){
    $pathPrefixes[] = substr($path, 0,$pos);
    $offset = $pos + 1;
}
if ($path === '' || $path === '/') {
    $crumbs = [$this->translate('Root')];
}
else {
    $crumbs = ['<a href="' . $this->url('decision/files', ['path' => '']) . '">' . $this->translate('Root') . '</a>'];
}

$skipfirst = true;
foreach($pathPrefixes as $prefix){
    if ($skipfirst) {
        $skipfirst = false;
        continue;
    }
    $crumburl = $this->url('decision/files', ['path' => '']) . $prefix;
    $crumburl = preg_replace('#[/]+#','/', $crumburl);
    $crumbtext = end(explode('/', $prefix));
    $crumbs[] = '<a href="' . $escaper->escapeHtmlAttr($crumburl) . '">' . $escaper->escapeHtml($crumbtext) . '</a>';
}
if ($trailingSlash && !($path === '/' || $path === '')){
    array_pop($crumbs);
}
// set title
$this->headTitle($this->translate('Public Archive') . ' - [' . ($folderName==='' ? $this->translate('Root') : $escaper->escapeHtml($folderName) ) . ']'); ?>
<section class="section">
    <div class="container">
        <h2>
            <?= $this->translate('Browsing directory: ') . ($folderName==='' ? $this->translate('Root') : $escaper->escapeHtml($folderName) ) ?>
        </h2>
    </div>
    <section class="section section-breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <?php foreach($crumbs as $crumb): ?>
                <li>
                    <?= $crumb ?>
                </li>
                <?php endforeach; ?>
                <li class="active">
                    <?= $escaper->escapeHtml($folderName) ?>
                </li>
            </ol>
        </div>
    </section>
    <p/>
    <div class="container">
        <table class="table table-hover">
            <thead>
            <tr>
                <th><div class="glyphicon glyphicon-folder-close"></div> / <div class="glyphicon glyphicon-file"></div></th>
                <th><?= $this->translate('Filename') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php if ($folderName!=='') : ?>
            <?php $parentPath = substr($path, 0, strrpos($path, '/'));
                  $parentUrl = $this->url('decision/files', ['path' => '']) . $parentPath;
                  $parentUrl = preg_replace('#[/]+#','/', $parentUrl);
            ?>
                <tr>
                    <td><div class="glyphicon glyphicon-arrow-left"></div></td>
                    <td><a style="display: block; height: 100%; width: 100%"
                           href="<?= $escaper->escapeHtmlAttr($parentUrl) ?>"><?= $this->translate(".. Move up a folder") ?></a></td>
                </tr>
            <?php endif;?>
            <?php if (empty($folder)): ?>
                <tr>
                    <td><div class="glyphicon glyphicon-ban-circle"></div></td>
                   <td><?= $this->translate('Empty folder') ?></td>
                </tr>
            <?php endif; ?>
            <?php foreach ($folder as $node): ?>
                <?php if ($node->getKind() === 'dir'): ?>
                <?php $kind_icon = 'glyphicon-folder-close';
                //directly putting the path in the url helper filters the '/', which we don't want.
                $url = $this->url('decision/files', ['path' => '']) . $node->getFullPath();
                $url = preg_replace('#[/]+#','/', $url);
                ?>
                <tr>
                    <td><div class="glyphicon <?= $kind_icon ?>"></div></td>
                    <td><a style="display: block; height: 100%; width: 100%"
                           href="<?= $escaper->escapeHtmlAttr($url) ?>"><?= $escaper->escapeHtml($node->getName()) ?></a></td>
                </tr>
                <?php endif;?>
            <?php endforeach; ?>
            <?php foreach ($folder as $node): ?>
                <?php if ($node->getKind() === 'file'): ?>
                <?php $kind_icon = 'glyphicon-file';
                //directly putting the path in the url helper html-escapes the '/', which we don't want.
                $url = $this->url('decision/files', ['path' => '']) . $node->getFullPath();
                $url = preg_replace('#[/]+#','/', $url);
                ?>
                <tr>
                    <td><div class="glyphicon <?= $kind_icon ?>"></div></td>
                    <td><a style="display: block; height: 100%; width: 100%"
                           href="<?= $escaper->escapeHtmlAttr($url) ?>"><?= $escaper->escapeHtml($node->getName()) ?></a></td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</section>

