<table class="table table-hover">
    <thead>
    <tr>
        <th><?= $this->translate('Type') ?></th>
        <th><?= $this->translate('Meeting number') ?></th>
        <th><?= $this->translate('Date') ?></th>
        <th><?= $this->translate('# Decisions') ?></th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($meetings as $info): ?>
    <?php $meeting = $info[0] ?>
    <tr>
        <td><?= $meeting->getType() ?></td>
        <td><?= $meeting->getNumber() ?></td>
        <td><?= $this->dateFormat(
            $meeting->getDate(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::NONE,
            'nl_NL'
        ) ?></td>
        <td><?= $info[1] ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
