<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Form\SearchDecision as SearchDecisionForm;
use Decision\Model\Decision as DecisionModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var SearchDecisionForm $form
 * @var DecisionModel[]|null $result
 * @var string|null $prompt
 */

$this->headTitle($this->translate('Search for decision'));

/**
 * Insert `<mark>` around a search prompt in the content of a decision.
 */
function highlightSearch(
    string $decision,
    string $search,
): string {
    // Convert the decision to something that is easily searchable (i.e. it MUST NOT contain any non-ASCII characters).
    $transliteratedDecision = iconv(
        'UTF-8',
        'ASCII//TRANSLIT//IGNORE',
        transliterator_transliterate('Any-Latin; Latin-ASCII', $decision),
    );
    // Do the same for the search prompt, as otherwise searches WITH non-ASCII characters will not work.
    $search = iconv(
        'UTF-8',
        'ASCII//TRANSLIT//IGNORE',
        transliterator_transliterate('Any-Latin; Latin-ASCII', $search),
    );

    $offset = 0;
    $output = '';
    $length = mb_strlen($search);

    // There is a very important assumption here; the transliterated version of the decision MUST be exactly as long as
    // the original version. Otherwise, the insertion is done with an incorrect offset.
    while (false !== ($position = mb_stripos($transliteratedDecision, $search, $offset, 'UTF-8'))) {
        // Progressively insert markers into the original decision.
        $output .= sprintf('%s%s%s%s',
            mb_substr($decision, $offset, $position - $offset, 'UTF-8'),
            '<mark>',
            mb_substr($decision, $position, $length, 'UTF-8'),
            '</mark>',
        );

        $offset = $position + $length;
    }

    // Add the final part of the decision back.
    $output .= mb_substr($decision, $offset, null, 'UTF-8');

    return $output;
}
?>
<section class="section">
    <div class="container">
        <?php
        $form->prepare();

        $form->setAttribute('action', $this->url('decision/default', ['action' => 'search']));
        $form->setAttribute('method', 'post');

        $form->setAttribute('role', 'form');
        ?>
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?php
            $element = $form->get('query');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $this->translate('Search query'));
            ?>
            <?= $this->formLabel($element) ?>
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>

        <?php
        $submit = $form->get('submit');
        $submit->setLabel($this->translate('Search'));
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>

        <?= $this->form()->closeTag() ?>

        <?php if (isset($result)): ?>
            <?php if (empty($result)): ?>
                <p><?= $this->translate('No decisions were found.') ?></p>
                <ul>
                    <li><?= $this->translate('Check the spelling of your search term') ?></li>
                    <li><?= $this->translate('Try alternate words or selections') ?></li>
                    <li><?= $this->translate('Try using a more generic search term') ?></li>
                    <li><?= $this->translate('Try entering fewer keywords') ?></li>
                    <li><?= $this->translate('Looking for a specific decision but forgot the numbers? Try dropping the decision point and/or number') ?></li>
                </ul>
            <?php else: ?>
                <ul class="list-unstyled">
                    <?php foreach ($result as $decision): ?>
                        <?php $type = $decision->getMeeting()->getType()->value; ?>
                        <?php $number = $decision->getMeeting()->getNumber(); ?>
                        <li>
                            <strong class="decision-meeting">
                                <a href="<?= $this->url(
                                    'decision/meeting',
                                    [
                                        'type' => $type,
                                        'number' => $number,
                                    ],
                                ) ?>">
                                    <?= sprintf(
                                        '%s %d.%d.%d',
                                        $type,
                                        $number,
                                        $decision->getPoint(),
                                        $decision->getNumber(),
                                    ) ?>
                                </a>
                            </strong>
                            <span class="decision-content">
                                <?= highlightSearch(
                                    $this->escapeHtml($decision->getContent()),
                                    $this->escapeHtml($prompt),
                                ) ?>
                            </span>
                        </li>
                    <?php endforeach ?>
                </ul>
            <?php endif; ?>
        <?php endif ?>
    </div>
</section>
