<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Decision\Form\SearchDecision as SearchDecisionForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var SearchDecisionForm $form
 */

$this->headTitle($this->translate('Search for decision'));
?>
<section class="section">
    <div class="container">
        <?php
        $form->prepare();

        $form->setAttribute('action', $this->url('decision/default', ['action' => 'search']));
        $form->setAttribute('method', 'post');

        $form->setAttribute('role', 'form');
        ?>
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?php
            $element = $form->get('query');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $this->translate('Search query'));
            ?>
            <?= $this->formLabel($element) ?>
            <?= $this->formText($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>

        <?php
        $submit = $form->get('submit');
        $submit->setLabel($this->translate('Search'));
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>

        <?= $this->form()->closeTag() ?>

        <?php if (isset($result)): ?>
            <?php if (empty($result)): ?>
                <p><?= $this->translate('No decisions were found.') ?></p>
                <ul>
                    <li><?= $this->translate('Check the spelling of your search term') ?></li>
                    <li><?= $this->translate('Try alternate words or selections') ?></li>
                    <li><?= $this->translate('Try using a more generic search term') ?></li>
                    <li><?= $this->translate('Try entering fewer keywords') ?></li>
                    <li><?= $this->translate('Looking for a specific decision but forgot the numbers? Try dropping the decision point and/or number') ?></li>
                </ul>
            <?php else: ?>
                <ul class="list-unstyled">
                    <?php foreach ($result as $decision): ?>
                        <?php $type = $decision->getMeeting()->getType()->value; ?>
                        <?php $number = $decision->getMeeting()->getNumber(); ?>
                        <li>
                            <strong class="decision-meeting">
                                <a href="<?= $this->url(
                                    'decision/meeting',
                                    [
                                        'type' => $type,
                                        'number' => $number,
                                    ],
                                ) ?>">
                                    <?= sprintf(
                                        '%s %d.%d.%d',
                                        $type,
                                        $number,
                                        $decision->getPoint(),
                                        $decision->getNumber(),
                                    ) ?>
                                </a>
                            </strong>
                            <span class="decision-content"><?= $this->escapeHtml($decision->getContent()) ?></span>
                        </li>
                    <?php endforeach ?>
                </ul>
            <?php endif; ?>
        <?php endif ?>
    </div>
</section>
