<?php

use Application\View\HelperTrait;
use Decision\Model\Meeting as MeetingModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MeetingModel $meeting
 */

$translator = $this->plugin('translate')->getTranslator();
$nf = new NumberFormatter($translator->getLocale(), NumberFormatter::ORDINAL);

$meetingName = sprintf(
    '%s %s',
    $nf->format($meeting->getNumber()),
    $meeting->getType()->getName($translator),
);

$this->headTitle($meetingName);
?>
<section class="section">
    <div class="container">
        <h1><?= $meetingName ?></h1>
        <h2><?= $this->dateFormat($meeting->getDate(), IntlDateFormatter::FULL, IntlDateFormatter::NONE) ?></h2>
        <div class="row">
            <div class="col-md-6">
                <h3><?= $this->translate('Documents') ?></h3>
                <?php if (count($meeting->getDocuments()) > 0): ?>
                    <table class="table table-striped table-hover">
                        <?php foreach ($meeting->getDocuments() as $document): ?>
                            <tr>
                                <td>
                                    <a href="<?= $this->url('decision/document', ['id' => $document->getId()]) ?>"
                                       class="d-block">
                                        <?= $document->getName() ?>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                <?php else: ?>
                    <p class="text-muted">
                        <?= $this->translate("No documents have been added.") ?>
                    </p>
                <?php endif; ?>
            </div>
            <?php if (!is_null($meeting->getMinutes())): ?>
                <div class="col-md-6">
                    <h3><?= $this->translate('Minutes') ?></h3>
                    <?php
                    $minutesUrl = $this->url('decision/meeting/minutes', [
                        'type' => $meeting->getType()->value,
                        'number' => $meeting->getNumber(),
                    ])
                    ?>
                    <p>
                        <a href="<?= $minutesUrl ?>">
                            <?= sprintf($this->translate('View the minutes of the %s'), $meetingName) ?>
                        </a>
                    </p>
                </div>
            <?php endif; ?>
        </div>
        <?php if (count($meeting->getDecisions()) > 0): ?>
            <div class="row">
                <div class="col-md-12">
                    <h3><?= $this->translate('Decisions') ?></h3>
                    <ul class="list-unstyled">
                        <?php foreach ($meeting->getDecisions() as $decision): ?>
                            <?php
                            $id = vsprintf('%s %s.%s.%s', [
                                $meeting->getType()->value,
                                $meeting->getNumber(),
                                $decision->getPoint(),
                                $decision->getNumber(),
                            ]);
                            ?>
                            <li id="<?= urlencode($id) ?>" class="link-permalink-container">
                                <strong class="decision-meeting"><?= $id ?></strong>
                                <span class="decision-content">
                                    <?= $this->escapeHtml($decision->getContent()) ?>
                                    <a href="#<?= urlencode($id) ?>" class="link-permalink">
                                        <span class="fa fa-link"></span>
                                    </a>
                                </span>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
