<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Frontpage\Form\NewsItem as NewsItemForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool $canDelete
 * @var NewsItemForm $form
 * @var int $newsItemId
 */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

$this->headScript()
    ->appendFile(
        $this->basepath('js/ckeditor/ckeditor.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );

if ('nl' === $lang) {
    $this->headScript()->appendFile(
        $this->basepath('js/ckeditor/translations/nl.js'),
        'text/javascript',
        ['nonce' => NONCE_REPLACEMENT_STRING],
    );
}

$this->headLink()
    ->appendStylesheet($this->basepath('css/ckeditor/style.css'));

$this->scriptUrl()->requireUrl('admin_page/upload');

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('News'), true, $this->url('admin_news'))
    ->addBreadcrumb($this->translate('Edit'));
?>
<?php
$form->prepare();

$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>
<?= $this->form()->openTag($form); ?>
<h3><?= $this->translate('English content') ?></h3>
<div class="form-group">
    <?php
    $element = $form->get('englishTitle');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('required', 'required');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<div class="form-group">
    <?php
    $element = $form->get('englishContent');
    $element->setAttribute('id', 'english-content')
        ->setAttribute('class', 'form-control');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<hr>
<h3><?= $this->translate('Dutch content') ?></h3>
<div class="form-group">
    <?php
    $element = $form->get('dutchTitle');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('required', 'required');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formText($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>

<div class="form-group">
    <?php
    $element = $form->get('dutchContent');
    $element->setAttribute('id', 'dutch-content')
        ->setAttribute('class', 'form-control');
    ?>
    <?= $this->formLabel($element); ?>
    <?= $this->formTextarea($element); ?>
    <?= $this->formElementErrors($element); ?>
</div>
<?php
$pinned = $form->get('pinned');
?>
<div class="form-group">
    <label>
        <?= $this->formCheckbox($pinned) ?>
        <?= $this->translate('Pin news item') ?>
        <span data-toggle="tooltip" data-placement="right"
              title="<?= $this->translate('Select this if you want this news item to stay at the top of the page.') ?>"
              class="fas fa-info-circle" aria-hidden="true"></span>
    </label>
</div>
<hr>
<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?php if ($canDelete): ?>
    <a href="<?= $this->url('admin_news/delete', ['item_id' => $newsItemId]) ?>" class="btn btn-danger">
        <span class="far fa-trash-alt"></span>&nbsp;
        <?= $this->translate('Delete this news item') ?>
    </a>
<?php endif ?>

<?= $this->form()->closeTag(); ?>
<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    GEDITOR.FullEditor
        .create(document.querySelector('#dutch-content'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });

    GEDITOR.FullEditor
        .create(document.querySelector('#english-content'), {
            language: '<?= $lang ?>'
        })
        .catch(error => {
            console.error(error);
        });
</script>
