<?php

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var \Laminas\Paginator\Paginator $paginator
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('News'));
?>
<h1><?= $this->translate('News items') ?></h1>
<a class="btn btn-primary" href="<?= $this->url('admin_news/create') ?>"><?= $this->translate('Create news item') ?></a>
<?= $this->paginationControl(
    $paginator,
    // the scrolling style
    'elastic',
    'paginator/default',
    [
        'path' => $this->url('admin_news/list')
    ]
)
?>
<?php if (!empty($paginator)): ?>

    <table class="table table-hover">
        <tbody>
        <?php foreach ($paginator as $newsItem): ?>
            <tr class="news-item" data-link="<?= $this->url('admin_news/edit', ['item_id' => $newsItem->getId()]) ?>">
                <td><?= $newsItem->getDutchTitle() ?></td>
                <td><?= $newsItem->getEnglishTitle() ?></td>
                <td><?= $newsItem->getDate()->format('d-m-Y') ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.querySelectorAll('.news-item').forEach(item => {
        item.addEventListener('click', () => {
            window.document.location = item.dataset.link;
        });
    });
</script>
