<h1><?= $this->translate('News items') ?></h1>
<?= $this->paginationControl(
    $paginator,
    // the scrolling style
    'elastic',
    'paginator/default',
    [
        'path' => $this->url('admin_news/list')
    ]
)
?>
<?php if (!empty($paginator)): ?>

    <table class="table table-striped">
        <tbody>
        <?php foreach ($paginator as $newsItem): ?>
            <tr>
                <td><?= $newsItem->getDutchTitle() ?></td>
                <td><?= $newsItem->getEnglishTitle() ?></td>
                <td><?= $newsItem->getDate()->format('d-m-Y') ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
