<h1><?= $this->translate('API Tokens') ?></h1>
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Token') ?></th>
            <th>Remove</th>
        <tr>
    </thead>
    <tbody>
        <?php foreach ($tokens as $token): ?>
        <tr>
            <td><?= $token->getId() ?></td>
            <td><?= $token->getName() ?></td>
            <td><?= $token->getToken() ?></td>
            <td><a class="btn btn-xs btn-danger" href="<?= $this->url('user_admin/api/remove', [
                    'id' => $token->getId()
                ]) ?>"><span class="fas fa-times"></span> <?= $this->translate('Remove') ?></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>

<a href="<?= $this->url('user_admin/api/default', ['action' => 'add']) ?>" class="btn btn-success">
    <i class="fas fa-plus"></i> <?= $this->translate('Add new Token') ?>
</a>
