<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Model\ApiUser as ApiUserModel;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ApiUserModel $token
 */

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('API Tokens'), true, $this->url('user_admin/api'))
    ->addBreadcrumb($this->translate('Remove Token'));
?>
<form method="POST" action="<?= $this->url('user_admin/api/remove', [
    'id' => $token->getId()
]) ?>">

    <p>
        Are you sure you want to remove the token with name <?= $this->escapeHtml($token->getName()) ?>?<br/>
    </p>
    <p>
        <button class="btn btn-primary">Yes</button>
        <a href="<?= $this->url('user_admin/api') ?>" class="btn btn-default">No</a>
    </p>

</form>
