<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Frontpage\Form\PollComment as PollCommentForm;
use Frontpage\Model\{
    Poll as PollModel,
    PollVote as PollVoteModel,
};
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var bool $canVote
 * @var PollCommentForm $commentForm
 * @var PollModel|null $poll
 * @var PollVoteModel $userVote
 */

if (!isset($poll)) {
    $title = $this->translate('Polls');
} else {
    $lang = $this->plugin('translate')->getTranslator()->getLocale();
    $title = $this->escapeHtml(('en' === $lang) ? $poll->getEnglishQuestion() : $poll->getDutchQuestion());
    $this->headTitle($title);
}

// set title
$this->headTitle($this->translate('Polls'));

?>
<section class="section">
    <div class="container">
        <div class="page-header">
            <div class="btn-toolbar pull-right">
                <a href="<?= $this->url('poll/history') ?>" class="btn btn-default">
                    <span class="fas fa-history"></span>
                    <?= $this->translate('Old polls') ?>
                </a>
                <?= sprintf($this->translate('%sRequest a poll%s'), '<a href="' . $this->url('poll/request') . '" class="btn btn-primary">', '</a>') ?>
            </div>
            <h1>
                <?= $title ?>
            </h1>
        </div>

        <?php if (isset($poll)): ?>
            <?= $this->partial('partial/poll.phtml', [
                'poll' => $poll,
                'canVote' => $canVote,
                'userVote' => $userVote,
                'showResults' => true
            ]) ?>
        <?php else: ?>
            <p class="lead"><?= $this->translate('Unfortunately there currently is no poll :('); ?></p>
        <?php endif; ?>

        <?php if (isset($poll) && $this->acl('frontpage_service_acl')->isAllowed('poll_comment', 'list')): ?>
            <hr>
            <h2><?= $this->translate('Comments') ?></h2>
            <?php if (count($poll->getComments()) == 0): ?>
                <?= $this->translate('This poll has no comments') ?>
            <?php else: ?>
                <?php foreach ($poll->getComments() as $comment): ?>
                    <div class="row">
                        <div class="col-sm-2">
                            <strong><?= $this->escapeHtml($comment->getAuthor()) ?></strong>
                            <?php if ($this->acl('frontpage_service_acl')->isAllowed('poll_comment', 'view_user')): ?>
                                <?php $lidnr = $comment->getUser()->getLidnr() ?>
                                (<a href="<?= $this->url('member/view', ['lidnr' => $lidnr]) ?>"><?= $lidnr ?></a>)
                                <br>
                                <?= $comment->getCreatedOn()->format('Y-m-d H:i:s') ?>
                            <?php endif ?>
                        </div>
                        <div class="col-sm-10">
                            <?= $this->escapeHtml($comment->getContent()) ?>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
            <?php if ($this->acl('frontpage_service_acl')->isAllowed('poll_comment', 'create')): ?>
                <hr>
                <h3><?= $this->translate('Comment on this poll') ?></h3>
                <?php
                $commentForm->prepare();

                $commentForm->setAttribute('action', $this->url('poll/comment', ['poll_id' => $poll->getId()]));
                ?>

                <?= $this->form()->openTag($commentForm) ?>

                <?php
                $element = $commentForm->get('author');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                ?>
                <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $element->getName() ?>" class="control-label"><?= $element->getLabel() ?></label>
                    <?= $this->formText($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>

                <?php
                $element = $commentForm->get('content');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                ?>
                <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label for="<?= $element->getName() ?>" class="control-label"><?= $element->getLabel() ?></label>
                    <?= $this->formTextarea($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>

                <div class="form-group">
                    <?php
                    $submit = $commentForm->get('submit');
                    $submit->setAttribute('class', 'btn btn-primary');
                    ?>
                    <?= $this->formSubmit($submit) ?>
                </div>

                <?= $this->form()->closeTag() ?>
            <?php endif ?>
        <?php endif ?>
    </div>
</section>
