<div class="container">
    <div class="row">
        <h1><?= $this->translate('Current poll') ?></h1>
    </div>

    <div class="row">
        <?php if (isset($poll)): ?>
            <?= $this->partial('partial/poll.phtml', [
                'poll' => $poll,
                'canVote' => $canVote,
                'userVote' => $userVote,
                'showResults' => true
            ]) ?>
        <?php else: ?>
            <p class="lead"><?= $this->translate('Unfortunately there currently is no poll :('); ?></p>
        <?php endif; ?>
    </div>

    <div class="row">
    <p>
        <?= sprintf('%sRequest a poll%s', '<a href="' . $this->url('poll/request') . '">', '</a>') ?>
    </p>
    </div>

    <div class="row">
        <a href="<?= $this->url('poll/history') ?>" class="pull-left text-uppercase">
             <i class="glyphicon glyphicon-arrow-left" /></i>
            <?= $this->translate('Old polls') ?>
        </a>
    </div>
</div>
