<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Frontpage\Form\Poll as PollForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var PollForm $form
 */

$this->headTitle($this->translate('Request a poll'));
?>
<section class="section">
    <div class="container">
        <div class="row">
            <h1><?= $this->translate('Request a poll') ?></h1>
            <?php if (isset($success)): ?>
                <?= $this->translate('Your poll request has been received and will be reviewed shortly.') ?>
            <?php else: ?>
                <div class="col-md-12">
                    <div class="alert alert-info" role="alert">
                        <strong><?= $this->translate('Heads up!') ?></strong>
                        <?= $this->translate('Polls are public and freely accessible, even to non-members. This means you cannot use personal data in the questions or options. For example, similar to infima, this means that you should always abbreviate family names, so instead of <em>John Doe</em> you should use <em>John D.</em> The board will check this before approving a poll, if personal data does appear in a poll it will be rejected and therefore not published on the website.') ?>
                    </div>
                </div>
                <?php
                $this->inlineScript()
                    ->appendFile(
                        $this->basePath() . '/js/frontpage-poll.js',
                        'text/javascript',
                        ['nonce' => NONCE_REPLACEMENT_STRING],
                    );

                $form->setAttribute('action', $this->url('poll/request'));
                $form->setAttribute('class', 'form-horizontal');

                $form->prepare();
                ?>
                <?= $this->form()->openTag($form) ?>

                <?php
                $element = $form->get('dutchQuestion');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                ?>
                <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label
                        for="<?= $element->getName() ?>"
                        class="control-label col-sm-2"
                    ><?= $element->getLabel() ?></label>
                    <div class="col-sm-10">
                        <?= $this->formText($element) ?>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                </div>

                <?php
                $element = $form->get('englishQuestion');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                ?>
                <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
                    <label
                        for="<?= $element->getName() ?>"
                        class="control-label col-sm-2"
                    ><?= $element->getLabel() ?></label>
                    <div class="col-sm-10">
                        <?= $this->formText($element) ?>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                </div>

                <?php
                /* render template for options */
                $fs = $form->get('options')->getTemplateElement();
                ob_start();
                ?>
                <?php
                $element = $fs->get('dutchText');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                ?>
                <div
                    id="option__index__"
                    class="option form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>"
                >
                    <label
                        for="<?= $element->getName() ?>"
                        class="control-label col-sm-2"
                    ><?= $element->getLabel() ?></label>
                    <div class="col-sm-4">
                        <?= $this->formText($element) ?>
                        <?= $this->formElementErrors($element) ?>
                    </div>

                    <?php
                    $element = $fs->get('englishText');
                    $element->setAttribute('class', 'form-control');
                    $element->setAttribute('placeholder', $element->getLabel());
                    ?>
                    <label
                        for="<?= $element->getName() ?>"
                        class="control-label col-sm-2"
                    ><?= $element->getLabel() ?></label>
                    <div class="col-sm-4">
                        <?= $this->formText($element) ?>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                </div>
                <?php $tpl = trim(ob_get_clean()) ?>

                <fieldset id="poll-options">
                    <span
                        class="template"
                        data-template="<?= $this->escapeHtmlAttr($tpl) ?>"
                    ></span>
                    <?php $i = 0; ?>
                    <?php foreach ($form->get('options')->getIterator() as $fs): ?>
                        <?php
                        $element = $fs->get('dutchText');
                        $element->setAttribute('class', 'form-control');
                        $element->setAttribute('placeholder', $element->getLabel());
                        ?>
                        <div
                            id="option<?= $i ?>"
                            class="option form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>"
                        >
                            <label
                                for="<?= $element->getName() ?>"
                                class="control-label col-sm-2"
                            ><?= $element->getLabel() ?></label>
                            <div class="col-sm-4">
                                <?= $this->formText($element) ?>
                                <?= $this->formElementErrors($element) ?>
                            </div>

                            <?php
                            $element = $fs->get('englishText');
                            $element->setAttribute('class', 'form-control');
                            $element->setAttribute('placeholder', $element->getLabel());
                            ?>
                            <label
                                for="<?= $element->getName() ?>"
                                class="control-label col-sm-2"
                            ><?= $element->getLabel() ?></label>
                            <div class="col-sm-4">
                                <?= $this->formText($element) ?>
                                <?= $this->formElementErrors($element) ?>
                            </div>
                        </div>
                        <?php
                        $i++;
                    endforeach
                    ?>

                    <div class="form-group option-menu">
                        <div class="col-sm-offset-8 col-sm-2">
                            <button class="btn btn-danger remove-option" type="button"
                                id="removeButton" <?= $i < 2 ? 'style="display:none"' : '' ?>
                            >
                                <span class="fas fa-minus"></span> <?= $this->translate('Remove option') ?>
                            </button>
                        </div>
                        <div class="col-sm-2">
                            <button class="btn btn-success add-option" type="button">
                                <span class="fas fa-plus"></span> <?= $this->translate('Add option') ?>
                            </button>
                        </div>
                    </div>
                </fieldset>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <?php
                        $submit = $form->get('submit');
                        $submit->setAttribute('class', 'btn btn-primary');
                        $submit->setLabel($this->translate('Request poll'));
                        ?>
                        <?= $this->formButton($submit) ?>
                    </div>
                </div>

                <?= $this->form()->closeTag() ?>
            <?php endif ?>
        </div>
    </div>
</section>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.querySelector('.add-option').addEventListener('click', () => {
        addOption();
    });
    document.querySelector('.remove-option').addEventListener('click', () => {
        removeOption();
    });
</script>
