<?php
if (isset($success)):
    ?>
    <?= $this->translate('Your poll request has been received and will be reviewed shortly.') ?>
    <?php
else:
    $this->headScript()
        ->prependFile($this->basePath() . '/js/frontpage-poll.js');
    $form->setAttribute('action', $this->url('poll/request'))
        ->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('dutchQuestion'));
    echo $this->formRow($form->get('englishQuestion'));
    echo $this->formCollection($form->get('options'));
    ?>
    <button class="btn btn-primary" onclick="return addOption()"><?= $this->translate('Add option') ?></button>
    <?php
    echo $this->formElement($form->get('submit'));

    echo $this->form()->closeTag();
endif;
?>