<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Frontpage\Form\Poll as PollForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var PollForm $form
 */

$this->headTitle($this->translate('Request a poll'));
?>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $this->translate('Request a poll') ?></h1>
            </div>
        </div>
            <?php if (isset($success)): ?>
                <?= $this->translate('Your poll request has been received and will be reviewed shortly.') ?>
            <?php else: ?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-info" role="alert">
                            <strong><?= $this->translate('Heads up!') ?></strong>
                            <?= $this->translate('Polls are public and freely accessible, even to non-members. This means you cannot use personal data in the questions or options. For example, similar to infima, this means that you should always abbreviate family names, so instead of <em>John Doe</em> you should use <em>John D.</em> The board will check this before approving a poll, if personal data does appear in a poll it will be rejected and therefore not published on the website.') ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <?php
                    $this->inlineScript()
                        ->appendFile(
                            $this->basepath('js/frontpage-poll.js'),
                            'text/javascript',
                            ['nonce' => NONCE_REPLACEMENT_STRING],
                        );

                    $form->setAttribute('action', $this->url('poll/request'));
                    $form->setAttribute('class', 'form-poll');

                    $form->prepare();
                    ?>
                    <div class="col-md-12">
                        <?= $this->form()->openTag($form) ?>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">
                                        <span class="flag-icon flag-icon-nl"></span>
                                        <?= $this->translate('Dutch') ?>
                                    </label>
                                </div>
                                <hr>
                                <?php
                                $element = $form->get('dutchQuestion');
                                $element->setAttribute('class', 'form-control form-control-dutch')
                                    ->setAttribute('id', 'question-nl');
                                ?>
                                <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                                    <label for="<?= $element->getName() ?>" class="control-label label-required">
                                        <?= $element->getLabel() ?>
                                    </label>
                                    <?= $this->formText($element) ?>
                                    <?= $this->formElementErrors($element) ?>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">
                                        <span class="flag-icon flag-icon-en"></span>
                                        <?= $this->translate('English') ?>
                                    </label>
                                </div>
                                <hr>
                                <?php
                                $element = $form->get('englishQuestion');
                                $element->setAttribute('class', 'form-control form-control-english')
                                    ->setAttribute('id', 'question-en');
                                ?>
                                <div class="form-group <?= $this->bootstrapElementError($element) ?>">
                                    <label for="<?= $element->getName() ?>" class="control-label label-required">
                                        <?= $element->getLabel() ?>
                                    </label>
                                    <?= $this->formText($element) ?>
                                    <?= $this->formElementErrors($element) ?>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <?php
                                /* render template for options */
                                $pollOptions = $form->get('options')->getTemplateElement();
                                ob_start();
                                echo $this->partial(
                                    'partial/poll-options.phtml',
                                    [
                                        'pollOption' => $pollOptions,
                                        'index' => '__option__',
                                    ],
                                );
                                $pollOptionsTemplate = trim(ob_get_clean());
                                ?>
                                <fieldset class="poll-options">
                                    <span class="template" data-template="<?= $this->escapeHtmlAttr($pollOptionsTemplate) ?>">
                                    </span>
                                    <?php
                                    $i = 1;
                                    foreach ($form->get('options')->getIterator() as $pollOption) {
                                        echo $this->partial(
                                            'partial/poll-options.phtml',
                                            [
                                                'pollOption' => $pollOption,
                                                'index' => $i,
                                            ],
                                        );
                                        $i++;
                                    }
                                    ?>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group poll-option-controls">
                                                <button class="btn btn-danger remove-option" type="button">
                                                    <span class="fas fa-minus"></span>
                                                    <?= $this->translate('Remove option') ?>
                                                </button>
                                                <button class="btn btn-success add-option" type="button">
                                                    <span class="fas fa-plus"></span>
                                                    <?= $this->translate('Add option') ?>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <?php
                                    $submit = $form->get('submit');
                                    $submit->setAttribute('class', 'btn btn-primary');
                                    $submit->setLabel($this->translate('Request poll'));
                                    ?>
                                    <?= $this->formButton($submit) ?>
                                </div>
                            </div>
                        </div>
                        <?= $this->form()->closeTag() ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</section>

<script nonce="<?= NONCE_REPLACEMENT_STRING ?>">
    document.querySelector('.add-option').addEventListener('click', () => {
        addOption();
    });
    document.querySelector('.remove-option').addEventListener('click', () => {
        removeOption();
    });
</script>
