<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

$this->headTitle($this->translate('Highlights'));

$this->breadcrumbs()
    ->addBreadcrumb($this->translate('Highlights'), true);
?>
<div class="row">
    <div class="col-md-6 col-md-push-3">
        <div class="alert alert-info">
            <p>
                <?= $this->translate(
                    'This functionality is currently unavailable. Our apologies for the inconvenience.'
                ) ?>
            </p>
        </div>
    </div>
</div>
