<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<section class="section">
    <div class="container">
        <h1><?= $this->translate('500 Internal Server Error') ?></h1>
        <h2><?= $this->message ?></h2>
        <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
            <?php if (isset($this->exception) && $this->exception instanceof Exception): ?>
                <hr/>
                <h2><?= $this->translate('Additional information') ?>:</h2>
                <h3><?= get_class($this->exception); ?></h3>
                <dl>
                    <dt><?= $this->translate('File') ?>:
                    </dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= sprintf(
                            '%s:%d',
                                $this->exception->getFile(),
                                $this->exception->getLine(),
                            ) ?>
                        </pre>
                    </dd>
                    <dt><?= $this->translate('Message') ?>:
                    </dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
                    </dd>
                    <dt><?= $this->translate('Stack trace') ?>:
                    </dt>
                    <dd>
                        <pre class="prettyprint linenums"><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                    </dd>
                </dl>
                <?php
                $e = $this->exception->getPrevious();
                if ($e) :
                    ?>
                    <hr/>
                    <h2><?= $this->translate('Previous exceptions') ?>:</h2>
                    <ul class="unstyled">
                        <?php while ($e): ?>
                            <li>
                                <h3><?= get_class($e); ?></h3>
                                <dl>
                                    <dt><?= $this->translate('File') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php
                                            echo $e->getFile() ?>
                                            :<?php
                                            echo $e->getLine() ?></pre>
                                    </dd>
                                    <dt><?php
                                        echo $this->translate('Message') ?>:
                                    </dt>
                                    <dd>
                                        <pre
                                            class="prettyprint linenums"><?php
                                            echo $this->escapeHtml($e->getMessage()) ?></pre>
                                    </dd>
                                    <dt><?php
                                        echo $this->translate('Stack trace') ?>:
                                    </dt>
                                    <dd>
                                        <pre
                                            class="prettyprint linenums"><?php
                                            echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                                    </dd>
                                </dl>
                            </li>
                            <?php
                            $e = $e->getPrevious();
                        endwhile;
                        ?>
                    </ul>
                <?php endif; ?>
            <?php else: ?>
                <h3><?= $this->translate('No Exception available') ?></h3>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</section>
