name: PHP Coding Standards

# Only run this action when pushing to main or on pull requests (creation, synchronisation, and reopening).
on:
    push:
        branches:
            - main
    pull_request:

# Cancel running jobs that have become stale through updates to the ref (e.g., pushes to a pull request).
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    php-codesniffer:
        uses: 'GEWIS/gewisphp-coding-standards/.github/workflows/coding-standards.yml@dce5fc259bfe9a34e9571a6992046d70d7f09911' # 2.1.0
        with:
            php-version: '8.5'
            extensions: 'amqp, apcu, gd, intl, pcntl, pdo_mysql, pdo_pgsql, pdo_sqlite, redis'
