name: PHPCS
on: [push]
jobs:
    PHPCS:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: cd ${{ github.workspace }}
            - run: php composer.phar install
            - name: Running PHPCS
              run: make phpcsnowarnings
