name: PHPStan PR
on: [push]
jobs:
    PHPStan-PR:
        runs-on: ubuntu-latest
        env:
            DOCKER_BUILDKIT: '1'
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: cd ${{ github.workspace }}
            - run: cp .env.dist .env
            - name: Compare PHPStan result with current master
              run: make phpstanpr
